define("databaseSwimlane",["diagnosticsHub","diagnosticsHub-swimlanes","plugin-vs-v2"],((e,t,i)=>{return a={989:(e,t,i)=>{var a,r;a=[i,t,i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(7),i(952)],r=function(e,t,i,a,r,n,s,h,o,l,g,d,u,c){"use strict";function m(e,t,m,p,_,v){const b=new d.SwimlaneConfiguration(e,_,p);b.header.isBodyExpanded=t;const C=b.graph,T=new i.LocalizedUnitConverter(C.jsonConfig.Units,C.resources),E=[],w=new h.CustomCounterDataSeries({CounterId:"",AnalyzerId:c.DatabaseAnalyzerId()},b.graph.timeRange,!1,b.graph.resources.DatabaseQueriesCountSeries,"",new r.ChartColorScheme("rgb(118, 174, 200)","rgba(118, 174, 200, 0.65)"),T);E.push(w);const S=new u.HighlightDataSeries(w,b.graph.timeRange);E.push(S);const y=new s.MultiSeriesGraph(b.graph,E);y.container.setAttribute("aria-label",e.Title);const D=new o.Scale(b.graph.scale,a.ScaleType.Left,T),f=new o.Scale(b.graph.scale,a.ScaleType.Right,T);y.scaleChangedEvent.addEventListener(D.onScaleChanged.bind(D)),y.scaleChangedEvent.addEventListener(f.onScaleChanged.bind(f)),b.header.unit=b.graph.unit;const H=new g.SwimlaneBase(b.header,b.graph.height,_,v);return y.scaleChangedEvent.addEventListener(H.onScaleChanged.bind(H)),H.addMainRegionControl(new l.SelectionOverlay(y,_,v,b.id)),H.addMainRegionControl(new n.GridLineRenderer(_)),H.addLeftRegionControl(D),H.addRightRegionControl(f),H}Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseSwimlaneFactory=void 0,t.DatabaseSwimlaneFactory=m,window.DatabaseSwimlaneFactory=m}.apply(t,a),void 0===r||(e.exports=r)},7:(e,t,i)=>{var a,r;a=[i,t,i(560),i(560),i(560),i(117),i(117),i(120)],r=function(e,t,i,a,r,n,s,h){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.HighlightDataSeries=void 0,t.HighlightDataSeries=class{constructor(e,t){this._timestamps=[],this._queryId=-1,this._startTime=-1,this._endTime=-1,this._onHighlightChangedHandler=this.onHighlightChanged.bind(this),this._newDataEvent=new n.AggregatedEvent,this._marshaler=new h.DatabaseMarshaler,this._databaseCounterDataSeries=e,this._currentTimespan=t,this._colorScheme=new a.ChartColorScheme("#903F8B","#903F8B"),this._marker=document.createElement("div"),this._marker.style.backgroundColor=this._colorScheme.lineColor,this._marker.style.width="1px",this._marker.style.height="100%",this._marshaler.graphHighlightEvent.addEventListener(this._onHighlightChangedHandler)}onHighlightChanged(e){null===e?(this._queryId=-1,this._startTime=-1,this._endTime=-1):(this._queryId=e.queryId,this._startTime=e.startTime,this._endTime=e.endTime,-1!==this._queryId&&-1!==this._startTime&&-1!==this._endTime?(this._timestamps.push(s.BigNumber.convertFromNumber(this._startTime)),this._timestamps.push(s.BigNumber.convertFromNumber(this._endTime))):this._timestamps=[]),this.requestUpdate()}requestUpdate(){this._newDataEvent.invokeEvent(this)}get minValue(){return Number.NaN}get maxValue(){return Number.NaN}get tooltip(){return""}get title(){return""}get marker(){return this._marker}draw(e,t){if(this._timestamps.length<2||t.gridX.elapsed.equals(s.BigNumber.zero)||t.chartRect.width<=0)return;e.save(),e.lineWidth=1,e.fillStyle=this._colorScheme.lineFillColor,e.strokeStyle=this._colorScheme.lineColor;const a=e=>r.Utilities.convertToPixel(e,t.gridX,t.chartRect.width,!1),n=e=>t.chartRect.height-r.Utilities.scaleToRange(e,t.gridY.min,t.gridY.max,0,t.chartRect.height),h=this._databaseCounterDataSeries.getPointAtTimestamp(this._timestamps[0],i.PointToFind.GreaterThanOrEqual),o=this._databaseCounterDataSeries.getPointAtTimestamp(this._timestamps[1],i.PointToFind.LessThanOrEqual);if(null===h||null===o)return;const l=a(h.timestamp);let g=a(o.timestamp);const d=g-l,u=d<1?t.gridY.max:n(h.value),c=d<1?t.gridY.max:n(o.value);g=d<1?g+1:g,e.beginPath(),e.moveTo(l,u),e.lineTo(g,c),e.stroke(),e.lineTo(g,n(t.gridY.min)),e.lineTo(l,t.chartRect.height),e.closePath(),e.fill(),e.closePath(),e.restore()}get newDataEvent(){return this._newDataEvent}dispose(){this._marshaler.graphHighlightEvent.removeEventListener(this._onHighlightChangedHandler),this._newDataEvent.dispose()}onViewportChanged(e){this._currentTimespan=e,this.requestUpdate()}getPointAtTimestamp(e,t=i.PointToFind.Nearest){if(0===this._timestamps.length)return null;const a=this.getOccurrencePointIndex(this._timestamps,e,0,this._timestamps.length-1,t);return{timestamp:this._timestamps[a],tooltip:"",value:Number.NaN,color:this._colorScheme}}getOccurrencePointIndex(e,t,a,n,h){const o=(e,t)=>t.greaterOrEqual(e);switch(h){case i.PointToFind.LessThanOrEqual:return r.Utilities.findLessThan(e,t,o,a,n);case i.PointToFind.GreaterThanOrEqual:return r.Utilities.findGreaterThan(e,t,o,a,n);case i.PointToFind.Nearest:default:{const i=r.Utilities.findLessThan(e,t,o),a=Math.min(i+1,e.length-1),n=s.BigNumber.subtract(t,e[i]),h=s.BigNumber.subtract(e[a],t);return n.greater(h)?a:i}}}}}.apply(t,a),void 0===r||(e.exports=r)},952:(e,t,i)=>{var a;a=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseAnalyzerId=t.QueryListDetailsViewId=void 0,t.QueryListDetailsViewId=function(){return"11197EBE-BE05-4A13-BBB9-C482C634CDEE"},t.DatabaseAnalyzerId=function(){return"4EF1311E-9AD5-4A55-B683-1CC2191E4346"}}.apply(t,[i,t]),void 0===a||(e.exports=a)},120:(e,t,i)=>{var a,r;a=[i,t,i(432),i(117)],r=function(e,t,i,a){"use strict";let r;Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseMarshaler=void 0,t.DatabaseMarshaler=class{constructor(){r||(r=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Database.DatabaseMarshaler",{},!0)),this._graphHighlightEvent=new a.ObservableEvent(r,"GraphHighlightChangedEvent")}getDoubleClickTimeMs(){return r._call("getDoubleClickTimeMs")}getColumnSettings(){return r._call("getColumnSettings")}onColumnChanged(e){return r._call("onColumnChanged",e)}updateGraphHighlight(e,t,i){return r._call("raiseGraphHighlightChangedEvent",e,t,i)}clearGraphHighlight(){return r._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}}}.apply(t,a),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},r={},function e(t){var i=r[t];if(void 0!==i)return i.exports;var n=r[t]={exports:{}};return a[t](n,n.exports,e),n.exports}(989);var a,r}));
// SIG // Begin signature block
// SIG // MIIoKwYJKoZIhvcNAQcCoIIoHDCCKBgCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // jWKuMMQnguLCkw8TJWoA81w/48SlCahlNivuJMfVAkag
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoNMIIaCQIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCynsuXhfFtsmyrcaqFVtLb3KOYwi8310TH
// SIG // JNR8ZwRlDzBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAIsvQA5F
// SIG // PsPirS9pi9wL79Jw6qBzLdSQlzIcPOxmiOF1TFCwPk38
// SIG // l5KM/NJJL3+mgLmSl1PNQ71MdMXfOD9a+dn7KnGEXPJN
// SIG // YnZpO7gSghmHTA6auSLT/BPBcVqL2ZU5/FN9ZjB0iLL2
// SIG // wG0b2ng55XBDTbplGtZXpIaSmf93ede+H47VtK5lZ3NG
// SIG // yDrRleiEXV0csoeE0qler/OTUfP6vGGx5Sj1eGy4kkw8
// SIG // r1uCjO6MwloJsby3VZVQO5GMRPm9TSrDBW+WaqoMo0Km
// SIG // 5RDpTJ7JhERrd9p41aIGAdycxTA50x3VoAZxBKhuNYcE
// SIG // vYFsb9RjSTkky94U34GEegpg2EGhgheXMIIXkwYKKwYB
// SIG // BAGCNwMDATGCF4Mwghd/BgkqhkiG9w0BBwKgghdwMIIX
// SIG // bAIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgniE46SeKXHALoBUtzMId
// SIG // 3+qhH9DpZEj5bazM4NXbTqoCBmUojUBZABgTMjAyMzEw
// SIG // MjAxNzA0MzQuOTEzWjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOkRDMDAtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR7TCCByAwggUIoAMCAQICEzMAAAHSISQxSli/LREA
// SIG // AQAAAdIwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNTI1MTkxMjIxWhcN
// SIG // MjQwMjAxMTkxMjIxWjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OkRDMDAtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEA3GCIQtECP0j2k+fp
// SIG // 2EgbEnYQTztklzONFcsoPBatUz6zDQ88QocVlA+32ysG
// SIG // BkrDjYLY41XneR0oeYpe+YzWnG+k62cLl/kNvvn9v/Ag
// SIG // srvE2NK8RCJw904+dm1s+UEVlUHo33QgP5+mc4p4XGWe
// SIG // /lXpVoE32Au6w64V90wV/PXpal5iEjlSFnl4kSvIfYR+
// SIG // kl4I4UBhkG39m0jO7hpCsyf6Wdi75U86vpjlvYj9o3GB
// SIG // AOG6T3rq6YJS1VEpxhkC5o0Ke0nctcBOdlozynS5wRei
// SIG // W5kkRDPw4/We6JMUTVI2EnYMr2dS1kopYVf8HoGF1UOj
// SIG // /TCo0ZxPAiOSjB5quxLB4SAStAffXRUMnS9b3bgu3lhI
// SIG // 88+eWfw8h+h5dkjzn+SmeJR3+jFMLYGn/jHmcZFtIsYf
// SIG // 7y9Zl/FbCUx2vAB/tJf/XZ1sxTBRSRRu4PeZxyejJmD6
// SIG // 35qHijkaMhEEbErrNqgq6TI4Pz92fViQLRRqF2DA9fTa
// SIG // 8xuFBT6VW5dzdV7xuP7pXaNfmpwaQ2IcUFO5NYHx5+kM
// SIG // XVFNE7KyfyQry330vPW+FV5SGsZ1RekGYfie8S1DRrRJ
// SIG // o+ncD86Any+86g2Sb5rL2DZNZXG8lcTCIAxT6ANn2T1x
// SIG // xe3cWoTNmRuwALd72RIjLQuhP3Ii0XCMM5SawYhxHpyD
// SIG // 78VteasCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBQgtp+3
// SIG // J0d06D/5GxGdlyRRZmdZJDAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // sOYqtBMtC5QHc9j3KnIUcFuXfn4rTSEgr6g9BOlvwMok
// SIG // 5PkzN1oWE2sUNqT+jq+Kjlfg7u/y/pNfIGK9aYbIcVTF
// SIG // Z1zXHY3nDLU1lDlQMGyaHlh2gIJJzSDM1yt/s4LhuU1X
// SIG // CxIfwlTMtSeyjxPENAs+ejYFs3fbqxvrIUgypCnYTmD1
// SIG // xfe9DK9RghRaXtaF4xMumkvh3mr6dsJsuuZm7tAHFDjx
// SIG // J/oWKoo4C10j6r7hZjjqOVJ0leug7+RXZKiu6uQ0XqMf
// SIG // UTxGXB1GvtgVCj46fnUNw+HPSB/O9uyozA/Dl2aJg/QP
// SIG // DK/33A5+RSO5X2XPIIWHO7KWCkzv9GfWEUWpoVVscayL
// SIG // ATeS61oftfLKFyfvhHko80mHYBlmD4NeoS/+wMnceCs/
// SIG // 1gU1JmxoolVHBPyNGkFNlP9Dc1IiBSFvNEr8Xg1p+iPo
// SIG // clYP7HRUgCz+SU+8AHvM077KyNoTKRFS3UrRQDKmpxWK
// SIG // rcGVORaALKD2e4dRJVpii2ZF5PHj7gC87TWNcrHjtE8H
// SIG // bniBnCMCLa5QWINV6T89fqTIRjFW5Xuih7p2iqOSv5XT
// SIG // jNJkEE+FY4OmW80SFUaA3AK0Of/9PO+YzlLybWMnOx5d
// SIG // OI3Jr4xCFwtx45FGL4BxFi9EBf+H+7ywHIWhGfN/f9xm
// SIG // Dnah+VVZ2a1CAUAeg02lCCwwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDUDCCAjgCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjpEQzAwLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAiabSwmbBNOjb
// SIG // Zh0MweRdU66BUgaggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjc
// SIG // 7pwwIhgPMjAyMzEwMjAxMjE4MzZaGA8yMDIzMTAyMTEy
// SIG // MTgzNlowdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA6Nzu
// SIG // nAIBADAKAgEAAgIIvwIB/zAHAgEAAgITOjAKAgUA6N5A
// SIG // HAIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZ
// SIG // CgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqG
// SIG // SIb3DQEBCwUAA4IBAQCzBeSWcLKUOZQYQg6ffQxXTbHY
// SIG // PsVHEx0pkApajuEQWQ/6tWdKVZ0aXuFM+CCj3w+o2hPG
// SIG // Y42pjUDeSWnFmZhJqIRVE5m6Otb/ApM66MaTkt8CMshK
// SIG // W3qx7tslfdg67EpcRunvfYhe0vxNtbyT908FhfUmdO0s
// SIG // 9LBxtsJP4DifmUaWHAVURVI7GPFHf8VgTXzwWRMnpvoR
// SIG // oyP+5hWWgKLwJ/qSG66WkFss1Ci6V5MwJ635H+EAKYc2
// SIG // JET08/E1pShoAs0a0clo/Y84++BZQhMD0Y2x2b9FC/Vq
// SIG // 3BKwt7USI4HolZ3YpCdzmtoC0zAllSj0Tha/8oMYsZHb
// SIG // 6vfEU4SVMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTACEzMAAAHSISQxSli/LREAAQAA
// SIG // AdIwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJ
// SIG // AzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQg
// SIG // KblQAlgcoGvHsztNkOHS4gR3UQ8kDyjkx2rScy5DiqEw
// SIG // gfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCDHgCCT
// SIG // 399IvWWzhMVOeexsFjWix9GebOuSRYGtg3mkTjCBmDCB
// SIG // gKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
// SIG // HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMz
// SIG // AAAB0iEkMUpYvy0RAAEAAAHSMCIEIEoYwrJSE8k2TeA3
// SIG // p0VOdOjjf7CHU0bEZaP2buO8DmNRMA0GCSqGSIb3DQEB
// SIG // CwUABIICACaV4dMTCGOHuOlQ0I/X8teMdhVt1g5YmXnl
// SIG // C/xbanEUobcKIPBLvmiMsvxCzWkbHisk0yqlH+3ZY/PU
// SIG // SoVmpQDrqOJ+aj8teJPcBHTQ1HTWTxBny/Dw27VUKc2q
// SIG // Spbk18D4N/f2l2XlD/ZW4SqPIw+VfL+yX8ptbJMDQ4WE
// SIG // d5CSF3ZN8kmA6h6o+KQYU6enhCYiBIaknedkAONxO9tR
// SIG // s2fqZsIXO1ot12O3TqFHp92TpFvD9vg1eTjT9kT+/IDX
// SIG // PVe1RbzrrY88mS4MuP1kzA4eBKAICQgSvMof0HY4Z1sb
// SIG // 5NK+z+WuAlPqOuRLAC/4MPLqOSFiO277uf6Hk59qOAf0
// SIG // 8RNac1UlwouEuAx3SCRO+6crltZnUbNMFqkZVLhJz52W
// SIG // 8gP4T3/xW43/EVTaa/D/r8zMfvKdhHtwVJq2I0wzzwNL
// SIG // i2H5EmiWSPhUjn7LkSz3dFDH7aOzxfkKOxffhEeEaNTN
// SIG // tspObMlvyvVVKUpH+pUSLT8MIJ1GZAWfLrvaev9ObK7B
// SIG // XCAqNiW6AKUKEEQE6WQfbmZUNuPE5jF7nvAhaWHah1qW
// SIG // oslVhlvFWdWhqDT7tGI0Fijv+Qj7LNA4NpfVdcX0F4pK
// SIG // VxQ4IrtNeUx1rCAQchutSmXn8VrYXRu2e8U0pSJrBLdP
// SIG // MPW1MIhuZbYEgqYL0zK+gkjue/mZbc7B
// SIG // End signature block
