define("databaseUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,r,i,s)=>{return o={680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},325:e=>{const t=document.createElement("script");t.id="QueryRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ic3RhcnRUaW1lIiBkYXRhLWJpbmQ9ImxvY2FsaXplZE51bWJlcjoge3ZhbHVlOiBzdGFydFRpbWUsIG9wdGlvbnM6IHttaW5pbXVtRnJhY3Rpb25EaWdpdHM6IDMsIG1heGltdW1GcmFjdGlvbkRpZ2l0czogM319IiBkYXRhLWNvbHVtbmlkPSJzdGFydFRpbWUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0icXVlcnkiIGRhdGEtY29sdW1uaWQ9InF1ZXJ5Ij4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IHF1ZXJ5Ij48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJkdXJhdGlvbiIgZGF0YS1iaW5kPSJ0ZXh0OiBkdXJhdGlvbkRpc3BsYXkiIGRhdGEtY29sdW1uaWQ9ImR1cmF0aW9uIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InJlY29yZHNBZmZlY3RlZCIgZGF0YS1iaW5kPSJ0ZXh0OiByZWNvcmRzQWZmZWN0ZWREaXNwbGF5IiBkYXRhLWNvbHVtbmlkPSJyZWNvcmRzQWZmZWN0ZWQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0icmVhZENvdW50IiBkYXRhLWJpbmQ9InRleHQ6IHJlYWRDb3VudERpc3BsYXkiIGRhdGEtY29sdW1uaWQ9InJlYWRDb3VudCI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJkYXRhYmFzZSIgZGF0YS1iaW5kPSJ0ZXh0OiBkYXRhYmFzZSIgZGF0YS1jb2x1bW5pZD0iZGF0YWJhc2UiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iY29ubmVjdGlvblN0ciIgZGF0YS1iaW5kPSJ0ZXh0OiBjb25uZWN0aW9uU3RyIiBkYXRhLWNvbHVtbmlkPSJjb25uZWN0aW9uU3RyIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InF1ZXJ5U291cmNlIiBkYXRhLWJpbmQ9InRleHQ6IHF1ZXJ5U291cmNlIiBkYXRhLWNvbHVtbmlkPSJxdWVyeVNvdXJjZSI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},952:(e,t,r)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseAnalyzerId=t.QueryListDetailsViewId=void 0,t.QueryListDetailsViewId=function(){return"11197EBE-BE05-4A13-BBB9-C482C634CDEE"},t.DatabaseAnalyzerId=function(){return"4EF1311E-9AD5-4A55-B683-1CC2191E4346"}}.apply(t,[r,t]),void 0===i||(e.exports=i)},120:(e,t,r)=>{var i,s;i=[r,t,r(432),r(117)],s=function(e,t,r,i){"use strict";let s;Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseMarshaler=void 0,t.DatabaseMarshaler=class{constructor(){s||(s=r.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Database.DatabaseMarshaler",{},!0)),this._graphHighlightEvent=new i.ObservableEvent(s,"GraphHighlightChangedEvent")}getDoubleClickTimeMs(){return s._call("getDoubleClickTimeMs")}getColumnSettings(){return s._call("getColumnSettings")}onColumnChanged(e){return s._call("onColumnChanged",e)}updateGraphHighlight(e,t,r){return s._call("raiseGraphHighlightChangedEvent",e,t,r)}clearGraphHighlight(){return s._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}}}.apply(t,i),void 0===s||(e.exports=s)},71:(e,t,r)=>{var i,s;i=[r,t,r(432)],s=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseTelemetryMarshaler=void 0;let i=null;t.DatabaseTelemetryMarshaler=class{constructor(){i||(i=r.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Database.DatabaseTelemetryMarshaler",{},!0))}goToSourceUsed(){i._post("goToSourceUsed")}initialColumnVisibility(e,t){i._post("initialColumnVisibility",e,t)}columnVisibilityChanged(e,t){i._post("columnVisibilityChanged",e,t)}sessionLoaded(e,t,r,s,o){i._post("sessionLoaded",e,t,r,s,o)}}}.apply(t,i),void 0===s||(e.exports=s)},371:function(e,t,r){var i,s,o=this&&this.__createBinding||(Object.create?function(e,t,r,i){void 0===i&&(i=r),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,i){void 0===i&&(i=r),e[i]=t[r]}),n=this&&this.__exportStar||function(e,t){for(var r in e)"default"===r||Object.prototype.hasOwnProperty.call(t,r)||o(t,e,r)};i=[r,t,r(566)],s=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),n(r,t)}.apply(t,i),void 0===s||(e.exports=s)},566:(e,t,r)=>{var i,s;i=[r,t,r(28),r(432),r(952),r(560),r(881),r(881),r(881),r(881),r(881),r(117),r(117),r(117),r(398),r(505),r(120),r(71),r(680),r(833),r(103)],s=function(e,t,r,i,s,o,n,a,d,l,c,u,h,g,m,b,I,p){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getQueryListViewModel=t.QueryListViewModel=void 0;class y{constructor(){let e;this._marshaler=new I.DatabaseMarshaler,this._telemetry=new p.DatabaseTelemetryMarshaler,this._currentOverlay=r.pureComputed((()=>this.computeOverlay())),u.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._queryListDAO=new m.QueryListDAO(e,t);const o=new d.TreeGridHeaderViewModel([{id:"startTime",text:i.Resources.getString("QueryListHeaderStartTime"),hideable:!0,sortable:a.SortDirection.Asc},{id:"query",text:i.Resources.getString("QueryListHeaderQuery"),hideable:!1,sortable:a.SortDirection.Desc},{id:"duration",text:i.Resources.getString("QueryListHeaderDuration"),hideable:!1,sortable:a.SortDirection.Desc},{id:"recordsAffected",text:i.Resources.getString("QueryListHeaderRecordsAffected"),hideable:!0,sortable:a.SortDirection.Desc},{id:"readCount",text:i.Resources.getString("QueryListHeaderReadCount"),hideable:!0,sortable:a.SortDirection.Desc},{id:"database",text:i.Resources.getString("QueryListHeaderDatabase"),hideable:!0,sortable:a.SortDirection.Desc},{id:"connectionStr",text:i.Resources.getString("QueryListHeaderConnectionStr"),hideable:!0,sortable:a.SortDirection.Desc},{id:"querySource",text:i.Resources.getString("QueryListHeaderQuerySource"),hideable:!0,sortable:a.SortDirection.Desc}],new b.QueryListColumnSettingsProvider,this._queryListDAO.defaultSortColumnId);this._queryList=new n.TreeGridViewModel(this._queryListDAO,o,"QueryListAriaLabel");const l=h.getViewEventManager();this._queryList.onResultChanged(0),this._queryList.dataLoadPromise.then((()=>this.createSessionLoadedEvent(this._queryList.roots()))),this._queryList.focusedRow.subscribe((()=>{this._marshaler.clearGraphHighlight()})),l.selectionChanged.addEventListener((e=>{e.isIntermittent||(this._queryListDAO.timeFilter(e.position),this._queryList.onResultChanged(0))})),r.applyBindings(this),l.detailsViewReady.raiseEvent({Id:s.QueryListDetailsViewId()})}))}get queryList(){return this._queryList}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==o.KeyCodes.C)return!0;const r=l.TreeGridUtils.formatTreeGridSelectedToText(this._queryList,!1);return navigator.clipboard.writeText(r),!1}showSourceFile(e){return this._telemetry.goToSourceUsed(),g.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition)}contextMenu(e,t){const r=e;if("number"!=typeof r.id)return null;const s=[{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>this.showSourceFile(r),disabled:()=>!r.sourceFilePosition,type:i.ContextMenu.MenuItemType.command},{type:i.ContextMenu.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=l.TreeGridUtils.formatTreeGridSelectedToText(this._queryList,!1);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=l.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._queryList,!1);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command}];return i.ContextMenu.create(s)}computeOverlay(){return this._queryList.dataLoadStatus()===a.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._queryList.dataLoadStatus()===a.DataLoadEvent.DataLoadCompleted&&0===this._queryList.treeAsArray().length?{name:"MessageView",data:i.Resources.getString("NoDataMessage")}:null}createSessionLoadedEvent(e){let t=0,r=0,i=0,s=0;const o={};e.forEach((e=>{"Microsoft.EntityFrameworkCore"===e.querySource?t++:"SqlClientDiagnosticListener"===e.querySource&&r++,null!==o[e.database]&&void 0!==o[e.database]||(o[e.database]=1,e.isSQLite&&i++),e.isBroken()&&s++})),this._telemetry.sessionLoaded(t,r,Object.keys(o).length,i,s)}}let S;t.QueryListViewModel=y,(new I.DatabaseMarshaler).getDoubleClickTimeMs().then((e=>{c.Init(e),S=new y})),t.getQueryListViewModel=function(){return S}}.apply(t,i),void 0===s||(e.exports=s)},505:(e,t,r)=>{var i,s;i=[r,t,r(120)],s=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.QueryListColumnSettingsProvider=void 0,t.QueryListColumnSettingsProvider=class{constructor(){this._marshaler=new r.DatabaseMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings()}onColumnChanged(e){this._marshaler.onColumnChanged(e)}}}.apply(t,i),void 0===s||(e.exports=s)},398:(e,t,r)=>{var i,s;i=[r,t,r(28),r(952),r(405),r(881),r(117)],s=function(e,t,r,i,s,o,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.QueryListDAO=void 0;class a{constructor(e,t){this._dataWarehouse=e,this._timeFilter=r.observable(t)}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"startTime"}getRoots(e,t,r){const o={timeDomain:this._timeFilter(),customDomain:{view:"QueryList"}};return this._dataWarehouse.getFilteredData(o,i.DatabaseAnalyzerId(),r).then((e=>(null==r||r.throwIfCancellationRequested(),this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this._currentResult?this._currentResult.getResult({task:"getRoots"},r):[]))).then((e=>e.map((e=>new s.QueryRowViewModel(e)))))}expand(e,t,r){return e.expand(this._currentResult,t,r)}search(e,t,r,i,s,o,n){throw new Error("Method not implemented.")}sort(e,t,r){return this._currentResult?this._currentResult.getResult({task:"sortColumn",sortInfo:t},r).then((()=>{null==r||r.throwIfCancellationRequested();const i=a.SortFunc[t.columnId](t.direction),s=e=>{e.children&&(e.children.sort(i),e.children().forEach(s))};return"startTime"===t.columnId||"query"===t.columnId||"duration"===t.columnId||"database"===t.columnId||"connectionStr"===t.columnId||"querySource"===t.columnId||"recordsAffected"===t.columnId||"readCount"===t.columnId?(e.sort(i),e.forEach(s),Promise.resolve(e)):(n.Assert.fail("Unknown sort column: ${sortInfo.columnId}"),Promise.resolve(e))})):Promise.resolve(e)}}t.QueryListDAO=a,a.SortFunc={startTime:e=>o.SortFunctions.numericSort("startTime",e),query:e=>o.SortFunctions.stringSort("query",e),duration:e=>o.SortFunctions.numericSort("duration",e),recordsAffected:e=>o.SortFunctions.numericSort("recordsAffected",e),readCount:e=>o.SortFunctions.numericSort("readCount",e),database:e=>o.SortFunctions.stringSort("database",e),connectionStr:e=>o.SortFunctions.stringSort("connectionStr",e),querySource:e=>o.SortFunctions.stringSort("querySource",e)}}.apply(t,i),void 0===s||(e.exports=s)},405:(e,t,r)=>{var i,s;i=[r,t,r(432),r(28),r(120),r(325)],s=function(e,t,r,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.QueryRowViewModel=void 0;class o{constructor(e,t,r=0){this._selected=i.observable(!1),this._expanded=i.observable(!1),this._children=i.observableArray([]),this._marshaler=new s.DatabaseMarshaler,this._haveLoaded=!1,this._parent=t,this._dto=e,this._depth=r}get query(){return this._dto.q?this._dto.q:this._dto.tt?this._dto.tt:r.Resources.getString("UnknownDataLabel")}get durationDisplay(){return-1===this._dto.d?r.Resources.getString("UnknownDataLabel"):this._dto.d.toFixed(3)}get duration(){return this._dto.d}get database(){return this._dto.db?this._dto.db:r.Resources.getString("UnknownDataLabel")}get connectionStr(){return this._dto.cn?this._dto.cn:r.Resources.getString("UnknownDataLabel")}get querySource(){return this._dto.qs?this._dto.qs:r.Resources.getString("UnknownDataLabel")}get isSQLite(){return this._dto.sl}get startTime(){return this._dto.s/1e9}get endTime(){return this._dto.e/1e6}get sourceFilePosition(){return this._dto.sfp}get recordsAffected(){return this._dto.ra}get recordsAffectedDisplay(){return-1===this._dto.ra?r.Resources.getString("UnknownDataLabel"):this._dto.ra.toString()}get readCount(){return this._dto.rc}get readCountDisplay(){return-1===this._dto.rc?r.Resources.getString("UnknownDataLabel"):this._dto.rc.toString()}get isPartOfTransaction(){return!this._parent}isBroken(){return!this._dto.tt&&!this._dto.q||-1===this._dto.d||!this._dto.db||!this._dto.cn||!this._dto.qs||-1===this._dto.s||-1===this._dto.e}get templateName(){return"QueryRowView"}get id(){return this._dto.id}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return!this._dto.c||this._dto.c.length>0}get children(){return this._children}invoke(){this._marshaler.updateGraphHighlight(this.id,this._dto.s,this._dto.e)}expand(e,t,r){let i=Promise.resolve(void 0);return this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",transactionId:this._dto.id},r).then((e=>{const t=e.map((e=>new o(e,this,this.depth+1)));this.children(t)}))),this._expanded(!this._expanded()),i}}t.QueryRowViewModel=o}.apply(t,i),void 0===s||(e.exports=s)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=r},28:e=>{"use strict";e.exports=i},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},n={},function e(t){var r=n[t];if(void 0!==r)return r.exports;var i=n[t]={exports:{}};return o[t].call(i.exports,i,i.exports,e),i.exports}(371);var o,n}));
// SIG // Begin signature block
// SIG // MIIoOgYJKoZIhvcNAQcCoIIoKzCCKCcCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // s1ENQ91vnwpQgYKprxp3BG5xRTg+FLruefYKbNaToKag
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoNMIIaCQIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCBy91ZJGx0vcZ6s
// SIG // hefLHuvrsoKoGGP4ht4TvlNwe1MUrzBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAM1yGImn2rypGuBGSQXjoq+KignsPHdX
// SIG // oGL1LKqHK4ka/e37kmW0BWFlT5UOC6SVtrDNIe4c/CL2
// SIG // RYMTfkZB/GMhrxDl/MjQIW07N0U6LfKkWgPdhY33t4w2
// SIG // 7TzmQAb4ofGuScoKpiOCrzF8OYh1vhJcdUlV9RFPmdoK
// SIG // 1MuXevFG90R/tkqWGeejXQ6w8bcMwVTVjiaV0kcmLYdL
// SIG // HU0/IgoRJiFjZvrBDdKSMhXeP5Lj/PibJ9dtTfQPFW6/
// SIG // 3VINRKgVbHg/qcL8bJQ5ocnaKgwM2tseLm1RdvXZq82h
// SIG // YR71+H8Of7Pc20lP/XWaY80hQwQA14/EW9B/X+PCmziJ
// SIG // evmhgheXMIIXkwYKKwYBBAGCNwMDATGCF4Mwghd/Bgkq
// SIG // hkiG9w0BBwKgghdwMIIXbAIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // 2TeJN097oQvOqlV6+rcItkVORa5A7OEqKSBfzUz4w+gC
// SIG // BmUojUBZhxgTMjAyMzEwMjAxNzA0MzcuNzY1WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkRDMDAt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR7TCCByAwggUIoAMCAQIC
// SIG // EzMAAAHSISQxSli/LREAAQAAAdIwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjIxWhcNMjQwMjAxMTkxMjIxWjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkRDMDAtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA3GCIQtECP0j2k+fp2EgbEnYQTztklzONFcsoPBat
// SIG // Uz6zDQ88QocVlA+32ysGBkrDjYLY41XneR0oeYpe+YzW
// SIG // nG+k62cLl/kNvvn9v/AgsrvE2NK8RCJw904+dm1s+UEV
// SIG // lUHo33QgP5+mc4p4XGWe/lXpVoE32Au6w64V90wV/PXp
// SIG // al5iEjlSFnl4kSvIfYR+kl4I4UBhkG39m0jO7hpCsyf6
// SIG // Wdi75U86vpjlvYj9o3GBAOG6T3rq6YJS1VEpxhkC5o0K
// SIG // e0nctcBOdlozynS5wReiW5kkRDPw4/We6JMUTVI2EnYM
// SIG // r2dS1kopYVf8HoGF1UOj/TCo0ZxPAiOSjB5quxLB4SAS
// SIG // tAffXRUMnS9b3bgu3lhI88+eWfw8h+h5dkjzn+SmeJR3
// SIG // +jFMLYGn/jHmcZFtIsYf7y9Zl/FbCUx2vAB/tJf/XZ1s
// SIG // xTBRSRRu4PeZxyejJmD635qHijkaMhEEbErrNqgq6TI4
// SIG // Pz92fViQLRRqF2DA9fTa8xuFBT6VW5dzdV7xuP7pXaNf
// SIG // mpwaQ2IcUFO5NYHx5+kMXVFNE7KyfyQry330vPW+FV5S
// SIG // GsZ1RekGYfie8S1DRrRJo+ncD86Any+86g2Sb5rL2DZN
// SIG // ZXG8lcTCIAxT6ANn2T1xxe3cWoTNmRuwALd72RIjLQuh
// SIG // P3Ii0XCMM5SawYhxHpyD78VteasCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQgtp+3J0d06D/5GxGdlyRRZmdZJDAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAsOYqtBMtC5QHc9j3KnIUcFuX
// SIG // fn4rTSEgr6g9BOlvwMok5PkzN1oWE2sUNqT+jq+Kjlfg
// SIG // 7u/y/pNfIGK9aYbIcVTFZ1zXHY3nDLU1lDlQMGyaHlh2
// SIG // gIJJzSDM1yt/s4LhuU1XCxIfwlTMtSeyjxPENAs+ejYF
// SIG // s3fbqxvrIUgypCnYTmD1xfe9DK9RghRaXtaF4xMumkvh
// SIG // 3mr6dsJsuuZm7tAHFDjxJ/oWKoo4C10j6r7hZjjqOVJ0
// SIG // leug7+RXZKiu6uQ0XqMfUTxGXB1GvtgVCj46fnUNw+HP
// SIG // SB/O9uyozA/Dl2aJg/QPDK/33A5+RSO5X2XPIIWHO7KW
// SIG // Ckzv9GfWEUWpoVVscayLATeS61oftfLKFyfvhHko80mH
// SIG // YBlmD4NeoS/+wMnceCs/1gU1JmxoolVHBPyNGkFNlP9D
// SIG // c1IiBSFvNEr8Xg1p+iPoclYP7HRUgCz+SU+8AHvM077K
// SIG // yNoTKRFS3UrRQDKmpxWKrcGVORaALKD2e4dRJVpii2ZF
// SIG // 5PHj7gC87TWNcrHjtE8HbniBnCMCLa5QWINV6T89fqTI
// SIG // RjFW5Xuih7p2iqOSv5XTjNJkEE+FY4OmW80SFUaA3AK0
// SIG // Of/9PO+YzlLybWMnOx5dOI3Jr4xCFwtx45FGL4BxFi9E
// SIG // Bf+H+7ywHIWhGfN/f9xmDnah+VVZ2a1CAUAeg02lCCww
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDUDCC
// SIG // AjgCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpEQzAwLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAiabSwmbBNOjbZh0MweRdU66BUgaggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjc7pwwIhgPMjAyMzEwMjAxMjE4
// SIG // MzZaGA8yMDIzMTAyMTEyMTgzNlowdzA9BgorBgEEAYRZ
// SIG // CgQBMS8wLTAKAgUA6NzunAIBADAKAgEAAgIIvwIB/zAH
// SIG // AgEAAgITOjAKAgUA6N5AHAIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCzBeSW
// SIG // cLKUOZQYQg6ffQxXTbHYPsVHEx0pkApajuEQWQ/6tWdK
// SIG // VZ0aXuFM+CCj3w+o2hPGY42pjUDeSWnFmZhJqIRVE5m6
// SIG // Otb/ApM66MaTkt8CMshKW3qx7tslfdg67EpcRunvfYhe
// SIG // 0vxNtbyT908FhfUmdO0s9LBxtsJP4DifmUaWHAVURVI7
// SIG // GPFHf8VgTXzwWRMnpvoRoyP+5hWWgKLwJ/qSG66WkFss
// SIG // 1Ci6V5MwJ635H+EAKYc2JET08/E1pShoAs0a0clo/Y84
// SIG // ++BZQhMD0Y2x2b9FC/Vq3BKwt7USI4HolZ3YpCdzmtoC
// SIG // 0zAllSj0Tha/8oMYsZHb6vfEU4SVMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAHSISQxSli/LREAAQAAAdIwDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQgcqP1fn5Ttr+/Oi5CBAY/u36D
// SIG // /mvuiGkN3UaU77RonDswgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCDHgCCT399IvWWzhMVOeexsFjWix9Ge
// SIG // bOuSRYGtg3mkTjCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAAB0iEkMUpYvy0RAAEAAAHS
// SIG // MCIEIEoYwrJSE8k2TeA3p0VOdOjjf7CHU0bEZaP2buO8
// SIG // DmNRMA0GCSqGSIb3DQEBCwUABIICALgdHssTFUUg1tbv
// SIG // 0ebEJydSGsDqCtOxiUCf1mGBvQgjDTehkiXOrouX2JmO
// SIG // Z13/JGzsVihX0zxHf0wTCXFBSqj9QPQ94z3I+Zr34cQy
// SIG // Hil2laN8J68vUgNUklqh6jeHoa/gRAgG2ppLDocNww0h
// SIG // i/oF/AjQV+uJyqlAk5uUKgDK5ktc3hz+oBrUXvHPYbVu
// SIG // /y4E9YPPD4Ayh4ZBecgeoIy9KyKUM7dmbj1UovOUmRLo
// SIG // KtHO1urTueo2P9bLnDB5CTcD/jOyaTPfp/NWsCGmjP4L
// SIG // VvGrlTFPZGVXiU3tk3+Q5qdOBDLLR6s78P8Op7u0zQX9
// SIG // AjahAMrHmSoB1q7Y/7SSGwQpwELbzgkX94G7bVqQoHZP
// SIG // b4kCtJz7bkfKITyDaJsBgBEMC+xy1e8XwZc2vVKxMos7
// SIG // z2JfsPHzQPI6XUtf7k2dNHR83REf5elYsMyEtXnf8A1m
// SIG // 6d0a29M67aJW7Vs7Ak+ZA03Gobg/yECzAA3l8a2AuOXD
// SIG // Z1YZRewyeHcSph2Ern4Ccr3ahpgTwIAvlkoc284WS5tx
// SIG // aSWyTyIqmgUvr2zh4tGP/3bA2f9Vs9qW4RZ6gILLhPfi
// SIG // gfcEfb7sk9RxcjQkM66ZSMNS1QofdUiWWizwm4hljOHG
// SIG // 56YFeu1QYJk6vnVJw583LTOVkYRo/lyxTbGaL9hmfRSO
// SIG // PYSbZA7P
// SIG // End signature block
