define("dotNetAsyncUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,a,s)=>{return r={946:e=>{const t=document.createElement("script");t.id="ActivityRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGFyaWFFeHBhbmRlZDogeyBleHBhbmRhYmxlOiBleHBhbmRhYmxlLCBleHBhbmRlZDogZXhwYW5kZWQgfSwNCiAgICBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSwNCiAgICBhdHRyOiB7ICdhcmlhLWxldmVsJzogZGVwdGggKyAxIH0iPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9Im5hbWUgY29udGFpbmVyIiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8ZGl2IGNsYXNzPSJ0eXBlSWNvbiIgZGF0YS1iaW5kPSJjc3M6IHsgaW5jcmVhc2U6IGlzQWJvdmVWYXJpYW5jZSwgZGVjcmVhc2U6IGlzQmVsb3dWYXJpYW5jZSB9LCB0b29sdGlwOiB2YXJpYW5jZVRvb2x0aXAiPjwvZGl2Pg0KICAgICAgICA8c3BhbiBjbGFzcz0idHJlZUdyaWRDZWxsLWxhYmVsIiBkYXRhLWJpbmQ9InRleHQ6IGxhYmVsIj48L3NwYW4+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iY291bnQiIGRhdGEtYmluZD0idGV4dDogY291bnQiIGRhdGEtY29sdW1uaWQ9ImNvdW50Ij48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InN0YXJ0VGltZSIgZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXI6IHt2YWx1ZTogc3RhcnRUaW1lLCBvcHRpb25zOiB7bWluaW11bUZyYWN0aW9uRGlnaXRzOiAyLCBtYXhpbXVtRnJhY3Rpb25EaWdpdHM6IDJ9fSIgZGF0YS1jb2x1bW5pZD0ic3RhcnRUaW1lIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InN0b3BUaW1lIiBkYXRhLWNvbHVtbmlkPSJzdG9wVGltZSI+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogYXN5bmNTdGF0ZUxhYmVsIj48L3NwYW4+DQogICAgICAgIDwhLS0ga28gaWY6IGlzQXN5bmNDb21wbGV0ZSAtLT4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXI6IHt2YWx1ZTogc3RvcFRpbWUsIG9wdGlvbnM6IHttaW5pbXVtRnJhY3Rpb25EaWdpdHM6IDIsIG1heGltdW1GcmFjdGlvbkRpZ2l0czogMn19Ij48L3NwYW4+DQogICAgICAgIDwhLS0gL2tvIC0tPg0KICAgICAgICA8IS0tIGtvIGlmbm90OiBpc0FzeW5jQ29tcGxldGUgLS0+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogJycsIHN0eWxlOiB7IGRpc3BsYXk6ICdub25lJyB9Ij48L3NwYW4+DQogICAgICAgIDwhLS0gL2tvIC0tPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0idG90YWxUaW1lIiBkYXRhLWNvbHVtbmlkPSJ0b3RhbFRpbWUiPg0KICAgICAgICA8c3BhbiBjbGFzcz0idHJlZUdyaWRDZWxsLWxhYmVsIiBkYXRhLWJpbmQ9InRleHQ6IGFzeW5jU3RhdGVMYWJlbCI+PC9zcGFuPg0KICAgICAgICA8IS0tIGtvIGlmOiBpc0FzeW5jQ29tcGxldGUgLS0+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0ibG9jYWxpemVkTnVtYmVyOiB7dmFsdWU6IHRvdGFsVGltZSwgb3B0aW9uczoge21pbmltdW1GcmFjdGlvbkRpZ2l0czogMiwgbWF4aW11bUZyYWN0aW9uRGlnaXRzOiAyfX0iPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBpc0FnZ3JlZ2F0ZWQgfHwgaXNWYXJpYW5jZSB8fCBpc0RldGFpbHMgPyBhZ2dyZWdhdGVkVGltZUxhYmVsIDogJycsIHN0eWxlOiB7IGRpc3BsYXk6IGlzQWdncmVnYXRlZCB8fCBpc1ZhcmlhbmNlIHx8IGlzRGV0YWlscyA/ICdpbmxpbmUnIDogJ25vbmUnIH0iPjwvc3Bhbj4NCiAgICAgICAgPCEtLSAva28gLS0+DQogICAgICAgIDwhLS0ga28gaWZub3Q6IGlzQXN5bmNDb21wbGV0ZSAtLT4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiAnJywgc3R5bGU6IHsgZGlzcGxheTogJ25vbmUnIH0iPjwvc3Bhbj4NCiAgICAgICAgPCEtLSAva28gLS0+DQogICAgPC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},486:(e,t,i)=>{var a,s;a=[i,t,i(432),i(28),i(886),i(946)],s=function(e,t,i,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityRowViewModel=void 0;class r{constructor(e,t,i,s){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._isChildDataLoaded=!1,this._isWithinAggregation=!1,this._dao=e,this._dto=t,this._depth=i,this._isWithinAggregation=s,this._name=a.pureComputed((()=>this.computeName()),this),this._label=a.pureComputed((()=>this.computeLabel()),this),this._asyncStateLabel=a.pureComputed((()=>this.computeAsyncStateLabel()),this),this._varianceTooltip=a.pureComputed((()=>this.computeVarianceTooltip()),this),this._children=a.observableArray([])}get templateName(){return"ActivityRowView"}get id(){return this._dto.id}get depth(){return this._depth}get label(){return this._label}get name(){return this._name}get totalTime(){return this._dto.tt}get startTime(){return this._dto.s}get stopTime(){return this._dto.st}get count(){return this._dto.co}get asyncStateLabel(){return this._asyncStateLabel}get isAggregated(){return this.hasFlag(s.ActivityFlags.Aggregation)}get isVariance(){return this.hasFlag(s.ActivityFlags.Variance)}get isDetails(){return this.hasFlag(s.ActivityFlags.Details)}get isIncomplete(){return this.hasFlag(s.ActivityFlags.Incomplete)}get isBelowVariance(){return this._isWithinAggregation&&this.hasFlag(s.ActivityFlags.BelowVariance)}get isAboveVariance(){return this._isWithinAggregation&&this.hasFlag(s.ActivityFlags.AboveVariance)}get varianceTooltip(){return this._varianceTooltip}get aggregatedTimeLabel(){return i.Resources.getString("AggregatedTimeLabel")}get isAsyncComplete(){return this._dto.st>0&&this._dto.tt>=0}get hasSourceInfo(){return(this._dto.f&s.ActivityFlags.HasSourceInfo)===s.ActivityFlags.HasSourceInfo}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return this._dto.c}get children(){return this._children}invoke(){this._dao.showSourceFile(this.id)}expand(e,t,i){let a=Promise.resolve();return this._isChildDataLoaded||(this._isChildDataLoaded=!0,a=e.getResult({task:"expand",id:this._dto.id,path:this.getIdPath()},i).then((async a=>{null==i||i.throwIfCancellationRequested();const s=a.map((e=>new r(this._dao,e,this.depth+1,this.isAggregated&&!this.isVariance)));return await this._dao.sort(s,t,i),this.children(s),1===s.length&&!s[0].isDetails||2===s.length&&s[1].isDetails?s[0].expand(e,t,i):Promise.resolve()}))),this._expanded(!this._expanded()),a}getIdPath(){return[this.id]}computeName(){return this.hasFlag(s.ActivityFlags.Variance)?i.Resources.getString("VarianceContainerRowName",this._dto.co):this.hasFlag(s.ActivityFlags.Incomplete)?i.Resources.getString("IncompleteContainerRowName",this._dto.co):this.hasFlag(s.ActivityFlags.Details)?"":this._dto.n}computeLabel(){return this.hasFlag(s.ActivityFlags.CallerName)?i.Resources.getString("TaskCallerActivityLabel"):this.hasFlag(s.ActivityFlags.IdentifiedTask)?i.Resources.getString("TaskActivityLabel"):this.hasFlag(s.ActivityFlags.Details)&&!this.hasFlag(s.ActivityFlags.Variance)?i.Resources.getString("TaskDetailsLabel"):""}computeAsyncStateLabel(){return this.isAsyncComplete?"":i.Resources.getString("TaskPendingLabel")}computeVarianceTooltip(){return this.isBelowVariance?i.Resources.getString("BelowVarianceTooltip"):this.isAboveVariance?i.Resources.getString("AboveVarianceTooltip"):""}hasFlag(e){return(this._dto.f&e)===e}}t.ActivityRowViewModel=r}.apply(t,a),void 0===s||(e.exports=s)},778:(e,t,i)=>{var a;a=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityTreeColumnSettingsProvider=void 0,t.ActivityTreeColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"name",isHidden:!1,width:500},{columnId:"count",isHidden:!1,width:70},{columnId:"startTime",isHidden:!1,width:140},{columnId:"stopTime",isHidden:!1,width:140},{columnId:"totalTime",isHidden:!1,width:140}])}onColumnChanged(e){}}}.apply(t,[i,t]),void 0===a||(e.exports=a)},670:(e,t,i)=>{var a,s;a=[i,t,i(28),i(952),i(881),i(117),i(117),i(486)],s=function(e,t,i,a,s,r,o,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityTreeDAO=void 0;class c{constructor(e,t,a){this._dataWarehouse=e,this._timeFilter=i.observable(t),this._marshaller=a}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"startTime"}async getRoots(e,t,i){const s={timeDomain:this.timeFilter(),customDomain:{view:"ActivityTree"}},r=await this._dataWarehouse.getFilteredData(s,a.DotNetAsyncAnalyzer(),i);null==i||i.throwIfCancellationRequested(),this._currentResult&&await this._currentResult.dispose(),this._currentResult=r;const o=await this._currentResult.getResult({task:"expand",id:0,path:[]},i);null==i||i.throwIfCancellationRequested();const c=o.map((e=>new n.ActivityRowViewModel(this,e,0,!1)));return await this.sort(c,t,i),c}sort(e,t,i){const a=c.SortFunc[t.columnId];if(a){const i=(e,i)=>{if(0!==e.depth){if(e.isAggregated&&!i.isAggregated)return-1;if(!e.isAggregated&&i.isAggregated)return 1;if(e.isDetails&&!i.isDetails)return 1;if(!e.isDetails&&i.isDetails)return-1;if(e.isVariance&&!i.isVariance)return 1;if(!e.isVariance&&i.isVariance)return-1}return a(t.direction)(e,i)},s=e=>{e.children&&(e.children.sort(i),e.children().forEach(s))};return e.sort(i),e.forEach(s),Promise.resolve(e)}return r.Assert.fail(`Unknown sort column: ${t.columnId}`),Promise.resolve(e)}search(e,t,i,a,s,r,o){throw new Error("Not implemented")}expand(e,t,i){return e.expand(this._currentResult,t,i)}getSourceInfo(e){return this._currentResult.getResult({task:"sourceInfo",id:e,path:[]}).then((e=>e.sfp))}async showSourceFile(e){const t=await this.getSourceInfo(e);await o.getSourceFileViewerService().openSourcePosition(t)}}t.ActivityTreeDAO=c,c.SortFunc={name:e=>s.SortFunctions.stringSort("name",e),count:e=>s.SortFunctions.numericSort("count",e),startTime:e=>s.SortFunctions.numericSort("startTime",e),stopTime:e=>s.SortFunctions.numericSort("stopTime",e),totalTime:e=>s.SortFunctions.numericSort("totalTime",e)}}.apply(t,a),void 0===s||(e.exports=s)},952:(e,t,i)=>{var a;a=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetAsyncAnalyzer=t.ActivityDetailsViewId=void 0,t.ActivityDetailsViewId=function(){return"67cabac5-0ec5-486f-9dd0-6f524c7390fb"},t.DotNetAsyncAnalyzer=function(){return"62070e76-dd33-417e-9665-a4ca5e510ee7"}}.apply(t,[i,t]),void 0===a||(e.exports=a)},940:(e,t,i)=>{var a,s;a=[i,t,i(28),i(432),i(952),i(560),i(881),i(881),i(881),i(881),i(881),i(117),i(117),i(778),i(670),i(766),i(680),i(833),i(103)],s=function(e,t,i,a,s,r,o,n,c,l,d,g,u,h,I,m){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getActivityTreeViewModel=t.DotNetAsyncViewModel=void 0;class p{constructor(){let e;this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._isOverlayActive=i.pureComputed((()=>null!==this._currentOverlay())),g.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._activityTreeDao=new I.ActivityTreeDAO(e,t,b);const r=new o.TreeGridHeaderViewModel([{id:"name",text:a.Resources.getString("ActivityTreeHeaderName"),hideable:!1,sortable:l.SortDirection.Desc},{id:"count",text:a.Resources.getString("ActivityTreeHeaderCount"),hideable:!0,sortable:l.SortDirection.Desc},{id:"startTime",text:a.Resources.getString("ActivityTreeHeaderStartTime"),hideable:!0,sortable:l.SortDirection.Asc},{id:"stopTime",text:a.Resources.getString("ActivityTreeHeaderStopTime"),hideable:!0,sortable:l.SortDirection.Desc},{id:"totalTime",text:a.Resources.getString("ActivityTreeHeaderTotalTime"),hideable:!0,sortable:l.SortDirection.Desc}],new h.ActivityTreeColumnSettingsProvider,this._activityTreeDao.defaultSortColumnId);this._activityTree=new c.TreeGridViewModel(this._activityTreeDao,r,"ActivityTreeAriaLabel"),this._activityTree.onResultChanged(0);const n=u.getViewEventManager();n.selectionChanged.addEventListener((e=>{e.isIntermittent||this._activityTreeDao.timeFilter().equals(e.position)||(this._activityTreeDao.timeFilter(e.position),this._activityTree.onResultChanged(0))})),i.applyBindings(this),n.detailsViewReady.raiseEvent({Id:s.ActivityDetailsViewId()})}))}get activityTree(){return this._activityTree}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==r.KeyCodes.C)return!0;const i=n.TreeGridUtils.formatTreeGridSelectedToText(this._activityTree);return navigator.clipboard.writeText(i),!1}contextMenu(e,t){const i=e;if("number"!=typeof i.id)return null;const s=()=>{this._activityTreeDao.showSourceFile(i.id)},r=[{label:a.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>s(),disabled:()=>!i.id||!i.hasSourceInfo,type:a.ContextMenu.MenuItemType.command},{type:a.ContextMenu.MenuItemType.separator},{label:a.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=n.TreeGridUtils.formatTreeGridSelectedToText(this._activityTree);navigator.clipboard.writeText(e)},type:a.ContextMenu.MenuItemType.command},{label:a.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=n.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._activityTree);navigator.clipboard.writeText(e)},type:a.ContextMenu.MenuItemType.command}];return a.ContextMenu.create(r)}computeOverlay(){return this._activityTree.dataLoadStatus()===l.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._activityTree.dataLoadStatus()===l.DataLoadEvent.DataLoadCompleted&&0===this._activityTree.treeAsArray().length?{name:"MessageView",data:a.Resources.getString("NoDataMessage")}:null}}let v;t.DotNetAsyncViewModel=p;const b=new m.DotNetAsyncMarshaler;b.getDoubleClickTimeMs().then((e=>{d.Init(e),v=new p})),t.getActivityTreeViewModel=function(){return v}}.apply(t,a),void 0===s||(e.exports=s)},371:function(e,t,i){var a,s,r=this&&this.__createBinding||(Object.create?function(e,t,i,a){void 0===a&&(a=i),Object.defineProperty(e,a,{enumerable:!0,get:function(){return t[i]}})}:function(e,t,i,a){void 0===a&&(a=i),e[a]=t[i]}),o=this&&this.__exportStar||function(e,t){for(var i in e)"default"===i||Object.prototype.hasOwnProperty.call(t,i)||r(t,e,i)};a=[i,t,i(940),i(558)],s=function(e,t,i,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),o(i,t),window.DotNetAsyncUI_onAfterDomInsert=a.onAfterDomInsert}.apply(t,a),void 0===s||(e.exports=s)},886:(e,t,i)=>{var a;a=function(e,t){"use strict";var i;Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityFlags=void 0,(i=t.ActivityFlags||(t.ActivityFlags={}))[i.None=0]="None",i[i.FullNameFound=1]="FullNameFound",i[i.ExactStopTime=2]="ExactStopTime",i[i.IdentifiedTask=4]="IdentifiedTask",i[i.CallerName=8]="CallerName",i[i.HasSourceInfo=16]="HasSourceInfo",i[i.HasProcessedAggregation=32]="HasProcessedAggregation",i[i.Aggregation=64]="Aggregation",i[i.Variance=128]="Variance",i[i.BelowVariance=256]="BelowVariance",i[i.AboveVariance=512]="AboveVariance",i[i.Details=1024]="Details",i[i.Incomplete=2048]="Incomplete"}.apply(t,[i,t]),void 0===a||(e.exports=a)},766:(e,t,i)=>{var a,s;a=[i,t,i(432)],s=function(e,t,i){"use strict";let a;Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetAsyncMarshaler=void 0,t.DotNetAsyncMarshaler=class{constructor(){a||(a=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetAsync.DotNetAsyncMarshaler",{},!0))}getDoubleClickTimeMs(){return a._call("getDoubleClickTimeMs")}}}.apply(t,a),void 0===s||(e.exports=s)},558:(e,t,i)=>{var a,s;a=[i,t,i(28),i(560)],s=function(e,t,i,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=i.utils.domData.get(e,"mediaQuery");if(t){const a=i.utils.domData.get(e,"mediaQueryListener");t.removeListener(a)}const s=e.children;let r=45;for(let e=0;e<s.length;e++)r+=s.item(e).offsetWidth;const o=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},n=window.matchMedia(a.Utilities.formatString("(max-width: {0}px)",r.toString()));o(n),n.addListener(o),i.utils.domData.set(e,"mediaQuery",n),i.utils.domData.set(e,"mediaQueryListener",o)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,a),void 0===s||(e.exports=s)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=i},28:e=>{"use strict";e.exports=a},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},o={},function e(t){var i=o[t];if(void 0!==i)return i.exports;var a=o[t]={exports:{}};return r[t].call(a.exports,a,a.exports,e),a.exports}(371);var r,o}));
// SIG // Begin signature block
// SIG // MIIoNwYJKoZIhvcNAQcCoIIoKDCCKCQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // cVNl24fkUnxyx6963yxa6xzWET3EG+vHB8AlDmSpnPeg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoKMIIaBgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCB8tLFxzVPM+GAe
// SIG // CM/EGB1uhSgGTMbK8WOCJ6jPai4GrzBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAHz9PknUKQmldI0cGmC3Q3BbRTprIFyZ
// SIG // TyVHABxqsu14Tz6IzQu/WGmtbF+av4RtfWrb+u9YnI6g
// SIG // 2HYlG3PNrSVHvzaqx810vlXQXXoyBpzI8yHX6ZgeLDYO
// SIG // Vqe+S41NIkJKg/7DaT1KAIh8iaIjzPjWCUUEExXfmjUQ
// SIG // 4w+3K81NVb8S+OaFkk1aijM9PT3KLgJyrWEw92N/9u/v
// SIG // hdbpjzKEXAgpZ/RIhPxO9g9epzU6LBjKNsbdt433ZxW+
// SIG // ahB+2MvgSdtEDRU7Xsyfes7LiIj/Zjywv32eV/KJAEUZ
// SIG // fQ0hhYj/JA30PMVVKa7g4jRRk0PUoPZTTgnh1xLkSBRv
// SIG // y8mhgheUMIIXkAYKKwYBBAGCNwMDATGCF4Awghd8Bgkq
// SIG // hkiG9w0BBwKgghdtMIIXaQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // Cn8PWKKeEKjqnhnhVWm9Uo4GB5W1gDvgNt8UuxK0nywC
// SIG // BmUorOGU0RgTMjAyMzEwMjAxNzA0MzYuNzcyWjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkUwMDIt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR6jCCByAwggUIoAMCAQIC
// SIG // EzMAAAHZnFwFkrCDaz4AAQAAAdkwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNjAxMTgzMjU4WhcNMjQwMjAxMTgzMjU4WjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkUwMDItMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA1ekgzda4GNt9Oci3QnVDbxwhBOGdLnA+giry+ZQO
// SIG // xzPNUjJFt+kVO+1GgS/T0nL4qn1cxNq9qUW0TLQwTMBM
// SIG // dYmos1dhGbDRhrs3kd1zWDm0LyVS2gogZLQGXau+QTRS
// SIG // Ipfkn3aV4Cs1UGYgwSQzedFggAza62+PGeGe/yr8s2g+
// SIG // Bm/mmXgoqAdhoNZud3fuqVEwXN1jucR2Yv66yP13Z4Yh
// SIG // Ov27KY6VOWrnwpSA8dEA6tUEcNOGnayoXA1shi90mgaf
// SIG // 4YzfuCSVOys77ClmVXU7lz6I52k8FnB3RBn88Ymhd9M3
// SIG // fEmOGEVHDBjzkDkR9SD8JMMJakJHNBwZCQkM4ml2PyKY
// SIG // DEcP1z+FL/iQSfEWRimTdc0T1k/XebxxlEpl95u+0SqA
// SIG // n5IEiYnyIkIuhXNDmCkuoGTgO53eLfpYgK6/Z4qngv1H
// SIG // DTrla3FQuAm5MHydnh5GlodfLFLd1A/EB2C0MJ/eT/h5
// SIG // vD2SYoK9UkS3LJvKTj3nuzwW53SP1XiibJkHY3pNmhTv
// SIG // VRp1LcwwwaMJYV7IbMGTDJCyf+I1M0JlAX5viQB9edeh
// SIG // PhtNsEuzYMzMJqR1gpgGhXXew8iSKhmum3Ga0e0AC3ZM
// SIG // CIVUA4M2QLjcasL4eCGuGSOVaMo+G+81gIZrq6cKTKYo
// SIG // 8/onnlsH+mXZsrEY0f8melF5hmsCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQcOsEpU2eoBV5dOcP7NxmtX+dcJzAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAKjbVWCzutUzLiGpwu3JbdIvl
// SIG // 0UWx8J8DaNOUN7OKaRbXeJwpgf0yTwyerrxK8sbNL8OW
// SIG // Po0MFIip4ZdlRhsCKtKVgyLmluKaTFdaWEHyenbQRpEY
// SIG // kz9XilbwEWGTEWiE3vWYcCSZ2D/N6TMRwsWhLGQuIpWN
// SIG // /+eXaneGV0ws/3KRuWp5g2q7Z1poMrMoDbLU8G1iSUY/
// SIG // OYGEZI8Yv58SgIhBcZehn5HJ11cvA0RUI9XdwIqrHj6H
// SIG // iM8btYrgCUcA633uDZyh6qE4FrL+3gliZ1o1lkbe0URq
// SIG // 6b8y0KPwcVG/IuPVMEYPRuW8aXeUrtW9tuBr+htR0VPq
// SIG // iRwdc6HuNQ9q/4nNgT6LrFfZ3mCuaiOTxy7IQJ+mE0JZ
// SIG // W1faQmzlL2TtHbXcKeRx9n8OqHyTcCnDxJWqpBHMb64Y
// SIG // UVqsDYGhFU8iFeIzHPIz28djYfcwM7Z2/TX5wxThPv4B
// SIG // fHGak2v0+uUxjT97jIj94K/JyF0NiEcDFVKC5hrtqn5o
// SIG // Q6HsLN3XL5OrNWgOplx8PjADRCAyio8N4thuibWZBHpr
// SIG // tTl7bJIP7Rp38sGjIKuQmrlPW+np07QPlBPhip5okFum
// SIG // FBz4QSNC9kBu+k0Qa3uT6TVR4snP9NW41BDKXmgfiJwB
// SIG // +Jw8WF8dfMGyRPnvyGzL9NeOxBS+/dnRCxdF8KqnFNEw
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDTTCC
// SIG // AjUCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpFMDAyLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUA4hxFugmt5+QYGVf7UP3wkdPU3/eggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjdDkcwIhgPMjAyMzEwMjAxNDMz
// SIG // NDNaGA8yMDIzMTAyMTE0MzM0M1owdDA6BgorBgEEAYRZ
// SIG // CgQBMSwwKjAKAgUA6N0ORwIBADAHAgEAAgIXWjAHAgEA
// SIG // AgITnzAKAgUA6N5fxwIBADA2BgorBgEEAYRZCgQCMSgw
// SIG // JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIB
// SIG // AAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQAlyKoFZDQe
// SIG // bzs6XVy5bvmGQAD02K8psIX5/clUV6vjOnuSgJqGbNK2
// SIG // T9KqkhwZGAqYmOOxHMvVmo9Dx5tno2pYr2BwHc6kgSiR
// SIG // 0WFW/GQBLhSfelmlHJvuNFgfmw+pslG7NepOseQtoMTb
// SIG // OqlIjbsHi3cQnMj1TIOEOw6q7FBmGfwwYZ+HaYtkfX8N
// SIG // pewZX4/HAadzuTPQOfWo1uJeY3RWO+X8l1GZ5GXoc4wv
// SIG // yR8E75dGD9py1ohry1wQOJdF/buqqGo18Ki68dK7x5Ui
// SIG // fETATw+9vxkpebdrngE6hCuRmDKVFkKHF1NEVuvU2aXx
// SIG // UbSPzInzPRjSUWdNmyjUBTkuMYIEDTCCBAkCAQEwgZMw
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHZ
// SIG // nFwFkrCDaz4AAQAAAdkwDQYJYIZIAWUDBAIBBQCgggFK
// SIG // MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkq
// SIG // hkiG9w0BCQQxIgQg29sImGV4nsFHEBrzUC7uutVToxc5
// SIG // dR2AK/DDg6qIt00wgfoGCyqGSIb3DQEJEAIvMYHqMIHn
// SIG // MIHkMIG9BCCfoBWyLTpv1DAwJxE82yXtLtA1ndjIKYG9
// SIG // EnG0IAd58zCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwAhMzAAAB2ZxcBZKwg2s+AAEAAAHZMCIE
// SIG // IPUOVde2gAWjKyuqhiqZlCJPYyMfrswf0/G6vlVRSyHR
// SIG // MA0GCSqGSIb3DQEBCwUABIICALVFlI2tB2rynfOWfRx/
// SIG // sCQDqZTSNb2FeyDVulb/6yMgMCk2BGTNIejVKEWSTS19
// SIG // 9qwJRZ7ewqwJzSRBeE0CGhQgdTeaGrqck1235KVU90jM
// SIG // e6bCG14LTjAcKHb4vVA96neP0QBQ86zabIwSGSggRPzm
// SIG // OEEKrjODJb1yUCH8C2T5RL3bCBhIQdR813sv59VSdHll
// SIG // lxCXqqSoUz23tI0rMoIWORS83Vlr+EHC+yoZYWUm5Scr
// SIG // UbILEur8polIKCi6fpWEgBjmSrrUI6JqZdh+C9HJGUcX
// SIG // eU+eMa4zuPp0Iuh+lz4eI8Cqx9EKwiOw0MXLa6Zi1L+Y
// SIG // zEnTqc5PY4cHsGHUnA7qx1EGyIRgO6EgeOzW5l/mvXaB
// SIG // 225wo8wWmGkviEzjYBbmTr7AbVbXJAYIInJzi3KKJr3E
// SIG // Xyk9ezAcDp5ViLWnPHUbjyMlFuesOfuLNdzmyebLEvtT
// SIG // 0rXyXM/Hj7nnZqv82OIlaBk+urJro0aLo9vRapL7yGYP
// SIG // iw68eK2TfT4yC1XvLlxfIlSF2doYTuq4rxeq07xlMnad
// SIG // LRfsaVZa35Oj0HVAUU1AuVbzkN6OKv1jEqShv9i0ehEX
// SIG // c14dy3GkSONnmZFQ0Wxfp1a/0oCDiP09VoRZyKdrx2lk
// SIG // U2yr6nXZHXYDzDRx6BURrD51ttOL2I+f5wlWXPleENEq
// SIG // C0RM
// SIG // End signature block
