define("activeCollectionViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,l,o,i)=>{return n={1655:e=>{const t=document.createElement("script");t.id="ActionLinkView",t.innerHTML=atob("PGRpdiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6IHN0YXR1c1RleHQiPjwvZGl2Pg0KPGEgcm9sZT0ibGluayIgdGFiaW5kZXg9IjAiDQogICAgZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBsaW5rVGV4dCwNCiAgICAgICAgY2xpY2s6IGFjdGlvbiwNCiAgICAgICAgb25FbnRlcjogYWN0aW9uLA0KICAgICAgICBjc3M6IHsgJ2h5cGVybGluay1kaXNhYmxlZCc6IGFjdGlvblBlbmRpbmcgfSwNCiAgICAgICAgbG9jYWxpemVkQXJpYUxhYmVsOiBsaW5rVGV4dCI+DQo8L2E+"),t.type="text/html",document.head.appendChild(t),e.exports={}},4198:e=>{const t=document.createElement("script");t.id="EnableSamplingButtonView",t.innerHTML=atob("PGRpdiBpZD0iZW5hYmxlVmlld0J1dHRvbiI+DQogICAgPGJ1dHRvbiBjbGFzcz0idG9nZ2xlLWJ1dHRvbiIgdHlwZT0iYnV0dG9uIiByb2xlPSJidXR0b24iIGRhdGEtYmluZD0iDQogICAgICAgICAgICBjc3M6IHsNCiAgICAgICAgICAgICAgICB0b2dnbGVkOiB0b2dnbGVkLA0KICAgICAgICAgICAgICAgIGVuYWJsZWQ6IGVuYWJsZWQNCiAgICAgICAgICAgIH0sDQogICAgICAgICAgICB0b29sdGlwOiB0b29sdGlwLA0KICAgICAgICAgICAgYXR0cjogew0KICAgICAgICAgICAgICAgICdhcmlhLXByZXNzZWQnOiB0b2dnbGVkLA0KICAgICAgICAgICAgICAgICdhcmlhLWRpc2FibGVkJzogIWVuYWJsZWQoKQ0KICAgICAgICAgICAgfSwNCiAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ0J1dHRvbkFyaWFMYWJlbF9Eb3ROZXRBbGxvY1Byb2ZpbGluZycsDQogICAgICAgICAgICBjbGljazogb25DbGljaywNCiAgICAgICAgICAgIG9uRW50ZXI6IG9uQ2xpY2siPg0KICAgICAgICA8ZGl2IGNsYXNzPSJidXR0b24taW1hZ2UgaWNvbiIgZGF0YS1iaW5kPSJzdmdJbWFnZTogaWNvbiI+PC9kaXY+DQogICAgICAgIDxzcGFuIGNsYXNzPSJidXR0b24tdGV4dCIgZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiAnQnV0dG9uX0RvdE5ldEFsbG9jUHJvZmlsaW5nJyI+PC9zcGFuPg0KICAgIDwvYnV0dG9uPg0KPC9kaXY+"),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},5701:function(e,t,l){var o,i,n=this&&this.__createBinding||(Object.create?function(e,t,l,o){void 0===o&&(o=l),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[l]}})}:function(e,t,l,o){void 0===o&&(o=l),e[o]=t[l]}),s=this&&this.__exportStar||function(e,t){for(var l in e)"default"===l||Object.prototype.hasOwnProperty.call(t,l)||n(t,e,l)};o=[l,t,l(3432),l(3028),l(9371),l(8117),l(8117),l(4881),l(952),l(9321),l(3766),l(5758),l(833),l(1655)],i=function(e,t,l,o,i,n,a,r,c,d,g,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getActiveCollectionViewModel=t.ActiveCollectionViewModel=void 0,s(i,t);class b{constructor(){this._neverBeenEnabled=o.observable(!0),this._enablePending=o.observable(!1),this._collectionEnabled=o.observable(!1),this._globalCollectionEnabled=!1,this._pauseResumeEnabled=!0,this._agentErrorMessage=o.observable(""),this._telemetry=new u.DotNetObjectAllocTelemetryMarshaler,this._currentOverlay=o.pureComputed((()=>this.computeOverlay())),Promise.all([C.isCollectionEnabled(),C.isGlobalCollectionEnabled(),C.isPauseResumeSupported()]).then((e=>{const t=e[0];this._globalCollectionEnabled=e[1],this._pauseResumeEnabled=e[2],this._neverBeenEnabled(!t),this._collectionEnabled(t),this._enableSamplingButtonViewModel=new d.EnableSamplingButtonViewModel((()=>{this.setCollectionEnabled(!this._collectionEnabled())})),this._enableSamplingButtonViewModel.toggled(this._collectionEnabled()),this._collectionEnabled.subscribe((e=>{this._telemetry.collectionToggled(e),this._enableSamplingButtonViewModel.toggled(e)})),this._enablePending.subscribe((e=>{this._agentErrorMessage(""),this._enableSamplingButtonViewModel.enabled(!e)})),C.onUpdateCollection.addEventListener(this.onCollectionUpdated.bind(this))})).then((()=>{o.applyBindings(this),a.getViewEventManager().detailsViewReady.raiseEvent({Id:c.ActiveCollectionViewId()})}))}get enableSamplingButtonViewModel(){return this._enableSamplingButtonViewModel}get currentOverlay(){return this._currentOverlay}get globalCollectionEnabled(){return this._globalCollectionEnabled}setCollectionEnabled(e){return this._enablePending(!0),C.setCollectionEnabled(e)}onCollectionUpdated(e){this._enablePending(!1),e.hresult<0?this._agentErrorMessage(l.Resources.getString("ActiveCollectionViewCannotEnableProfiling",e.errorMessage)):(this._neverBeenEnabled()&&e.isEnabled&&this._neverBeenEnabled(!1),this._collectionEnabled(e.isEnabled))}computeOverlay(){return this._agentErrorMessage()?{name:"MessageView",data:this._agentErrorMessage()}:this._neverBeenEnabled()?{name:"ActionLinkView",data:{action:()=>this.setCollectionEnabled(!this._collectionEnabled()),actionPending:this._enablePending,linkText:"Overlay_EnableProfiling",statusText:"Overlay_ProfilingDisabled"}}:{name:"ActionLinkView",data:{action:()=>n.getCurrentSession().stopCollection(),actionPending:!1,linkText:"Overlay_StopCollection",statusText:this._collectionEnabled()?"Overlay_CollectingData":"Overlay_CollectionPaused"}}}}let h;t.ActiveCollectionViewModel=b;const C=new g.DotNetObjectAllocMarshaler;C.getDoubleClickTimeMs().then((e=>{r.Init(e),h=new b})),t.getActiveCollectionViewModel=function(){return h}}.apply(t,o),void 0===i||(e.exports=i)},9321:(e,t,l)=>{var o,i;o=[l,t,l(3432),l(3028),l(4198)],i=function(e,t,l,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EnableSamplingButtonViewModel=void 0,t.EnableSamplingButtonViewModel=class{constructor(e){this._toggled=o.observable(!1),this._enabled=o.observable(!0),this._clickHandler=e,this._tooltip=o.pureComputed((()=>JSON.stringify({content:this._toggled()?l.Resources.getString("ButtonTooltip_DotNetAllocProfilingToggled"):l.Resources.getString("ButtonTooltip_DotNetAllocProfilingNotToggled")}))),this._icon=o.pureComputed((()=>this._toggled()?"diagnosticsHub-dotNetAllocEnabled":"diagnosticsHub-dotNetAllocDisabled"))}get toggled(){return this._toggled}get enabled(){return this._enabled}get tooltip(){return this._tooltip}get icon(){return this._icon}onClick(e,t){return this._enabled()&&this._clickHandler(t),!1}}}.apply(t,o),void 0===i||(e.exports=i)},952:(e,t,l)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[l,t]),void 0===o||(e.exports=o)},9371:(e,t,l)=>{var o,i;o=[l,t,l(8558)],i=function(e,t,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.DotNetObjectAllocUI_OnAfterDomInsert=l.onAfterDomInsert}.apply(t,o),void 0===i||(e.exports=i)},3766:(e,t,l)=>{var o,i;o=[l,t,l(3432),l(8117)],i=function(e,t,l,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let i=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===i&&(i=l.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new o.ObservableEvent(i,"onGoToAllocation"),this._onCrossReferenceEvent=new o.ObservableEvent(i,"onCrossReferenceEvent"),this._graphHighlightEvent=new o.ObservableEvent(i,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new o.ObservableEvent(i,"updateNativeCodeEvent"),this._updateCollectionEvent=new o.ObservableEvent(i,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return i._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return i._call("crossReference",e)}updateGraphHighlight(e){return i._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return i._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}graphHighlightingFeatureEnabled(){return i._call("graphHighlightingFeatureEnabled")}getDoubleClickTimeMs(){return i._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return i._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return i._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return i._call("getColumnSettings",e)}onColumnChanged(e,t){return i._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return i._call("isCollectionEnabled")}isGlobalCollectionEnabled(){return i._call("isStartPausedSupported")}isPauseResumeSupported(){return i._call("isPauseResumeSupported")}setCollectionEnabled(e){return i._call("setCollectionEnabled",e)}openLink(e){return i._call("openLink",e)}isTopInsightsSupported(){return i._call("isTopInsightsSupported")}}}.apply(t,o),void 0===i||(e.exports=i)},5758:(e,t,l)=>{var o,i;o=[l,t,l(3432)],i=function(e,t,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let o=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===o&&(o=l.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){o._post("searchIsUsed")}searchOptionsChanged(){o._post("searchOptionsChanged")}crossReferenceUsed(){o._post("crossReferenceUsed")}goToSourceUsed(){o._post("goToSourceUsed")}hotPathUsed(){o._post("hotPathUsed")}collectionToggled(e){o._post("collectionToggled",e)}topInsightLearnMore(e,t,l){o._post("topInsightsLearnMore",e,t,l)}goToAllocationView(e){o._post("goToAllocationView",e)}}}.apply(t,o),void 0===i||(e.exports=i)},8558:(e,t,l)=>{var o,i;o=[l,t,l(3028),l(2560)],i=function(e,t,l,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=l.utils.domData.get(e,"mediaQuery");if(t){const o=l.utils.domData.get(e,"mediaQueryListener");t.removeListener(o)}let i=45;const n=e.children;for(let e=0;e<n.length;e++)i+=n.item(e).offsetWidth;const s=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},a=window.matchMedia(o.Utilities.formatString("(max-width: {0}px)",i.toString()));s(a),a.addListener(s),l.utils.domData.set(e,"mediaQuery",a),l.utils.domData.set(e,"mediaQueryListener",s)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,o),void 0===i||(e.exports=i)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=l},3028:e=>{"use strict";e.exports=o},3432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},s={},function e(t){var l=s[t];if(void 0!==l)return l.exports;var o=s[t]={exports:{}};return n[t].call(o.exports,o,o.exports,e),o.exports}(5701);var n,s}));
// SIG // Begin signature block
// SIG // MIIoJwYJKoZIhvcNAQcCoIIoGDCCKBQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // vdhDwYmoVDA0en+xsV4yfY/Syx6x+5u5uv4t2d48cBug
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoJMIIaBQIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCUs+No1oTRLgs/W0Cne98Rm+RnfKvibaY4
// SIG // 8dQLZXtzyDBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAIFuLQMA
// SIG // z+fUOhstJoUXV736cH8fLlqk+gWRQ+XUwxqIsLCWU+cJ
// SIG // zuRfrazr5ChO2N+pQRGx+HZoW2dCD71YwlJEUA/R5pP2
// SIG // gw/YT6eoT7gKZkIF4OkD4qU/CGd5xTNEZWdFgBe8FqaJ
// SIG // UGETzlBwGiQCNWD750h0H2OQH5nclJ1txJmqdWzNYK/b
// SIG // rPRifLGzVwRqxxOgjYEzny4FwItpQYpWQp1dNShsPLRV
// SIG // m+gnBg7B5HG0RLXy1uD3lEsTonRBaigvB1zoTl/B0f7G
// SIG // uahvP2uGutLILqMyFrzPKZWCluNQz/GkOn5g3gptN9PW
// SIG // fg9h4pvTqofoCDjqfmgXVmxs+pmhgheTMIIXjwYKKwYB
// SIG // BAGCNwMDATGCF38wghd7BgkqhkiG9w0BBwKgghdsMIIX
// SIG // aAIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgVKKEXnb3DTM1kot26jJy
// SIG // SACQ3i19iaDb9HPEKkc2nXsCBmUohnXImhgTMjAyMzEw
// SIG // MjAxNzA0MzYuNzI3WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOjg2MDMtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6TCCByAwggUIoAMCAQICEzMAAAHXmw0eVy6MUY4A
// SIG // AQAAAdcwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNTI1MTkxMjM3WhcN
// SIG // MjQwMjAxMTkxMjM3WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // Ojg2MDMtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAxKxgpDdl/1L7jQnH
// SIG // 5dMlQTaPiyCMsxuwNdF+ZFYBp6fbPJn+GmbLpGbua7y7
// SIG // OzamjRMXMJz7hyFnaepLMI2tWMPUsU1/hNJXqvlgbnCE
// SIG // SlnXDLpiAwYCxNBG/9/wWPeWbU9V7J52rQRWYa9Li5A4
// SIG // k/R4K0W9dtrJu/2JMjIoBZE9CbqIkj16Cy+8GlBPbXiP
// SIG // UDpKI6o0ZXCAuGFTWPtlCATOUKKyjWjnc/7KPkyBeps8
// SIG // V+Z8tlP6P4jBVU378JuE/IP2KscMnvpTpmvSivfL+r8H
// SIG // v4ou9kzE1VsClxXVzsrD/RoqHF7d/HLj/XPGhNXh96uB
// SIG // XRk4CjndKxvsYQoLERfBqi0+5OfFaUJyfLvso0Vui6Jr
// SIG // eUXK6KYH/RB/HuH6A1KFMlOUO4j4MDicWIaCsUYxmZbY
// SIG // Q5qeXsfulOs7/ea3fe9+uvKRqQpLtCAeNy/wU8zHAwFe
// SIG // P8bukX3FRcGqzf8iauan2cjLKR+YHGkwlQKLl5EE3PC8
// SIG // LX8bYCM+d6jElUfXPYJEp8TOXNbR4IjF9w9hgZ0Gp/eb
// SIG // cvgnU2AAIY4AU3Mo/T+zhhDIa95cmmcY694KbOmZqOO1
// SIG // TkyPLbEmB4R7Q/AaQaIN/S+XuP5QyYPzquKxrBSksTF7
// SIG // iEWdRNPHZl+u1zO6pr5tuzvNOAoRJm/gjkfFm+OjBRBM
// SIG // +to7vsUCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBSup8C7
// SIG // /VkC9zSMRCcj7iTGejCNjTAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // UgXd1CfiLL3TAl/iu8ah2uVAbVQtQml2bx0XfrLVtJVw
// SIG // P3UzZ3gltExawaCWOfW/X5206Lj0XmpLtpd1+W5obGqO
// SIG // gwkVbqnJoVTwGcklxnqFX4+dnCxosmSxMOk0M7ug/vr4
// SIG // zThpkomztChPRnb/IUBEceURtCoK05pPHJHgtVVKrnlE
// SIG // BylQhEqkw1Aw/HV0y1gppuh6pkF+v/oCg0l4IMKXO+YY
// SIG // tgGykqOLbpTME31yXRncK7Ih45M/J8yFv2dz5zIBhVO+
// SIG // irs2BVdF8h/Q00vwzzvOkS7UIwOWZVRspkz3058O5MaI
// SIG // iyTf8pbjByJB0s6Wibwoql/g59UBkRBJzSGXkXpLy6Lq
// SIG // 6j0RCDk5tWyUSdOuXPWF+2ydJ2j4sc5ucvGNgfmCCBAI
// SIG // uI1K2jod6BO2uCbyFtxIN6Daj+6oaXe8TC8atlpzPlPW
// SIG // 6lk3k+FQqKQIV7trhkHsXS6u21nXGMMhBQ4UuGfTdLsN
// SIG // 4em4we0uDF/eqX2EhFdDChRjim5nwlEu1nppLhamctKD
// SIG // Rzz8fnH3TWHkhem4Tjx3bK6NRFXd81iJHQ9RuZBAz5xE
// SIG // LRWq7TPB/m7+c1IQFCbPKi87hQHQWUC7ng/V2Xsp40Cs
// SIG // BHgM+t8QEyAofLTlDNszIEhIVS/B5uOUgen6HrOAUwtG
// SIG // PEmVqL9yGobb8MhxW1KrNWIwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTDCCAjQCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjo4NjAzLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAMVvbosxt4RGP
// SIG // Pbi9rrvl/phv63WggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjc
// SIG // 5/UwIhgPMjAyMzEwMjAxMTUwMTNaGA8yMDIzMTAyMTEx
// SIG // NTAxM1owczA5BgorBgEEAYRZCgQBMSswKTAKAgUA6Nzn
// SIG // 9QIBADAGAgEAAgFKMAcCAQACAhNVMAoCBQDo3jl1AgEA
// SIG // MDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKg
// SIG // CjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcN
// SIG // AQELBQADggEBAJvI+HdTaDVDrMgcLk0BWWEPmJX6GZdM
// SIG // U/2CTdTUrw0aVcceOts2eK3qAxsdjSiwnB9gV16qgVwB
// SIG // L0Ionk2L/tXerrk6fa01vJg7aRM8tBk4kXWNq96CYYBK
// SIG // XpYe84jI00NYg0iE4XT3jP6WVlf2prSt0OjufCmXFLPb
// SIG // uIfvLLDRcr+s6WTUQq7yoOigW/edhsFpWe1biy/QUTxY
// SIG // lHfTbSb+N69216bUppHXoPvzpiYqChlhX7oZrqunnqvJ
// SIG // ltAzsOzXkTrSDFlPpdrzehF2m2y0EhdwiPD3AZKd2Zhn
// SIG // j8svrQW3Y/8Lrp0uN7BIX7MATOdNVgdyRbaPZC0xOnOO
// SIG // A3kxggQNMIIECQIBATCBkzB8MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFt
// SIG // cCBQQ0EgMjAxMAITMwAAAdebDR5XLoxRjgABAAAB1zAN
// SIG // BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0G
// SIG // CyqGSIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCDzqsg9
// SIG // +Fhpl4QqWq0RyawIW2ho4hdNIXfuzKRKt2HvjzCB+gYL
// SIG // KoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIJzePl5LXn1P
// SIG // iqNjx8YN7TN1ZI0d1ZX/2zRdnI97rJo7MIGYMIGApH4w
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHX
// SIG // mw0eVy6MUY4AAQAAAdcwIgQggjbMnpDhyqZWarNLJWJU
// SIG // TWduELPXY4mGpjQM823x/CkwDQYJKoZIhvcNAQELBQAE
// SIG // ggIAJT63wYxeFgkmLU1YRfgsF6gD9fsBbHcf9EZQiFfi
// SIG // 0DE/FwN7lilat4lshhuMUBXT/kOnCU93JIw5FWCQ/u18
// SIG // CCtCvSzPCERp7qpwK2WmnOtkvJBFPpyRagPzLeHjr7I9
// SIG // 1R2hluDzB9v3cb+Ap8PoO5fDSCFrgIoxjt3Y623GQFBy
// SIG // LjJwycFOoL+v3H4Uz8Y/aAuDNPNMgnWWfXmIQ3lImEkb
// SIG // IClVM/kLODrQBtoi3O0/FPCgwj2unfxWtHlxop42HDC3
// SIG // MJT0oa74V7w4FYHmVt7PNRaBIpoiadypI2TWf8o+8pTF
// SIG // 55TAwZHwCcTJQE2q5kBU7cCscGc1GLhLsPFALFypen1R
// SIG // e2DTkAnQv6R435qRita1870plx0cqKZoiHM+DMYwox+W
// SIG // ht9KA6c0WY26v/HUT25VxpXWumBQOOgpwsZ46Z6lh4F2
// SIG // /sxbgVmIa/qsmJbrNSrl36hQez2c4GNVCG+eaUGPBc2O
// SIG // VisJ4GlTN2dQWVAJm6Z0+odzBfRVWNnylFSiV5hCXhik
// SIG // ovGlEFbhoObfEkBGWflEJ/RpvSSY+d/DVERcLyARPoyt
// SIG // gpo4sa3ETb5ULFe5XfK0TDc3nAqarDk+XUrJwdP/L8FK
// SIG // RSyzOkpJNSCYelJEyAcdD/8bxMxtGr4/Nn3XXaio4C7S
// SIG // aAOD9y5YHagVKaCp8BCbjsVRwwk=
// SIG // End signature block
