define("allocationViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,o,i,a)=>{return r={8012:e=>{const t=document.createElement("script");t.id="AllocationRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGFyaWFFeHBhbmRlZDogeyBleHBhbmRhYmxlOiBleHBhbmRhYmxlLCBleHBhbmRlZDogZXhwYW5kZWQgfSwNCiAgICBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSwNCiAgICBhdHRyOiB7ICdhcmlhLWxldmVsJzogZGVwdGggKyAxIH0iPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9Im5hbWUgY29udGFpbmVyIiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8ZGl2IGNsYXNzPSJ0eXBlSWNvbiIgZGF0YS1iaW5kPSJjc3M6IHsgdmFsdWVDb2xsZWN0aW9uVHlwZTogaXNWYWx1ZUNvbGxlY3Rpb25UeXBlLCByZWZDb2xsZWN0aW9uVHlwZTogaXNSZWZDb2xsZWN0aW9uVHlwZSwgdmFsdWVUeXBlOiBpc1ZhbHVlVHlwZSwgcmVmVHlwZTogaXNSZWZUeXBlIH0iPjwvZGl2Pg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IGxhYmVsIj48L3NwYW4+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGxvY2FsaXplZFRvdGFsIiBkYXRhLWNvbHVtbmlkPSJ0b3RhbCI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkVG90YWxTaXplIiBkYXRhLWNvbHVtbmlkPSJ0b3RhbFNpemUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGxvY2FsaXplZEF2ZXJhZ2VTaXplIiBkYXRhLWNvbHVtbmlkPSJhdmVyYWdlU2l6ZSI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},9050:e=>{const t=document.createElement("script");t.id="HeapTypeRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGFyaWFFeHBhbmRlZDogeyBleHBhbmRhYmxlOiBleHBhbmRhYmxlLCBleHBhbmRlZDogZXhwYW5kZWQgfSwNCiAgICBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8ZGl2IGRhdGEtYmluZD0idHJlZUdyaWRFeHBhbmRlcjogZXhwYW5kZWQsIHN0eWxlOiB7IHZpc2liaWxpdHk6ICd2aXNpYmxlJ30iPjwvZGl2Pg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IG5hbWUiPjwvc3Bhbj4NCiAgICA8L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},8836:e=>{const t=document.createElement("script");t.id="BacktraceRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogbGFiZWwiPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkVG90YWwiIGRhdGEtY29sdW1uaWQ9InRvdGFsQmFja3RyYWNlIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRUb3RhbFNpemUiIGRhdGEtY29sdW1uaWQ9InRvdGFsU2l6ZUJhY2t0cmFjZSI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkQXZlcmFnZVNpemUiIGRhdGEtY29sdW1uaWQ9ImF2ZXJhZ2VTaXplQmFja3RyYWNlIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBtb2R1bGVOYW1lIiBkYXRhLWNvbHVtbmlkPSJtb2R1bGVOYW1lIj48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},6680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},5784:(e,t,o)=>{var i,a;i=[o,t,o(3028),o(3432),o(3735),o(3766),o(8012)],a=function(e,t,o,i,a,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.AllocationRowViewModel=void 0;class s{constructor(e,t,i,a,s){this._selected=o.observable(!1),this._expanded=o.observable(!1),this._children=o.observableArray([]),this._haveLoaded=!1,this._marshaler=new r.DotNetObjectAllocMarshaler,this._depth=i,this._parent=e,this._backtrace=a,this._dto=t,this._backtraceDao=s}get templateName(){return"AllocationRowView"}get id(){return this._dto.id}get name(){return this._dto.n}get isValueCollectionType(){return this._dto.ia&&this._dto.iv&&!this._dto.is}get isRefCollectionType(){return this._dto.ia&&!this._dto.iv&&!this._dto.is}get isValueType(){return!this._dto.ia&&this._dto.iv&&!this._dto.is}get isRefType(){return!this._dto.ia&&!this._dto.iv&&!this._dto.is}get total(){return this._dto.a}get heapType(){return this._dto.ht}get localizedTotal(){return this.total.toLocaleString(i.Culture.formatRegion)}get totalSize(){return this._dto.ts}get localizedTotalSize(){return this.totalSize.toLocaleString(i.Culture.formatRegion)}get selfSize(){return this._dto.ss}get averageSize(){return this._dto.as?this._dto.as:this._dto.ts/this._dto.a}get localizedAverageSize(){return this.averageSize.toLocaleString(i.Culture.formatRegion,{maximumFractionDigits:2})}get sourceFilePosition(){return this._dto.sfp}get label(){return this._dto.u?i.Resources.getString("UnknownTypeLabel"):""}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){this._marshaler.updateGraphHighlight(this.id),this.id===this._backtraceDao.currentTypeId&&this._dto.ht===this._backtraceDao.heapType()||(this._backtraceDao.heapType(this._dto.ht),this._backtrace.onResultChanged(this.id),this._backtraceDao.currentTypeName(this.name))}get expandable(){return this._dto.children}expand(e,t,o){let i=Promise.resolve();return this.expandable?(this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",id:this._dto.id,ht:this._dto.ht,path:this.getIdPath()},o).then((i=>{null==o||o.throwIfCancellationRequested();const r=i.map((e=>new s(this,e,this.depth+1,this._backtrace,this._backtraceDao))),l=a.AllocationTreeDAO.SortFunc[t.columnId](t.direction);return r.sort(l),this.children(r),1===r.length?r[0].expand(e,t,o):Promise.resolve()}))),this._expanded(!this._expanded()),i):i}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}}t.AllocationRowViewModel=s}.apply(t,i),void 0===a||(e.exports=a)},3735:(e,t,o)=>{var i,a;i=[o,t,o(952),o(3028),o(4881),o(4881),o(4881),o(5784),o(8558),o(7886),o(1015)],a=function(e,t,o,i,a,r,s,l,n,c,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.AllocationTreeDAO=void 0;class h{constructor(e,t,o,s,l,c,h){this._rootDataLoadStatus=i.observable(a.DataLoadEvent.DataLoadCompleted),this._rootFilter=i.observable(""),this._allRoots=i.observableArray([]),this._allAllocations=i.observableArray([]),this._heapTypeToAllocationRow=new Map,this._dataWarehouse=s,this._backtrace=e,this._backtraceDao=t,this._header=o,this._timeFilter=i.observable(l),this._timeFilter.equalityComparer=n.areTimespansEqual,this._showNative=!c,this._marshaler=h,this._marshaler.onGoToAllocation.addEventListener(this.goToAllocation.bind(this)),this._timeFilter.subscribe((e=>{this.loadData()})),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>{const t=!e.isEnabled;this._showNative!==t&&(this._showNative=t,this.loadData())})),this._filteredRoots=r.AsyncComputed((()=>{if(this._allRoots(),!this._rootFilter()||!this._currentResult)return Promise.resolve(this._allRoots());const e=Array.from(this._heapTypeToAllocationRow.keys());let t=[];return e.forEach(((e,o)=>{t.push(new d.HeapTypeRowViewModel(e,o,this._heapTypeToAllocationRow.get(e)))})),this._currentResult.getResult({task:"filter",filter:this._rootFilter()}).then((e=>(t=t.map((t=>(t.children(t.children().filter((t=>t.id in e))),t))).filter((e=>e.children().length>0)),t)))}),void 0,[]),this._timeFilter.notifySubscribers(l)}getAutoCompleteSuggestions(e){return this._currentResult?this._currentResult.getResult({task:"autocomplete",filter:e,count:10}):Promise.resolve([])}loadData(e){return this._marshaler.isNativeCodeFoldingEnabled().then((e=>({timeDomain:this.timeFilter(),customDomain:{view:"Allocations",FoldNativeFrames:e?"true":"false"}}))).then((t=>(this._rootDataLoadStatus(a.DataLoadEvent.DataLoadStart),this._dataWarehouse.getFilteredData(t,o.DotNetAllocAnalyzerId(),e)))).then((t=>(null==e||e.throwIfCancellationRequested(),this._currentResult&&this._currentResult.dispose(),this._currentResult=t,this._currentResult?this._currentResult.getResult({task:"getRoots"},e):[]))).then((t=>{null==e||e.throwIfCancellationRequested(),this._heapTypeToAllocationRow.clear(),this._allAllocations(t.map((e=>{const t=new l.AllocationRowViewModel(null,e,1,this._backtrace,this._backtraceDao);return this._heapTypeToAllocationRow.has(e.ht)||this._heapTypeToAllocationRow.set(e.ht,[]),this._heapTypeToAllocationRow.get(e.ht).push(t),t})));const o=[c.HeapType.SOH,c.HeapType.LOH,c.HeapType.POH];this._allRoots(o.filter((e=>this._heapTypeToAllocationRow.has(e))).map(((e,t)=>new d.HeapTypeRowViewModel(e,t,this._heapTypeToAllocationRow.get(e))))),this._rootDataLoadStatus(a.DataLoadEvent.DataLoadCompleted)}))}get rootFilter(){return this._rootFilter}get timeFilter(){return this._timeFilter}get filteredRoots(){return this._filteredRoots}static get defaultSortColumnId(){return"totalSize"}get rootDataLoadStatus(){return this._rootDataLoadStatus}getRoots(e,t,o){return this._filteredRoots().forEach((e=>{this.sort(e.children(),t,o)})),Promise.resolve(this._filteredRoots())}expand(e,t,o){return e.expand(this._currentResult,t,o)}search(e,t,o,i,a,r,s){throw new Error("Method not implemented.")}sort(e,t,o){const i=h.SortFunc[t.columnId](t.direction),a=function(e){e.children&&(e.children.sort(i),e.children().forEach(a))};return e.sort(i),e.forEach(a),Promise.resolve(e)}goToAllocation(e,t){this._currentResult&&this._currentResult.getResult({task:"getTypeInfo",typeId:e.value},t).then((e=>{if(null==t||t.throwIfCancellationRequested(),!e)return;let o=this._allAllocations();const i=(e,t)=>{null==t||t.throwIfCancellationRequested();const a=e.shift();let r=null;for(let e=0;e<o.length&&(r=o[e],r.id!==a);++e);r&&(e.length>0&&(r.expanded()||this.expand(r,this._header.sortInfo(),t).then((()=>{o=r.children()})).then((()=>i(e,t))),o=r.children(),i(e,t)),r.selected(!0),r.invoke())};i(e.path,t).then((()=>this._rootFilter(e.name)))}))}}t.AllocationTreeDAO=h,h.SortFunc={name:e=>s.SortFunctions.natSort("name",e),total:e=>s.SortFunctions.numericSort("total",e),totalSize:e=>s.SortFunctions.numericSort("totalSize",e),averageSize:e=>s.SortFunctions.numericSort("averageSize",e)}}.apply(t,i),void 0===a||(e.exports=a)},1015:(e,t,o)=>{var i,a;i=[o,t,o(3028),o(3432),o(7886),o(9050)],a=function(e,t,o,i,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.HeapTypeRowViewModel=void 0,t.HeapTypeRowViewModel=class{constructor(e,t,r){this._selected=o.observable(!1),this._expanded=o.observable(!0),this._children=o.observableArray([]),this._heapTypeNames={[a.HeapType.ALL]:i.Resources.getString("HeapType_ALL"),[a.HeapType.SOH]:i.Resources.getString("HeapType_SOH"),[a.HeapType.LOH]:i.Resources.getString("HeapType_LOH"),[a.HeapType.POH]:i.Resources.getString("HeapType_POH")},this._type=e,this._rowId=t,this._children(r)}get id(){return this._rowId}get name(){return this._heapTypeNames[this._type]}get templateName(){return"HeapTypeRowView"}get depth(){return 0}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return!0}expand(e){const t=Promise.resolve();return this._expanded(!this._expanded()),t}get children(){return this._children}invoke(){this._expanded(!this._expanded())}}}.apply(t,i),void 0===a||(e.exports=a)},5694:function(e,t,o){var i,a,r=this&&this.__createBinding||(Object.create?function(e,t,o,i){void 0===i&&(i=o),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[o]}})}:function(e,t,o,i){void 0===i&&(i=o),e[i]=t[o]}),s=this&&this.__exportStar||function(e,t){for(var o in e)"default"===o||Object.prototype.hasOwnProperty.call(t,o)||r(t,e,o)};i=[o,t,o(3432),o(3028),o(9371),o(4881),o(4881),o(4881),o(4881),o(2560),o(8117),o(8117),o(8117),o(8117),o(8117),o(4881),o(952),o(3766),o(5758),o(7886),o(3735),o(361),o(4982),o(118),o(4881),o(4881),o(6680),o(833),o(4103)],a=function(e,t,o,i,a,r,l,n,c,d,h,u,g,p,m,_,b,I,v,C,w,R,T,S,A,y){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getAllocationViewModel=t.AllocationViewModel=void 0,s(a,t);class D{constructor(){this._marshaler=new I.DotNetObjectAllocMarshaler,this._telemetry=new v.DotNetObjectAllocTelemetryMarshaler,this._logger=u.getLogger("AllocationViewModel"),this._automation=g.getAutomationManager(this._logger),this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._backtraceOverlay=i.pureComputed((()=>this.computeBacktraceOverlay())),this._backtraceType=i.pureComputed((()=>o.Resources.getString("BacktraceTypeDisplay",this._backtraceDao.currentTypeName()))),h.loadDataWarehouse().then((e=>(this._dataWarehouse=e,this._dataWarehouse.getContextService().getGlobalContext()))).then((e=>Promise.all([this._dataWarehouse.getJmcService().getJmcEnabledState(),e.getTimeDomain(),this._marshaler.isNativeCodeFoldingEnabled()]))).then((e=>{this._showJmc=new y.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(e[0]),this._showJmc.isChecked.subscribe((()=>{this._dataWarehouse.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new y.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked(!e[2]),this._showNative.isChecked.subscribe((()=>{this._marshaler.setNativeCodeFoldingEnabled(!this._showNative.isChecked()),this._backtraceTree.onResultChanged(R.BacktraceDAO.NewFilterRequest)})),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>this._showNative.isChecked(!e.isEnabled))),this._marshaler.onCrossReferenceEvent.addEventListener((e=>this.crossReferenceEvent(e))),this._backtraceDao=new R.BacktraceDAO(this._dataWarehouse,e[1],this._marshaler);const t=o.Resources.getString,a=new n.TreeGridHeaderViewModel([{id:"name",text:t("HeaderName"),tooltip:t("HeaderNameToolTip"),hideable:!1,sortable:r.SortDirection.Asc},{id:"totalBacktrace",text:t("HeaderTotalAllocCount"),tooltip:t("HeaderTotalAllocCountToolTipFunction"),hideable:!0,sortable:r.SortDirection.Desc},{id:"totalSizeBacktrace",text:t("HeaderTotalAllocSize"),tooltip:t("HeaderTotalAllocSizeToolTipFunction"),hideable:!0,sortable:r.SortDirection.Desc},{id:"averageSizeBacktrace",text:t("HeaderAverageSize"),tooltip:t("HeaderAverageSizeToolTipFunction"),hideable:!0,sortable:r.SortDirection.Desc},{id:"moduleName",text:t("HeaderModuleName"),tooltip:t("HeaderModuleNameToolTip"),hideable:!0,sortable:r.SortDirection.Asc}],new S.DotNetObjectAllocColumnSettingsProvider("BackTraceView"),this._backtraceDao.defaultSortColumnId);this._backtraceTree=new l.TreeGridViewModel(this._backtraceDao,a,"BacktraceAriaLabel");const s=new n.TreeGridHeaderViewModel([{id:"name",text:t("AllocationTreeHeaderName"),tooltip:t("AllocationTreeHeaderNameToolTip"),hideable:!1,sortable:r.SortDirection.Asc},{id:"total",text:t("HeaderTotalAllocCount"),tooltip:t("HeaderTotalAllocCountToolTipType"),hideable:!0,sortable:r.SortDirection.Desc},{id:"totalSize",text:t("HeaderTotalAllocSize"),tooltip:t("HeaderTotalAllocSizeToolTipType"),hideable:!0,sortable:r.SortDirection.Desc},{id:"averageSize",text:t("HeaderAverageSize"),tooltip:t("HeaderAverageSizeToolTipType"),hideable:!0,sortable:r.SortDirection.Desc}],new S.DotNetObjectAllocColumnSettingsProvider("AllocationView"),w.AllocationTreeDAO.defaultSortColumnId);this._allocationDao=new w.AllocationTreeDAO(this._backtraceTree,this._backtraceDao,s,this._dataWarehouse,e[1],e[2],this._marshaler),this._allocationTree=new l.TreeGridViewModel(this._allocationDao,s,"AllocationTreeAriaLabel"),this._allocationTree.onResultChanged(0),this._allocationDao.filteredRoots.subscribe((()=>this._allocationTree.onResultChanged(0)));const c=p.getViewEventManager();c.selectionChanged.addEventListener((e=>{e.isIntermittent||(this._allocationDao.timeFilter(e.position),this._backtraceDao.timeFilter(e.position))})),this._backtraceDao.timeFilter.subscribe((()=>this._backtraceTree.onResultChanged(R.BacktraceDAO.NewFilterRequest))),c.jmcEnabledStateChanged.addEventListener((e=>{this.showJmc.isChecked(e.currEnabledState),this._backtraceTree.onResultChanged(R.BacktraceDAO.NewFilterRequest),this.allocationTree.selectedRows([])})),this._autocompleteViewModel=new A.AutoCompleteViewModel(this._allocationDao.rootFilter,this._allocationDao.getAutoCompleteSuggestions.bind(this._allocationDao)),i.applyBindings(this),c.detailsViewReady.raiseEvent({Id:b.AllocationDetailsViewId()})}))}get allocationTree(){return this._allocationTree}get backtraceTree(){return this._backtraceTree}get filterText(){return this._allocationDao.rootFilter}get autoCompleteViewModel(){return this._autocompleteViewModel}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get showJmcButtonEnabled(){return!0}get currentOverlay(){return this._currentOverlay}get backtraceOverlay(){return this._backtraceOverlay}get backtraceType(){return this._backtraceType}onKeyDownTypes(e,t){if(!t.ctrlKey||t.keyCode!==d.KeyCodes.C)return!0;const o=c.TreeGridUtils.formatTreeGridSelectedToText(this._allocationTree,!1);return navigator.clipboard.writeText(o),!1}onKeyDownBacktrace(e,t){if(!t.ctrlKey||t.keyCode!==d.KeyCodes.C)return!0;const o=c.TreeGridUtils.formatTreeGridSelectedToText(this._backtraceTree);return navigator.clipboard.writeText(o),!1}contextMenu(e,t){const i=e;if("number"!=typeof i.id)return null;const a=()=>{const e=i;this._telemetry.goToSourceUsed(),e&&("unsearched"===i.sourceFilePosition.sourceFile.path.toLowerCase()?this._backtraceDao.getSourceInfo(e.AggregationId).then((t=>{e.sourceFilePosition=t,t?m.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition):this._automation.getAlertPromise(g.AutomationConstants.DataWarehouseRequestKey,o.Resources.getString("NoSource"))})):m.getSourceFileViewerService().openSourcePosition(i.sourceFilePosition))},s=[];let l=this._allocationTree;if(i instanceof T.BacktraceRowViewModel){const e=()=>this._marshaler.crossReference({rowId:i.AggregationId,rowType:r.RowType.Function,viewToShow:C.ToolView.FunctionsListView});l=this._backtraceTree,s.push({label:o.Resources.getString("ContextMenu_ShowInFunctions"),callback:e,type:o.ContextMenu.MenuItemType.command},{label:o.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>a(),disabled:()=>!i.sourceFilePosition,type:o.ContextMenu.MenuItemType.command},{type:o.ContextMenu.MenuItemType.separator})}const n=i instanceof T.BacktraceRowViewModel;return s.push({label:o.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToText(l,n);navigator.clipboard.writeText(e)},type:o.ContextMenu.MenuItemType.command},{label:o.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToMarkdown(l,n);navigator.clipboard.writeText(e)},type:o.ContextMenu.MenuItemType.command}),o.ContextMenu.create(s)}computeOverlay(){return this._allocationDao.rootDataLoadStatus()===r.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._allocationDao.rootDataLoadStatus()===r.DataLoadEvent.DataLoadCompleted&&0===this._allocationTree.treeAsArray().length?{name:"MessageView",data:o.Resources.getString("NoAllocationDataMessage")}:null}computeBacktraceOverlay(){return this._backtraceDao.dataLoadStatus()===r.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._backtraceDao.dataLoadStatus()===r.DataLoadEvent.DataLoadCompleted&&0===this._backtraceTree.roots().length?{name:"MessageView",data:o.Resources.getString("SelectTypeMessage")}:null}crossReferenceEvent(e){e.viewToShow===C.ToolView.Allocations&&(this._telemetry.crossReferenceUsed(),this._marshaler.clearGraphHighlight(),this._allocationTree.dataLoadPromise.then((()=>this._allocationDao.goToAllocation({value:e.rowId}))))}}let k;t.AllocationViewModel=D,(new I.DotNetObjectAllocMarshaler).getDoubleClickTimeMs().then((e=>{_.Init(e),k=new D})),t.getAllocationViewModel=function(){return k}}.apply(t,i),void 0===a||(e.exports=a)},361:(e,t,o)=>{var i,a;i=[o,t,o(952),o(3028),o(4881),o(4881),o(4982),o(8558)],a=function(e,t,o,i,a,r,s,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BacktraceDAO=void 0;class n{constructor(e,t,o){this._dataLoadStatus=i.observable(a.DataLoadEvent.DataLoadCompleted),this._currentTypeId=-1,this._currentSelectedTypeName=i.observable(""),this._heapType=i.observable(""),this._dataWarehouse=e,this._timeFilter=i.observable(t),this._timeFilter.equalityComparer=l.areTimespansEqual,this._marshaler=o}getRoots(e,t,i){this._dataLoadStatus(a.DataLoadEvent.DataLoadStart),this._currentTypeId=e;let r=!1;e===n.NewFilterRequest&&(this._currentResult&&(this._currentResult.dispose(),this._currentResult=null),r=!0);let l=Promise.resolve(this._currentResult);return!this._currentResult&&(l=this._marshaler.isNativeCodeFoldingEnabled().then((e=>({timeDomain:this.timeFilter(),customDomain:{view:"Backtrace",FoldNativeFrames:e?"true":"false"}}))).then((e=>this._dataWarehouse.getFilteredData(e,o.DotNetAllocAnalyzerId(),i))),r)?l.then((()=>(this._dataLoadStatus(a.DataLoadEvent.DataLoadCompleted),Promise.resolve([])))):l.then((e=>{null==i||i.throwIfCancellationRequested();const t=this._dataWarehouse.getJmcService().getJmcEnabledState();this._currentResult=e;const o=Promise.resolve(this._currentResult.getResult({task:"getRoots",typeId:this._currentTypeId,heapType:this._heapType()},i));return Promise.all([o,t])})).then((e=>{null==i||i.throwIfCancellationRequested();const o=e[0],r=e[1],l=o.map((e=>new s.BacktraceRowViewModel(null,this,this._currentTypeId,this._heapType(),e,0,r)));return this._dataLoadStatus(a.DataLoadEvent.DataLoadCompleted),1===l.length?this.expand(l[0],t,i).then((()=>l)):Promise.resolve(l)})).then((e=>this.sort(e,t,i)))}get timeFilter(){return this._timeFilter}expand(e,t,o){return e.expand(this._currentResult,t,o)}search(e,t,o,i,a,r,s){throw new Error("Method not implemented.")}sort(e,t,o){const i=n.SortFunc[t.columnId](t.direction),a=e=>{e.children&&(e.children.sort(i),e.children().forEach(a))};return e.sort(i),e.forEach(a),Promise.resolve(e)}get defaultSortColumnId(){return"totalSizeBacktrace"}get currentTypeId(){return this._currentTypeId}get dataLoadStatus(){return this._dataLoadStatus}get currentTypeName(){return this._currentSelectedTypeName}get heapType(){return this._heapType}getSourceInfo(e){return this._currentResult.getResult({task:"getSourceInfo",rowId:e})}}t.BacktraceDAO=n,n.NewFilterRequest=-1,n.SortFunc={name:e=>r.SortFunctions.stringSort("name",e),totalBacktrace:e=>r.SortFunctions.numericSort("total",e),totalSizeBacktrace:e=>r.SortFunctions.numericSort("totalSize",e),averageSizeBacktrace:e=>r.SortFunctions.numericSort("averageSize",e),moduleName:e=>r.SortFunctions.stringSort("moduleName",e)}}.apply(t,i),void 0===a||(e.exports=a)},4982:(e,t,o)=>{var i,a;i=[o,t,o(3028),o(3432),o(4881),o(8836)],a=function(e,t,o,i,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BacktraceRowViewModel=void 0;class r{constructor(e,t,i,a,r,s,l){this._selected=o.observable(!1),this._expanded=o.observable(!1),this._haveLoaded=!1,this._jmcEnabled=!1,this._dto=r,this._depth=s,this._jmcEnabled=l,this._parent=e,this._dao=t,this._typeId=i,this._heapType=a,this._children=o.observableArray([]),this._label=o.pureComputed((()=>this.computeLabel()))}get templateName(){return"BacktraceRowView"}get id(){return this._dto.id}get name(){return this._dto.n}get label(){return this._label}get depth(){return this._depth}get selected(){return this._selected}get children(){return this._children}get expanded(){return this._expanded}invoke(){}get total(){return this._dto.t}get localizedTotal(){return this.total.toLocaleString(i.Culture.formatRegion)}get totalSize(){return this._dto.ts}get localizedTotalSize(){return this.totalSize.toLocaleString(i.Culture.formatRegion)}get averageSize(){return this._dto.ts/this._dto.t}get localizedAverageSize(){return this.averageSize.toLocaleString(i.Culture.formatRegion,{maximumFractionDigits:2})}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get AggregationId(){return this._dto.aId}get moduleName(){switch(this._dto.mc){case 0:return i.Resources.getString("UnknownModuleLabel");case 1:return this._dto.mn;default:return i.Resources.getString("MultipleModuleLabel")}}get expandable(){return void 0===this._dto.c||this._children().length>0}computeLabel(){if(this._dto.a===a.AggregateType.BrokenStack)return i.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case a.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");case a.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");default:return""}if(this._dto.n)switch(this._dto.j){case a.JmcState.SystemCode:return i.Resources.getString("SystemCallLabel");case a.JmcState.LibraryCode:return i.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case a.AggregateType.SystemCode:return i.Resources.getString("SystemCodeLabel");case a.AggregateType.JmcRejected:return i.Resources.getString("ExternalCodeLabel");case a.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");case a.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");default:return""}}expand(e,t,o){let i=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",typeId:this._typeId,heapType:this._heapType,id:this._dto.id,path:this.getIdPath()},o).then((e=>{null==o||o.throwIfCancellationRequested();const i=e.map((e=>new r(this,this._dao,this._typeId,this._heapType,e,this.depth+1,this._jmcEnabled)));return this._dao.sort(i,t)})).then((i=>(null==o||o.throwIfCancellationRequested(),this.children(i),1===i.length?i[0].expand(e,t,o):Promise.resolve())))),this._expanded(!this._expanded()),i}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}}t.BacktraceRowViewModel=r}.apply(t,i),void 0===a||(e.exports=a)},118:(e,t,o)=>{var i,a;i=[o,t,o(3766)],a=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocColumnSettingsProvider=void 0,t.DotNetObjectAllocColumnSettingsProvider=class{constructor(e){this._marshaler=new o.DotNetObjectAllocMarshaler,this._templateName=e}getColumnSettings(){return this._marshaler.getColumnSettings(this._templateName)}onColumnChanged(e){this._marshaler.onColumnChanged(this._templateName,e)}}}.apply(t,i),void 0===a||(e.exports=a)},952:(e,t,o)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[o,t]),void 0===i||(e.exports=i)},9371:(e,t,o)=>{var i,a;i=[o,t,o(8558)],a=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.DotNetObjectAllocUI_OnAfterDomInsert=o.onAfterDomInsert}.apply(t,i),void 0===a||(e.exports=a)},7886:(e,t,o)=>{var i;i=function(e,t){"use strict";var o,i;Object.defineProperty(t,"__esModule",{value:!0}),t.HeapType=t.ToolView=void 0,(i=t.ToolView||(t.ToolView={}))[i.FunctionsListView=1]="FunctionsListView",i[i.CallTreeView=2]="CallTreeView",i[i.Allocations=3]="Allocations",(o=t.HeapType||(t.HeapType={}))[o.ALL=0]="ALL",o[o.SOH=1]="SOH",o[o.LOH=2]="LOH",o[o.POH=3]="POH"}.apply(t,[o,t]),void 0===i||(e.exports=i)},3766:(e,t,o)=>{var i,a;i=[o,t,o(3432),o(8117)],a=function(e,t,o,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let a=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===a&&(a=o.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new i.ObservableEvent(a,"onGoToAllocation"),this._onCrossReferenceEvent=new i.ObservableEvent(a,"onCrossReferenceEvent"),this._graphHighlightEvent=new i.ObservableEvent(a,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new i.ObservableEvent(a,"updateNativeCodeEvent"),this._updateCollectionEvent=new i.ObservableEvent(a,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return a._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return a._call("crossReference",e)}updateGraphHighlight(e){return a._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return a._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}graphHighlightingFeatureEnabled(){return a._call("graphHighlightingFeatureEnabled")}getDoubleClickTimeMs(){return a._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return a._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return a._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return a._call("getColumnSettings",e)}onColumnChanged(e,t){return a._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return a._call("isCollectionEnabled")}isGlobalCollectionEnabled(){return a._call("isStartPausedSupported")}isPauseResumeSupported(){return a._call("isPauseResumeSupported")}setCollectionEnabled(e){return a._call("setCollectionEnabled",e)}openLink(e){return a._call("openLink",e)}isTopInsightsSupported(){return a._call("isTopInsightsSupported")}}}.apply(t,i),void 0===a||(e.exports=a)},5758:(e,t,o)=>{var i,a;i=[o,t,o(3432)],a=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let i=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===i&&(i=o.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){i._post("searchIsUsed")}searchOptionsChanged(){i._post("searchOptionsChanged")}crossReferenceUsed(){i._post("crossReferenceUsed")}goToSourceUsed(){i._post("goToSourceUsed")}hotPathUsed(){i._post("hotPathUsed")}collectionToggled(e){i._post("collectionToggled",e)}topInsightLearnMore(e,t,o){i._post("topInsightsLearnMore",e,t,o)}goToAllocationView(e){i._post("goToAllocationView",e)}}}.apply(t,i),void 0===a||(e.exports=a)},8558:(e,t,o)=>{var i,a;i=[o,t,o(3028),o(2560)],a=function(e,t,o,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const i=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}let a=45;const r=e.children;for(let e=0;e<r.length;e++)a+=r.item(e).offsetWidth;const s=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},l=window.matchMedia(i.Utilities.formatString("(max-width: {0}px)",a.toString()));s(l),l.addListener(s),o.utils.domData.set(e,"mediaQuery",l),o.utils.domData.set(e,"mediaQueryListener",s)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,i),void 0===a||(e.exports=a)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=o},3028:e=>{"use strict";e.exports=i},3432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},s={},function e(t){var o=s[t];if(void 0!==o)return o.exports;var i=s[t]={exports:{}};return r[t].call(i.exports,i,i.exports,e),i.exports}(5694);var r,s}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // F8WpA8PMrBof//F97WucjLqcgr4HyXEkGF3MDn0ONwGg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCC0fxwntYX3nPH0DYiMVI8U23bcRWYv2BsC
// SIG // uwyYMJjmYDBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAAg4TId4
// SIG // cvznKhxXum2ERHRpg4NoderKGoFP/BjVQsP9mUSYw3YB
// SIG // +OrCsWGb13mxDPjKGYIrrUgume5vcGaFSpdOsP55XzxI
// SIG // cvI7QGKnl5PnU8bI3Z34RRZuvXkkmCnBfd+8ffoWqnsG
// SIG // 7kCZB0zRm+bLPRc5vyqkjmiZoSch9r93LtJTBj/yvlXI
// SIG // NDLjtLKRqGCu5o725G2IXWcnnhI27sQiHjmBbBvHtrAp
// SIG // cneT5q2Ss/jZ35S/EsTlomf7LJC8a+vKJd6LSNyJg0Vh
// SIG // WO/WXahXu7yGqos9gKplH7Rkt/FNQUnHTMKoLjLhiXsz
// SIG // 25u7eE+96ofQ2bnWzPjzhgvC6CyhgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgubrS8S6B/2QH1kYPt8xG
// SIG // TdVyQRdogl3j0pQCOwsxtAoCBmUorOGUtRgTMjAyMzEw
// SIG // MjAxNzA0MzUuNDQyWjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOkUwMDItMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAHZnFwFkrCDaz4A
// SIG // AQAAAdkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNjAxMTgzMjU4WhcN
// SIG // MjQwMjAxMTgzMjU4WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OkUwMDItMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEA1ekgzda4GNt9Oci3
// SIG // QnVDbxwhBOGdLnA+giry+ZQOxzPNUjJFt+kVO+1GgS/T
// SIG // 0nL4qn1cxNq9qUW0TLQwTMBMdYmos1dhGbDRhrs3kd1z
// SIG // WDm0LyVS2gogZLQGXau+QTRSIpfkn3aV4Cs1UGYgwSQz
// SIG // edFggAza62+PGeGe/yr8s2g+Bm/mmXgoqAdhoNZud3fu
// SIG // qVEwXN1jucR2Yv66yP13Z4YhOv27KY6VOWrnwpSA8dEA
// SIG // 6tUEcNOGnayoXA1shi90mgaf4YzfuCSVOys77ClmVXU7
// SIG // lz6I52k8FnB3RBn88Ymhd9M3fEmOGEVHDBjzkDkR9SD8
// SIG // JMMJakJHNBwZCQkM4ml2PyKYDEcP1z+FL/iQSfEWRimT
// SIG // dc0T1k/XebxxlEpl95u+0SqAn5IEiYnyIkIuhXNDmCku
// SIG // oGTgO53eLfpYgK6/Z4qngv1HDTrla3FQuAm5MHydnh5G
// SIG // lodfLFLd1A/EB2C0MJ/eT/h5vD2SYoK9UkS3LJvKTj3n
// SIG // uzwW53SP1XiibJkHY3pNmhTvVRp1LcwwwaMJYV7IbMGT
// SIG // DJCyf+I1M0JlAX5viQB9edehPhtNsEuzYMzMJqR1gpgG
// SIG // hXXew8iSKhmum3Ga0e0AC3ZMCIVUA4M2QLjcasL4eCGu
// SIG // GSOVaMo+G+81gIZrq6cKTKYo8/onnlsH+mXZsrEY0f8m
// SIG // elF5hmsCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBQcOsEp
// SIG // U2eoBV5dOcP7NxmtX+dcJzAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // KjbVWCzutUzLiGpwu3JbdIvl0UWx8J8DaNOUN7OKaRbX
// SIG // eJwpgf0yTwyerrxK8sbNL8OWPo0MFIip4ZdlRhsCKtKV
// SIG // gyLmluKaTFdaWEHyenbQRpEYkz9XilbwEWGTEWiE3vWY
// SIG // cCSZ2D/N6TMRwsWhLGQuIpWN/+eXaneGV0ws/3KRuWp5
// SIG // g2q7Z1poMrMoDbLU8G1iSUY/OYGEZI8Yv58SgIhBcZeh
// SIG // n5HJ11cvA0RUI9XdwIqrHj6HiM8btYrgCUcA633uDZyh
// SIG // 6qE4FrL+3gliZ1o1lkbe0URq6b8y0KPwcVG/IuPVMEYP
// SIG // RuW8aXeUrtW9tuBr+htR0VPqiRwdc6HuNQ9q/4nNgT6L
// SIG // rFfZ3mCuaiOTxy7IQJ+mE0JZW1faQmzlL2TtHbXcKeRx
// SIG // 9n8OqHyTcCnDxJWqpBHMb64YUVqsDYGhFU8iFeIzHPIz
// SIG // 28djYfcwM7Z2/TX5wxThPv4BfHGak2v0+uUxjT97jIj9
// SIG // 4K/JyF0NiEcDFVKC5hrtqn5oQ6HsLN3XL5OrNWgOplx8
// SIG // PjADRCAyio8N4thuibWZBHprtTl7bJIP7Rp38sGjIKuQ
// SIG // mrlPW+np07QPlBPhip5okFumFBz4QSNC9kBu+k0Qa3uT
// SIG // 6TVR4snP9NW41BDKXmgfiJwB+Jw8WF8dfMGyRPnvyGzL
// SIG // 9NeOxBS+/dnRCxdF8KqnFNEwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjpFMDAyLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUA4hxFugmt5+QY
// SIG // GVf7UP3wkdPU3/eggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjd
// SIG // DkcwIhgPMjAyMzEwMjAxNDMzNDNaGA8yMDIzMTAyMTE0
// SIG // MzM0M1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA6N0O
// SIG // RwIBADAHAgEAAgIXWjAHAgEAAgITnzAKAgUA6N5fxwIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQAlyKoFZDQebzs6XVy5bvmGQAD02K8p
// SIG // sIX5/clUV6vjOnuSgJqGbNK2T9KqkhwZGAqYmOOxHMvV
// SIG // mo9Dx5tno2pYr2BwHc6kgSiR0WFW/GQBLhSfelmlHJvu
// SIG // NFgfmw+pslG7NepOseQtoMTbOqlIjbsHi3cQnMj1TIOE
// SIG // Ow6q7FBmGfwwYZ+HaYtkfX8NpewZX4/HAadzuTPQOfWo
// SIG // 1uJeY3RWO+X8l1GZ5GXoc4wvyR8E75dGD9py1ohry1wQ
// SIG // OJdF/buqqGo18Ki68dK7x5UifETATw+9vxkpebdrngE6
// SIG // hCuRmDKVFkKHF1NEVuvU2aXxUbSPzInzPRjSUWdNmyjU
// SIG // BTkuMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAHZnFwFkrCDaz4AAQAAAdkw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgBGgl
// SIG // qIsLV7fX0BmYA6YBG7/lC1KjF9Ardzv5z9OgC0YwgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCCfoBWyLTpv
// SIG // 1DAwJxE82yXtLtA1ndjIKYG9EnG0IAd58zCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
// SIG // 2ZxcBZKwg2s+AAEAAAHZMCIEIPUOVde2gAWjKyuqhiqZ
// SIG // lCJPYyMfrswf0/G6vlVRSyHRMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAC5Y8vVxxe2kMqHAcSWaWxiyQ5AsYoKKg18wIq9g
// SIG // 3A3tLOY9xOOPPZAFYI4qm+8Gd10wOEERBo0ZldJQw5kS
// SIG // Rrccs18/kCnfJSjOGIkwvl/P2NMHXudZ1n5niZknalLT
// SIG // eKoi7F9qO0EcN7tq4OX2E0zVaUaPvVuO5IYkLNR2bPDE
// SIG // wFA3eubI5Vnk/C4sOxZJuFi08mJOj0Q9HxQFCt9DQoLm
// SIG // yfPhof3ZzwUsMFZabuOAcTJOY8fDucC33rLH4sd3BhvB
// SIG // KuP3f++1ERRpwYBdjmKb8Q29ms44vBWpqVSMytuIr/Rd
// SIG // 0t/jgHnqQjy/VhXoX0f+xBwEjiiuJR4sMEccPjCWvhBr
// SIG // eF1hxwbeQ1uwLRDv7Q2rihbRGrxQFCkQFhFisTNuHiI1
// SIG // RHFKWSnQiex9HzT/7FdS3OI9AOP2Jv+k1U3Vk2M4wzSS
// SIG // H3Vx8tCsHLO/PwzvvtmqZU4kBkuBmvnqUn0Nq4U09Say
// SIG // hx500xPkt+cAnU5CTs289eTbvpDcSgtpKXxJp+LG3yev
// SIG // T4H1FY7lvJpULTpCBYX57BCAPFYNZBWmlwQSMUpoGOAc
// SIG // LPfaLYh+oUZwFRrWBUZmHzWLOkNkQl54+XqCJ3vhTBP+
// SIG // fC8UAQaPRgVCMDh5s33CF+J0tUHLTdXcmKE9TnpMx5XT
// SIG // Mb6h1zltG2SquEwln/BdJiDBheFy
// SIG // End signature block
