define("callTreeViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,o,i,l)=>{return a={9442:e=>{const t=document.createElement("script");t.id="CallTreeRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxkaXYgY2xhc3M9ImhvdEhpZ2hsaWdodCIgZGF0YS1iaW5kPSJjc3M6IHsgaG90UGF0aDogJHBhcmVudC5zaG93SG90UGF0aEhpZ2hsaWdodGluZygpICYmIGlzSG90UGF0aCgpLCBob3RJdGVtOiAkcGFyZW50LnNob3dIb3RQYXRoSGlnaGxpZ2h0aW5nKCkgJiYgaXNIb3RJdGVtKCkgfSI+PC9kaXY+DQogICAgICAgIDxkaXYgY2xhc3M9InR5cGVJY29uIiBkYXRhLWJpbmQ9ImNzczogeyB2YWx1ZUNvbGxlY3Rpb25UeXBlOiBpc1ZhbHVlQ29sbGVjdGlvblR5cGUsIHJlZkNvbGxlY3Rpb25UeXBlOiBpc1JlZkNvbGxlY3Rpb25UeXBlLCB2YWx1ZVR5cGU6IGlzVmFsdWVUeXBlLCByZWZUeXBlOiBpc1JlZlR5cGUgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogbGFiZWwiPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkVG90YWwiIGRhdGEtY29sdW1uaWQ9InRvdGFsIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRTZWxmIiBkYXRhLWNvbHVtbmlkPSJzZWxmIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRUb3RhbFNpemUiIGRhdGEtY29sdW1uaWQ9InRvdGFsU2l6ZSI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkU2VsZlNpemUiIGRhdGEtY29sdW1uaWQ9InNlbGZTaXplIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRBdmVyYWdlU2l6ZSIgZGF0YS1jb2x1bW5pZD0iYXZlcmFnZVNpemUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWNvbHVtbmlkPSJtb2R1bGVOYW1lIiBkYXRhLWJpbmQ9InRleHQ6IG1vZHVsZU5hbWUiPjwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},6680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},4956:e=>{const t=document.createElement("script");t.id="SearchControlView",t.innerHTML=atob("PGRpdiBjbGFzcz0iY29udGFpbmVyIHNlYXJjaC1jb250YWluZXIiIGRhdGEtYmluZD0iY3NzOiB7IGNvbnRyb2xEaXNhYmxlZDogaXNEaXNhYmxlZCgpLCBjb250cm9sRW5hYmxlZDogIWlzRGlzYWJsZWQoKSB9LCBhdHRyOiB7ICdhcmlhLWRpc2FibGVkJzogaXNEaXNhYmxlZCB9LCB0ZW1wbGF0ZTogeyBhZnRlclJlbmRlcjogb25BZnRlckRvbUluc2VydCB9Ij4NCiAgICA8ZGl2IGNsYXNzPSJzZWFyY2gtY29udHJvbCIgZGF0YS1iaW5kPSJjc3M6IHsgaGFzRm9jdXM6IGhhc0ZvY3VzKCkgfSI+DQogICAgICAgIDxpbnB1dCB0eXBlPSJzZWFyY2giIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICBkaXNhYmxlOiBpc0Rpc2FibGVkLA0KICAgICAgICAgICAgICAgdGV4dElucHV0OiBzZWFyY2hUZXJtLA0KICAgICAgICAgICAgICAgZm9jdXM6IHNlYXJjaElucHV0SGFzRm9jdXMsDQogICAgICAgICAgICAgICB2YWx1ZVVwZGF0ZTogJ2FmdGVya2V5ZG93bicsDQogICAgICAgICAgICAgICBsb2NhbGl6ZWRQbGFjZWhvbGRlclRleHQ6ICdTZWFyY2hXYXRlcm1hcmsnLA0KICAgICAgICAgICAgICAgZXZlbnQ6IHsga2V5ZG93bjogb25TZWFyY2hCb3hLZXlEb3duLCBjbGljazogY2xvc2VBdXRvQ29tcGxldGVMaXN0cyB9LA0KICAgICAgICAgICAgICAgYXR0cjogeyAnYXJpYS1sYWJlbCc6IGFyaWFMYWJlbCB9IiAvPg0KICAgICAgICA8ZGl2IGNsYXNzPSJzZWFyY2gtc3VibWl0LWJ1dHRvbiIgZGF0YS1iaW5kPSJjbGljazogb25DbGljaywgZm9jdXM6IHNlYXJjaFN1Ym1pdEhhc0ZvY3VzLCBsb2NhbGl6ZWRBcmlhTGFiZWw6ICdTZWFyY2hJY29uQXJpYUxhYmVsJywgc3ZnSW1hZ2U6ICdkaWFnbm9zdGljc0h1Yi1zZWFyY2gnIj48L2Rpdj4NCiAgICAgICAgPGRpdiBpZD0ic2VhcmNoLW9wdGlvbnMtYnV0dG9uIiBjbGFzcz0iZHJvcGRvd24tYnV0dG9uIiBkYXRhLWJpbmQ9ImNsaWNrOiBvbkRyb3BEb3duQ2xpY2siPjwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgaWQ9InNlYXJjaE9wdGlvbnNGbHlvdXQiIGRhdGEtYmluZD0iY3NzOiB7IGZseW91dEFjdGl2ZTogc2hvd1NldHRpbmdzKCkgfSwgZXZlbnQ6IHsga2V5ZG93bjogb25GbHlvdXRLZXlEb3duIH0iPg0KICAgICAgICA8c3BhbiBjbGFzcz0iZmx5b3V0SGVhZGVyIiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6ICdTZWFyY2hPcHRpb25zVGl0bGUnIj48L3NwYW4+DQogICAgICAgIDxsYWJlbCBjbGFzcz0icmVnRXhTZXR0aW5nIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBpc1JlZ3VsYXJFeHByZXNzaW9uSGFzRm9jdXMoKSB9LA0KICAgICAgICAgICAgZXZlbnQ6IHsgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5pc1JlZ3VsYXJFeHByZXNzaW9uSGFzRm9jdXModHJ1ZSk7IH0gfSI+DQogICAgICAgICAgICA8aW5wdXQgdHlwZT0iY2hlY2tib3giDQogICAgICAgICAgICAgICAgICAgZGF0YS1iaW5kPSJjaGVja2VkOiBpc1JlZ3VsYXJFeHByZXNzaW9uLCBmb2N1czogaXNSZWd1bGFyRXhwcmVzc2lvbkhhc0ZvY3VzLA0KICAgICAgICAgICAgICAgICAgICBsb2NhbGl6ZWRBcmlhTGFiZWw6ICdTZWFyY2hSZWd1bGFyRXhwcmVzc2lvbicsDQogICAgICAgICAgICAgICAgICAgIGF0dHI6IHsgJ2FyaWEtY2hlY2tlZCc6IGlzUmVndWxhckV4cHJlc3Npb24oKSB9IiAvPg0KICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ1NlYXJjaFJlZ3VsYXJFeHByZXNzaW9uJyI+PC9zcGFuPg0KICAgICAgICA8L2xhYmVsPg0KICAgICAgICA8bGFiZWwgY2xhc3M9ImNhc2VTZW5zaXRpdmVTZXR0aW5nIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBpc0Nhc2VTZW5zaXRpdmVIYXNGb2N1cygpIH0sDQogICAgICAgICAgICBldmVudDogeyBtb3VzZWVudGVyOiBmdW5jdGlvbih2aWV3TW9kZWwpIHsgdmlld01vZGVsLmlzQ2FzZVNlbnNpdGl2ZUhhc0ZvY3VzKHRydWUpOyB9IH0iPg0KICAgICAgICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94Ig0KICAgICAgICAgICAgICAgICAgIGRhdGEtYmluZD0iY2hlY2tlZDogaXNDYXNlU2Vuc2l0aXZlLCBmb2N1czogaXNDYXNlU2Vuc2l0aXZlSGFzRm9jdXMsDQogICAgICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ1NlYXJjaENhc2VTZW5zaXRpdmUnLA0KICAgICAgICAgICAgICAgICAgICBhdHRyOiB7ICdhcmlhLWNoZWNrZWQnOiBpc0Nhc2VTZW5zaXRpdmUoKSB9IiAvPg0KICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ1NlYXJjaENhc2VTZW5zaXRpdmUnIj48L3NwYW4+DQogICAgICAgIDwvbGFiZWw+DQogICAgPC9kaXY+DQogICAgPCEtLSBrbyBpZjogaXNBdXRvY29tcGxldGVFbmFibGVkIC0tPg0KICAgIDwhLS0ga28gdGVtcGxhdGU6IHsgbmFtZTogJ0F1dG9Db21wbGV0ZVZpZXcnLCBkYXRhOiBhdXRvQ29tcGxldGVWaWV3TW9kZWwgfSAtLT48IS0tIC9rbyAtLT4NCiAgICA8IS0tIC9rbyAtLT4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},4423:function(e,t,o){var i,l,a=this&&this.__createBinding||(Object.create?function(e,t,o,i){void 0===i&&(i=o),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[o]}})}:function(e,t,o,i){void 0===i&&(i=o),e[i]=t[o]}),s=this&&this.__exportStar||function(e,t){for(var o in e)"default"===o||Object.prototype.hasOwnProperty.call(t,o)||a(t,e,o)};i=[o,t,o(3432),o(3028),o(9371),o(4881),o(4881),o(4881),o(4881),o(2560),o(8117),o(8117),o(8117),o(8117),o(8117),o(4881),o(952),o(3766),o(5758),o(7886),o(2027),o(1521),o(118),o(4881),o(4881),o(4881),o(4881),o(6680),o(833),o(4956),o(4103)],l=function(e,t,o,i,l,a,r,n,c,d,h,g,u,I,C,m,p,b,A,_,v,G,w,R,S,T,Z){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getCallTreeViewModel=t.CallTreeViewModel=void 0,s(l,t);class Y{constructor(){this._marshaler=new b.DotNetObjectAllocMarshaler,this._telemetry=new A.DotNetObjectAllocTelemetryMarshaler,this._logger=g.getLogger("CallTreeViewModel"),this._isOverlayActive=i.pureComputed((()=>null!==this._currentOverlay())),this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._automation=u.getAutomationManager(this._logger),h.loadDataWarehouse().then((e=>(this._dataWarehouse=e,this._dataWarehouse.getContextService().getGlobalContext()))).then((e=>Promise.all([this._dataWarehouse.getJmcService().getJmcEnabledState(),e.getTimeDomain(),this._marshaler.isNativeCodeFoldingEnabled()]))).then((e=>{this._showJmc=new S.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(e[0]),this._showJmc.isChecked.subscribe((()=>{this._dataWarehouse.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new S.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked(!e[2]),this._showNative.isChecked.subscribe((()=>{this._marshaler.setNativeCodeFoldingEnabled(!this._showNative.isChecked()),this._callTree.onResultChanged(0)})),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>this._showNative.isChecked(!e.isEnabled))),this._marshaler.onCrossReferenceEvent.addEventListener((e=>this.crossReferenceEvent(e))),this._dao=new v.CallTreeDAO(this._dataWarehouse,e[1],this._marshaler);const t=o.Resources.getString,l=new n.TreeGridHeaderViewModel([{id:"name",text:t("HeaderName"),tooltip:t("HeaderNameToolTip"),hideable:!1,sortable:a.SortDirection.Asc},{id:"total",text:t("CallTreeHeaderTotalAllocCount"),tooltip:t("HeaderTotalAllocCountToolTipFunction"),hideable:!0,sortable:a.SortDirection.Desc},{id:"self",text:t("CallTreeHeaderSelfAllocCount"),tooltip:t("CallTreeHeaderSelfAllocCountToolTip"),hideable:!0,sortable:a.SortDirection.Desc},{id:"totalSize",text:t("CallTreeHeaderTotalAllocSize"),tooltip:t("CallTreeHeaderTotalAllocSizeToolTip"),hideable:!0,sortable:a.SortDirection.Desc},{id:"selfSize",text:t("CallTreeHeaderSelfAllocSize"),tooltip:t("CallTreeHeaderSelfAllocSizeToolTip"),hideable:!0,sortable:a.SortDirection.Desc},{id:"averageSize",text:t("HeaderAverageSize"),tooltip:t("HeaderAverageSizeToolTipFunction"),hideable:!0},{id:"moduleName",text:t("HeaderModuleName"),tooltip:t("HeaderModuleNameToolTip"),hideable:!0,sortable:a.SortDirection.Desc}],new w.DotNetObjectAllocColumnSettingsProvider("CallTreeView"),this._dao.defaultSortColumnId);this._callTree=new r.TreeGridViewModel(this._dao,l,"CallTreeAriaLabel"),this._expandHotPathButton=new Z.ToolbarButtonViewModel("hotItemIcon","CallTree_ExpandHotPathButtonText","CallTree_ExpandHotPathAriaLabel",(()=>{this.expandHotPath()})),this._showHotPathToggleButton=new S.ToggleButtonViewModel("hotPathIcon","hotPathDisabledIcon","CallTree_ShowPathButtonText","CallTree_ShowHotPathAriaLabel"),this._showHotPathToggleButton.isChecked(!0),this._callTree.showHotPathHighlighting=this._showHotPathToggleButton.isChecked,this._callTree.roots.subscribe((()=>{this.showHotPathToggleButton.isChecked()&&this.expandHotPath()})),this._callTree.onResultChanged(0);const s=I.getViewEventManager();s.selectionChanged.addEventListener((e=>{e.isIntermittent||this._dao.timeFilter(e.position)})),this._dao.timeFilter.subscribe((()=>this._callTree.onResultChanged(0))),s.jmcEnabledStateChanged.addEventListener((e=>{this.showJmc.isChecked(e.currEnabledState),this._callTree.onResultChanged(0)}));const c=new R.AutoCompleteViewModel(null,this._dao.getAutoCompleteSuggestions.bind(this._dao));return this._searchViewModel=new T.SearchControlViewModel(this._callTree,!1,o.Resources.getString("DotNetAllocSearchControlAriaLabel"),this._telemetry,c),this._isOverlayActive.subscribe((e=>{this._searchViewModel.isDisabled(e)})),i.applyBindings(this),s.detailsViewReady.raiseEvent({Id:p.CallTreeDetailsViewId()}),this._callTree.dataLoadPromise})).then((()=>{this.expandHotPath()}))}get callTree(){return this._callTree}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get searchViewModel(){return this._searchViewModel}get currentOverlay(){return this._currentOverlay}get showHotPathToggleButton(){return this._showHotPathToggleButton}get expandHotPathButton(){return this._expandHotPathButton}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==d.KeyCodes.C)return!0;const o=c.TreeGridUtils.formatTreeGridSelectedToText(this._callTree);return navigator.clipboard.writeText(o),!1}contextMenu(e,t){if("number"!=typeof e.id)return null;const i=t=>this._marshaler.crossReference({rowId:t===_.ToolView.Allocations?e.typeId:e.AggregationId,rowType:e.rowType,viewToShow:t}),l=()=>{const t=e;this._telemetry.goToSourceUsed(),t.sourceFilePosition&&("unsearched"===t.sourceFilePosition.sourceFile.path.toLowerCase()?this._dao.getSourceInfo(t.AggregationId).then((e=>{t.sourceFilePosition=e,e?C.getSourceFileViewerService().openSourcePosition(t.sourceFilePosition):this._automation.getAlertPromise(u.AutomationConstants.DataWarehouseRequestKey,o.Resources.getString("NoSource"))})):C.getSourceFileViewerService().openSourcePosition(t.sourceFilePosition))};let a;a=!e.expandable||e.isExpandableAllocationRow?{label:o.Resources.getString("ContextMenu_ShowInAllocations"),callback:()=>i(_.ToolView.Allocations),disabled:()=>e.isExpandableAllocationRow,type:o.ContextMenu.MenuItemType.command}:{label:o.Resources.getString("ContextMenu_ShowInFunctions"),callback:()=>i(_.ToolView.FunctionsListView),type:o.ContextMenu.MenuItemType.command};const s=[a,{label:o.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>l(),disabled:()=>!e.sourceFilePosition,type:o.ContextMenu.MenuItemType.command},{label:o.Resources.getString("ContextMenu_ExpandHotPath"),callback:()=>this.expandHotPath(),type:o.ContextMenu.MenuItemType.command},{type:o.ContextMenu.MenuItemType.separator},{label:o.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToText(this._callTree);navigator.clipboard.writeText(e)},type:o.ContextMenu.MenuItemType.command},{label:o.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._callTree);navigator.clipboard.writeText(e)},type:o.ContextMenu.MenuItemType.command}];return o.ContextMenu.create(s)}computeOverlay(){return this._callTree.dataLoadStatus()===a.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._callTree.dataLoadStatus()===a.DataLoadEvent.DataLoadCompleted&&0===this._callTree.treeAsArray().length?{name:"MessageView",data:o.Resources.getString("NoAllocationDataMessage")}:this._callTree.dataLoadStatus()===a.DataLoadEvent.DataLoadFailed?{name:"MessageView",data:o.Resources.getString("UnableShowDataMessage")}:null}crossReferenceEvent(e){e.viewToShow===_.ToolView.CallTreeView&&(this._telemetry.crossReferenceUsed(),this._marshaler.clearGraphHighlight(),this._callTree.dataLoadPromise.then((()=>this._dao.getNodePath(e.rowId,e.rowType))).then((e=>c.TreeGridUtils.expandNodePath(this._callTree,this._dao,e))).then((e=>{if(null!==e)c.TreeGridUtils.selectRow(this._callTree,e),this._marshaler.clearGraphHighlight(),this._marshaler.updateGraphHighlight(e.id);else{const e=o.Resources.getString("NoRowMessage");this._automation.getAlertPromise(u.AutomationConstants.DataWarehouseRequestKey,e)}}),(t=>{this._logger.error(`Unable to navigate to RowId: ${e.rowId} RowType: ${e.rowType}`),this._logger.error(t.message)})))}expandHotPath(){this._telemetry.hotPathUsed();let e=this._callTree.focusedRow();if(e=e||this._callTree.roots()[0],!e)return Promise.resolve();if(e.rowType===a.RowType.Allocation)return e.expanded()||this._dao.expand(e,this._callTree.header.sortInfo()),Promise.resolve();this._callTree.treeAsArray().forEach((e=>{e instanceof G.CallTreeRowViewModel&&(e.isHotPath(!1),e.isHotItem(!1))}));let t=e?[e]:this._callTree.roots();const o=l=>{const a=l.shift();for(let o=0;o<t.length;++o)if(e=t[o],e.id===a.id){e.isHotItem(a.hi),e.isHotPath(a.hp);break}return l.length>0?a.f?e.expanded()?(t=e.children(),o(l)):this._dao.expand(e,this._callTree.header.sortInfo()).then((()=>{t=e.children()})).then((()=>o(l))):o(l):(i.tasks.schedule((()=>{const t=this._callTree.treeAsArray().indexOf(e);-1!==t&&this._callTree.selectedRows([t])})),Promise.resolve())};return this._dao.getHotPath(e,e.rowType).then((e=>o(e))).then((()=>{this._showHotPathToggleButton.isEnabled(!0),this._showHotPathToggleButton.isChecked(!0)}))}}let y;t.CallTreeViewModel=Y,(new b.DotNetObjectAllocMarshaler).getDoubleClickTimeMs().then((e=>{m.Init(e),y=new Y})),t.getCallTreeViewModel=function(){return y}}.apply(t,i),void 0===l||(e.exports=l)},2027:(e,t,o)=>{var i,l;i=[o,t,o(3028),o(4881),o(4881),o(952),o(8558),o(1521)],l=function(e,t,o,i,l,a,s,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CallTreeDAO=void 0;class n{constructor(e,t,i){this._jmcEnabled=!0,this._nativeEnabled=!0,this._dataWarehouse=e,this._timeFilter=o.observable(t),this._timeFilter.equalityComparer=s.areTimespansEqual,this._marshaler=i}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"totalSize"}getAutoCompleteSuggestions(e,t){return this._currentResult?this._currentResult.getResult({task:"autocomplete",filter:e,count:10},t).then((e=>e.filter((e=>(!this._jmcEnabled||this._jmcEnabled&&e.j===i.JmcState.UserCode)&&(this._nativeEnabled||!e.n))).map((e=>e.t)))):Promise.resolve([])}getNodePath(e,t){return this._currentResult.getResult({task:"getData",rowId:e,rowType:t})}getSourceInfo(e){return this._currentResult.getResult({task:"getSourceInfo",rowId:e})}getRoots(e,t,o){return this._marshaler.isNativeCodeFoldingEnabled().then((e=>(null==o||o.throwIfCancellationRequested(),this._nativeEnabled=!e,{timeDomain:this.timeFilter(),customDomain:{view:"CallTree",FoldNativeFrames:e?"true":"false"}}))).then((e=>(null==o||o.throwIfCancellationRequested(),this._dataWarehouse.getFilteredData(e,a.DotNetAllocAnalyzerId(),o)))).then((e=>{null==o||o.throwIfCancellationRequested(),this._currentResult&&this._currentResult.dispose();const t=this._dataWarehouse.getJmcService().getJmcEnabledState();this._currentResult=e;const i=this._currentResult?this._currentResult.getResult({task:"getRoots"},o):Promise.resolve([]);return Promise.all([i,t])})).then((e=>{null==o||o.throwIfCancellationRequested();const i=e[0],l=e[1];this._jmcEnabled=l;const a=i.map((e=>new r.CallTreeRowViewModel(null,e,0,l)));return this.sort(a,t,o),1===a.length?this.expand(a[0],t,o).then((()=>a)):Promise.resolve(a)}))}expand(e,t,o){return e.expand(this._currentResult,t,o)}search(e,t,o,i,l,a,s){const r=l?l.getIdPath():[];return this._currentResult.getResult({task:"search",selectedPath:r,str:e,caseSensitive:t,isRegex:o,isForward:i},s)}sort(e,t,o){const i=n.SortFunc[t.columnId](t.direction),l=e=>{e.children&&(e.children.sort(i),e.children().forEach(l))};return this._currentResult.getResult({task:"sort",column:t.columnId,direction:t.direction},o).then((()=>(e.sort(i),e.forEach(l),e)))}getHotPath(e,t,o){return this._currentResult.getResult({view:"CallTree",task:"expandHotPath",rowId:e.id,rowType:t},o)}}t.CallTreeDAO=n,n.SortFunc={name:e=>l.SortFunctions.stringSort("name",e),total:e=>l.SortFunctions.numericSort("total",e),self:e=>l.SortFunctions.numericSort("self",e),moduleName:e=>l.SortFunctions.stringSort("moduleName",e),totalSize:e=>l.SortFunctions.numericSort("totalSize",e),selfSize:e=>l.SortFunctions.numericSort("selfSize",e),averageSize:e=>l.SortFunctions.numericSort("averageSize",e)}}.apply(t,i),void 0===l||(e.exports=l)},1521:(e,t,o)=>{var i,l;i=[o,t,o(3028),o(3432),o(4881),o(9442)],l=function(e,t,o,i,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CallTreeRowViewModel=void 0;class a{constructor(e,t,i,l){this._selected=o.observable(!1),this._expanded=o.observable(!1),this._haveLoaded=!1,this._isHotPath=o.observable(!1),this._isHotItem=o.observable(!1),this._isHotRoot=o.observable(!1),this._parent=e,this._dto=t,this._depth=i,this._children=o.observableArray([]),this._jmcEnabled=l,this._label=o.pureComputed((()=>this.computeLabel()))}get templateName(){return"CallTreeRowView"}get id(){return this._dto.id}get rowType(){return this._dto.rt}get isHotPath(){return this._isHotPath}get isHotItem(){return this._isHotItem}get isHotRoot(){return this._isHotRoot}get name(){return this._dto.rt===l.RowType.Process?this._dto.n?i.Resources.getString("ProcessNameFormat",this._dto.n,this._dto.pid):i.Resources.getString("ProcessIdFormat",this._dto.pid):this.isExpandableAllocationRow?"":this._dto.n}get isValueCollectionType(){return!this.expandable&&this._dto.ia&&this._dto.iv}get isRefCollectionType(){return!this.expandable&&this._dto.ia&&!this._dto.iv}get isValueType(){return!this.expandable&&!this._dto.ia&&this._dto.iv}get isRefType(){return!this.expandable&&!this._dto.ia&&!this._dto.iv}get label(){return this._label}computeLabel(){if(this._dto.rt===l.RowType.Process)return"";if(this._dto.a===l.AggregateType.BrokenStack)return i.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case l.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");case l.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");default:return this.isExpandableAllocationRow?i.Resources.getString("AllocationsLabel"):this.expandable?"":i.Resources.getString("TypesLabel")}if(this._dto.n)switch(this._dto.j){case l.JmcState.SystemCode:return i.Resources.getString("SystemCallLabel");case l.JmcState.LibraryCode:return i.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case l.AggregateType.SystemCode:return i.Resources.getString("SystemCodeLabel");case l.AggregateType.JmcRejected:return i.Resources.getString("ExternalCodeLabel");case l.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");case l.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");default:return this.isExpandableAllocationRow?i.Resources.getString("AllocationsLabel"):this.expandable?"":i.Resources.getString("TypesLabel")}}get total(){return this._dto.rt===l.RowType.Allocation?null:this._dto.t}get localizedTotal(){return this.total?this.total.toLocaleString(i.Culture.formatRegion):""}get self(){return this._dto.s}get localizedSelf(){return this.self.toLocaleString(i.Culture.formatRegion)}get totalSize(){return this._dto.rt===l.RowType.Allocation?null:this._dto.ts}get localizedTotalSize(){return this.totalSize?this.totalSize.toLocaleString(i.Culture.formatRegion):""}get selfSize(){return this._dto.ss}get localizedSelfSize(){return this.selfSize.toLocaleString(i.Culture.formatRegion)}get averageSize(){return this.expandable?null:this._dto.ss/this._dto.s}get localizedAverageSize(){return this.averageSize?this.averageSize.toLocaleString(i.Culture.formatRegion,{maximumFractionDigits:2}):""}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get AggregationId(){return this._dto.aId}get typeId(){return this._dto.ty?this._dto.ty:-1}get moduleName(){switch(this._dto.mc){case 0:return i.Resources.getString("UnknownModuleLabel");case 1:return this._dto.mn;default:return i.Resources.getString("MultipleModuleLabel")}}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return void 0===this._dto.c||this._dto.c.length>0}get children(){return this._children}invoke(){}expand(e,t,o){let i=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",id:this._dto.id,path:this.getIdPath()},o).then((i=>{null==o||o.throwIfCancellationRequested();const l=i.map((e=>new a(this,e,this.depth+1,this._jmcEnabled)));return this.children(l),1===l.length?l[0].expand(e,t,o):Promise.resolve()}))),this._expanded(!this._expanded()),i}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}get isExpandableAllocationRow(){return this._dto.rt===l.RowType.Allocation&&this.expandable}}t.CallTreeRowViewModel=a}.apply(t,i),void 0===l||(e.exports=l)},118:(e,t,o)=>{var i,l;i=[o,t,o(3766)],l=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocColumnSettingsProvider=void 0,t.DotNetObjectAllocColumnSettingsProvider=class{constructor(e){this._marshaler=new o.DotNetObjectAllocMarshaler,this._templateName=e}getColumnSettings(){return this._marshaler.getColumnSettings(this._templateName)}onColumnChanged(e){this._marshaler.onColumnChanged(this._templateName,e)}}}.apply(t,i),void 0===l||(e.exports=l)},952:(e,t,o)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[o,t]),void 0===i||(e.exports=i)},9371:(e,t,o)=>{var i,l;i=[o,t,o(8558)],l=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.DotNetObjectAllocUI_OnAfterDomInsert=o.onAfterDomInsert}.apply(t,i),void 0===l||(e.exports=l)},7886:(e,t,o)=>{var i;i=function(e,t){"use strict";var o,i;Object.defineProperty(t,"__esModule",{value:!0}),t.HeapType=t.ToolView=void 0,(i=t.ToolView||(t.ToolView={}))[i.FunctionsListView=1]="FunctionsListView",i[i.CallTreeView=2]="CallTreeView",i[i.Allocations=3]="Allocations",(o=t.HeapType||(t.HeapType={}))[o.ALL=0]="ALL",o[o.SOH=1]="SOH",o[o.LOH=2]="LOH",o[o.POH=3]="POH"}.apply(t,[o,t]),void 0===i||(e.exports=i)},3766:(e,t,o)=>{var i,l;i=[o,t,o(3432),o(8117)],l=function(e,t,o,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let l=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===l&&(l=o.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new i.ObservableEvent(l,"onGoToAllocation"),this._onCrossReferenceEvent=new i.ObservableEvent(l,"onCrossReferenceEvent"),this._graphHighlightEvent=new i.ObservableEvent(l,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new i.ObservableEvent(l,"updateNativeCodeEvent"),this._updateCollectionEvent=new i.ObservableEvent(l,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return l._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return l._call("crossReference",e)}updateGraphHighlight(e){return l._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return l._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}graphHighlightingFeatureEnabled(){return l._call("graphHighlightingFeatureEnabled")}getDoubleClickTimeMs(){return l._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return l._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return l._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return l._call("getColumnSettings",e)}onColumnChanged(e,t){return l._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return l._call("isCollectionEnabled")}isGlobalCollectionEnabled(){return l._call("isStartPausedSupported")}isPauseResumeSupported(){return l._call("isPauseResumeSupported")}setCollectionEnabled(e){return l._call("setCollectionEnabled",e)}openLink(e){return l._call("openLink",e)}isTopInsightsSupported(){return l._call("isTopInsightsSupported")}}}.apply(t,i),void 0===l||(e.exports=l)},5758:(e,t,o)=>{var i,l;i=[o,t,o(3432)],l=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let i=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===i&&(i=o.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){i._post("searchIsUsed")}searchOptionsChanged(){i._post("searchOptionsChanged")}crossReferenceUsed(){i._post("crossReferenceUsed")}goToSourceUsed(){i._post("goToSourceUsed")}hotPathUsed(){i._post("hotPathUsed")}collectionToggled(e){i._post("collectionToggled",e)}topInsightLearnMore(e,t,o){i._post("topInsightsLearnMore",e,t,o)}goToAllocationView(e){i._post("goToAllocationView",e)}}}.apply(t,i),void 0===l||(e.exports=l)},8558:(e,t,o)=>{var i,l;i=[o,t,o(3028),o(2560)],l=function(e,t,o,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const i=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}let l=45;const a=e.children;for(let e=0;e<a.length;e++)l+=a.item(e).offsetWidth;const s=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},r=window.matchMedia(i.Utilities.formatString("(max-width: {0}px)",l.toString()));s(r),r.addListener(s),o.utils.domData.set(e,"mediaQuery",r),o.utils.domData.set(e,"mediaQueryListener",s)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,i),void 0===l||(e.exports=l)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=o},3028:e=>{"use strict";e.exports=i},3432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},s={},function e(t){var o=s[t];if(void 0!==o)return o.exports;var i=s[t]={exports:{}};return a[t].call(i.exports,i,i.exports,e),i.exports}(4423);var a,s}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // T6jzIelDAeG1f3GKcarKtbqWTDmEyuncC592vi38uwqg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCv+IGCCjtkEvyPLKP8QFPi656aTCBywhlT
// SIG // iE3KyJEWgDBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAJdSVbIe
// SIG // pruZRUNPYx2TU7hBXBUDoQ19/iLVhzC2Yu/nvfrddD6b
// SIG // p5bW8BdEll5Lfx4MeBQ2sIQCK/Q/vmCDse2+vFIowKkY
// SIG // kkh+I8SUIvts88RzwWMQghIOphtcVD2+hnh0wfYZ+jvO
// SIG // xGfzrPzekC34GggVWJB52YOdq4iCuOyy7o/Yd44LsjlD
// SIG // iqUkYAZVy4cs+BB57JGAbnyNTeBoPti9EfzTbsgtIh/5
// SIG // bpODV/aDsFg9lbtk/v4vceT+LOFacqFpRFQ+giEMg9fQ
// SIG // RITFq8JsPlT/Eqsejspuf6lT/E5Dcc/UerV6O4s6lBVQ
// SIG // 9Dr94Lit6NJMm+Ojz3wGBaoxBMahgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgP9NNTxZwrhKUNiwT3oDf
// SIG // tuyMxLKxjLsWn6gEWv1CnrACBmUonhizHRgTMjAyMzEw
// SIG // MjAxNzA0MzcuNTc5WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOjM3MDMtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAHU5OkDL8CsaawA
// SIG // AQAAAdQwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNTI1MTkxMjI3WhcN
// SIG // MjQwMjAxMTkxMjI3WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OjM3MDMtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAmFPeLZsCJJd+d0ln
// SIG // o9cm1nEgG7vBS8ExLTr8N7lzKWtQ5w1w8G7ZC3PqE/AT
// SIG // bYvLft/E8JLX4KADPTfwTh8k+AqVwdR8J9WGKL7mLo6E
// SIG // FfZJslOg+kLbUyCje32U46DbSISOQgZMEvjJMAsHWjcs
// SIG // kr48D72bsR/ETXDjgfAAQ4SR/r8P43r/httBxNBsGnd9
// SIG // t8eLgOLS5BNHvcmg+8f7NRd5bezYuO6STBjC6mUAiu1A
// SIG // lHlmrlhfcGSDUOOfbUjyHv8SurbS8mB83dw3kUS8UD/+
// SIG // 3O6DyTwxYKWxgdh0SWhNKbkUQ6Igz+yScWK/kwRMYSNr
// SIG // pWVm4C+An1msMG9S7CZhViR26hq+qNIq1uyKg5H9qhGz
// SIG // EU9VlDNeReaAXOS4NfJW97FFu5ET7ysJn2kQZK5opdB/
// SIG // 7b9x2MhOgOPdGRRHD5Onc2ACnwnt7yqUVROHT6AylZwi
// SIG // 1Ey5KtX/6Z7g/2RhydnG7iHq/bpkGLvxc9Qwa3gvAkbN
// SIG // 8yZuPByEt623i1GLvwvd41SCTpaygL/6pmEcpow5qX82
// SIG // b37xgRlGzqcfuKH8KgUy7oQHzuxWc99/DbbIw86t7Ikd
// SIG // HD++KfVLjV9U6c+CmSzPBpc2S43t2h3w95rpazyDIqZ1
// SIG // agZJGNdmtrJbGyJY3t7qvAUq4+9uf8BwreB8l1uFoExj
// SIG // 4s8hMU0CAwEAAaOCAUkwggFFMB0GA1UdDgQWBBQ82ozH
// SIG // cLQGehKAeR3nXLK7tAx2STAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // tMVDz/srcJLXUYWJWfQZOP2y8yzs6vsHAu1QGkUBxkUv
// SIG // iD8lP/Di4laF3KMiiiokUOyvXPdDnTPqi+D4syp0rSww
// SIG // bFk/nbNYWsjZE8J4VXGXgNRBipTWb3ZU7AlMSeQu8qGU
// SIG // JgPtpaZNODxo3BYR9YBkaYc/rXAzSvwrSifj6xLjY+7I
// SIG // JgaKfyRUHGMpoj/76/nbnaykHkrXE1fVtd3JthQ+Rf11
// SIG // jt+04vhuE4NQZFNuUQPrfEQlsvyB7oN662M6lHHVUau1
// SIG // IEZeNGCJEzZ7nKOp8u7xAZlhY3K+0pL6P0FrnjvDQLz9
// SIG // mSn90DH4nZh9cb8cfYfcFVOq7xEPz1CYt6aKWLK0CrqI
// SIG // KYXT6h2eY/TqEPhIwAlH4CZR55/BlWz1t8RqZQpF28hB
// SIG // 4XkDXf2t1/9s6UsBETjnMtWGnkKrn5RopQH9MuNABSql
// SIG // tkNck29fXEVwaUc22VTvkV1AeAOlC9RNV47c6/2/as/V
// SIG // OFDVfMMvGL/9O26d4QBX8QeJp9HPjzvmBb9mLFb2AE1S
// SIG // NpcC/UA0hLfBdEVui3pMT3725JlUkcD+qX+QFH5KqKCm
// SIG // uqX6kwp3aRk+9R8opbXpWjIUVLDVZGiswCa1KBEko+7E
// SIG // z9WRokvSYCPqdwDuX5zIbd5ixzIOvBrM0h+Fst71AyaY
// SIG // 1E2C7Wk1pELc+lKmTze1l4YwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjozNzAzLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUALTNdlo6NscQO
// SIG // bHbswf9x3c2ZokiggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjc
// SIG // /1EwIhgPMjAyMzEwMjAxMzI5NTNaGA8yMDIzMTAyMTEz
// SIG // Mjk1M1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA6Nz/
// SIG // UQIBADAHAgEAAgJHbjAHAgEAAgITpDAKAgUA6N5Q0QIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQBIdsFPFxPqnbxNlY1K79vQUoakOKtX
// SIG // qoIAbRRVi+vNKr7H0VuFG/CZ/WdMC/dKukPg/A+ReN5n
// SIG // BpZIDzdi4fQ04Co6oe0V3PI1pHhLghnWLQ+puMti6Gem
// SIG // wcuDE9ewF4eVpACEMIrqAja3Qys7EMecr1Zt7Jc/2Es0
// SIG // x7Gw9M1AnXIrlQVSfSkTTGSnEtVlxqPYjumcDh8t364X
// SIG // FntY7D+5tqW7bAY6xWO/GdoP0YWP4YINpOj0drRr7iEA
// SIG // 4pPpi0Smy8Vw+a/T5kfzl4wjgsZScKTabIaNJRBL+XS7
// SIG // fBSKREwsPSRIn/tUH6m/aWyb9iFmGaAUkGebgssaTmua
// SIG // UJKNMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAHU5OkDL8CsaawAAQAAAdQw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgnibA
// SIG // CtUq8ygOEZ36332Qr3tvzMUsQc2ifojKBCmscVwwgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCDM6of62BSl
// SIG // zpc71kucQrT4vWlPnwVJMSK4l6dlkz1iNzCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
// SIG // 1OTpAy/ArGmsAAEAAAHUMCIEIEO0ylCgUsxDgMHa+KiY
// SIG // lzUW61QYCtvY80skoeJuPlBXMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAI1Y6+8gdu49ecKpWnRF8vxnRUOAWezr/dEF1XNT
// SIG // qbqc4SXmzjIbzffxfPJWch96PuVP65Gg1HFri6MVDxBi
// SIG // Plct5BrT/6rA0pjuNALssPur88X8H2s3kGHOclfvAD7e
// SIG // 2IYCb8voZavv9fmomGAAmtDB9pIckdUhQUYtHpcPW5Tl
// SIG // qVoEvsD5YJKPnGuNXbsNk+eB//gjmZjKZRGi2wRTHJDA
// SIG // qVeSQLnbTr4BjMEd1KiaEfr11jS6s5BqPYyrdwcV8X80
// SIG // cTD+IytO2KnkwMMx8OAHfHMTpHOaXcOLvP76ssIRr1Xx
// SIG // BWFvoxTe1pRqHRxLBD/azpW0KyvVEdDFisPiT8yO53V/
// SIG // /vQgSWoZHHoPUdbxGNUwtXi1vVPbjkM+5dgxTdNUneJh
// SIG // 8aicQ5zuyU2N6lPHvjUh18KlZU29roA4rSaR4F8JqUpP
// SIG // kEbQ5NIUJv08ezsCRvDv4WARla7IcmWO969TV02T8ov8
// SIG // 3BJSdMKp5ZQZZCnS0qTssg6f7cocX52nKhLQ0rc/9TD0
// SIG // QtkxD6tU4exAGUeq47FJ0Axq+4FEBaXZOc30V23NK9av
// SIG // aCvvPK5+pZnb1e9kHxUB6VhfgGUMv7ytBHZt3VtKasI2
// SIG // wf76TST3uAWyICnmvUd/VoUv0HwgLgKltfhMIOOYREGM
// SIG // csDKsAlyZXorOO56wYylhQYcgous
// SIG // End signature block
