define("functionsListViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,o,s)=>{return n={6411:e=>{const t=document.createElement("script");t.id="EmptyRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyBlbXB0eVJvdyIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGFyaWEtbGV2ZWw9IjIiIGRhdGEtYmluZD0idHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLCBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjb2xzcGFuPSI1Ij4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogdGV4dEtleSI+PC9zcGFuPg0KICAgIDwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},2743:e=>{const t=document.createElement("script");t.id="FunctionListRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxkaXYgY2xhc3M9InR5cGVJY29uIiBkYXRhLWJpbmQ9ImNzczogeyB2YWx1ZUNvbGxlY3Rpb25UeXBlOiBpc1ZhbHVlQ29sbGVjdGlvblR5cGUsIHJlZkNvbGxlY3Rpb25UeXBlOiBpc1JlZkNvbGxlY3Rpb25UeXBlLCB2YWx1ZVR5cGU6IGlzVmFsdWVUeXBlLCByZWZUeXBlOiBpc1JlZlR5cGUgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogbGFiZWwiPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkVG90YWwiIGRhdGEtY29sdW1uaWQ9InRvdGFsIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRTZWxmIiBkYXRhLWNvbHVtbmlkPSJzZWxmIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRUb3RhbFNpemUiIGRhdGEtY29sdW1uaWQ9InRvdGFsU2l6ZSI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkU2VsZlNpemUiIGRhdGEtY29sdW1uaWQ9InNlbGZTaXplIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRBdmVyYWdlU2l6ZSIgZGF0YS1jb2x1bW5pZD0iYXZlcmFnZVNpemUiPjwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},6680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},4956:e=>{const t=document.createElement("script");t.id="SearchControlView",t.innerHTML=atob("PGRpdiBjbGFzcz0iY29udGFpbmVyIHNlYXJjaC1jb250YWluZXIiIGRhdGEtYmluZD0iY3NzOiB7IGNvbnRyb2xEaXNhYmxlZDogaXNEaXNhYmxlZCgpLCBjb250cm9sRW5hYmxlZDogIWlzRGlzYWJsZWQoKSB9LCBhdHRyOiB7ICdhcmlhLWRpc2FibGVkJzogaXNEaXNhYmxlZCB9LCB0ZW1wbGF0ZTogeyBhZnRlclJlbmRlcjogb25BZnRlckRvbUluc2VydCB9Ij4NCiAgICA8ZGl2IGNsYXNzPSJzZWFyY2gtY29udHJvbCIgZGF0YS1iaW5kPSJjc3M6IHsgaGFzRm9jdXM6IGhhc0ZvY3VzKCkgfSI+DQogICAgICAgIDxpbnB1dCB0eXBlPSJzZWFyY2giIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICBkaXNhYmxlOiBpc0Rpc2FibGVkLA0KICAgICAgICAgICAgICAgdGV4dElucHV0OiBzZWFyY2hUZXJtLA0KICAgICAgICAgICAgICAgZm9jdXM6IHNlYXJjaElucHV0SGFzRm9jdXMsDQogICAgICAgICAgICAgICB2YWx1ZVVwZGF0ZTogJ2FmdGVya2V5ZG93bicsDQogICAgICAgICAgICAgICBsb2NhbGl6ZWRQbGFjZWhvbGRlclRleHQ6ICdTZWFyY2hXYXRlcm1hcmsnLA0KICAgICAgICAgICAgICAgZXZlbnQ6IHsga2V5ZG93bjogb25TZWFyY2hCb3hLZXlEb3duLCBjbGljazogY2xvc2VBdXRvQ29tcGxldGVMaXN0cyB9LA0KICAgICAgICAgICAgICAgYXR0cjogeyAnYXJpYS1sYWJlbCc6IGFyaWFMYWJlbCB9IiAvPg0KICAgICAgICA8ZGl2IGNsYXNzPSJzZWFyY2gtc3VibWl0LWJ1dHRvbiIgZGF0YS1iaW5kPSJjbGljazogb25DbGljaywgZm9jdXM6IHNlYXJjaFN1Ym1pdEhhc0ZvY3VzLCBsb2NhbGl6ZWRBcmlhTGFiZWw6ICdTZWFyY2hJY29uQXJpYUxhYmVsJywgc3ZnSW1hZ2U6ICdkaWFnbm9zdGljc0h1Yi1zZWFyY2gnIj48L2Rpdj4NCiAgICAgICAgPGRpdiBpZD0ic2VhcmNoLW9wdGlvbnMtYnV0dG9uIiBjbGFzcz0iZHJvcGRvd24tYnV0dG9uIiBkYXRhLWJpbmQ9ImNsaWNrOiBvbkRyb3BEb3duQ2xpY2siPjwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgaWQ9InNlYXJjaE9wdGlvbnNGbHlvdXQiIGRhdGEtYmluZD0iY3NzOiB7IGZseW91dEFjdGl2ZTogc2hvd1NldHRpbmdzKCkgfSwgZXZlbnQ6IHsga2V5ZG93bjogb25GbHlvdXRLZXlEb3duIH0iPg0KICAgICAgICA8c3BhbiBjbGFzcz0iZmx5b3V0SGVhZGVyIiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6ICdTZWFyY2hPcHRpb25zVGl0bGUnIj48L3NwYW4+DQogICAgICAgIDxsYWJlbCBjbGFzcz0icmVnRXhTZXR0aW5nIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBpc1JlZ3VsYXJFeHByZXNzaW9uSGFzRm9jdXMoKSB9LA0KICAgICAgICAgICAgZXZlbnQ6IHsgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5pc1JlZ3VsYXJFeHByZXNzaW9uSGFzRm9jdXModHJ1ZSk7IH0gfSI+DQogICAgICAgICAgICA8aW5wdXQgdHlwZT0iY2hlY2tib3giDQogICAgICAgICAgICAgICAgICAgZGF0YS1iaW5kPSJjaGVja2VkOiBpc1JlZ3VsYXJFeHByZXNzaW9uLCBmb2N1czogaXNSZWd1bGFyRXhwcmVzc2lvbkhhc0ZvY3VzLA0KICAgICAgICAgICAgICAgICAgICBsb2NhbGl6ZWRBcmlhTGFiZWw6ICdTZWFyY2hSZWd1bGFyRXhwcmVzc2lvbicsDQogICAgICAgICAgICAgICAgICAgIGF0dHI6IHsgJ2FyaWEtY2hlY2tlZCc6IGlzUmVndWxhckV4cHJlc3Npb24oKSB9IiAvPg0KICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ1NlYXJjaFJlZ3VsYXJFeHByZXNzaW9uJyI+PC9zcGFuPg0KICAgICAgICA8L2xhYmVsPg0KICAgICAgICA8bGFiZWwgY2xhc3M9ImNhc2VTZW5zaXRpdmVTZXR0aW5nIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBpc0Nhc2VTZW5zaXRpdmVIYXNGb2N1cygpIH0sDQogICAgICAgICAgICBldmVudDogeyBtb3VzZWVudGVyOiBmdW5jdGlvbih2aWV3TW9kZWwpIHsgdmlld01vZGVsLmlzQ2FzZVNlbnNpdGl2ZUhhc0ZvY3VzKHRydWUpOyB9IH0iPg0KICAgICAgICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94Ig0KICAgICAgICAgICAgICAgICAgIGRhdGEtYmluZD0iY2hlY2tlZDogaXNDYXNlU2Vuc2l0aXZlLCBmb2N1czogaXNDYXNlU2Vuc2l0aXZlSGFzRm9jdXMsDQogICAgICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ1NlYXJjaENhc2VTZW5zaXRpdmUnLA0KICAgICAgICAgICAgICAgICAgICBhdHRyOiB7ICdhcmlhLWNoZWNrZWQnOiBpc0Nhc2VTZW5zaXRpdmUoKSB9IiAvPg0KICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ1NlYXJjaENhc2VTZW5zaXRpdmUnIj48L3NwYW4+DQogICAgICAgIDwvbGFiZWw+DQogICAgPC9kaXY+DQogICAgPCEtLSBrbyBpZjogaXNBdXRvY29tcGxldGVFbmFibGVkIC0tPg0KICAgIDwhLS0ga28gdGVtcGxhdGU6IHsgbmFtZTogJ0F1dG9Db21wbGV0ZVZpZXcnLCBkYXRhOiBhdXRvQ29tcGxldGVWaWV3TW9kZWwgfSAtLT48IS0tIC9rbyAtLT4NCiAgICA8IS0tIC9rbyAtLT4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},118:(e,t,i)=>{var o,s;o=[i,t,i(3766)],s=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocColumnSettingsProvider=void 0,t.DotNetObjectAllocColumnSettingsProvider=class{constructor(e){this._marshaler=new i.DotNetObjectAllocMarshaler,this._templateName=e}getColumnSettings(){return this._marshaler.getColumnSettings(this._templateName)}onColumnChanged(e){this._marshaler.onColumnChanged(this._templateName,e)}}}.apply(t,o),void 0===s||(e.exports=s)},952:(e,t,i)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[i,t]),void 0===o||(e.exports=o)},4599:function(e,t,i){var o,s,n=this&&this.__createBinding||(Object.create?function(e,t,i,o){void 0===o&&(o=i),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[i]}})}:function(e,t,i,o){void 0===o&&(o=i),e[o]=t[i]}),l=this&&this.__exportStar||function(e,t){for(var i in e)"default"===i||Object.prototype.hasOwnProperty.call(t,i)||n(t,e,i)};o=[i,t,i(3028),i(9371),i(6411)],s=function(e,t,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EmptyRowViewModel=void 0,l(o,t),t.EmptyRowViewModel=class{constructor(e,t,o,s){this._selected=i.observable(!1),this._expanded=i.observable(!1),this._children=i.observableArray([]),this._id=e,this._textKey=t,this._depth=o,this._parent=s}get templateName(){return"EmptyRowView"}get textKey(){return this._textKey}get id(){return this._id}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){}getIdPath(){return this._parent.getIdPath()}}}.apply(t,o),void 0===s||(e.exports=s)},5868:(e,t,i)=>{var o,s;o=[i,t,i(3028),i(4881),i(4881),i(952),i(1738),i(8558),i(4599)],s=function(e,t,i,o,s,n,l,r,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FunctionListDAO=void 0;class c{constructor(e,t,o){this._jmcEnabled=!0,this._nativeEnabled=!0,this._dataWarehouse=e,this._timeFilter=i.observable(t),this._timeFilter.equalityComparer=r.areTimespansEqual,this._marshaler=o}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"selfSize"}getNodePath(e,t){return this._currentResult.getResult({task:"getData",rowId:e,rowType:t})}getRoots(e,t,i){return this._marshaler.isNativeCodeFoldingEnabled().then((e=>(null==i||i.throwIfCancellationRequested(),this._nativeEnabled=!e,{timeDomain:this.timeFilter(),customDomain:{view:"FunctionList",FoldNativeFrames:e?"true":"false"}}))).then((e=>(null==i||i.throwIfCancellationRequested(),this._dataWarehouse.getFilteredData(e,n.DotNetAllocAnalyzerId(),i)))).then((e=>{null==i||i.throwIfCancellationRequested(),this._currentResult&&this._currentResult.dispose(),this._currentResult=e;const t=this._currentResult?this._currentResult.getResult({task:"getProcesses"},i):Promise.resolve([]),o=this._dataWarehouse.getJmcService().getJmcEnabledState();return Promise.all([t,o])})).then((e=>{null==i||i.throwIfCancellationRequested();const o=e[0],s=e[1];this._jmcEnabled=s;const n=o.map((e=>new l.FunctionListRowViewModel(e,null,s)));return this.sort(n,t),1===n.length?this.expand(n[0],t).then((()=>n)):Promise.resolve(n)}))}getAutoCompleteSuggestions(e,t){return this._currentResult?this._currentResult.getResult({task:"autocomplete",filter:e,count:10},t).then((e=>e.filter((e=>(!this._jmcEnabled||this._jmcEnabled&&e.j===o.JmcState.UserCode)&&(this._nativeEnabled||!e.n))).map((e=>e.t)))):Promise.resolve([])}expand(e,t,i){return e.expand(this._currentResult,t,i)}search(e,t,i,o,s,n,l){let r;return a.EmptyRowViewModel,r=s?s.getIdPath():[],this._currentResult.getResult({task:"search",selectedPath:r,str:e,caseSensitive:t,isForward:o,isRegex:i},l)}sort(e,t,i){const o=c.ColumndIdToSortFunction[t.columnId](t.direction),s=e=>{e.children&&(e.children.sort(o),e.children().forEach(s))};return this._currentResult.getResult({task:"sort",column:t.columnId,direction:t.direction},i).then((()=>(e.sort(o),e.forEach(s),e)))}getSourceInfo(e,t){return this._currentResult.getResult({task:"getSourceInfo",rowId:e},t)}}t.FunctionListDAO=c,c.ColumndIdToSortFunction={name:e=>s.SortFunctions.stringSort("name",e),total:e=>s.SortFunctions.numericSort("total",e),self:e=>s.SortFunctions.numericSort("self",e),totalSize:e=>s.SortFunctions.numericSort("totalSize",e),selfSize:e=>s.SortFunctions.numericSort("selfSize",e),averageSize:e=>s.SortFunctions.numericSort("averageSize",e)}}.apply(t,o),void 0===s||(e.exports=s)},1738:(e,t,i)=>{var o,s;o=[i,t,i(3432),i(3028),i(4881),i(4599),i(2743)],s=function(e,t,i,o,s,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FunctionListRowViewModel=void 0;class l{constructor(e,t,i){this._selected=o.observable(!1),this._expanded=o.observable(!1),this._children=o.observableArray([]),this._haveLoaded=!1,this._jmcEnabled=!1,this._dto=e,this._parent=t,this._jmcEnabled=i,this._label=o.pureComputed((()=>this.computeLabel()))}get templateName(){return"FunctionListRowView"}get id(){return this._dto.id}get rowType(){return this._dto.rt}get depth(){switch(this._dto.rt){case s.RowType.Process:return 0;case s.RowType.Module:return 1;case s.RowType.Function:return 2;case s.RowType.Allocation:return 3;default:return 0}}get name(){switch(this._dto.rt){case s.RowType.Process:return this._dto.n?i.Resources.getString("ProcessNameFormat",this._dto.n,this._dto.pid):i.Resources.getString("ProcessIdFormat",this._dto.pid);case s.RowType.Module:return this._dto.n?this._dto.n:i.Resources.getString("UnknownModuleLabel");case s.RowType.Function:return this._dto.n?this._dto.n:i.Resources.getString("UnknownFunctionLabel");case s.RowType.Allocation:return this._dto.n?this._dto.n:i.Resources.getString("UnknownTypeLabel");default:return this._dto.n}}get isValueCollectionType(){return this._dto.rt===s.RowType.Allocation&&this._dto.ia&&this._dto.iv}get isRefCollectionType(){return this._dto.rt===s.RowType.Allocation&&this._dto.ia&&!this._dto.iv}get isValueType(){return this._dto.rt===s.RowType.Allocation&&!this._dto.ia&&this._dto.iv}get isRefType(){return this._dto.rt===s.RowType.Allocation&&!this._dto.ia&&!this._dto.iv}get label(){return this._label}computeLabel(){if(this._dto.rt===s.RowType.Process)return"";if(this._dto.rt===s.RowType.Allocation)return i.Resources.getString("TypesLabel");if(this._dto.a===s.AggregateType.BrokenStack)return i.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case s.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");case s.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");default:return""}if(this._dto.n)switch(this._dto.j){case s.JmcState.SystemCode:return i.Resources.getString("SystemCallLabel");case s.JmcState.LibraryCode:return i.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case s.AggregateType.SystemCode:return i.Resources.getString("SystemCodeLabel");case s.AggregateType.JmcRejected:return i.Resources.getString("ExternalCodeLabel");case s.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");case s.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");default:return""}}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get total(){return this._dto.rt===s.RowType.Allocation?null:this._dto.t}get localizedTotal(){return this.total?this.total.toLocaleString(i.Culture.formatRegion):""}get self(){return this._dto.s}get localizedSelf(){return this.self.toLocaleString(i.Culture.formatRegion)}get totalSize(){return this._dto.rt===s.RowType.Allocation?null:this._dto.ts}get localizedTotalSize(){return this.totalSize?this.totalSize.toLocaleString(i.Culture.formatRegion):""}get selfSize(){return this._dto.ss}get localizedSelfSize(){return this.selfSize.toLocaleString(i.Culture.formatRegion)}get averageSize(){return this._dto.rt===s.RowType.Allocation?this._dto.ss/this._dto.s:null}get localizedAverageSize(){return this.averageSize?this.averageSize.toLocaleString(i.Culture.formatRegion,{maximumFractionDigits:2}):""}get expandable(){return this._dto.rt!==s.RowType.Allocation}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}expand(e,t,i){let o=Promise.resolve();if(this._expanded(!this._expanded()),!this._haveLoaded){let r;switch(this._haveLoaded=!0,this._dto.rt){case s.RowType.Process:r="getModules";break;case s.RowType.Module:r="getFunctions";break;case s.RowType.Function:r="getAllocations";break;default:return o}o=e.getResult({id:this._dto.id,task:r,functionLimit:l.FunctionLimit},i).then((o=>{null==i||i.throwIfCancellationRequested();const s=o.map((e=>new l(e,this,this._jmcEnabled)));return this.children(s),1===s.length?s[0].expand(e,t,i):(0===s.length&&this.children([new n.EmptyRowViewModel(0,"NoAllocations",this.depth+1,this)]),Promise.resolve())}))}return o}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}invoke(){}}t.FunctionListRowViewModel=l,l.FunctionLimit=250}.apply(t,o),void 0===s||(e.exports=s)},2018:function(e,t,i){var o,s,n=this&&this.__createBinding||(Object.create?function(e,t,i,o){void 0===o&&(o=i),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[i]}})}:function(e,t,i,o){void 0===o&&(o=i),e[o]=t[i]}),l=this&&this.__exportStar||function(e,t){for(var i in e)"default"===i||Object.prototype.hasOwnProperty.call(t,i)||n(t,e,i)};o=[i,t,i(3432),i(3028),i(9371),i(4881),i(4881),i(4881),i(4881),i(2560),i(8117),i(8117),i(8117),i(8117),i(8117),i(4881),i(952),i(3766),i(5758),i(4599),i(7886),i(118),i(5868),i(4881),i(4881),i(4881),i(6680),i(833),i(4956),i(4103)],s=function(e,t,i,o,s,n,r,a,c,d,g,h,u,I,C,m,p,b,A,v,w,G,_,R,S,y){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getFunctionsListViewModel=t.FunctionsListViewModel=void 0,l(s,t);class Z{constructor(){this._logger=h.getLogger("FunctionsListViewModel"),this._marshaler=new b.DotNetObjectAllocMarshaler,this._telemetry=new A.DotNetObjectAllocTelemetryMarshaler,this._isOverlayActive=o.pureComputed((()=>null!==this._currentOverlay())),this._currentOverlay=o.pureComputed((()=>this.computeOverlay())),this._automation=u.getAutomationManager(this._logger),g.loadDataWarehouse().then((e=>(this._dataWarehouse=e,this._dataWarehouse.getContextService().getGlobalContext()))).then((e=>Promise.all([this._dataWarehouse.getJmcService().getJmcEnabledState(),e.getTimeDomain(),this._marshaler.isNativeCodeFoldingEnabled()]))).then((e=>{this._showJmc=new S.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(e[0]),this._showJmc.isChecked.subscribe((()=>{this._dataWarehouse.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new S.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked(!e[2]),this._showNative.isChecked.subscribe((()=>{this._marshaler.setNativeCodeFoldingEnabled(!this._showNative.isChecked()),this._functionList.onResultChanged(0)})),this._dao=new _.FunctionListDAO(this._dataWarehouse,e[1],this._marshaler),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>this._showNative.isChecked(!e.isEnabled))),this._marshaler.onCrossReferenceEvent.addEventListener((e=>this.crossReferenceEvent(e)));const t=i.Resources.getString,s=new a.TreeGridHeaderViewModel([{id:"name",text:t("FunctionListHeaderName"),tooltip:t("FunctionListHeaderNameToolTip"),hideable:!1,sortable:n.SortDirection.Asc},{id:"total",text:t("FunctionListHeaderTotal"),tooltip:t("FunctionListHeaderTotalToolTip"),hideable:!0,sortable:n.SortDirection.Desc},{id:"self",text:t("FunctionListHeaderSelf"),tooltip:t("FunctionListHeaderSelfToolTip"),hideable:!0,sortable:n.SortDirection.Desc},{id:"totalSize",text:t("FunctionListHeaderTotalAllocSize"),tooltip:t("FunctionListHeaderTotalAllocSizeToolTip"),hideable:!0,sortable:n.SortDirection.Desc},{id:"selfSize",text:t("FunctionListHeaderSelfAllocSize"),tooltip:t("FunctionListHeaderSelfAllocSizeToolTip"),hideable:!0,sortable:n.SortDirection.Desc},{id:"averageSize",text:t("HeaderAverageSize"),tooltip:t("HeaderAverageSizeToolTipFunction"),hideable:!0}],new G.DotNetObjectAllocColumnSettingsProvider("FunctionsListView"),this._dao.defaultSortColumnId);this._functionList=new r.TreeGridViewModel(this._dao,s,"FunctionListAriaLabel"),this._functionList.onResultChanged(0);const l=I.getViewEventManager();l.selectionChanged.addEventListener((e=>{e.isIntermittent||this._dao.timeFilter(e.position)})),this._dao.timeFilter.subscribe((()=>this._functionList.onResultChanged(0))),l.jmcEnabledStateChanged.addEventListener((e=>{this.showJmc.isChecked(e.currEnabledState),this._functionList.onResultChanged(0)}));const c=new R.AutoCompleteViewModel(null,this._dao.getAutoCompleteSuggestions.bind(this._dao));this._searchViewModel=new y.SearchControlViewModel(this._functionList,!1,i.Resources.getString("DotNetAllocSearchControlAriaLabel"),this._telemetry,c),this._isOverlayActive.subscribe((e=>{this._searchViewModel.isDisabled(e)})),o.applyBindings(this),l.detailsViewReady.raiseEvent({Id:p.FunctionListDetailsViewId()})}))}get functionsList(){return this._functionList}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get searchViewModel(){return this._searchViewModel}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==d.KeyCodes.C)return!0;const i=c.TreeGridUtils.formatTreeGridSelectedToText(this._functionList);return navigator.clipboard.writeText(i),!1}computeOverlay(){return this._functionList.dataLoadStatus()===n.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._functionList.dataLoadStatus()===n.DataLoadEvent.DataLoadCompleted&&0===this._functionList.treeAsArray().length?{name:"MessageView",data:i.Resources.getString("NoAllocationDataMessage")}:this._functionList.dataLoadStatus()===n.DataLoadEvent.DataLoadFailed?{name:"MessageView",data:i.Resources.getString("UnableShowDataMessage")}:null}contextMenu(e,t){if("number"!=typeof e.id||e instanceof v.EmptyRowViewModel)return null;const o=t=>this._marshaler.crossReference({rowId:e.id,rowType:e.rowType,viewToShow:t}),s=()=>{const t=e;this._telemetry.goToSourceUsed(),t.sourceFilePosition&&("unsearched"===t.sourceFilePosition.sourceFile.path.toLowerCase()?this._dao.getSourceInfo(t.id).then((e=>{t.sourceFilePosition=e,e?C.getSourceFileViewerService().openSourcePosition(t.sourceFilePosition):this._automation.getAlertPromise(u.AutomationConstants.DataWarehouseRequestKey,i.Resources.getString("NoSource"))})):C.getSourceFileViewerService().openSourcePosition(t.sourceFilePosition))};let l;l=e.rowType!==n.RowType.Allocation?{label:i.Resources.getString("ContextMenu_ShowInCallTree"),callback:()=>o(w.ToolView.CallTreeView),type:i.ContextMenu.MenuItemType.command}:{label:i.Resources.getString("ContextMenu_ShowInAllocations"),callback:()=>o(w.ToolView.Allocations),type:i.ContextMenu.MenuItemType.command};const r=[l,{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>s(),disabled:()=>!e.sourceFilePosition,type:i.ContextMenu.MenuItemType.command},{type:i.ContextMenu.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToText(this._functionList,!1);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._functionList,!1);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command}];return i.ContextMenu.create(r)}crossReferenceEvent(e){e.viewToShow===w.ToolView.FunctionsListView&&(this._telemetry.crossReferenceUsed(),this._marshaler.clearGraphHighlight(),this._functionList.dataLoadPromise.then((()=>this._dao.getNodePath(e.rowId,e.rowType))).then((e=>c.TreeGridUtils.expandNodePath(this._functionList,this._dao,e))).then((e=>{if(null!==e)c.TreeGridUtils.selectRow(this._functionList,e),this._marshaler.clearGraphHighlight(),this._marshaler.updateGraphHighlight(e.id);else{const e=i.Resources.getString("NoRowMessage");this._automation.getAlertPromise(u.AutomationConstants.DataWarehouseRequestKey,e)}}),(t=>{this._logger.error(`Unable to navigate to RowId: ${e.rowId} RowType: ${e.rowType}`),this._logger.error(t.message)})))}}let F;t.FunctionsListViewModel=Z,(new b.DotNetObjectAllocMarshaler).getDoubleClickTimeMs().then((e=>{m.Init(e),F=new Z})),t.getFunctionsListViewModel=function(){return F}}.apply(t,o),void 0===s||(e.exports=s)},9371:(e,t,i)=>{var o,s;o=[i,t,i(8558)],s=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.DotNetObjectAllocUI_OnAfterDomInsert=i.onAfterDomInsert}.apply(t,o),void 0===s||(e.exports=s)},7886:(e,t,i)=>{var o;o=function(e,t){"use strict";var i,o;Object.defineProperty(t,"__esModule",{value:!0}),t.HeapType=t.ToolView=void 0,(o=t.ToolView||(t.ToolView={}))[o.FunctionsListView=1]="FunctionsListView",o[o.CallTreeView=2]="CallTreeView",o[o.Allocations=3]="Allocations",(i=t.HeapType||(t.HeapType={}))[i.ALL=0]="ALL",i[i.SOH=1]="SOH",i[i.LOH=2]="LOH",i[i.POH=3]="POH"}.apply(t,[i,t]),void 0===o||(e.exports=o)},3766:(e,t,i)=>{var o,s;o=[i,t,i(3432),i(8117)],s=function(e,t,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let s=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===s&&(s=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new o.ObservableEvent(s,"onGoToAllocation"),this._onCrossReferenceEvent=new o.ObservableEvent(s,"onCrossReferenceEvent"),this._graphHighlightEvent=new o.ObservableEvent(s,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new o.ObservableEvent(s,"updateNativeCodeEvent"),this._updateCollectionEvent=new o.ObservableEvent(s,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return s._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return s._call("crossReference",e)}updateGraphHighlight(e){return s._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return s._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}graphHighlightingFeatureEnabled(){return s._call("graphHighlightingFeatureEnabled")}getDoubleClickTimeMs(){return s._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return s._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return s._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return s._call("getColumnSettings",e)}onColumnChanged(e,t){return s._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return s._call("isCollectionEnabled")}isGlobalCollectionEnabled(){return s._call("isStartPausedSupported")}isPauseResumeSupported(){return s._call("isPauseResumeSupported")}setCollectionEnabled(e){return s._call("setCollectionEnabled",e)}openLink(e){return s._call("openLink",e)}isTopInsightsSupported(){return s._call("isTopInsightsSupported")}}}.apply(t,o),void 0===s||(e.exports=s)},5758:(e,t,i)=>{var o,s;o=[i,t,i(3432)],s=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let o=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===o&&(o=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){o._post("searchIsUsed")}searchOptionsChanged(){o._post("searchOptionsChanged")}crossReferenceUsed(){o._post("crossReferenceUsed")}goToSourceUsed(){o._post("goToSourceUsed")}hotPathUsed(){o._post("hotPathUsed")}collectionToggled(e){o._post("collectionToggled",e)}topInsightLearnMore(e,t,i){o._post("topInsightsLearnMore",e,t,i)}goToAllocationView(e){o._post("goToAllocationView",e)}}}.apply(t,o),void 0===s||(e.exports=s)},8558:(e,t,i)=>{var o,s;o=[i,t,i(3028),i(2560)],s=function(e,t,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=i.utils.domData.get(e,"mediaQuery");if(t){const o=i.utils.domData.get(e,"mediaQueryListener");t.removeListener(o)}let s=45;const n=e.children;for(let e=0;e<n.length;e++)s+=n.item(e).offsetWidth;const l=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},r=window.matchMedia(o.Utilities.formatString("(max-width: {0}px)",s.toString()));l(r),r.addListener(l),i.utils.domData.set(e,"mediaQuery",r),i.utils.domData.set(e,"mediaQueryListener",l)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,o),void 0===s||(e.exports=s)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=i},3028:e=>{"use strict";e.exports=o},3432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},l={},function e(t){var i=l[t];if(void 0!==i)return i.exports;var o=l[t]={exports:{}};return n[t].call(o.exports,o,o.exports,e),o.exports}(2018);var n,l}));
// SIG // Begin signature block
// SIG // MIIoOgYJKoZIhvcNAQcCoIIoKzCCKCcCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // 7XoCl+ETw6iqo3OJDB9JliRcsPLBR8sF8Z/T2ErK5KCg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoNMIIaCQIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCCozCDmEmPgTX1K
// SIG // n+LDnQ4Vxl8rId1j2k728R/9j79hpzBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAMsIfBrhjc09igxKzb3fTqXLDDPMBH83
// SIG // D6bZaxYsv62x8zYDobmpBE2c1rZFPo0AKywHsno38zKb
// SIG // d1xtsFkqKcvRy6/FAtGErjPZ8mXHfsqbuQwgC9JDrf9t
// SIG // tJUSCe+3y6RIBT38SIJAiNZi+e76TojzdSk7nCcJHR6K
// SIG // U7T9VxIuhpaTvkQ00aBv9FPzv7ieQFiwiud3bwrLoZ7A
// SIG // N+XmHIX6M9MaMj+kyjiqxRnWwHDlnEQzA5RGS2yXJX17
// SIG // GPDhFg+ZPD2kSJqRcnQpU1SCJ0tAF/8BRxXkGNLHFO+j
// SIG // 3boQ3wuSrruporR4mQ9dRSw6QdLgK02++4OFnUx5+FlL
// SIG // t6GhgheXMIIXkwYKKwYBBAGCNwMDATGCF4Mwghd/Bgkq
// SIG // hkiG9w0BBwKgghdwMIIXbAIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // rxToTcMarElKDDDqTKjoEKTSt4UlR2C2ivaFmBgEC8wC
// SIG // BmUojUBZvBgTMjAyMzEwMjAxNzA0MzguODY4WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkRDMDAt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR7TCCByAwggUIoAMCAQIC
// SIG // EzMAAAHSISQxSli/LREAAQAAAdIwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjIxWhcNMjQwMjAxMTkxMjIxWjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkRDMDAtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA3GCIQtECP0j2k+fp2EgbEnYQTztklzONFcsoPBat
// SIG // Uz6zDQ88QocVlA+32ysGBkrDjYLY41XneR0oeYpe+YzW
// SIG // nG+k62cLl/kNvvn9v/AgsrvE2NK8RCJw904+dm1s+UEV
// SIG // lUHo33QgP5+mc4p4XGWe/lXpVoE32Au6w64V90wV/PXp
// SIG // al5iEjlSFnl4kSvIfYR+kl4I4UBhkG39m0jO7hpCsyf6
// SIG // Wdi75U86vpjlvYj9o3GBAOG6T3rq6YJS1VEpxhkC5o0K
// SIG // e0nctcBOdlozynS5wReiW5kkRDPw4/We6JMUTVI2EnYM
// SIG // r2dS1kopYVf8HoGF1UOj/TCo0ZxPAiOSjB5quxLB4SAS
// SIG // tAffXRUMnS9b3bgu3lhI88+eWfw8h+h5dkjzn+SmeJR3
// SIG // +jFMLYGn/jHmcZFtIsYf7y9Zl/FbCUx2vAB/tJf/XZ1s
// SIG // xTBRSRRu4PeZxyejJmD635qHijkaMhEEbErrNqgq6TI4
// SIG // Pz92fViQLRRqF2DA9fTa8xuFBT6VW5dzdV7xuP7pXaNf
// SIG // mpwaQ2IcUFO5NYHx5+kMXVFNE7KyfyQry330vPW+FV5S
// SIG // GsZ1RekGYfie8S1DRrRJo+ncD86Any+86g2Sb5rL2DZN
// SIG // ZXG8lcTCIAxT6ANn2T1xxe3cWoTNmRuwALd72RIjLQuh
// SIG // P3Ii0XCMM5SawYhxHpyD78VteasCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQgtp+3J0d06D/5GxGdlyRRZmdZJDAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAsOYqtBMtC5QHc9j3KnIUcFuX
// SIG // fn4rTSEgr6g9BOlvwMok5PkzN1oWE2sUNqT+jq+Kjlfg
// SIG // 7u/y/pNfIGK9aYbIcVTFZ1zXHY3nDLU1lDlQMGyaHlh2
// SIG // gIJJzSDM1yt/s4LhuU1XCxIfwlTMtSeyjxPENAs+ejYF
// SIG // s3fbqxvrIUgypCnYTmD1xfe9DK9RghRaXtaF4xMumkvh
// SIG // 3mr6dsJsuuZm7tAHFDjxJ/oWKoo4C10j6r7hZjjqOVJ0
// SIG // leug7+RXZKiu6uQ0XqMfUTxGXB1GvtgVCj46fnUNw+HP
// SIG // SB/O9uyozA/Dl2aJg/QPDK/33A5+RSO5X2XPIIWHO7KW
// SIG // Ckzv9GfWEUWpoVVscayLATeS61oftfLKFyfvhHko80mH
// SIG // YBlmD4NeoS/+wMnceCs/1gU1JmxoolVHBPyNGkFNlP9D
// SIG // c1IiBSFvNEr8Xg1p+iPoclYP7HRUgCz+SU+8AHvM077K
// SIG // yNoTKRFS3UrRQDKmpxWKrcGVORaALKD2e4dRJVpii2ZF
// SIG // 5PHj7gC87TWNcrHjtE8HbniBnCMCLa5QWINV6T89fqTI
// SIG // RjFW5Xuih7p2iqOSv5XTjNJkEE+FY4OmW80SFUaA3AK0
// SIG // Of/9PO+YzlLybWMnOx5dOI3Jr4xCFwtx45FGL4BxFi9E
// SIG // Bf+H+7ywHIWhGfN/f9xmDnah+VVZ2a1CAUAeg02lCCww
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDUDCC
// SIG // AjgCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpEQzAwLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAiabSwmbBNOjbZh0MweRdU66BUgaggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjc7pwwIhgPMjAyMzEwMjAxMjE4
// SIG // MzZaGA8yMDIzMTAyMTEyMTgzNlowdzA9BgorBgEEAYRZ
// SIG // CgQBMS8wLTAKAgUA6NzunAIBADAKAgEAAgIIvwIB/zAH
// SIG // AgEAAgITOjAKAgUA6N5AHAIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCzBeSW
// SIG // cLKUOZQYQg6ffQxXTbHYPsVHEx0pkApajuEQWQ/6tWdK
// SIG // VZ0aXuFM+CCj3w+o2hPGY42pjUDeSWnFmZhJqIRVE5m6
// SIG // Otb/ApM66MaTkt8CMshKW3qx7tslfdg67EpcRunvfYhe
// SIG // 0vxNtbyT908FhfUmdO0s9LBxtsJP4DifmUaWHAVURVI7
// SIG // GPFHf8VgTXzwWRMnpvoRoyP+5hWWgKLwJ/qSG66WkFss
// SIG // 1Ci6V5MwJ635H+EAKYc2JET08/E1pShoAs0a0clo/Y84
// SIG // ++BZQhMD0Y2x2b9FC/Vq3BKwt7USI4HolZ3YpCdzmtoC
// SIG // 0zAllSj0Tha/8oMYsZHb6vfEU4SVMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAHSISQxSli/LREAAQAAAdIwDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQgQVZEud5DnZwG+5iRdbPeGxEe
// SIG // DSuZ9dCJLf8z3Geb1gswgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCDHgCCT399IvWWzhMVOeexsFjWix9Ge
// SIG // bOuSRYGtg3mkTjCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAAB0iEkMUpYvy0RAAEAAAHS
// SIG // MCIEIEoYwrJSE8k2TeA3p0VOdOjjf7CHU0bEZaP2buO8
// SIG // DmNRMA0GCSqGSIb3DQEBCwUABIICAAgGRihnSz3AnBhy
// SIG // tSfeURM5hn/XVBoTZLbmuMD1MfPk+Uk9ndvGyPdJG7N9
// SIG // LIJMfHx4STs4ZsRHNgq4BxqOT345eQy3ZbKM3Lm8udXb
// SIG // KgFdqdYKCIcgvrAzCvxlgGkksOmS1Gv2T/Cb/nu1V5sF
// SIG // 3PDZyOIwPkjKPIxrWVQlL/Qh0qnghO4YfBL1DFF/kzJD
// SIG // EcwywlL1CCE4x9esh4ZR9/OHKEIb6EHMNcy/K72rrXqZ
// SIG // KrIhBFZ6HAJBWyzXJjOo1NGbooUM2Y27t9KzTTMGe8wQ
// SIG // SZqOEu7+YUXyHWWk93hlKYMO60j+OrLx7GS/98CgUbVi
// SIG // Op3JaK1/kh2FyU43hdKBCl6gnBFXELo20DiVzpD8ETh9
// SIG // 6Ep3bo6A9l7daEj0EnwsrbsdrBPpPdPkZBpa41vLk7Js
// SIG // +EIcC6zzGyblObMLSpmR6YJkwJ/VZLYSD9qJ4uFRPyP2
// SIG // KkMYnEpyYRml7ZRTl0jZ6y5yfdZRdN3GH4TOs77r9qu0
// SIG // Dy5VHD79r1H61C0b9ohxhXHLKKdMog3o2ehJFaeJc1ZR
// SIG // K81k6kcj1hRh1//HUJNrBOL86+G09t9XOaCrXI83wQUc
// SIG // +4fu6iYNKbQpQXAHCNicu1XTQ4IS3DEUMZoTvXHuSnpz
// SIG // 2pCx5uyrlZGcJVe4pL7nwmXHFJQZhNMNNwA6anfIDZUJ
// SIG // xHSIHEfq
// SIG // End signature block
