define("insightsViewModel",["diagnosticsHub","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,o)=>{return a={6680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},952:(e,t,i)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[i,t]),void 0===o||(e.exports=o)},6815:(e,t,i)=>{var o,a;o=[i,t,i(3766),i(4881),i(4881),i(8117),i(8117),i(5758),i(952),i(3028),i(9387),i(6680),i(4103)],a=function(e,t,i,o,a,n,s,l,r,c,h){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getInsightsViewModel=t.InsightsViewModel=void 0;class d{constructor(){let e;this._marshaler=new i.DotNetObjectAllocMarshaler,this._telemetry=new l.DotNetObjectAllocTelemetryMarshaler,this._canShowTopInsights=!1,this._viewEventManager=n.getViewEventManager(),this._currentOverlay=c.pureComputed((()=>this.computeOverlay())),this._marshaler.isTopInsightsSupported().then((e=>{this._canShowTopInsights=e})),s.loadDataWarehouse().then((t=>(e=t,t.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._insightsDAO=new h.InsightsDAO(e,t,this._canShowTopInsights)})).then((()=>{c.applyBindings(this),this._viewEventManager.detailsViewReady.raiseEvent({Id:r.InsightsViewId()})}))}get gcInsights(){return this._insightsDAO.gcInsights}get canShowTopInsights(){return this._canShowTopInsights}linkNavigate(e,t,i){return this._telemetry.topInsightLearnMore(e,t.ruleId,t.ruleType),this._marshaler.openLink(e),!1}investigate(e,t){return"e6d9c1db-4d2a-4fc3-8780-6404532270bf"!==e&&"2ffbc4a2-549f-4f21-a52f-ef41dc4dd5da"!==e||(this._telemetry.goToAllocationView(e),this._viewEventManager.selectDetailsView(r.AllocationDetailsViewId())),!1}get dataLoadStatus(){return this._insightsDAO.dataLoadStatus}computeOverlay(){return this._insightsDAO.dataLoadStatus()===a.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:null}get currentOverlay(){return this._currentOverlay}}let g;t.InsightsViewModel=d,(new i.DotNetObjectAllocMarshaler).getDoubleClickTimeMs().then((e=>{o.Init(e),g=new d})),t.getInsightsViewModel=function(){return g}}.apply(t,o),void 0===a||(e.exports=a)},9387:(e,t,i)=>{var o,a;o=[i,t,i(3028),i(4881),i(952)],a=function(e,t,i,o,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsDAO=void 0,t.InsightsDAO=class{constructor(e,t,n){if(this._gcInsights=i.observableArray([]),this._canShowTopInsights=!1,this._rootDataLoadStatus=i.observable(o.DataLoadEvent.DataLoadStart),this._canShowTopInsights=n,!this._canShowTopInsights)return void this._rootDataLoadStatus(o.DataLoadEvent.DataLoadCompleted);this._dataWarehouse=e,this._timeFilter=i.observable(t);const s={timeDomain:this.timeFilter(),customDomain:{view:"Insights"}};this._rootDataLoadStatus(o.DataLoadEvent.DataLoadStart),this._dataWarehouse.getFilteredData(s,a.DotNetAllocAnalyzerId()).then((e=>e.getResult({type:"GCInsights"}))).then((e=>{this._gcInsights(e.issues),this._rootDataLoadStatus(o.DataLoadEvent.DataLoadCompleted)}))}get gcInsights(){return this._gcInsights}get timeFilter(){return this._timeFilter}get dataLoadStatus(){return this._rootDataLoadStatus}}}.apply(t,o),void 0===a||(e.exports=a)},3766:(e,t,i)=>{var o,a;o=[i,t,i(3432),i(8117)],a=function(e,t,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let a=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===a&&(a=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new o.ObservableEvent(a,"onGoToAllocation"),this._onCrossReferenceEvent=new o.ObservableEvent(a,"onCrossReferenceEvent"),this._graphHighlightEvent=new o.ObservableEvent(a,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new o.ObservableEvent(a,"updateNativeCodeEvent"),this._updateCollectionEvent=new o.ObservableEvent(a,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return a._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return a._call("crossReference",e)}updateGraphHighlight(e){return a._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return a._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}graphHighlightingFeatureEnabled(){return a._call("graphHighlightingFeatureEnabled")}getDoubleClickTimeMs(){return a._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return a._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return a._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return a._call("getColumnSettings",e)}onColumnChanged(e,t){return a._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return a._call("isCollectionEnabled")}isGlobalCollectionEnabled(){return a._call("isStartPausedSupported")}isPauseResumeSupported(){return a._call("isPauseResumeSupported")}setCollectionEnabled(e){return a._call("setCollectionEnabled",e)}openLink(e){return a._call("openLink",e)}isTopInsightsSupported(){return a._call("isTopInsightsSupported")}}}.apply(t,o),void 0===a||(e.exports=a)},5758:(e,t,i)=>{var o,a;o=[i,t,i(3432)],a=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let o=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===o&&(o=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){o._post("searchIsUsed")}searchOptionsChanged(){o._post("searchOptionsChanged")}crossReferenceUsed(){o._post("crossReferenceUsed")}goToSourceUsed(){o._post("goToSourceUsed")}hotPathUsed(){o._post("hotPathUsed")}collectionToggled(e){o._post("collectionToggled",e)}topInsightLearnMore(e,t,i){o._post("topInsightsLearnMore",e,t,i)}goToAllocationView(e){o._post("goToAllocationView",e)}}}.apply(t,o),void 0===a||(e.exports=a)},8117:t=>{"use strict";t.exports=e},4881:e=>{"use strict";e.exports=t},3028:e=>{"use strict";e.exports=i},3432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},n={},function e(t){var i=n[t];if(void 0!==i)return i.exports;var o=n[t]={exports:{}};return a[t](o,o.exports,e),o.exports}(6815);var a,n}));
// SIG // Begin signature block
// SIG // MIIoOgYJKoZIhvcNAQcCoIIoKzCCKCcCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // UTrW62xBCB1PV2XS9xp1m+1pZBQgbZScPx0/9ytqua2g
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoNMIIaCQIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCBRiFBFknzAle1Z
// SIG // GWZikCEo55irr3JJ6YcQ8gZO1HrQFDBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAHMBemxSztKsuH98dKtTh/Y8B7f0Io6O
// SIG // n25D/0Fz5JL2EjDYrZbjA1XhyqXNZlaL3YgJCySrAx8R
// SIG // 6/+8FpFf2yVHEhbWRIxASCeZksHw7/WvtWzM9Zd7WahQ
// SIG // tjiHMqITnnTLtUxtZ2HuasFq/QzOtM2ALuNFXFbgCAgG
// SIG // k7pF/MC2I35nm2t4otN8GTEtXYRzfKN1TIBO0gw9s19f
// SIG // CuITjr2NACcrSs8khGtwMlBmR6K8GgigxHNM7zADVxQB
// SIG // 8q+FAjQLx+7STh4LVPzuHKDm2vwYjYhxOU3kc86BvB0g
// SIG // 7UPaMnB1Kn0g9C3WU9LvjAjDpPo7pySbwuQF6vLT/PL3
// SIG // T/mhgheXMIIXkwYKKwYBBAGCNwMDATGCF4Mwghd/Bgkq
// SIG // hkiG9w0BBwKgghdwMIIXbAIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // GaT3L2BMp/GtW54Tw5a9+XS4tTqQ058pcIHf4l7sd2YC
// SIG // BmUojUBZmhgTMjAyMzEwMjAxNzA0MzguMTQ0WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkRDMDAt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR7TCCByAwggUIoAMCAQIC
// SIG // EzMAAAHSISQxSli/LREAAQAAAdIwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjIxWhcNMjQwMjAxMTkxMjIxWjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkRDMDAtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA3GCIQtECP0j2k+fp2EgbEnYQTztklzONFcsoPBat
// SIG // Uz6zDQ88QocVlA+32ysGBkrDjYLY41XneR0oeYpe+YzW
// SIG // nG+k62cLl/kNvvn9v/AgsrvE2NK8RCJw904+dm1s+UEV
// SIG // lUHo33QgP5+mc4p4XGWe/lXpVoE32Au6w64V90wV/PXp
// SIG // al5iEjlSFnl4kSvIfYR+kl4I4UBhkG39m0jO7hpCsyf6
// SIG // Wdi75U86vpjlvYj9o3GBAOG6T3rq6YJS1VEpxhkC5o0K
// SIG // e0nctcBOdlozynS5wReiW5kkRDPw4/We6JMUTVI2EnYM
// SIG // r2dS1kopYVf8HoGF1UOj/TCo0ZxPAiOSjB5quxLB4SAS
// SIG // tAffXRUMnS9b3bgu3lhI88+eWfw8h+h5dkjzn+SmeJR3
// SIG // +jFMLYGn/jHmcZFtIsYf7y9Zl/FbCUx2vAB/tJf/XZ1s
// SIG // xTBRSRRu4PeZxyejJmD635qHijkaMhEEbErrNqgq6TI4
// SIG // Pz92fViQLRRqF2DA9fTa8xuFBT6VW5dzdV7xuP7pXaNf
// SIG // mpwaQ2IcUFO5NYHx5+kMXVFNE7KyfyQry330vPW+FV5S
// SIG // GsZ1RekGYfie8S1DRrRJo+ncD86Any+86g2Sb5rL2DZN
// SIG // ZXG8lcTCIAxT6ANn2T1xxe3cWoTNmRuwALd72RIjLQuh
// SIG // P3Ii0XCMM5SawYhxHpyD78VteasCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQgtp+3J0d06D/5GxGdlyRRZmdZJDAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAsOYqtBMtC5QHc9j3KnIUcFuX
// SIG // fn4rTSEgr6g9BOlvwMok5PkzN1oWE2sUNqT+jq+Kjlfg
// SIG // 7u/y/pNfIGK9aYbIcVTFZ1zXHY3nDLU1lDlQMGyaHlh2
// SIG // gIJJzSDM1yt/s4LhuU1XCxIfwlTMtSeyjxPENAs+ejYF
// SIG // s3fbqxvrIUgypCnYTmD1xfe9DK9RghRaXtaF4xMumkvh
// SIG // 3mr6dsJsuuZm7tAHFDjxJ/oWKoo4C10j6r7hZjjqOVJ0
// SIG // leug7+RXZKiu6uQ0XqMfUTxGXB1GvtgVCj46fnUNw+HP
// SIG // SB/O9uyozA/Dl2aJg/QPDK/33A5+RSO5X2XPIIWHO7KW
// SIG // Ckzv9GfWEUWpoVVscayLATeS61oftfLKFyfvhHko80mH
// SIG // YBlmD4NeoS/+wMnceCs/1gU1JmxoolVHBPyNGkFNlP9D
// SIG // c1IiBSFvNEr8Xg1p+iPoclYP7HRUgCz+SU+8AHvM077K
// SIG // yNoTKRFS3UrRQDKmpxWKrcGVORaALKD2e4dRJVpii2ZF
// SIG // 5PHj7gC87TWNcrHjtE8HbniBnCMCLa5QWINV6T89fqTI
// SIG // RjFW5Xuih7p2iqOSv5XTjNJkEE+FY4OmW80SFUaA3AK0
// SIG // Of/9PO+YzlLybWMnOx5dOI3Jr4xCFwtx45FGL4BxFi9E
// SIG // Bf+H+7ywHIWhGfN/f9xmDnah+VVZ2a1CAUAeg02lCCww
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDUDCC
// SIG // AjgCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpEQzAwLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAiabSwmbBNOjbZh0MweRdU66BUgaggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjc7pwwIhgPMjAyMzEwMjAxMjE4
// SIG // MzZaGA8yMDIzMTAyMTEyMTgzNlowdzA9BgorBgEEAYRZ
// SIG // CgQBMS8wLTAKAgUA6NzunAIBADAKAgEAAgIIvwIB/zAH
// SIG // AgEAAgITOjAKAgUA6N5AHAIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCzBeSW
// SIG // cLKUOZQYQg6ffQxXTbHYPsVHEx0pkApajuEQWQ/6tWdK
// SIG // VZ0aXuFM+CCj3w+o2hPGY42pjUDeSWnFmZhJqIRVE5m6
// SIG // Otb/ApM66MaTkt8CMshKW3qx7tslfdg67EpcRunvfYhe
// SIG // 0vxNtbyT908FhfUmdO0s9LBxtsJP4DifmUaWHAVURVI7
// SIG // GPFHf8VgTXzwWRMnpvoRoyP+5hWWgKLwJ/qSG66WkFss
// SIG // 1Ci6V5MwJ635H+EAKYc2JET08/E1pShoAs0a0clo/Y84
// SIG // ++BZQhMD0Y2x2b9FC/Vq3BKwt7USI4HolZ3YpCdzmtoC
// SIG // 0zAllSj0Tha/8oMYsZHb6vfEU4SVMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAHSISQxSli/LREAAQAAAdIwDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQg/WzLi/Ez3viovegrg2M/KvwP
// SIG // ZtJnYDUNlTKvBuU9NkcwgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCDHgCCT399IvWWzhMVOeexsFjWix9Ge
// SIG // bOuSRYGtg3mkTjCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAAB0iEkMUpYvy0RAAEAAAHS
// SIG // MCIEIEoYwrJSE8k2TeA3p0VOdOjjf7CHU0bEZaP2buO8
// SIG // DmNRMA0GCSqGSIb3DQEBCwUABIICAHurWkNXnHRgZGi8
// SIG // /sEtNGBPpiHGy/FMf49/DRNuozzrIRadFJBvacfo5OkM
// SIG // Q+1xAdGdXxFeYiBRcvuNmeZF7cf3p6Ry/qfcAeTU6Yzr
// SIG // 6y5p9Odbw47/WSlKZIgG2WfuNSbOX7ZtQL3coGeQ09k+
// SIG // jTp17kD/ZRmfNatiTFa1gvDH/B2cFvZlDW/GikjpurBC
// SIG // 4ZRO5SENUXmykoK+mAqky9JQyr+MyDPHgRuda/Y09TKC
// SIG // 0Y4dGtj/GhMvgO8x2kLXk4OCKntbwTs2CYypcssmDr/p
// SIG // QCWhVa2dK6i/FQK9FvcjsLC8fR0AwQNEou9HOQ37TNDj
// SIG // irWfJkYKunMKirzpxdBM3bU/jz6a3q6udMwVPFTvP38Y
// SIG // tlGup7rqvvKX/a5N1VwFBkB6X/BZPSP4LeSjQcr5I9jA
// SIG // wG/9GN1zDxAkjUBTj3JMEWdrMCqyQASKrOAtzwp/2zAV
// SIG // JZpCJKbyTJWmVY0ZkkdYzyPQiJP7farcpzW4Lj8Ev4Pg
// SIG // 10pfTamOszGP3XlRZctkbtn/y1ztCcBRx2AuvDuiyZDF
// SIG // KdfW7D2OGUZX66wmF2PV890gX1e8bZuoxRAETFr6FMvr
// SIG // n7WT31NPm5lwh0b+bbLpbck3cCbFbR6BezHXX2OT/hNY
// SIG // D9LfqfjGAhv5icQW93mONNkZQqR5T3Qa2m3O7tnCJ8GR
// SIG // ebmIBCa8
// SIG // End signature block
