define("dotNetCountersSwimlane",["diagnosticsHub","diagnosticsHub-swimlanes","plugin-vs-v2"],((e,t,n)=>{return r={374:(e,t,n)=>{var r,i;r=[n,t,n(560),n(560),n(560),n(714),n(558),n(560),n(560),n(560),n(560),n(560),n(560)],i=function(e,t,n,r,i,o,s,a,d,l,u,c,C){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersSwimlane=void 0,t.DotNetCountersSwimlane=class{constructor(e,t,r,i){this._counterSwimlaneMap={},this._counterIdsAdded=[],this._swimlaneConfig=e,this._currentTimespan=t,this._selectionTimespan=r,this._renderer=i,this._noCounterSelectedMessage=new o.NoCounterSelectedMessage(e),i.addControl(this._noCounterSelectedMessage,n.Renderer.headerSwimlanePriority+this._counterIdsAdded.length)}addCounterSwimlane(e,t,n){if(-1!==this._counterIdsAdded.indexOf(e))return;this._swimlaneConfig.header.titleText=t;const o=s.getLocalizedUnitConverter(n,0),g=s.getLocalizedUnitConverter(n,2),m=this._swimlaneConfig.graph,h=[],v=new a.CountersDataSeries(e,this._swimlaneConfig.graph.timeRange,g,new d.ChartColorScheme("rgb(118, 174, 200)",""),"");h.push(v),m.jsonConfig.Series=[];const D=new l.MultiSeriesGraph(this._swimlaneConfig.graph,h,g),p=new c.Scale(this._swimlaneConfig.graph.scale,C.ScaleType.Left,o),E=new c.Scale(this._swimlaneConfig.graph.scale,C.ScaleType.Right,o);D.scaleChangedEvent.addEventListener(p.onScaleChanged.bind(p)),D.scaleChangedEvent.addEventListener(E.onScaleChanged.bind(E));const w=new r.SwimlaneBase(this._swimlaneConfig.header,this._swimlaneConfig.graph.height,this._currentTimespan,this._selectionTimespan);D.scaleChangedEvent.addEventListener(w.onScaleChanged.bind(w)),w.addMainRegionControl(new i.SelectionOverlay(D,this._currentTimespan,this._selectionTimespan,this._swimlaneConfig.id)),w.addMainRegionControl(new u.GridLineRenderer(this._currentTimespan)),w.addLeftRegionControl(p),w.addRightRegionControl(E),w.onViewportChanged({currentTimespan:this._renderer.viewportController.visible,selectionTimespan:this._renderer.viewportController.selection,isIntermittent:!1}),w.swimlaneVisibilityChangedEvent.addEventListener((()=>this.updateSwimlaneHost())),0===this._counterIdsAdded.length&&this._renderer.removeControl(this._noCounterSelectedMessage),this._counterIdsAdded.push(e),this._renderer.viewportController.viewportStateChanged.addEventListener(w.onViewportChanged.bind(w)),this._renderer.addControl(w,1/0),this._counterSwimlaneMap[e]=w}removeCounterSwimlane(e){const t=this._counterIdsAdded.indexOf(e);if(-1===t)return;this._counterIdsAdded.splice(t,1);const r=this._counterSwimlaneMap[e];this._renderer.removeControl(r),this._renderer.viewportController.viewportStateChanged.removeEventListener(r.onViewportChanged.bind(r)),0===this._counterIdsAdded.length&&this._renderer.addControl(this._noCounterSelectedMessage,n.Renderer.headerSwimlanePriority+this._counterIdsAdded.length)}updateSwimlaneHost(){n.getRenderer().resizeHost()}}}.apply(t,r),void 0===i||(e.exports=i)},597:(e,t,n)=>{var r,i;r=[n,t,n(560),n(560),n(374),n(766)],i=function(e,t,n,r,i,o){"use strict";function s(e,t,s,a,d,l){const u=new r.SwimlaneConfiguration(e,d,a);u.header.isBodyExpanded=t,u.graph.height=40;const c=n.getRenderer({dataManager:null,containerId:null,isSelectionEnabled:!0,isLive:!0}),C=new i.DotNetCountersSwimlane(u,d,l,c),g=new o.DotNetCountersMarshaler;g.getCountersAddedToSwimlane().then((e=>{e.forEach((e=>{C.addCounterSwimlane(e.CounterId,e.DisplayName,e.DisplayUnit)}))})),g.counterAddedEvent.addEventListener((e=>{C.addCounterSwimlane(e.counterId,e.displayName,e.displayUnit)})),g.counterRemovedEvent.addEventListener((e=>{C.removeCounterSwimlane(e.counterId)}))}Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersSwimlaneFactory=void 0,t.DotNetCountersSwimlaneFactory=s,window.DotNetCountersSwimlaneFactory=s}.apply(t,r),void 0===i||(e.exports=i)},714:(e,t,n)=>{var r,i;r=[n,t,n(952),n(117)],i=function(e,t,n,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.NoCounterSelectedMessage=void 0,t.NoCounterSelectedMessage=class{constructor(e){if(this._viewEventManager=r.getViewEventManager(),this._container=document.createElement("div"),"PerformanceDebugging"===e.graph.jsonConfig.viewDestinations){const t=document.createElement("span");t.innerText=e.graph.resources.NoCounterSelectedMessage_PerformanceDebugger;const n=document.createElement("a");n.innerText=e.graph.resources.NoCounterSelectedMessage_PerformanceDebuggerLink,this._container.appendChild(t),this._container.appendChild(n),n.onclick=e=>this.onClick(e)}else this._container.innerText=e.graph.resources.NoCounterSelectedMessage_PerformanceProfiler;this._container.style.width="100%",this._container.style.textAlign="center"}onClick(e){this._viewEventManager.selectDetailsView(n.CountersPerformanceDebuggingDetailsViewId())}get container(){return this._container}}}.apply(t,r),void 0===i||(e.exports=i)},952:(e,t,n)=>{var r;r=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.providerIds=t.providerIdToProviderNameMap=t.errorNameCanceled=t.TimeoutImmediate=t.CountersAnalyzerId=t.DotNetCountersAnalyzerId=t.CountersPerformanceDebuggingDetailsViewId=t.CountersCollectionDetailsViewId=t.CountersAnalysisDetailsViewId=void 0,t.CountersAnalysisDetailsViewId=function(){return"7FB3ABC0-46CA-4888-8AC4-265DB211561B"},t.CountersCollectionDetailsViewId=function(){return"26396E76-DFA0-4CF2-924F-121A8A24DD84"},t.CountersPerformanceDebuggingDetailsViewId=function(){return"F7D99DE5-927E-490D-B41F-573944E0B44E"},t.DotNetCountersAnalyzerId=function(){return"3769A1FC-E2C8-43DE-B722-254410B82363"},t.CountersAnalyzerId=function(){return"66EDDDF1-2277-40F3-983A-6FF57A433ECB"},t.TimeoutImmediate=function(){return 0},t.errorNameCanceled=function(){return"Canceled"},t.providerIdToProviderNameMap={"{49592C0F-5A05-516D-AA4B-A64E02026C89}":"System.Runtime","{9DED64A4-414C-5251-DCF7-1E4E20C15E70}":"Microsoft.AspNetCore.Hosting","{D30B5633-7EF1-5485-B4E0-94979B102068}":"System.Net.Http","{BDEB4676-A36E-5442-DB99-4764E2326C7D}":"Microsoft-AspNetCore-Server-Kestrel","{7BEEE6B1-E3FA-5DDB-34BE-1404AD0E2520}":"System.Net.Security","{D5B2E7D4-B6EC-50AE-7CDE-AF89427AD21F}":"System.Net.Sockets","{DDB567A6-2B86-545E-887F-2677536A7C50}":"System.Runtime.Caching.Default","{C26FE4B6-8790-5D41-5900-0F2B6B74EFAA}":"Microsoft.AspNetCore.Http.Connections","{A605548A-6963-55CF-F000-99A6013DEB01}":"Microsoft.AspNetCore.ConcurrencyLimiter","{4B326142-BFB5-5ED3-8585-7714181D14B0}":"System.Net.NameResolution"},t.providerIds=["{49592C0F-5A05-516D-AA4B-A64E02026C89}","{9DED64A4-414C-5251-DCF7-1E4E20C15E70}","{D30B5633-7EF1-5485-B4E0-94979B102068}","{BDEB4676-A36E-5442-DB99-4764E2326C7D}","{7BEEE6B1-E3FA-5DDB-34BE-1404AD0E2520}","{D5B2E7D4-B6EC-50AE-7CDE-AF89427AD21F}","{DDB567A6-2B86-545E-887F-2677536A7C50}","{C26FE4B6-8790-5D41-5900-0F2B6B74EFAA}","{A605548A-6963-55CF-F000-99A6013DEB01}","{4B326142-BFB5-5ED3-8585-7714181D14B0}","{20752BC4-C151-50F5-F27B-DF92D8AF5A61}"]}.apply(t,[n,t]),void 0===r||(e.exports=r)},766:(e,t,n)=>{var r,i;r=[n,t,n(432),n(117)],i=function(e,t,n,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersMarshaler=void 0;let i=null;t.DotNetCountersMarshaler=class{constructor(){i||(i=n.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetCounters.DotNetCountersMarshaler",{},!0)),this._counterAddedEvent=new r.ObservableEvent(i,"CounterAddedEvent"),this._counterRemovedEvent=new r.ObservableEvent(i,"CounterRemovedEvent")}getDoubleClickTimeMs(){return i._call("getDoubleClickTimeMs")}getCountersAddedToSwimlane(){return i._call("getCountersAddedToSwimlane")}get counterAddedEvent(){return this._counterAddedEvent}get counterRemovedEvent(){return this._counterRemovedEvent}addCounter(e,t,n){i._call("addCounter",e,t,n)}removeCounter(e){i._call("removeCounter",e)}getColumnSettings(e){return i._call("getColumnSettings",e)}onColumnChanged(e,t){i._call("onColumnChanged",e,t)}}}.apply(t,r),void 0===i||(e.exports=i)},558:(e,t,n)=>{var r,i;r=[n,t,n(432),n(560)],i=function(e,t,n,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.MiBUnitConverter=t.ByteUnitConverter=t.getFormatTemplate=t.getLocalizedUnitConverter=void 0,t.getLocalizedUnitConverter=function(e,t){return"%"===e?new r.LocalizedUnitConverter([{Unit:"percentage",Divider:1,Decimals:t,LowerBound:0}],{percentage:"%"}):"B"===e?new i(t):"MB"===e?new o(t):new r.LocalizedUnitConverter([{Unit:"",Divider:1,Decimals:t,LowerBound:0},{Unit:n.Resources.getString("/DiagnosticsHubSwimlaneResources/CountKUnit"),Divider:1e3,Decimals:t,LowerBound:1e3},{Unit:n.Resources.getString("/DiagnosticsHubSwimlaneResources/CountMUnit"),Divider:1e6,Decimals:t,LowerBound:1e6},{Unit:n.Resources.getString("/DiagnosticsHubSwimlaneResources/CountBUnit"),Divider:1e9,Decimals:t,LowerBound:1e9}],{"":""})},t.getFormatTemplate=function(e){return"%"===e?n.Resources.getString("/DiagnosticsHubSwimlaneResources/FormattedPercentage"):n.Resources.getString("/DiagnosticsHubSwimlaneResources/FormattedNumberWithUnitsTableView")};class i extends r.BitBinaryMultipleUnitConverter{scaleValue(e){return super.scaleValue(8*e)}}t.ByteUnitConverter=i;class o extends r.BitBinaryMultipleUnitConverter{scaleValue(e){return super.scaleValue(1024*e*1024*8)}}t.MiBUnitConverter=o}.apply(t,r),void 0===i||(e.exports=i)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},i={},function e(t){var n=i[t];if(void 0!==n)return n.exports;var o=i[t]={exports:{}};return r[t](o,o.exports,e),o.exports}(597);var r,i}));
// SIG // Begin signature block
// SIG // MIIoOgYJKoZIhvcNAQcCoIIoKzCCKCcCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // DJMUQPsNpJ++MiH69p3W/yMLUK0mgSQsN0eNFlTHgBqg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoNMIIaCQIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCAYu9BuRXRvzH6i
// SIG // IyNDEeyxtVtsDL4MFMTtzq4kYTca0DBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBABFHhArYhP1sRDzgEkH45zeNpzgX8J9N
// SIG // wgJAEN8N9zBIkwXTRixEsUJP4VblO67HFhKfcTEET4C1
// SIG // 0KOzoeaouKnaQcdEcGSpkAnJi5ykO6tefebNhGClyZrI
// SIG // 8llJLs6SM3Ke+RhJINOMB4pksnbsw0zYRKWDitDCRzCu
// SIG // 9aLdZmNlApjm/arsIOGwp/izQCVJse2ChrkPRX20kEwC
// SIG // OqauImvbvRvUCfJ/TM8MzlXm+OSAIW3WalmTYsmFXmfo
// SIG // xPVy37uzK5G6pZyQ7UgKWmWxwXEckUz1tZSOlW27Qr/7
// SIG // 6smoDxfr7+xJT7PhN5MgSCsIgLJtTzgXWTDSUqwo+HLO
// SIG // jqOhgheXMIIXkwYKKwYBBAGCNwMDATGCF4Mwghd/Bgkq
// SIG // hkiG9w0BBwKgghdwMIIXbAIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // TlMwd5HudfVjjxFDzRXkUDlpccguNWNk+0Upkaha548C
// SIG // BmUojUBZRRgTMjAyMzEwMjAxNzA0MzYuNTg5WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkRDMDAt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR7TCCByAwggUIoAMCAQIC
// SIG // EzMAAAHSISQxSli/LREAAQAAAdIwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjIxWhcNMjQwMjAxMTkxMjIxWjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkRDMDAtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA3GCIQtECP0j2k+fp2EgbEnYQTztklzONFcsoPBat
// SIG // Uz6zDQ88QocVlA+32ysGBkrDjYLY41XneR0oeYpe+YzW
// SIG // nG+k62cLl/kNvvn9v/AgsrvE2NK8RCJw904+dm1s+UEV
// SIG // lUHo33QgP5+mc4p4XGWe/lXpVoE32Au6w64V90wV/PXp
// SIG // al5iEjlSFnl4kSvIfYR+kl4I4UBhkG39m0jO7hpCsyf6
// SIG // Wdi75U86vpjlvYj9o3GBAOG6T3rq6YJS1VEpxhkC5o0K
// SIG // e0nctcBOdlozynS5wReiW5kkRDPw4/We6JMUTVI2EnYM
// SIG // r2dS1kopYVf8HoGF1UOj/TCo0ZxPAiOSjB5quxLB4SAS
// SIG // tAffXRUMnS9b3bgu3lhI88+eWfw8h+h5dkjzn+SmeJR3
// SIG // +jFMLYGn/jHmcZFtIsYf7y9Zl/FbCUx2vAB/tJf/XZ1s
// SIG // xTBRSRRu4PeZxyejJmD635qHijkaMhEEbErrNqgq6TI4
// SIG // Pz92fViQLRRqF2DA9fTa8xuFBT6VW5dzdV7xuP7pXaNf
// SIG // mpwaQ2IcUFO5NYHx5+kMXVFNE7KyfyQry330vPW+FV5S
// SIG // GsZ1RekGYfie8S1DRrRJo+ncD86Any+86g2Sb5rL2DZN
// SIG // ZXG8lcTCIAxT6ANn2T1xxe3cWoTNmRuwALd72RIjLQuh
// SIG // P3Ii0XCMM5SawYhxHpyD78VteasCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQgtp+3J0d06D/5GxGdlyRRZmdZJDAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAsOYqtBMtC5QHc9j3KnIUcFuX
// SIG // fn4rTSEgr6g9BOlvwMok5PkzN1oWE2sUNqT+jq+Kjlfg
// SIG // 7u/y/pNfIGK9aYbIcVTFZ1zXHY3nDLU1lDlQMGyaHlh2
// SIG // gIJJzSDM1yt/s4LhuU1XCxIfwlTMtSeyjxPENAs+ejYF
// SIG // s3fbqxvrIUgypCnYTmD1xfe9DK9RghRaXtaF4xMumkvh
// SIG // 3mr6dsJsuuZm7tAHFDjxJ/oWKoo4C10j6r7hZjjqOVJ0
// SIG // leug7+RXZKiu6uQ0XqMfUTxGXB1GvtgVCj46fnUNw+HP
// SIG // SB/O9uyozA/Dl2aJg/QPDK/33A5+RSO5X2XPIIWHO7KW
// SIG // Ckzv9GfWEUWpoVVscayLATeS61oftfLKFyfvhHko80mH
// SIG // YBlmD4NeoS/+wMnceCs/1gU1JmxoolVHBPyNGkFNlP9D
// SIG // c1IiBSFvNEr8Xg1p+iPoclYP7HRUgCz+SU+8AHvM077K
// SIG // yNoTKRFS3UrRQDKmpxWKrcGVORaALKD2e4dRJVpii2ZF
// SIG // 5PHj7gC87TWNcrHjtE8HbniBnCMCLa5QWINV6T89fqTI
// SIG // RjFW5Xuih7p2iqOSv5XTjNJkEE+FY4OmW80SFUaA3AK0
// SIG // Of/9PO+YzlLybWMnOx5dOI3Jr4xCFwtx45FGL4BxFi9E
// SIG // Bf+H+7ywHIWhGfN/f9xmDnah+VVZ2a1CAUAeg02lCCww
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDUDCC
// SIG // AjgCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpEQzAwLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAiabSwmbBNOjbZh0MweRdU66BUgaggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjc7pwwIhgPMjAyMzEwMjAxMjE4
// SIG // MzZaGA8yMDIzMTAyMTEyMTgzNlowdzA9BgorBgEEAYRZ
// SIG // CgQBMS8wLTAKAgUA6NzunAIBADAKAgEAAgIIvwIB/zAH
// SIG // AgEAAgITOjAKAgUA6N5AHAIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCzBeSW
// SIG // cLKUOZQYQg6ffQxXTbHYPsVHEx0pkApajuEQWQ/6tWdK
// SIG // VZ0aXuFM+CCj3w+o2hPGY42pjUDeSWnFmZhJqIRVE5m6
// SIG // Otb/ApM66MaTkt8CMshKW3qx7tslfdg67EpcRunvfYhe
// SIG // 0vxNtbyT908FhfUmdO0s9LBxtsJP4DifmUaWHAVURVI7
// SIG // GPFHf8VgTXzwWRMnpvoRoyP+5hWWgKLwJ/qSG66WkFss
// SIG // 1Ci6V5MwJ635H+EAKYc2JET08/E1pShoAs0a0clo/Y84
// SIG // ++BZQhMD0Y2x2b9FC/Vq3BKwt7USI4HolZ3YpCdzmtoC
// SIG // 0zAllSj0Tha/8oMYsZHb6vfEU4SVMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAHSISQxSli/LREAAQAAAdIwDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQgauGbmeSIXzjbYoUNeFm5IPdo
// SIG // s74fxLoNRKz3ne9VQlowgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCDHgCCT399IvWWzhMVOeexsFjWix9Ge
// SIG // bOuSRYGtg3mkTjCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAAB0iEkMUpYvy0RAAEAAAHS
// SIG // MCIEIEoYwrJSE8k2TeA3p0VOdOjjf7CHU0bEZaP2buO8
// SIG // DmNRMA0GCSqGSIb3DQEBCwUABIICAIuWjfs7YAq7529C
// SIG // 9O+G6/EOP9F4eNnpghdGicrz5OgHrDzESag1M2aHaTKy
// SIG // Ai8nx1IyPE5i7IcjaCxOrwGq1XisnkowE9hIh1XVspez
// SIG // yQZtWLfSMS3QubJ8H0YeMaCphBulcjAyiHQ4vUgNqJQT
// SIG // h4naffsNzqsecpYfIn5lMsTRr5LbEALup8Lf7i2NkEtM
// SIG // 1E0CLiVToP87VYV+FGlHIer0nvDBTE2RMluVUSIfa3+7
// SIG // 1Vcn7EoR2kOZac7IAw6ZqMCdBRKB8fkJ+e7LNvyJmSeA
// SIG // 4rcS0itpBtUIHEZmQRfXEBtnQB24Zu5zsRiR7XfXzkQN
// SIG // lL//TJ60TnuNbj5AmuqU30moxzqVy98yYsT2xEXIIk1a
// SIG // Jgb9RTMFVO4WBZUq0w/HdgPFXrvRIhyUFvsUAm1cgsgG
// SIG // fIxKvzX7/1I2IfANUU8n1J4fRQM5QWqzh0UonTeamdaR
// SIG // 1PdWVRJxqW0prx2NLok7A7oXvStfLqSqIMl00BnMC8vQ
// SIG // H0f/XUarXHG23zxUdh7HfDzex/fe9rfW4BJCh2ugZHb2
// SIG // oaJ1wIUXYU3MJicZpYKIy7L0C55uv17y/rruMCsEb9+h
// SIG // jzXg/jmjjxzYAeqYS6q7ZFfEGx5yPXDK+VK1qDW8Gd2s
// SIG // ZS2r1ufoPTkQWHf3cWh6Tk5yVxSFkgyLNqBXXfftNQ7C
// SIG // ou1EoZK7
// SIG // End signature block
