define("dotNetCountersUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,s,r)=>{return o={572:e=>{const t=document.createElement("script");t.id="CollectionCountersRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGV2ZW50OiB7IGtleWRvd246IG9uS2V5RG93biB9LA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGlucHV0IHRhYmluZGV4PSItMSIgdHlwZT0iY2hlY2tib3giIGNsYXNzPSJzZWxlY3QtY291bnRlciIgZGF0YS1iaW5kPSJjaGVja2VkOiBpc0NoZWNrZWQsDQogICAgICAgICAgICAgICBtdWx0aUNsaWNrOiB7Y2xpY2s6IG9uQ2xpY2ssIGRibGNsaWNrOiBvbkNsaWNrLCBzdG9wUHJvcGFnYXRpb246IHRydWV9DQogICAgICAgICAgICAgICBmb2N1czogc2VsZWN0ZWQsDQogICAgICAgICAgICAgICBhdHRyOiB7J2FyaWEtbGFiZWwnOiBuYW1lKCksICdhcmlhLWNoZWNrZWQnOiBpc0NoZWNrZWQoKX0iIC8+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibGF0ZXN0VmFsdWUgZ3JpZGNlbGwiIGRhdGEtY29sdW1uaWQ9ImxhdGVzdFZhbHVlIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXJVbml0U3Bhbjoge3ZhbHVlOiBsYXRlc3RWYWx1ZSgpLCBjb252ZXJ0ZXI6IGNvbnZlcnRlciwgZm9ybWF0VGVtcGxhdGU6IGZvcm1hdFRlbXBsYXRlfSI+PC9zcGFuPg0KICAgIDwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},799:e=>{const t=document.createElement("script");t.id="CollectionMeterCountersRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGV2ZW50OiB7IGtleWRvd246IG9uS2V5RG93biB9LA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGlucHV0IHRhYmluZGV4PSItMSIgdHlwZT0iY2hlY2tib3giIGNsYXNzPSJzZWxlY3QtY291bnRlciIgZGF0YS1iaW5kPSJjaGVja2VkOiBpc0NoZWNrZWQsDQogICAgICAgICAgICAgICBtdWx0aUNsaWNrOiB7Y2xpY2s6IG9uQ2xpY2ssIGRibGNsaWNrOiBvbkNsaWNrLCBzdG9wUHJvcGFnYXRpb246IHRydWV9DQogICAgICAgICAgICAgICBmb2N1czogc2VsZWN0ZWQsDQogICAgICAgICAgICAgICBhdHRyOiB7J2FyaWEtbGFiZWwnOiBuYW1lKCksICdhcmlhLWNoZWNrZWQnOiBpc0NoZWNrZWQoKX0iIC8+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibGF0ZXN0VmFsdWUgZ3JpZGNlbGwiIGRhdGEtY29sdW1uaWQ9ImxhdGVzdFZhbHVlIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBbJ0Zvcm1hdHRlZE51bWJlcldpdGhVbml0cycsIGNvbnZlcnRlcigpLmZvcm1hdE51bWJlcihsYXRlc3RWYWx1ZSgpLCBmb3JtYXRUZW1wbGF0ZSwgMiksIGRpc3BsYXlVbml0KCldIj48L3NwYW4+DQogICAgPC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},756:e=>{const t=document.createElement("script");t.id="CountersRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGV2ZW50OiB7IGtleWRvd246IG9uS2V5RG93biB9LA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGlucHV0IHRhYmluZGV4PSItMSIgdHlwZT0iY2hlY2tib3giIGNsYXNzPSJzZWxlY3QtY291bnRlciIgZGF0YS1iaW5kPSJjaGVja2VkOiBpc0NoZWNrZWQsDQogICAgICAgICAgICAgICBtdWx0aUNsaWNrOiB7Y2xpY2s6IG9uQ2xpY2ssIGRibGNsaWNrOiBvbkNsaWNrLCBzdG9wUHJvcGFnYXRpb246IHRydWV9LA0KICAgICAgICAgICAgICAgZm9jdXM6IHNlbGVjdGVkLA0KICAgICAgICAgICAgICAgYXR0cjogeydhcmlhLWxhYmVsJzogbmFtZSgpLCAnYXJpYS1jaGVja2VkJzogaXNDaGVja2VkKCl9IiAvPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IG5hbWUiPjwvc3Bhbj4NCiAgICA8L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImdyaWRjZWxsIG1pbiIgZGF0YS1jb2x1bW5pZD0ibWluIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXJVbml0U3Bhbjoge3ZhbHVlOiBtaW4oKSwgY29udmVydGVyOiBjb252ZXJ0ZXIsIGZvcm1hdFRlbXBsYXRlOiBmb3JtYXRUZW1wbGF0ZX0iPjwvc3Bhbj4NCiAgICA8L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImdyaWRjZWxsIG1heCIgZGF0YS1jb2x1bW5pZD0ibWF4Ij4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXJVbml0U3Bhbjoge3ZhbHVlOiBtYXgoKSwgY29udmVydGVyOiBjb252ZXJ0ZXIsIGZvcm1hdFRlbXBsYXRlOiBmb3JtYXRUZW1wbGF0ZX0iPjwvc3Bhbj4NCiAgICA8L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImdyaWRjZWxsIGF2ZXJhZ2UiIGRhdGEtY29sdW1uaWQ9ImF2ZXJhZ2UiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9ImxvY2FsaXplZE51bWJlclVuaXRTcGFuOiB7dmFsdWU6IGF2ZXJhZ2UoKSwgY29udmVydGVyOiBjb252ZXJ0ZXIsIGZvcm1hdFRlbXBsYXRlOiBmb3JtYXRUZW1wbGF0ZX0iPjwvc3Bhbj4NCiAgICA8L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},302:e=>{const t=document.createElement("script");t.id="MeterCountersRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGlucHV0IHRhYmluZGV4PSItMSIgdHlwZT0iY2hlY2tib3giIGNsYXNzPSJzZWxlY3QtY291bnRlciIgZGF0YS1iaW5kPSJjaGVja2VkOiBpc0NoZWNrZWQsDQogICAgICAgICAgICAgICBtdWx0aUNsaWNrOiB7Y2xpY2s6IG9uQ2xpY2ssIGRibGNsaWNrOiBvbkNsaWNrLCBzdG9wUHJvcGFnYXRpb246IHRydWV9LA0KICAgICAgICAgICAgICAgZm9jdXM6IHNlbGVjdGVkLA0KICAgICAgICAgICAgICAgYXR0cjogeydhcmlhLWxhYmVsJzogbmFtZSgpLCAnYXJpYS1jaGVja2VkJzogaXNDaGVja2VkKCl9IiAvPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IG5hbWUiPjwvc3Bhbj4NCiAgICA8L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImdyaWRjZWxsIG1pbiIgZGF0YS1jb2x1bW5pZD0ibWluIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBbJ0Zvcm1hdHRlZE51bWJlcldpdGhVbml0cycsIGNvbnZlcnRlcigpLmZvcm1hdE51bWJlcihtaW4oKSwgZm9ybWF0VGVtcGxhdGUsIDIpLCBkaXNwbGF5VW5pdCgpXSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZ3JpZGNlbGwgbWF4IiBkYXRhLWNvbHVtbmlkPSJtYXgiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6IFsnRm9ybWF0dGVkTnVtYmVyV2l0aFVuaXRzJywgY29udmVydGVyKCkuZm9ybWF0TnVtYmVyKG1heCgpLCBmb3JtYXRUZW1wbGF0ZSwgMiksIGRpc3BsYXlVbml0KCldIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJncmlkY2VsbCBhdmVyYWdlIiBkYXRhLWNvbHVtbmlkPSJhdmVyYWdlIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBbJ0Zvcm1hdHRlZE51bWJlcldpdGhVbml0cycsIGNvbnZlcnRlcigpLmZvcm1hdE51bWJlcihhdmVyYWdlKCksIGZvcm1hdFRlbXBsYXRlLCAyKSwgZGlzcGxheVVuaXQoKV0iPjwvc3Bhbj4NCiAgICA8L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},834:e=>{const t=document.createElement("script");t.id="ProviderRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyBlbXB0eVJvdyIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGFyaWEtbGV2ZWw9IjIiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGFyaWFFeHBhbmRlZDogeyBleHBhbmRhYmxlOiBleHBhbmRhYmxlLCBleHBhbmRlZDogZXhwYW5kZWQgfSwNCiAgICBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSIgY29sc3Bhbj0iNSI+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCI+PC9kaXY+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},952:(e,t,i)=>{var s;s=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.providerIds=t.providerIdToProviderNameMap=t.errorNameCanceled=t.TimeoutImmediate=t.CountersAnalyzerId=t.DotNetCountersAnalyzerId=t.CountersPerformanceDebuggingDetailsViewId=t.CountersCollectionDetailsViewId=t.CountersAnalysisDetailsViewId=void 0,t.CountersAnalysisDetailsViewId=function(){return"7FB3ABC0-46CA-4888-8AC4-265DB211561B"},t.CountersCollectionDetailsViewId=function(){return"26396E76-DFA0-4CF2-924F-121A8A24DD84"},t.CountersPerformanceDebuggingDetailsViewId=function(){return"F7D99DE5-927E-490D-B41F-573944E0B44E"},t.DotNetCountersAnalyzerId=function(){return"3769A1FC-E2C8-43DE-B722-254410B82363"},t.CountersAnalyzerId=function(){return"66EDDDF1-2277-40F3-983A-6FF57A433ECB"},t.TimeoutImmediate=function(){return 0},t.errorNameCanceled=function(){return"Canceled"},t.providerIdToProviderNameMap={"{49592C0F-5A05-516D-AA4B-A64E02026C89}":"System.Runtime","{9DED64A4-414C-5251-DCF7-1E4E20C15E70}":"Microsoft.AspNetCore.Hosting","{D30B5633-7EF1-5485-B4E0-94979B102068}":"System.Net.Http","{BDEB4676-A36E-5442-DB99-4764E2326C7D}":"Microsoft-AspNetCore-Server-Kestrel","{7BEEE6B1-E3FA-5DDB-34BE-1404AD0E2520}":"System.Net.Security","{D5B2E7D4-B6EC-50AE-7CDE-AF89427AD21F}":"System.Net.Sockets","{DDB567A6-2B86-545E-887F-2677536A7C50}":"System.Runtime.Caching.Default","{C26FE4B6-8790-5D41-5900-0F2B6B74EFAA}":"Microsoft.AspNetCore.Http.Connections","{A605548A-6963-55CF-F000-99A6013DEB01}":"Microsoft.AspNetCore.ConcurrencyLimiter","{4B326142-BFB5-5ED3-8585-7714181D14B0}":"System.Net.NameResolution"},t.providerIds=["{49592C0F-5A05-516D-AA4B-A64E02026C89}","{9DED64A4-414C-5251-DCF7-1E4E20C15E70}","{D30B5633-7EF1-5485-B4E0-94979B102068}","{BDEB4676-A36E-5442-DB99-4764E2326C7D}","{7BEEE6B1-E3FA-5DDB-34BE-1404AD0E2520}","{D5B2E7D4-B6EC-50AE-7CDE-AF89427AD21F}","{DDB567A6-2B86-545E-887F-2677536A7C50}","{C26FE4B6-8790-5D41-5900-0F2B6B74EFAA}","{A605548A-6963-55CF-F000-99A6013DEB01}","{4B326142-BFB5-5ED3-8585-7714181D14B0}","{20752BC4-C151-50F5-F27B-DF92D8AF5A61}"]}.apply(t,[i,t]),void 0===s||(e.exports=s)},414:(e,t,i)=>{var s,r;s=[i,t,i(28),i(560),i(766),i(758),i(558),i(572)],r=function(e,t,i,s,r,o,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CollectionCountersRowViewModel=void 0,t.CollectionCountersRowViewModel=class{constructor(e,t,s){this._decimals=2,this._selected=i.observable(!1),this._expanded=i.observable(!1),this._isChecked=i.observable(!1),this._children=i.observableArray([]),this._latestValue=i.observable(0),this._displayName=i.observable(""),this._displayUnit=i.observable(""),this._providerId=i.observable(""),this._providerName=i.observable(""),this._marshaler=new r.DotNetCountersMarshaler,this._telemetry=new o.DotNetCountersTelemetryMarshaler,this._rowId=s,this._counterId=e,this._isChecked(t),this._localizedUnitConverter=i.pureComputed((()=>n.getLocalizedUnitConverter(this._displayUnit(),this._decimals)))}get templateName(){return"CollectionCountersRowView"}get id(){return this._rowId}get name(){return this._displayName}get formatTemplate(){return n.getFormatTemplate(this._displayUnit())}get converter(){return this._localizedUnitConverter}get latestValue(){return this._latestValue}get providerId(){return this._providerId}get displayUnit(){return this._displayUnit}get providerName(){return this._providerName}get depth(){return 1}get selected(){return this._selected}get expanded(){return this._expanded}expand(){return this._isChecked(!this._isChecked()),this.toggleSwimlane(),Promise.resolve()}get isChecked(){return this._isChecked}onClick(e,t){if(t.which!==s.MouseCodes.Left)return;const i=t.target;i.classList&&i.classList.contains("select-counter")&&this.toggleSwimlane()}onKeyDown(e,t){if("Enter"!==t.key&&"Space"!==t.key)return;const i=t.target;let s;s=i.classList&&i.classList.contains("select-counter")?i:i.querySelector(".select-counter"),s.focus()}get children(){return this._children}invoke(){this._isChecked(!this._isChecked()),this.toggleSwimlane()}updateDto(e){this._latestValue(e.lv);const t=JSON.parse(e.cd);this._displayName(t.dn),this._displayUnit(t.du),this._providerId(t.pId),this._providerName(t.pn)}toggleSwimlane(){this._isChecked()?(this._marshaler.addCounter(this._counterId,this._displayName(),this._displayUnit()),this._telemetry.enableCounter(this._counterId)):(this._marshaler.removeCounter(this._counterId),this._telemetry.disableCounter(this._counterId))}}}.apply(t,s),void 0===r||(e.exports=r)},908:(e,t,i)=>{var s,r;s=[i,t,i(414),i(799)],r=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CollectionMeterCountersRowViewModel=void 0;class s extends i.CollectionCountersRowViewModel{constructor(e,t,i){super(e,t,i)}get templateName(){return"CollectionMeterCountersRowView"}}t.CollectionMeterCountersRowViewModel=s}.apply(t,s),void 0===r||(e.exports=r)},905:(e,t,i)=>{var s,r;s=[i,t,i(766)],r=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CollectionCountersListColumnSettingsProvider=t.AnalysisCountersListColumnSettingsProvider=void 0,t.AnalysisCountersListColumnSettingsProvider=class{constructor(){this.VIEW="Analysis",this._marshaler=new i.DotNetCountersMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings(this.VIEW)}onColumnChanged(e){this._marshaler.onColumnChanged(this.VIEW,e)}},t.CollectionCountersListColumnSettingsProvider=class{constructor(){this.VIEW="Collection",this._marshaler=new i.DotNetCountersMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings(this.VIEW)}onColumnChanged(e){this._marshaler.onColumnChanged(this.VIEW,e)}}}.apply(t,s),void 0===r||(e.exports=r)},484:(e,t,i)=>{var s,r;s=[i,t,i(952),i(28),i(881),i(881),i(766),i(414),i(908),i(663),i(258),i(443),i(117),i(117),i(117)],r=function(e,t,i,s,r,o,n,a,d,l,c,u,h,g,C){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CountersListDAO=void 0;class I{constructor(e,t,i,o){this._countersAdded=[],this._marshaler=new n.DotNetCountersMarshaler,this._providerDataLoadStatus=s.observable(r.DataLoadEvent.DataLoadStart),this._logger=C.getLogger("CountersListDAO"),this._providers=s.observableArray([]),this._providerNameToRow={},this._addedProviderNameToCounterIds={},this._collectionRows=new Map,this._dataWarehouse=e,this._isCollection=o,this._timeFilter=s.observable(i),this._updateHandler=null,this._counterIdToTypes=t,o()&&g.getCollectionTimeService().timeUpdateEvent.addEventListener((()=>{this.fetchCounters()}))}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"name"}async loadDetailsView(e,t,s){this._addedProviderNameToCounterIds={};try{s.throwIfCancellationRequested(),this._providerDataLoadStatus(r.DataLoadEvent.DataLoadStart),this._isCollection()?await this.fetchCounters(s):await Promise.all(this._counterIdToTypes().map((e=>this.fetchCounter(e))));const e=await this.sort(this._providers(),t);return 0===e.length&&this._logger.warning("No rows returned for Counters Tool tree grid."),this._providerDataLoadStatus(r.DataLoadEvent.DataLoadCompleted),Promise.resolve(e)}catch(e){return e&&e.name!==i.errorNameCanceled()&&this._providerDataLoadStatus(r.DataLoadEvent.DataLoadFailed),Promise.resolve([])}}get providers(){return this._providers}get providerDataLoadStatus(){return this._providerDataLoadStatus}async fetchCounters(e){if(this._updateHandler||0===this._counterIdToTypes().length)return Promise.resolve([]);try{this._countersResultPromise||(this._countersResultPromise=this._dataWarehouse.getFilteredData({customDomain:{Task:"GetAllCounters"}},i.CountersAnalyzerId(),e));const t=await this._countersResultPromise,s=await t.getResult({type:"GetLatestValues",idToTypes:this._counterIdToTypes()},e);null==e||e.throwIfCancellationRequested();const r=Promise.all(s.values.map((e=>this.fetchData(e))));return this._updateHandler=null,Promise.resolve(r)}catch(e){const t=e;return t&&t.name!==i.errorNameCanceled()&&this._logger.error(`Error occurred while communicating with the DataWarehouse: ${JSON.stringify(t,Object.getOwnPropertyNames(t))}`),this._updateHandler=null,Promise.resolve([])}}async fetchData(e){let t;return this._collectionRows.has(e.id)?t=this._collectionRows.get(e.id):"MeterCounter"===e.ct?(t=new d.CollectionMeterCountersRowViewModel(e.id,-1!==this._countersAdded.indexOf(e.id),I.NextRowId++),this._collectionRows.set(e.id,t)):(t=new a.CollectionCountersRowViewModel(e.id,-1!==this._countersAdded.indexOf(e.id),I.NextRowId++),this._collectionRows.set(e.id,t)),t.updateDto(e),this.addToProvider(t.providerId().toUpperCase(),t.providerName(),e.id,t),Promise.resolve(t)}async fetchCounter(e){const{id:t,t:i}=e;let s;return s="MeterCounter"===i?new c.MeterCountersRowViewModel(t,this._timeFilter,this._dataWarehouse,-1!==this._countersAdded.indexOf(t),I.NextRowId++):new l.CountersRowViewModel(t,this._timeFilter,this._dataWarehouse,-1!==this._countersAdded.indexOf(t),I.NextRowId++),await s.dataLoadPromise,this.addToProvider(s.providerId().toUpperCase(),s.providerName(),t,s),Promise.resolve(s)}addToProvider(e,t,s,r){if(0!==e.length){if(t||(t=i.providerIdToProviderNameMap[e]),-1===Object.keys(this._providerNameToRow).indexOf(t)){const e=new u.ProviderRowViewModel(t,I.NextRowId++);e.expanded(!0),this._providerNameToRow[t]=e,this._providers.push(e)}this._addedProviderNameToCounterIds[t]||(this._addedProviderNameToCounterIds[t]=[],this._providerNameToRow[t].children([])),-1===this._addedProviderNameToCounterIds[t].indexOf(s)&&(this._providerNameToRow[t].children.push(r),this._addedProviderNameToCounterIds[t].push(s))}}getRoots(e,t,i){return this._countersAdded=[],this._marshaler.getCountersAddedToSwimlane().then((e=>{e.forEach((e=>{this._countersAdded.push(e.CounterId)}))})).then((()=>this.loadDetailsView(e,t,i)))}expand(e,t,i){return e.expand(i)}search(e,t,i,s,r,o,n){throw new Error("Method not implemented.")}sort(e,t,i){const s=I.SortFunc[t.columnId](t.direction),r=e=>{e.children&&(e.children.sort(s),e.children().forEach(r))};return s?(e.sort(s),e.forEach(r),Promise.resolve(e)):(h.Assert.fail(`Unknown sort column: ${t.columnId}`),Promise.resolve(e))}}t.CountersListDAO=I,I.SortFunc={name:e=>o.SortFunctions.stringSort("name",e)},I.NextRowId=0}.apply(t,s),void 0===r||(e.exports=r)},663:(e,t,i)=>{var s,r;s=[i,t,i(28),i(952),i(560),i(766),i(758),i(558),i(756)],r=function(e,t,i,s,r,o,n,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CountersRowViewModel=void 0,t.CountersRowViewModel=class{constructor(e,t,r,d,l){this._decimals=2,this._selected=i.observable(!1),this._expanded=i.observable(!1),this._isChecked=i.observable(!1),this._children=i.observableArray([]),this._displayName=i.observable(""),this._displayUnit=i.observable(""),this._providerId=i.observable(""),this._providerName=i.observable(""),this._min=i.observable(0),this._max=i.observable(0),this._average=i.observable(0),this._marshaler=new o.DotNetCountersMarshaler,this._telemetry=new n.DotNetCountersTelemetryMarshaler,this._rowId=l,this._dataWarehouse=r,this._timeFilter=t,this._counterId=e,this._isChecked(d),this._localizedUnitConverter=i.pureComputed((()=>a.getLocalizedUnitConverter(this._displayUnit(),this._decimals)));const c={customDomain:{Task:"GetCounter",CounterId:e}};this._dataLoadPromise=this._dataWarehouse.getFilteredData(c,s.CountersAnalyzerId()).then((e=>e.getResult({type:"GetCounterSummary",begin:this._timeFilter().begin.jsonValue,end:this._timeFilter().end.jsonValue}))).then((e=>{if(this._min(e.min),this._max(e.max),this._average(e.a),e.cd){const t=JSON.parse(e.cd);t&&(this._displayName(t.dn),this._displayUnit(t.du),this._providerId(t.pId),this._providerName(t.pn))}}))}get templateName(){return"CountersRowView"}get id(){return this._rowId}get dataLoadPromise(){return this._dataLoadPromise}get name(){return this._displayName}get providerId(){return this._providerId}get displayUnit(){return this._displayUnit}get providerName(){return this._providerName}get converter(){return this._localizedUnitConverter}get formatTemplate(){return a.getFormatTemplate(this._displayUnit())}get min(){return this._min}get max(){return this._max}get average(){return this._average}get depth(){return 1}get selected(){return this._selected}get expanded(){return this._expanded}expand(){return this._isChecked(!this._isChecked()),this.toggleSwimlane(),Promise.resolve()}get isChecked(){return this._isChecked}onClick(e,t){if(t.which!==r.MouseCodes.Left)return;const i=t.target;i.classList&&i.classList.contains("select-counter")&&this.toggleSwimlane()}onKeyDown(e,t){if("Enter"!==t.key&&"Space"!==t.key)return;const i=t.target;let s;s=i.classList&&i.classList.contains("select-counter")?i:i.querySelector(".select-counter"),s.focus()}get children(){return this._children}invoke(){this._isChecked(!this._isChecked()),this.toggleSwimlane()}toggleSwimlane(){this._isChecked()?(this._marshaler.addCounter(this._counterId,this._displayName(),this._displayUnit()),this._telemetry.enableCounter(this._counterId)):(this._marshaler.removeCounter(this._counterId),this._telemetry.disableCounter(this._counterId))}}}.apply(t,s),void 0===r||(e.exports=r)},258:(e,t,i)=>{var s,r;s=[i,t,i(663),i(302)],r=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.MeterCountersRowViewModel=void 0;class s extends i.CountersRowViewModel{constructor(e,t,i,s,r){super(e,t,i,s,r)}get templateName(){return"MeterCountersRowView"}}t.MeterCountersRowViewModel=s}.apply(t,s),void 0===r||(e.exports=r)},443:(e,t,i)=>{var s,r;s=[i,t,i(28),i(834)],r=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ProviderRowViewModel=void 0,t.ProviderRowViewModel=class{constructor(e,t){this._selected=i.observable(!1),this._expanded=i.observable(!1),this._children=i.observableArray([]),this._providerName=e,this._rowId=t}get id(){return this._rowId}get name(){return this._providerName}get templateName(){return"ProviderRowView"}get depth(){return 0}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return!0}expand(e){const t=Promise.resolve();return this._expanded(!this._expanded()),t}get children(){return this._children}invoke(){this._expanded(!this._expanded())}}}.apply(t,s),void 0===r||(e.exports=r)},904:(e,t,i)=>{var s,r;s=[i,t,i(432),i(28),i(952),i(881),i(484),i(881),i(117),i(117),i(117),i(117),i(117),i(905),i(881),i(560),i(881),i(766),i(881),i(117),i(680),i(833),i(103)],r=function(e,t,i,s,r,o,n,a,d,l,c,u,h,g,C,I,m,b,p,v){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getDetailsViewModel=t.DotNetCountersViewModel=void 0;class A{constructor(){this._countersList=s.observable(),this._countersListDAO=s.observable(),this._counterIdsToTypes=s.observableArray([]),this._currentOverlay=s.pureComputed((()=>this.computeOverlay())),this._logger=d.getLogger("DotNetCountersViewModel"),this._updateDataHandler=!1,this._initialized=s.observable(!1),l.loadDataWarehouse().then((e=>(this._dataWarehouse=e,this._dataWarehouse.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((e=>{const t=c.getCurrentDocument();Promise.all([t.isActiveSession(),t.isPerformanceDebuggerDocument()]).then((async t=>{this._isCollection=s.observable(t[0]);const i=t[1];await this.loadAllCounterIds(),this.initializeView(e),this._counterIdsToTypes.subscribe((()=>{this._countersList().onResultChanged(0)}));const o=h.getViewEventManager();o.selectionChanged.addEventListener((e=>{e.isIntermittent||(this._countersListDAO().timeFilter(e.position),this._countersList().onResultChanged(0))})),s.applyBindings(this);let n=r.CountersAnalysisDetailsViewId();this._isCollection()&&(v.getCurrentSession().addStateChangedEventListener((t=>{400===t.currentState&&(this._initialized(!1),this._isCollection(!1),this.initializeView(e))})),n=i?r.CountersPerformanceDebuggingDetailsViewId():r.CountersCollectionDetailsViewId()),o.detailsViewReady.raiseEvent({Id:n})}))}))}get countersList(){return this._countersList()}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==I.KeyCodes.C)return!0;const i=m.TreeGridUtils.formatTreeGridSelectedToText(this._countersList());return navigator.clipboard.writeText(i),!1}initializeView(e){this._isCollection()?(u.getCollectionTimeService().timeUpdateEvent.addEventListener(this.loadAllCounterIds.bind(this)),this._countersListDAO(new n.CountersListDAO(this._dataWarehouse,this._counterIdsToTypes,e,this._isCollection)),this._header=new a.TreeGridHeaderViewModel([{id:"name",text:i.Resources.getString("CountersListHeaderName"),hideable:!1,sortable:C.SortDirection.Asc},{id:"latestValue",text:i.Resources.getString("CountersListHeaderLatestValue"),hideable:!0}],new g.CollectionCountersListColumnSettingsProvider,this._countersListDAO().defaultSortColumnId)):(this._countersListDAO(new n.CountersListDAO(this._dataWarehouse,this._counterIdsToTypes,e,this._isCollection)),this._header=new a.TreeGridHeaderViewModel([{id:"name",text:i.Resources.getString("CountersListHeaderName"),hideable:!1,sortable:C.SortDirection.Asc},{id:"min",text:i.Resources.getString("CountersListHeaderMin"),hideable:!0},{id:"max",text:i.Resources.getString("CountersListHeaderMax"),hideable:!0},{id:"average",text:i.Resources.getString("CountersListHeaderAverage"),hideable:!0}],new g.AnalysisCountersListColumnSettingsProvider,this._countersListDAO().defaultSortColumnId)),this._countersList(new o.TreeGridViewModel(this._countersListDAO(),this._header,"CountersListAriaLabel")),this._initialized(!0),this._countersList().onResultChanged(0)}loadAllCounterIds(){if(this._updateDataHandler)return Promise.resolve(void 0);const e={customDomain:{Task:"GetFilteredCounterIds",Providers:r.providerIds}};return this._updateDataHandler=!0,this._dataWarehouse.getFilteredData(e,r.CountersAnalyzerId()).then((e=>e.getResult({}))).then((e=>{const t=this._counterIdsToTypes().map((e=>e.id));e.idToTypes.map((e=>e.id)).length>t.length&&this._counterIdsToTypes(e.idToTypes),this._updateDataHandler=!1}),(e=>{this._logger.error(`Error occurred while communicating with the DataWarehouse: ${JSON.stringify(e,Object.getOwnPropertyNames(e))}`)}))}computeOverlay(){return this._isCollection()?null:this._initialized()&&this._countersList().dataLoadStatus()!==C.DataLoadEvent.DataLoadStart&&this._countersListDAO().providerDataLoadStatus()!==C.DataLoadEvent.DataLoadStart?this._initialized()&&this._countersList().dataLoadStatus()===C.DataLoadEvent.DataLoadCompleted&&this._countersListDAO().providerDataLoadStatus()===C.DataLoadEvent.DataLoadCompleted&&0===this._countersList().treeAsArray().length?{name:"MessageView",data:i.Resources.getString("NoDataMessage")}:null:{name:"LoadingView"}}}let _;t.DotNetCountersViewModel=A,(new b.DotNetCountersMarshaler).getDoubleClickTimeMs().then((e=>{p.Init(e),_=new A})),t.getDetailsViewModel=function(){return _}}.apply(t,s),void 0===r||(e.exports=r)},371:function(e,t,i){var s,r,o=this&&this.__createBinding||(Object.create?function(e,t,i,s){void 0===s&&(s=i),Object.defineProperty(e,s,{enumerable:!0,get:function(){return t[i]}})}:function(e,t,i,s){void 0===s&&(s=i),e[s]=t[i]}),n=this&&this.__exportStar||function(e,t){for(var i in e)"default"===i||Object.prototype.hasOwnProperty.call(t,i)||o(t,e,i)};s=[i,t,i(904)],r=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),n(i,t)}.apply(t,s),void 0===r||(e.exports=r)},766:(e,t,i)=>{var s,r;s=[i,t,i(432),i(117)],r=function(e,t,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersMarshaler=void 0;let r=null;t.DotNetCountersMarshaler=class{constructor(){r||(r=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetCounters.DotNetCountersMarshaler",{},!0)),this._counterAddedEvent=new s.ObservableEvent(r,"CounterAddedEvent"),this._counterRemovedEvent=new s.ObservableEvent(r,"CounterRemovedEvent")}getDoubleClickTimeMs(){return r._call("getDoubleClickTimeMs")}getCountersAddedToSwimlane(){return r._call("getCountersAddedToSwimlane")}get counterAddedEvent(){return this._counterAddedEvent}get counterRemovedEvent(){return this._counterRemovedEvent}addCounter(e,t,i){r._call("addCounter",e,t,i)}removeCounter(e){r._call("removeCounter",e)}getColumnSettings(e){return r._call("getColumnSettings",e)}onColumnChanged(e,t){r._call("onColumnChanged",e,t)}}}.apply(t,s),void 0===r||(e.exports=r)},758:(e,t,i)=>{var s,r;s=[i,t,i(432)],r=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersTelemetryMarshaler=void 0;let s=null;t.DotNetCountersTelemetryMarshaler=class{constructor(){null===s&&(s=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetCounters.DotNetCountersTelemetryMarshaler",{},!0))}enableCounter(e){s._post("enableCounter",e)}disableCounter(e){s._post("disableCounter",e)}}}.apply(t,s),void 0===r||(e.exports=r)},558:(e,t,i)=>{var s,r;s=[i,t,i(432),i(560)],r=function(e,t,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.MiBUnitConverter=t.ByteUnitConverter=t.getFormatTemplate=t.getLocalizedUnitConverter=void 0,t.getLocalizedUnitConverter=function(e,t){return"%"===e?new s.LocalizedUnitConverter([{Unit:"percentage",Divider:1,Decimals:t,LowerBound:0}],{percentage:"%"}):"B"===e?new r(t):"MB"===e?new o(t):new s.LocalizedUnitConverter([{Unit:"",Divider:1,Decimals:t,LowerBound:0},{Unit:i.Resources.getString("/DiagnosticsHubSwimlaneResources/CountKUnit"),Divider:1e3,Decimals:t,LowerBound:1e3},{Unit:i.Resources.getString("/DiagnosticsHubSwimlaneResources/CountMUnit"),Divider:1e6,Decimals:t,LowerBound:1e6},{Unit:i.Resources.getString("/DiagnosticsHubSwimlaneResources/CountBUnit"),Divider:1e9,Decimals:t,LowerBound:1e9}],{"":""})},t.getFormatTemplate=function(e){return"%"===e?i.Resources.getString("/DiagnosticsHubSwimlaneResources/FormattedPercentage"):i.Resources.getString("/DiagnosticsHubSwimlaneResources/FormattedNumberWithUnitsTableView")};class r extends s.BitBinaryMultipleUnitConverter{scaleValue(e){return super.scaleValue(8*e)}}t.ByteUnitConverter=r;class o extends s.BitBinaryMultipleUnitConverter{scaleValue(e){return super.scaleValue(1024*e*1024*8)}}t.MiBUnitConverter=o}.apply(t,s),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=i},28:e=>{"use strict";e.exports=s},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},n={},function e(t){var i=n[t];if(void 0!==i)return i.exports;var s=n[t]={exports:{}};return o[t].call(s.exports,s,s.exports,e),s.exports}(371);var o,n}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // g7tPUCY3IImBDMu+ZMb0EeZQhMH78CjPhfbMTcHLBiSg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCDl4egalK5Dlq1Y3MIrBc2TGqTmy9e5h/8h
// SIG // whk+aQ6qyTBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAJ/zmRJq
// SIG // OujtG0Bz5fhhVv+ut9exzCXLsr8GBh0me8UfjBIoLaZ4
// SIG // Tm1092F49waQJ9Pyh+Y1Ed3JRl/oI2Vvi34KEsti8iRS
// SIG // qECCc28iEypCYey4XBzfQOOv/BmXcS4AEGOo2WA3tz3z
// SIG // fpsgANzgCOolLFF8qHYNjxjOiBgcydOdki6JbvPjAibt
// SIG // vTM6Xwve/pnpqnrmsqgZ1u45M6PdMDgAyHdlDgXT2+ny
// SIG // 6VNeuYCvRK58fT5F4Kq6HFvyTHo4NNpallS0DQIEJj7p
// SIG // z44bgvrfLnZ7RlulF3wMyVZCt1vCqIwu7AjZM9KbELR0
// SIG // V4X1d7kUB3tvXJZY8IF+hGqhmjyhgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgjn/vAgfu3v6OhnTRr0/0
// SIG // hpDXcMlTHuxaxRVNFFinoHwCBmUoXJWJXBgTMjAyMzEw
// SIG // MjAxNzA0MzcuNDcyWjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOkE0MDAtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAHWJ2n/ci1WyK4A
// SIG // AQAAAdYwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNTI1MTkxMjM0WhcN
// SIG // MjQwMjAxMTkxMjM0WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OkE0MDAtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAzyzNjpvK+bt33Gwx
// SIG // Dl8nSbW5FuVN+ChWn7QvvEMjaqZTCM0kwtU6BNM3MHkA
// SIG // rzyH6WLcjwd47enz0aa74cApLFMPadDn5mc1jw75LeNA
// SIG // VErbvNd0Ja5aEXaZS89saZNvYyDmePqwWymmZAT2eEeC
// SIG // 10IZJB53tGP2IfOWajDEWjFpATOp1MFeWg4sF6nRPScp
// SIG // dItWlmGwqs8AUXTewk5QCcayeO6L97n/5RYPYZ1UHKkG
// SIG // IEa0RaQzRTDj9IMM+TY+mtuBmZ3BRBkZisCJi/uSlj51
// SIG // YL2nSUkaemaq2FdxZmwZmbbBdIUpVYy0DvJ8XpRle076
// SIG // iCEiLL9m0DIFAVRM/MBxclN/Ot4B4/AQmxKSc5u+Xyyb
// SIG // C9z+upSVDUTewkbHzRGx3V/3eo6KVThcBe6Jpk0I6VN+
// SIG // wP+2EdMCQ07embF1Po/8GJaPW9trdalLYao0bN9qBn9k
// SIG // 0UwqEFi4SXt3ACGEZZWv4BCpW7gw7Bt/dusuBDBxcU47
// SIG // I63GRGw1sIwd8K6ddQ8oNUCnA8i1LNmpwaJb0MCUzdJj
// SIG // DrlzvLQc9tJ4P/l8PuMPlvTzJL1tX2mIuN+VYykWbB38
// SIG // SD4yM2dMH+BYm5lTyR2fmk8RrFST8cnQob7xgn+H3vF3
// SIG // 2GPT+ZW5/UnCnOGnU3eOBgqwZSfyTrKAODrzR2Olvl3C
// SIG // lXCCBlsCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBRhmlQ2
// SIG // O00AYjAioNvo/80U3GLGTjAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // 1L/kYzYncCcUmzJNSL0vC38TTPFWlYacUdUpFvhUWOgC
// SIG // pJ9rNzp9vZxhFZWrW5SL9alUypK1MS2DGdM/kQOppn17
// SIG // ntmO/2AW8zOZFHlIFNstTJm4p+sWnU/Q8xAnhOxOPt5N
// SIG // g5mcblfhixWELKpA23vKMu/twUolNvasmQGE/b0QwCz1
// SIG // AuWcMqD5DXym6o5d1YBU6iLmxEK+ejNGHTFpagqqtMlZ
// SIG // Z/Zj24Rx81xzo2kLLq6IRwn+1U/HLe/aaN+BXfF3LKps
// SIG // oXSgctY3cpJ64pPhd7xJf/dKmqJ+TfCk2aBrThZWiRT5
// SIG // 2dg6kLW9llpH7gKBlqxkgONzMpe/j2G1LK4vzazLwHfW
// SIG // fifRZarDMF0BcQAe7oyYuIT/AR/I+qpJsuLrpVOUkkGu
// SIG // l5BJXGikGEqSXEo5I8kwyDqX+i2QU2hcennqKg2dJVEY
// SIG // YkajvtcqPLlzvPXupIAXgvLdVjeSE6l546HGIA78haab
// SIG // bFA4J0VIiNTP0JfztvfVZLTJCC+9oukHeAQbK492foix
// SIG // Jyj/XqVMKLD9Ztzdr/coV0NR4rrCZetyH1yMnwSWlr0A
// SIG // 4FNyZOHiGUq/9iiI+KbV7ePegkYh04tNdZHMA6XY0CwE
// SIG // Igr6I9absoX8FX9huWcAabSF4rzUW2t+CpA+aKphKBdc
// SIG // kRUPOIg7H/4Isp/1yE+2GP8wggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjpBNDAwLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUA+a9w1UaQBkKP
// SIG // bEy1B3gQvOzaSvqggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjc
// SIG // vWUwIhgPMjAyMzEwMjAwODQ4MzdaGA8yMDIzMTAyMTA4
// SIG // NDgzN1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA6Ny9
// SIG // ZQIBADAHAgEAAgIGRDAHAgEAAgISYDAKAgUA6N4O5QIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQA6gqoxwGYJdgG/QskmrjCsOtwmaDB5
// SIG // 3zV29t6keen7Q0qWdr7ZfpSJM3DJcffLeNPG8rft/Rlb
// SIG // 90/XKpwD/YJPOZaBJDZT5sOHK88BFFXwRAzy+ghYTxm/
// SIG // 3EBFPR831MfNdlDlgwQBwvthPepGSUosxgGojXvWU+FL
// SIG // pWTAtE7xVJlc9OTyNJut/iTrVD5U8sn8DOJbU/2bU76d
// SIG // x6Wbzm3LzJEcrWSB9vvVGLYkconP2YeGkvhyGaHW4mv6
// SIG // udGMzbB4PQyZ2cHdbpsXNfstvY3Ay2PhBl0wXfT15wnU
// SIG // AU1dkTTN96g/aPvV9p/QX6TtYcikKWYsKWy3Yac0i4LN
// SIG // eXNhMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAHWJ2n/ci1WyK4AAQAAAdYw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQghgPj
// SIG // 4jplApD9Ls1ZzvwL3Wm9DeDT/iaYPiK2dEGBkxowgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCDWy00NV3jT
// SIG // PhAYpzhCTI2XdIzDQ7q/gCvjvD9do+Uk/DCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
// SIG // 1idp/3ItVsiuAAEAAAHWMCIEIKQEpZmXB09LvnOSgPUU
// SIG // miouVYcWKKd+PpVNrUuHCHufMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAGC+JDqTzQk8e0flDrdxxmD/+E6tptzyFiGiyKHy
// SIG // L1eAovl4wIvSo0R0+KG8PVQvP9HDbcRZj2kO0W5EnZut
// SIG // FsdL8GBf45AnqFHCFXY20W2L7Ps22pVd6ViUMmBdwZ0B
// SIG // ERBq4428Hp2lW17nSoPFZPjnb1von6eOzXbzekpgRIIJ
// SIG // BMDpWWCU9kpS3TSAgjxACjmBD9kJ6t74/asW1zXWsYh0
// SIG // FLYB09ZBxXQ07WQTv0pKkgZduWxux5bitEfW4CHd5zOD
// SIG // fxQ8ZR2/9RXtYzcTT4/BubyektWgqmOelJ+rm/nXqdEb
// SIG // UqWhI0wog//DPqtiay3ru8NalI5GhsJ0+8yelWioktv1
// SIG // QuLa+dVytrNEB9HxAAW25RqFHSM2BOGgblKcTx4gDg4+
// SIG // LJW57B2fHOYIhcywZzJAgjhBbVKEOUNJPyRP0tc2LSP6
// SIG // GPMDm4lXvhQl2hs/qubI3lD+boflwsp7Um0Kl+sYi6WL
// SIG // 6kGazQIt06MruqbNRwWjWF0Qa5/OzZFTxv5TWf7PPDFz
// SIG // gYBVsUQYkDRE4CNWkfuFWOpr7cchAU/Ld1uaEmw5ZWD0
// SIG // 8yLJM8k98I/vcv20M27RYYp++mO7nfjwiiEOsJiac6gW
// SIG // OEIIokfKLVMfWFwQ3TwWC5mK6xfkF9hEmD3kn4j3yUE+
// SIG // Ae3uGWYPtuqJatKwAD6sz+4d/CH1
// SIG // End signature block
