define("fileWritesViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,r,a)=>{return s={750:e=>{const t=document.createElement("script");t.id="BacktraceRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9ImJhY2t0cmFjZXNOYW1lIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8c3BhbiBjbGFzcz0idHJlZUdyaWRDZWxsLWxhYmVsIiBkYXRhLWJpbmQ9InRleHQ6IGxhYmVsIj48L3NwYW4+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9ImxvY2FsaXplZE51bWJlcjoge3ZhbHVlOiBvcGVyYXRpb25TaXplS0IsIG9wdGlvbnM6IHttaW5pbXVtRnJhY3Rpb25EaWdpdHM6IDMsIG1heGltdW1GcmFjdGlvbkRpZ2l0czogM319IiBkYXRhLWNvbHVtbmlkPSJiYWNrdHJhY2VzT3BlcmF0aW9uU2l6ZUtCIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBvcGVyYXRpb25Db3VudCIgZGF0YS1jb2x1bW5pZD0iYmFja3RyYWNlc09wZXJhdGlvbkNvdW50Ij48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBtb2R1bGVOYW1lIiBkYXRhLWNvbHVtbmlkPSJiYWNrdHJhY2VzTW9kdWxlTmFtZSI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},538:e=>{const t=document.createElement("script");t.id="FileReadWriteRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ib3BlcmF0aW9uQ291bnQiIGRhdGEtYmluZD0idGV4dDogb3BlcmF0aW9uQ291bnQiIGRhdGEtY29sdW1uaWQ9Im9wZXJhdGlvbkNvdW50Ij48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9Im9wZXJhdGlvblNpemVLQiIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRPcGVyYXRpb25TaXplS0IiIGRhdGEtY29sdW1uaWQ9Im9wZXJhdGlvblNpemVLQiI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJmaWxlU2l6ZUtCIiBkYXRhLWJpbmQ9InRleHQ6IGxvY2FsaXplZEZpbGVTaXplS0IiIGRhdGEtY29sdW1uaWQ9ImZpbGVTaXplS0IiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZHVwbGljYXRpb25GYWN0b3IiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkRHVwbGljYXRpb25GYWN0b3IiIGRhdGEtY29sdW1uaWQ9ImR1cGxpY2F0aW9uRmFjdG9yIj48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},701:(e,t,i)=>{var r,a;r=[i,t,i(952),i(28),i(881),i(881),i(117),i(117),i(453)],a=function(e,t,i,r,a,s,o,n,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BacktraceDAO=void 0;class d{constructor(e,t,i,s){this._dataLoadStatus=r.observable(a.DataLoadEvent.DataLoadCompleted),this._currentFileId=-1,this._currentProcessId=-1,this._currentPid=-1,this._currentSelectedFileName=r.observable(""),this._logger=o.getLogger("BacktraceDAO"),this._automation=n.getAutomationManager(this._logger),this._dataWarehouse=e,this._timeFilter=r.observable(t),this._marshaler=i,this._isReads=s}getRoots(e,t,r){this._dataLoadStatus(a.DataLoadEvent.DataLoadStart),this._currentFileId=e;let s=!1;e===d.NewFilterRequest&&(this._currentResult&&(this._currentResult.dispose(),this._currentResult=null),s=!0,this._currentProcessId=e,this._currentPid=e);let o=Promise.resolve(this._currentResult);return!this._currentResult&&(o=this._marshaler.isNativeCodeFoldingEnabled().then((e=>({timeDomain:this.timeFilter(),customDomain:{view:"Backtrace",FoldNativeFrames:e?"true":"false"}}))).then((e=>this._dataWarehouse.getFilteredData(e,i.FileIOAnalyzerId(),r))),s)?o.then((()=>(this._dataLoadStatus(a.DataLoadEvent.DataLoadCompleted),Promise.resolve([])))):o.then((e=>{null==r||r.throwIfCancellationRequested();const t=this._dataWarehouse.getJmcService().getJmcEnabledState();this._currentResult=e;const i=Promise.resolve(this._currentResult.getResult({task:"getRoots",fileId:this._currentFileId,isReads:this._isReads,processId:this._currentProcessId,pid:this._currentPid},r));return Promise.all([i,t])})).then((e=>{null==r||r.throwIfCancellationRequested();const i=e[0],s=e[1],o=i.map((e=>new l.BacktraceRowViewModel(null,this,this._currentFileId,this._currentProcessId,this._currentPid,e,0,s)));return this._dataLoadStatus(a.DataLoadEvent.DataLoadCompleted),1===o.length?this.expand(o[0],t,r).then((()=>o)):Promise.resolve(o)})).then((e=>this.sort(e,t,r)))}get timeFilter(){return this._timeFilter}expand(e,t,i){return e.expand(this._currentResult,t,i)}search(e,t,i,r,a,s,o){throw new Error("Method not implemented.")}sort(e,t,i){const r=d.SortFunc[t.columnId](t.direction),a=e=>{e.children&&(e.children.sort(r),e.children().forEach(a))};return e.sort(r),e.forEach(a),Promise.resolve(e)}get defaultSortColumnId(){return"backtracesOperationSizeKB"}get currentFileId(){return this._currentFileId}get currentPid(){return this._currentPid}set currentPid(e){this._currentPid=e}get currentProcessId(){return this._currentProcessId}set currentProcessId(e){this._currentProcessId=e}get dataLoadStatus(){return this._dataLoadStatus}get currentFileName(){return this._currentSelectedFileName}getSourceInfo(e){return this._currentResult.getResult({task:"getSourceInfo",rowId:e,isReads:this._isReads})}}t.BacktraceDAO=d,d.NewFilterRequest=-1,d.SortFunc={backtracesName:e=>s.SortFunctions.stringSort("name",e),backtracesOperationSizeKB:e=>s.SortFunctions.numericSort("operationSizeKB",e),backtracesOperationCount:e=>s.SortFunctions.numericSort("operationCount",e),backtracesModuleName:e=>s.SortFunctions.stringSort("moduleName",e)}}.apply(t,r),void 0===a||(e.exports=a)},453:(e,t,i)=>{var r,a;r=[i,t,i(28),i(432),i(881),i(558),i(750)],a=function(e,t,i,r,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BacktraceRowViewModel=void 0;class o{constructor(e,t,r,a,s,o,n,l){this._selected=i.observable(!1),this._expanded=i.observable(!1),this._haveLoaded=!1,this._jmcEnabled=!1,this._dto=o,this._depth=n,this._jmcEnabled=l,this._parent=e,this._dao=t,this._fileId=r,this._processId=a,this._pid=s,this._children=i.observableArray([]),this._label=i.pureComputed((()=>this.computeLabel()))}get templateName(){return"BacktraceRowView"}get id(){return this._dto.id}get name(){return this._dto.n}get operationCount(){return this._dto.co}get operationSizeKB(){return s.convertBytesToKB(this._dto.op)}get isReads(){return this._dto.ir}get label(){return this._label}get depth(){return this._depth}get selected(){return this._selected}get children(){return this._children}get expanded(){return this._expanded}invoke(){}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get AggregationId(){return this._dto.aId}get moduleName(){switch(this._dto.mc){case 0:return r.Resources.getString("UnknownModuleLabel");case 1:return this._dto.mn;default:return r.Resources.getString("MultipleModuleLabel")}}get expandable(){return void 0===this._dto.c||this._children().length>0}computeLabel(){if(this._dto.a===a.AggregateType.BrokenStack)return r.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case a.AggregateType.Native:return r.Resources.getString("FoldedNativeLabel");case a.AggregateType.AsyncMethod:return r.Resources.getString("AsyncMethodLabel");default:return""}if(this._dto.n)switch(this._dto.j){case a.JmcState.SystemCode:return r.Resources.getString("SystemCallLabel");case a.JmcState.LibraryCode:return r.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case a.AggregateType.SystemCode:return r.Resources.getString("SystemCodeLabel");case a.AggregateType.JmcRejected:return r.Resources.getString("ExternalCodeLabel");case a.AggregateType.AsyncMethod:return r.Resources.getString("AsyncMethodLabel");case a.AggregateType.Native:return r.Resources.getString("FoldedNativeLabel");default:return""}}expand(e,t,i){let r=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,r=e.getResult({task:"expand",fileId:this._fileId,rowId:this.id,path:this.getIdPath(),isReads:this.isReads,processId:this._processId},i).then((e=>{null==i||i.throwIfCancellationRequested();const r=e.map((e=>new o(this,this._dao,this._fileId,this._processId,this._pid,e,this.depth+1,this._jmcEnabled)));return this._dao.sort(r,t)})).then((r=>(null==i||i.throwIfCancellationRequested(),this.children(r),1===r.length?r[0].expand(e,t,i):Promise.resolve())))),this._expanded(!this._expanded()),r}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}}t.BacktraceRowViewModel=o}.apply(t,r),void 0===a||(e.exports=a)},118:(e,t,i)=>{var r,a;r=[i,t,i(79)],a=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOColumnSettingsProvider=void 0,t.FileIOColumnSettingsProvider=class{constructor(e){this._marshaler=new i.FileIOMarshaler,this._templateName=e}getColumnSettings(){return this._marshaler.getColumnSettings(this._templateName)}onColumnChanged(e){this._marshaler.onColumnChanged(this._templateName,e)}}}.apply(t,r),void 0===a||(e.exports=a)},952:(e,t,i)=>{var r;r=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOAnalyzerId=t.FileWritesViewId=t.FileReadsViewId=void 0,t.FileReadsViewId=function(){return"4AA24559-7978-4ECB-B9DE-697514D19709"},t.FileWritesViewId=function(){return"C9350735-F728-4EE7-A5F0-F008F3F82E03"},t.FileIOAnalyzerId=function(){return"C8556299-6B78-4348-848F-C90C46FF567D"}}.apply(t,[i,t]),void 0===r||(e.exports=r)},79:(e,t,i)=>{var r,a;r=[i,t,i(432),i(117)],a=function(e,t,i,r){"use strict";let a;Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOMarshaler=void 0,t.FileIOMarshaler=class{constructor(){a||(a=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.FileIO.FileIOMarshaler",{},!0)),this._updateNativeCodeEvent=new r.ObservableEvent(a,"updateNativeCodeEvent")}getDoubleClickTimeMs(){return a._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return a._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return a._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return a._call("getColumnSettings",e)}onColumnChanged(e,t){return a._call("onColumnChanged",e,t)}}}.apply(t,r),void 0===a||(e.exports=a)},455:(e,t,i)=>{var r,a;r=[i,t,i(432)],a=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOTelemetryMarshaler=void 0;let r=null;t.FileIOTelemetryMarshaler=class{constructor(){null===r&&(r=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.FileIO.VisualStudio.FileIOTelemetryMarshaler",{},!0))}backtraceComputed(){r._post("backtraceComputed")}contextMenuVisible(){r._post("contextMenuVisible")}sourceFileOpened(){r._post("sourceFileOpened")}}}.apply(t,r),void 0===a||(e.exports=a)},953:(e,t,i)=>{var r,a;r=[i,t,i(28),i(952),i(97),i(881)],a=function(e,t,i,r,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileReadWriteDAO=void 0;class o{constructor(e,t,r,a,s){this._roots=i.observableArray([]),this._dataWarehouse=e,this._timeFilter=i.observable(t),this._isReads=r,this._backtrace=a,this._backtraceDao=s,this._isReads?this._viewName="FileReads":this._viewName="FileWrites"}get timeFilter(){return this._timeFilter}get roots(){return this._roots}get defaultSortColumnId(){return"duplicationFactor"}getRoots(e,t,i){const s={timeDomain:this.timeFilter(),customDomain:{view:this._viewName}};return this._dataWarehouse.getFilteredData(s,r.FileIOAnalyzerId()).then((e=>(this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this._currentResult?this._currentResult.getResult({task:"getRoots",isReads:this._isReads}):[]))).then((e=>{e instanceof Array&&this._roots(e.map((e=>new a.FileReadWriteRowViewModel(e,0,this._backtrace,this._backtraceDao))))})).then((()=>1!==this._roots().length||this._roots()[0].expanded()?this.sort(this._roots(),t,i):this.expand(this._roots()[0],t,i).then((()=>this.sort(this._roots(),t,i)))))}expand(e,t,i){return e.expand(this._currentResult,t,i)}search(e,t,i,r,a,s,o){throw new Error("Method not implemented.")}sort(e,t,i){const r=o.SortFunc[t.columnId](t.direction),a=e=>{e.children&&(e.children.sort(r),e.children().forEach(a))};return e.sort(r),e.forEach(a),Promise.resolve(e)}getSourceInfo(e,t,i){return this._currentResult.getResult({task:"getSourceInfo",processId:e,codeAddress:t,timestamp:i})}}t.FileReadWriteDAO=o,o.SortFunc={name:e=>s.SortFunctions.stringSort("name",e),duplicationFactor:e=>s.SortFunctions.numericSort("duplicationFactor",e),operationCount:e=>s.SortFunctions.numericSort("operationCount",e),operationSizeKB:e=>s.SortFunctions.numericSort("operationSizeKB",e),fileSizeKB:e=>s.SortFunctions.numericSort("fileSizeKB",e)}}.apply(t,r),void 0===a||(e.exports=a)},97:(e,t,i)=>{var r,a;r=[i,t,i(432),i(28),i(558),i(455),i(538)],a=function(e,t,i,r,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileReadWriteRowViewModel=void 0;class o{constructor(e,t,i,a){this._selected=r.observable(!1),this._expanded=r.observable(!1),this._children=r.observableArray([]),this._haveLoaded=!1,this._telemetry=new s.FileIOTelemetryMarshaler,this._dto=e,this._depth=t,this._backtrace=i,this._backtraceDao=a}get fileId(){return this._dto.fid}get codeAddress(){return this._dto.ca}get name(){return this._dto.nm?this._dto.nm:i.Resources.getString("UnknownDataLabel")}get operationCount(){return this._dto.co}get operationSizeKB(){return a.convertBytesToKB(this._dto.op)}get localizedOperationSizeKB(){return this.operationSizeKB.toLocaleString(i.Culture.formatRegion,{minimumFractionDigits:3,maximumFractionDigits:3})}get fileSizeKB(){return 0===this._dto.s?null:a.convertBytesToKB(this._dto.s)}get localizedFileSizeKB(){return this.fileSizeKB?this.fileSizeKB.toLocaleString(i.Culture.formatRegion,{minimumFractionDigits:3,maximumFractionDigits:3}):""}get duplicationFactor(){return this.fileSizeKB?this.operationSizeKB/this.fileSizeKB:null}get localizedDuplicationFactor(){return this.duplicationFactor?this.duplicationFactor.toLocaleString(i.Culture.formatRegion,{minimumFractionDigits:3,maximumFractionDigits:3}):""}get isReads(){return this._dto.ir}get processId(){return this._dto.procId}get pid(){return this._dto.pid}get isSizeEstimate(){return this._dto.ie}get timestamp(){return this._dto.ti}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get templateName(){return"FileReadWriteRowView"}get id(){return this.fileId}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return this._dto.co>1}get children(){return this._children}invoke(){-1===this.fileId||this.processId===this._backtraceDao.currentProcessId&&this.fileId===this._backtraceDao.currentFileId||(this._backtraceDao.currentProcessId=this.processId,this._backtraceDao.currentPid=this.pid,this._backtrace.onResultChanged(this.id),this._telemetry.backtraceComputed(),this._backtraceDao.currentFileName(this.name))}expand(e,t,i){let r=Promise.resolve(void 0);return this.expandable?(this._haveLoaded||(this._haveLoaded=!0,r=e.getResult({task:"expand",fileId:this.fileId,isReads:this.isReads,processId:this.processId},i).then((e=>{const t=e.map((e=>new o(e,this.depth+1,this._backtrace,this._backtraceDao)));this.children(t)}))),this._expanded(!this._expanded()),r):r}}t.FileReadWriteRowViewModel=o}.apply(t,r),void 0===a||(e.exports=a)},811:(e,t,i)=>{var r,a;r=[i,t,i(28),i(432),i(952),i(117),i(117),i(560),i(881),i(881),i(881),i(881),i(881),i(117),i(117),i(117),i(881),i(455),i(953),i(79),i(701),i(453),i(118),i(680),i(833),i(103)],a=function(e,t,i,r,a,s,o,n,l,d,c,h,u,g,m,p,I,b,_,R,F,v,C){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getFileWritesViewModel=t.FileWritesViewModel=void 0;class S{constructor(){let e;this._marshaler=new R.FileIOMarshaler,this._telemetry=new b.FileIOTelemetryMarshaler,this._logger=s.getLogger("FileWritesViewModel"),this._automation=o.getAutomationManager(this._logger),this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._backtraceOverlay=i.pureComputed((()=>this.computeBacktraceOverlay())),this._backtraceFile=i.pureComputed((()=>r.Resources.getString("BacktraceFileDisplay",this._backtraceDao.currentFileName(),this._backtraceDao.currentPid))),g.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((t=>Promise.all([e.getJmcService().getJmcEnabledState(),t.getTimeDomain(),this._marshaler.isNativeCodeFoldingEnabled()]))).then((t=>{this._showJmc=new I.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(t[0]),this._showJmc.isChecked.subscribe((()=>{e.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new I.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked(!t[2]),this._showNative.isChecked.subscribe((()=>{this._marshaler.setNativeCodeFoldingEnabled(!this._showNative.isChecked()),this._backtraceTree.onResultChanged(F.BacktraceDAO.NewFilterRequest)})),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>this._showNative.isChecked(!e.isEnabled))),this._backtraceDao=new F.BacktraceDAO(e,t[1],this._marshaler,!1);const s=r.Resources.getString,o=new c.TreeGridHeaderViewModel([{id:"backtracesName",text:s("FileReadWriteHeaderName"),tooltip:s("FileReadWriteTreeGrid_NameTooltip"),hideable:!1,sortable:d.SortDirection.Asc},{id:"backtracesOperationSizeKB",text:s("FileWritesHeaderKBWritten"),tooltip:s("FileReadWriteTreeGrid_DataWriteTooltip"),hideable:!0,sortable:d.SortDirection.Desc},{id:"backtracesOperationCount",text:s("FileReadWriteHeaderCount"),tooltip:s("FileReadWriteTreeGrid_WriteCountTooltip"),hideable:!0,sortable:d.SortDirection.Desc},{id:"backtracesModuleName",text:s("HeaderModuleName"),tooltip:s("HeaderModuleNameToolTip"),hideable:!0,sortable:d.SortDirection.Asc}],new C.FileIOColumnSettingsProvider("BacktraceView"),this._backtraceDao.defaultSortColumnId);this._backtraceTree=new l.TreeGridViewModel(this._backtraceDao,o,"BacktraceAriaLabel"),this._fileReadWriteDAO=new _.FileReadWriteDAO(e,t[1],!1,this._backtraceTree,this._backtraceDao);const n=new c.TreeGridHeaderViewModel([{id:"name",text:s("FileReadWriteHeaderName"),tooltip:s("FileReadWriteTreeGrid_NameTooltip"),hideable:!1,sortable:d.SortDirection.Asc},{id:"duplicationFactor",text:s("FileReadWriteHeaderDuplicationFactor"),tooltip:s("FileReadWriteTreeGrid_WriteDuplicationFactorTooltip"),hideable:!0,sortable:d.SortDirection.Desc},{id:"operationCount",text:s("FileReadWriteHeaderCount"),tooltip:s("FileReadWriteTreeGrid_WriteCountTooltip"),hideable:!0,sortable:d.SortDirection.Desc},{id:"operationSizeKB",text:s("FileWritesHeaderKBWritten"),tooltip:s("FileReadWriteTreeGrid_DataWriteTooltip"),hideable:!0,sortable:d.SortDirection.Desc},{id:"fileSizeKB",text:s("FileReadWriteHeaderSize"),tooltip:s("FileReadWriteTreeGrid_SizeTooltip"),hideable:!0,sortable:d.SortDirection.Desc}],new C.FileIOColumnSettingsProvider("ReadWriteView"),this._fileReadWriteDAO.defaultSortColumnId);this._fileWrites=new l.TreeGridViewModel(this._fileReadWriteDAO,n,"FileWritesAriaLabel");const h=m.getViewEventManager();this._fileWrites.onResultChanged(0),h.selectionChanged.addEventListener((e=>{e.isIntermittent||(this._fileReadWriteDAO.timeFilter(e.position),this._backtraceDao.timeFilter(e.position),this._fileWrites.onResultChanged(0))})),this._backtraceDao.timeFilter.subscribe((()=>this._backtraceTree.onResultChanged(F.BacktraceDAO.NewFilterRequest))),h.jmcEnabledStateChanged.addEventListener((e=>{this.showJmc.isChecked(e.currEnabledState),this._backtraceTree.onResultChanged(F.BacktraceDAO.NewFilterRequest),this._fileWrites.onResultChanged(0),this._fileWrites.selectedRows([])})),i.applyBindings(this),h.detailsViewReady.raiseEvent({Id:a.FileWritesViewId()})}))}get fileWrites(){return this._fileWrites}get backtraceTree(){return this._backtraceTree}get currentOverlay(){return this._currentOverlay}get backtraceOverlay(){return this._backtraceOverlay}get backtraceFile(){return this._backtraceFile}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get showJmcButtonEnabled(){return!0}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==n.KeyCodes.C)return!0;const i=h.TreeGridUtils.formatTreeGridSelectedToText(this._fileWrites,!1);return navigator.clipboard.writeText(i),!1}onKeyDownBacktrace(e,t){if(!t.ctrlKey||t.keyCode!==n.KeyCodes.C)return!0;const i=h.TreeGridUtils.formatTreeGridSelectedToText(this._backtraceTree);return navigator.clipboard.writeText(i),!1}showSourceFile(e){e instanceof v.BacktraceRowViewModel?this._backtraceDao.getSourceInfo(e.AggregationId).then((t=>{e.sourceFilePosition=t,t?(this._telemetry.sourceFileOpened(),p.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition)):this._automation.getAlertPromise(o.AutomationConstants.DataWarehouseRequestKey,r.Resources.getString("NoSource"))})):this._fileReadWriteDAO.getSourceInfo(e.processId,e.codeAddress,e.timestamp).then((t=>{e.sourceFilePosition=t,t?(this._telemetry.sourceFileOpened(),p.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition)):this._automation.getAlertPromise(o.AutomationConstants.DataWarehouseRequestKey,r.Resources.getString("NoSource"))}))}contextMenu(e,t){this._telemetry.contextMenuVisible();const i=e;if("number"!=typeof i.id)return null;const a=i instanceof v.BacktraceRowViewModel;let s=this._fileWrites;a&&(s=this._backtraceTree);const o=a,n=[{label:r.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>this.showSourceFile(i),disabled:()=>!i.sourceFilePosition,type:r.ContextMenu.MenuItemType.command},{type:r.ContextMenu.MenuItemType.separator},{label:r.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=h.TreeGridUtils.formatTreeGridSelectedToText(s,o);navigator.clipboard.writeText(e)},type:r.ContextMenu.MenuItemType.command},{label:r.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=h.TreeGridUtils.formatTreeGridSelectedToMarkdown(s,o);navigator.clipboard.writeText(e)},type:r.ContextMenu.MenuItemType.command}];return r.ContextMenu.create(n)}computeOverlay(){return this._fileWrites.dataLoadStatus()===d.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._fileWrites.dataLoadStatus()===d.DataLoadEvent.DataLoadCompleted&&0===this._fileWrites.treeAsArray().length?{name:"MessageView",data:r.Resources.getString("NoDataMessage")}:this._fileWrites.dataLoadStatus()===d.DataLoadEvent.DataLoadFailed?{name:"MessageView",data:r.Resources.getString("UnableShowDataMessage")}:null}computeBacktraceOverlay(){return this._backtraceDao.dataLoadStatus()===d.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._backtraceDao.dataLoadStatus()===d.DataLoadEvent.DataLoadCompleted&&0===this._backtraceTree.roots().length?-1===this._backtraceDao.currentProcessId?{name:"MessageView",data:r.Resources.getString("SelectFileMessage")}:{name:"MessageView",data:r.Resources.getString("BacktraceNoStacks")}:null}}let w;t.FileWritesViewModel=S,(new R.FileIOMarshaler).getDoubleClickTimeMs().then((e=>{u.Init(e),w=new S})),t.getFileWritesViewModel=function(){return w}}.apply(t,r),void 0===a||(e.exports=a)},558:(e,t,i)=>{var r;r=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.convertBytesToKB=void 0,t.convertBytesToKB=function(e){return e/1024}}.apply(t,[i,t]),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=i},28:e=>{"use strict";e.exports=r},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},o={},function e(t){var i=o[t];if(void 0!==i)return i.exports;var r=o[t]={exports:{}};return s[t](r,r.exports,e),r.exports}(811);var s,o}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // LccD1HwGf5YqktEvnT1pKtuCedNV7kPWjQfBd3knNnyg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCj1IK0QsLN+zGuTNy5BXLQzwwwL4sqYlpg
// SIG // /z2L03eztTBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBALYRjgsl
// SIG // wNWIWp8rPYXcugQw/DSeo4aplrAfH1nVAvLtZf6KkVsv
// SIG // 8UWe9DNcKIUZPZ5yEobTK6+HJP5QeV3ipJjH8i9bIpLi
// SIG // yQJ1STyRbx9M3gzBHhvebs00rZGIAihq8wUlNaK4nibV
// SIG // WqcSHMzErCzwxQRby7BY1yMFwyeymc6SgzpsxSdw5H4X
// SIG // FNk78fSaY21BkuH8PWyp+PuWu3N3juGAAJB1HSLtGxB8
// SIG // fRfCLUJ+hTqVIWkkhpv6DMKvmPS5ERZy4B7Grv2z+AxK
// SIG // oahRGIwyiYPfCsSgte4/pErZEd2NONWvFFwwvsUF5EGS
// SIG // 60lzcBQZveQ+pKdoknfa92g2LCahgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgMw04SktOOx6Z7k8gwPue
// SIG // tgMg4TnMh3Y2thTDpAK3qksCBmUorOGUyhgTMjAyMzEw
// SIG // MjAxNzA0MzYuNjg1WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOkUwMDItMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAHZnFwFkrCDaz4A
// SIG // AQAAAdkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNjAxMTgzMjU4WhcN
// SIG // MjQwMjAxMTgzMjU4WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OkUwMDItMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEA1ekgzda4GNt9Oci3
// SIG // QnVDbxwhBOGdLnA+giry+ZQOxzPNUjJFt+kVO+1GgS/T
// SIG // 0nL4qn1cxNq9qUW0TLQwTMBMdYmos1dhGbDRhrs3kd1z
// SIG // WDm0LyVS2gogZLQGXau+QTRSIpfkn3aV4Cs1UGYgwSQz
// SIG // edFggAza62+PGeGe/yr8s2g+Bm/mmXgoqAdhoNZud3fu
// SIG // qVEwXN1jucR2Yv66yP13Z4YhOv27KY6VOWrnwpSA8dEA
// SIG // 6tUEcNOGnayoXA1shi90mgaf4YzfuCSVOys77ClmVXU7
// SIG // lz6I52k8FnB3RBn88Ymhd9M3fEmOGEVHDBjzkDkR9SD8
// SIG // JMMJakJHNBwZCQkM4ml2PyKYDEcP1z+FL/iQSfEWRimT
// SIG // dc0T1k/XebxxlEpl95u+0SqAn5IEiYnyIkIuhXNDmCku
// SIG // oGTgO53eLfpYgK6/Z4qngv1HDTrla3FQuAm5MHydnh5G
// SIG // lodfLFLd1A/EB2C0MJ/eT/h5vD2SYoK9UkS3LJvKTj3n
// SIG // uzwW53SP1XiibJkHY3pNmhTvVRp1LcwwwaMJYV7IbMGT
// SIG // DJCyf+I1M0JlAX5viQB9edehPhtNsEuzYMzMJqR1gpgG
// SIG // hXXew8iSKhmum3Ga0e0AC3ZMCIVUA4M2QLjcasL4eCGu
// SIG // GSOVaMo+G+81gIZrq6cKTKYo8/onnlsH+mXZsrEY0f8m
// SIG // elF5hmsCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBQcOsEp
// SIG // U2eoBV5dOcP7NxmtX+dcJzAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // KjbVWCzutUzLiGpwu3JbdIvl0UWx8J8DaNOUN7OKaRbX
// SIG // eJwpgf0yTwyerrxK8sbNL8OWPo0MFIip4ZdlRhsCKtKV
// SIG // gyLmluKaTFdaWEHyenbQRpEYkz9XilbwEWGTEWiE3vWY
// SIG // cCSZ2D/N6TMRwsWhLGQuIpWN/+eXaneGV0ws/3KRuWp5
// SIG // g2q7Z1poMrMoDbLU8G1iSUY/OYGEZI8Yv58SgIhBcZeh
// SIG // n5HJ11cvA0RUI9XdwIqrHj6HiM8btYrgCUcA633uDZyh
// SIG // 6qE4FrL+3gliZ1o1lkbe0URq6b8y0KPwcVG/IuPVMEYP
// SIG // RuW8aXeUrtW9tuBr+htR0VPqiRwdc6HuNQ9q/4nNgT6L
// SIG // rFfZ3mCuaiOTxy7IQJ+mE0JZW1faQmzlL2TtHbXcKeRx
// SIG // 9n8OqHyTcCnDxJWqpBHMb64YUVqsDYGhFU8iFeIzHPIz
// SIG // 28djYfcwM7Z2/TX5wxThPv4BfHGak2v0+uUxjT97jIj9
// SIG // 4K/JyF0NiEcDFVKC5hrtqn5oQ6HsLN3XL5OrNWgOplx8
// SIG // PjADRCAyio8N4thuibWZBHprtTl7bJIP7Rp38sGjIKuQ
// SIG // mrlPW+np07QPlBPhip5okFumFBz4QSNC9kBu+k0Qa3uT
// SIG // 6TVR4snP9NW41BDKXmgfiJwB+Jw8WF8dfMGyRPnvyGzL
// SIG // 9NeOxBS+/dnRCxdF8KqnFNEwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjpFMDAyLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUA4hxFugmt5+QY
// SIG // GVf7UP3wkdPU3/eggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjd
// SIG // DkcwIhgPMjAyMzEwMjAxNDMzNDNaGA8yMDIzMTAyMTE0
// SIG // MzM0M1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA6N0O
// SIG // RwIBADAHAgEAAgIXWjAHAgEAAgITnzAKAgUA6N5fxwIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQAlyKoFZDQebzs6XVy5bvmGQAD02K8p
// SIG // sIX5/clUV6vjOnuSgJqGbNK2T9KqkhwZGAqYmOOxHMvV
// SIG // mo9Dx5tno2pYr2BwHc6kgSiR0WFW/GQBLhSfelmlHJvu
// SIG // NFgfmw+pslG7NepOseQtoMTbOqlIjbsHi3cQnMj1TIOE
// SIG // Ow6q7FBmGfwwYZ+HaYtkfX8NpewZX4/HAadzuTPQOfWo
// SIG // 1uJeY3RWO+X8l1GZ5GXoc4wvyR8E75dGD9py1ohry1wQ
// SIG // OJdF/buqqGo18Ki68dK7x5UifETATw+9vxkpebdrngE6
// SIG // hCuRmDKVFkKHF1NEVuvU2aXxUbSPzInzPRjSUWdNmyjU
// SIG // BTkuMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAHZnFwFkrCDaz4AAQAAAdkw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgMJ53
// SIG // TQ7/rJfTAFnVhrvZxcYoXp9ueujKRSw8jB5kx3AwgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCCfoBWyLTpv
// SIG // 1DAwJxE82yXtLtA1ndjIKYG9EnG0IAd58zCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
// SIG // 2ZxcBZKwg2s+AAEAAAHZMCIEIPUOVde2gAWjKyuqhiqZ
// SIG // lCJPYyMfrswf0/G6vlVRSyHRMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAI5afqfIAPJ3v0Hz+0hNDDpMskD4RWWSmRn8sRoO
// SIG // VQ7mv5+3HzmC0bIRanEvTjtNo/i+fV9XA9vGTSQDSbYE
// SIG // xi8xYJbie6chlRU3HC+EY1OUxRIU5mLgMwI6eNBU6RxU
// SIG // HTyzcjK0MLaDZQF6xNz+NO7FM2o14NdMdvtmIswqGn6q
// SIG // W3ZYbmARlVk63OXEuPB2LzPkkfdF0ofsPyl9x8HrXSjD
// SIG // OjdgZoWPXIrpYhTN4Nmviv4IWzA+YH4JWHuFhA4iFwVa
// SIG // DGtY11XLbfIlSKSQRqy/6T/r1HQWS2wF0Olu1wMUOMhC
// SIG // 2dK719VcyoflkQMvG4/55QizOKC6miNnN7PCTNSU+PYL
// SIG // DQT3DxdLAs+ac+bOF+6hqL/a8an5AHvUH7tb8ka51mby
// SIG // ErHSQ5RkOPWEgAcoKE25q+MEcqgt50tdwzLUr3B1cu3w
// SIG // rFaP2meht+1ahXtY3t6tcvIsK0hdvRvdfEPkJGcrQBAB
// SIG // 5zPVjZKxaGA6L5h8VQYHui9sdx8Al1z+/2Pa40+Bi9fr
// SIG // r7ofTZ3psgMNqIGcGPIL5ERggpx1RHoR/DPV/89n50yo
// SIG // IFkqPW74kOURyI8UISyDTH3jxmAfqlAr3Z0Q6gxFNd2K
// SIG // VEf5MQyWovoKKmBm4zEAOMpKtKrcoDtXoTj5CHUvN4oC
// SIG // N7WdJSKjbtyenbdCRpOV/M4EwfN/
// SIG // End signature block
