define("blockedTimeDetailsViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,a,o,r)=>{return i={2608:e=>{const t=document.createElement("script");t.id="BlockedEventRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyBibG9ja2VkRXZlbnRSb3ciIHRhYmluZGV4PSItMSIgcm9sZT0icm93IiBkYXRhLWJpbmQ9InRyZWVHcmlkUm93Rm9jdXM6ICRwYXJlbnQuZm9jdXNlZFJvdygpID09PSAkZGF0YSwgY3NzOiB7IHNlbGVjdGVkOiBzZWxlY3RlZCgpIH0iPg0KICAgIDx0ZCBjbGFzcz0ibmFtZSIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBjbGFzcz0iaW5kZW50Ij4mbmJzcDs8L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgY2xhc3M9ImR1cmF0aW9uIiByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBkdXJhdGlvbkluTXMiIGRhdGEtY29sdW1uaWQ9ImR1cmF0aW9uIj48L3RkPg0KICAgIDx0ZCBjbGFzcz0ibWF4IiByb2xlPSJncmlkY2VsbCIgZGF0YS1jb2x1bW5pZD0ibWF4Ij48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},7348:e=>{const t=document.createElement("script");t.id="BlockedThreadRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGRhdGEtYmluZD0idHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLCBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIGNsYXNzPSJuYW1lIGNvbnRhaW5lciIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0iY3NzOiB7IHNob3dUcmFja0FkZDogIXRyYWNrQWRkZWQoKSB9IiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBoYXNFdmVudHMgPyAndmlzaWJsZScgOiAnaGlkZGVuJyB9Ij48L2Rpdj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgICAgIDxkaXYgY2xhc3M9ImJsb2NrZWRUaHJlYWQtYWRkVHJhY2siIGRhdGEtYmluZD0iY2xpY2s6IGFkZFRyYWNrLCB2aXNpYmxlOiAhdHJhY2tBZGRlZCgpIj48L2Rpdj4NCiAgICA8L3RkPg0KICAgIDx0ZCBjbGFzcz0iZHVyYXRpb24iIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGR1cmF0aW9uSW5NcyIgZGF0YS1jb2x1bW5pZD0iZHVyYXRpb24iPjwvdGQ+DQogICAgPHRkIGNsYXNzPSJtYXgiIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IG1heEluTXMiIGRhdGEtY29sdW1uaWQ9Im1heCI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},4816:function(e,t,a){var o,r,i=this&&this.__createBinding||(Object.create?function(e,t,a,o){void 0===o&&(o=a),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[a]}})}:function(e,t,a,o){void 0===o&&(o=a),e[o]=t[a]}),n=this&&this.__exportStar||function(e,t){for(var a in e)"default"===a||Object.prototype.hasOwnProperty.call(t,a)||i(t,e,a)};o=[a,t,a(3028),a(5639),a(4828),a(952),a(8117),a(8117)],r=function(e,t,a,o,r,i,d,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getBlockedTimeDetailsViewModel=t.BlockedTimeDetailsViewModel=void 0,n(o,t);class l{constructor(){d.loadDataWarehouse().then((e=>{this._blockedTimeViewModel=new r.BlockedTimeViewModel(e),s.getViewEventManager().detailsViewReady.raiseEvent({Id:i.blockedTimeDetailsViewId()}),a.applyBindings(this)}))}get mainViewModel(){return this._blockedTimeViewModel}}let c;t.BlockedTimeDetailsViewModel=l,t.getBlockedTimeDetailsViewModel=function(){return c||(c=new l),c}}.apply(t,o),void 0===r||(e.exports=r)},4037:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(8117),a(8117),a(2608)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedEventRowViewModel=void 0,t.BlockedEventRowViewModel=class{constructor(e,t){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._dto=e,this._children=a.observableArray([]),this._parent=t}get parent(){return this._parent}get templateName(){return"BlockedEventRowView"}get id(){return this._dto.id}get depth(){return 1}get durationInMs(){return this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){r.getViewEventManager().selectionChanged.raiseEvent({position:new o.JsonTimespan(new o.BigNumber(this._dto.start.h,this._dto.start.l),new o.BigNumber(this._dto.end.h,this._dto.end.l)),isIntermittent:!1})}}}.apply(t,o),void 0===r||(e.exports=r)},7490:(e,t,a)=>{var o,r;o=[a,t,a(3432),a(3467),a(4881)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedStackFrame=void 0,t.BlockedStackFrame=class{constructor(e){this._dto=e}get name(){return this._dto.name}get label(){if(void 0===this._dto.jmcState)return"";switch(this._dto.jmcState){case r.JmcState.SystemCode:return a.Resources.getString("SystemCallLabel");case r.JmcState.LibraryCode:return a.Resources.getString("ExternalCallLabel");case r.JmcState.UserCode:default:return""}}get canGoToSource(){return this._dto.fileName&&"number"==typeof this._dto.lineNumber}goToSource(){return this.canGoToSource?(new o.BlockedTimeMarshaler).goToSource(this._dto.fileName,this._dto.lineNumber):Promise.resolve(!1)}}}.apply(t,o),void 0===r||(e.exports=r)},1336:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(3467),a(4037),a(7348)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedThreadRowViewModel=void 0,t.BlockedThreadRowViewModel=class{constructor(e){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._trackAdded=a.observable(!1),this._children=a.observableArray([]),this._haveLoaded=!1,this._marshaler=new o.BlockedTimeMarshaler,this._dto=e,this._marshaler.onTracksAdded.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!0)})),this._marshaler.onTracksRemoved.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!1)}))}get templateName(){return"BlockedThreadRowView"}get id(){return this._dto.threadId}get depth(){return 0}get name(){return this._dto.threadId.toString()}get durationInMs(){return this._dto.durationInMs}get maxInMs(){return this._dto.maxInMs}get trackAdded(){return this._trackAdded}get hasEvents(){return 0!==this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){}expand(e,t,a){let o=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,o=e.getResult({op:"threadDetails",threadId:this._dto.threadId},a).then((e=>{const t=e.map((e=>new r.BlockedEventRowViewModel(e,this)));this._children(t)}))),this._expanded(!this._expanded()),o}addTrack(e,t){return this.trackAdded()||this._marshaler.addTrack(this._dto.threadId),!1}}}.apply(t,o),void 0===r||(e.exports=r)},5732:(e,t,a)=>{var o,r;o=[a,t,a(7490),a(952),a(1336)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeDAO=void 0,t.BlockedTimeDAO=class{constructor(e){this._dataWarehouse=e}getRoots(e,t,a){return this._dataWarehouse.getFilteredData({customDomain:{Task:"Summary"}},o.blockedTimeAnalyzer(),a).then((e=>(null==a||a.throwIfCancellationRequested(),this._currentResult=e,this._currentResult.getResult({op:"threadSummary"},a)))).then((e=>e.map((e=>new r.BlockedThreadRowViewModel(e)))))}sort(e,t,a){return Promise.resolve(e)}search(e,t,a,o,r,i,n){return Promise.resolve(null)}expand(e,t,a){return e.expand(this._currentResult,t,a)}queryStacks(e,t){return this._currentResult.getResult({op:"queryStacks",threadId:e.parent.id,eventId:e.id},t).then((e=>({blockedStack:e.blockedStack.map((e=>new a.BlockedStackFrame(e))),readyStack:e.readyStack.map((e=>new a.BlockedStackFrame(e)))})))}}}.apply(t,o),void 0===r||(e.exports=r)},3467:(e,t,a)=>{var o,r;o=[a,t,a(3432),a(8117)],r=function(e,t,a,o){"use strict";let r;Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeMarshaler=void 0,t.BlockedTimeMarshaler=class{constructor(){null===r&&(r=a.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.CpuSampling.BlockedTime.BlockedTimeMarshaler",{},!0)),this._onTracksAdded=new o.ObservableEvent(r,"onTracksAdded"),this._onTracksRemoved=new o.ObservableEvent(r,"onTracksRemoved")}get onTracksAdded(){return this._onTracksAdded}get onTracksRemoved(){return this._onTracksRemoved}addTrack(e){r._post("addTrack",e)}removeTrack(e){return r._call("removeTrack",e)}goToSource(e,t){return r._call("goToSource",e,t)}}}.apply(t,o),void 0===r||(e.exports=r)},7014:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeSummaryColumnSettingsProvider=void 0,t.BlockedTimeSummaryColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"0",isHidden:!1,width:75},{columnId:"1",isHidden:!1,width:200},{columnId:"2",isHidden:!1,width:200}])}onColumnChanged(e){}}}.apply(t,[a,t]),void 0===o||(e.exports=o)},4828:(e,t,a)=>{var o,r;o=[a,t,a(3432),a(3028),a(4881),a(4881),a(4881),a(5732),a(7014),a(8117),a(952),a(8117)],r=function(e,t,a,o,r,i,n,d,s,l,c,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeViewModel=void 0,t.BlockedTimeViewModel=class{constructor(e){this._blockedStack=o.observableArray([]),this._readyStack=o.observableArray([]),this._dataLoadStatus=o.observable(r.DataLoadEvent.DataLoadCompleted),this._dataLoadPromise=null,this._dao=new d.BlockedTimeDAO(e);const t=new n.TreeGridHeaderViewModel([{id:"name",text:a.Resources.getString("BlockedTimeSummary_NameHeader"),hideable:!1},{id:"duration",text:a.Resources.getString("BlockedTimeSummary_DurationHeader"),hideable:!1},{id:"max",text:a.Resources.getString("BlockedTimeSummary_MaxHeader"),hideable:!1}],new s.BlockedTimeSummaryColumnSettingsProvider,"name");this._summaryViewModel=new i.TreeGridViewModel(this._dao,t,"BlockedTimeSummary_AriaLabel"),this._summaryViewModel.focusedRow.subscribe(this.onSelectionChanged.bind(this)),l.getViewEventManager().jmcEnabledStateChanged.addEventListener((()=>{this._summaryViewModel.onResultChanged(0)})),this._summaryViewModel.onResultChanged(0)}get summaryViewModel(){return this._summaryViewModel}get dataLoadStatus(){return this._dataLoadStatus}get blockedStack(){return this._blockedStack}get readyStack(){return this._readyStack}onSelectionChanged(e){if(null===e||!e.parent)return this._blockedStack([]),void this._readyStack([]);this._dataLoadCancellationTokenSource&&this._dataLoadCancellationTokenSource.cancel(),this._dataLoadCancellationTokenSource=new u.CancellationTokenSource,this._dataLoadCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._dataLoadStatus(r.DataLoadEvent.DataLoadCanceled)}),{once:!0});const t=e;this._dataLoadStatus(r.DataLoadEvent.DataLoadStart),this._dataLoadPromise=this._dao.queryStacks(t,this._dataLoadCancellationTokenSource.token).then((e=>{this._blockedStack(e.blockedStack),this._readyStack(e.readyStack)})).then((()=>{this._dataLoadPromise=null,this._dataLoadStatus(r.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==c.errorNameCanceled()&&this._dataLoadStatus(r.DataLoadEvent.DataLoadFailed)}))}}}.apply(t,o),void 0===r||(e.exports=r)},952:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.flameGraphViewModelMappingKey=t.flatFunctionsViewModelMappingKey=t.modulesViewModelMappingKey=t.callTreeViewModelMappingKey=t.callerCalleeViewModelMappingKey=t.functionLimit=t.defaultSampleRate=t.errorNameCanceled=t.blockedTimeDetailsViewId=t.performanceDebuggerDetailsViewId=t.collectionDetailsViewId=t.analysisDetailsViewId=t.blockedTimeAnalyzer=t.cpuSamplingAnalyzer=void 0,t.cpuSamplingAnalyzer=function(){return"DCA8B3EF-28C5-4B08-BAFC-B072F8AA9277"},t.blockedTimeAnalyzer=function(){return"3BA86369-05EE-409B-B598-BCCDFA4EFE2F"},t.analysisDetailsViewId=function(){return"7D95F423-6D5E-488C-B3A9-169D6D297D5C"},t.collectionDetailsViewId=function(){return"DDEDFB2B-8979-4CA9-BED3-7A3E4C495F1C"},t.performanceDebuggerDetailsViewId=function(){return"47660699-1BCE-4442-AEA7-A520683BDA66"},t.blockedTimeDetailsViewId=function(){return"CA734335-A674-41E2-BC61-98564E300942"},t.errorNameCanceled=function(){return"Canceled"},t.defaultSampleRate=function(){return 1e3},t.functionLimit=function(){return 5},t.callerCalleeViewModelMappingKey=function(){return"CallerCalleeView"},t.callTreeViewModelMappingKey=function(){return"CallTreeView"},t.modulesViewModelMappingKey=function(){return"ModulesView"},t.flatFunctionsViewModelMappingKey=function(){return"FlatFunctionsView"},t.flameGraphViewModelMappingKey=function(){return"FlameGraphView"}}.apply(t,[a,t]),void 0===o||(e.exports=o)},5639:(e,t,a)=>{var o,r;o=[a,t,a(8558)],r=function(e,t,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.CpuSamplingUI_onAfterDomInsert=a.onAfterDomInsert}.apply(t,o),void 0===r||(e.exports=r)},7886:(e,t,a)=>{var o;o=function(e,t){"use strict";var a,o,r,i,n,d,s;Object.defineProperty(t,"__esModule",{value:!0}),t.SortColumn=t.CpuToolView=t.ResultStage=t.ResultNotStartedReason=t.ResultPreparationStatus=t.ActivityType=t.ResultTaskType=void 0,(s=t.ResultTaskType||(t.ResultTaskType={}))[s.Expand=1]="Expand",s[s.Search=2]="Search",s[s.GetData=3]="GetData",s[s.Sort=4]="Sort",s[s.ExpandHotPath=5]="ExpandHotPath",s[s.TopFunctions=6]="TopFunctions",s[s.GetNodePath=7]="GetNodePath",s[s.TopInsights=8]="TopInsights",s[s.Autocomplete=9]="Autocomplete",s[s.UpdateRoot=10]="UpdateRoot",s[s.InsightHelp=11]="InsightHelp",(d=t.ActivityType||(t.ActivityType={}))[d.Unknown=0]="Unknown",d[d.ThreadRun=1]="ThreadRun",d[d.AsyncTask=2]="AsyncTask",(n=t.ResultPreparationStatus||(t.ResultPreparationStatus={}))[n.NotStarted=0]="NotStarted",n[n.InProgress=1]="InProgress",n[n.Completed=2]="Completed",n[n.Canceled=3]="Canceled",n[n.Failed=4]="Failed",(i=t.ResultNotStartedReason||(t.ResultNotStartedReason={}))[i.Unknown=0]="Unknown",i[i.NoValidTimeSelection=1]="NoValidTimeSelection",i[i.NoValidThreadSelection=2]="NoValidThreadSelection",i[i.ToolIsDisabled=3]="ToolIsDisabled",i[i.TargetRunningUnderDebugger=4]="TargetRunningUnderDebugger",(r=t.ResultStage||(t.ResultStage={}))[r.Unknown=0]="Unknown",r[r.Threads=1]="Threads",r[r.Sampling=2]="Sampling",(o=t.CpuToolView||(t.CpuToolView={}))[o.FlatFunctionsView=1]="FlatFunctionsView",o[o.CallerCalleeView=2]="CallerCalleeView",o[o.CallTreeView=3]="CallTreeView",o[o.ModulesView=4]="ModulesView",o[o.FlameGraphView=5]="FlameGraphView",(a=t.SortColumn||(t.SortColumn={}))[a.Id=1]="Id",a[a.FunctionName=2]="FunctionName",a[a.TotalSamples=3]="TotalSamples",a[a.SelfSamples=4]="SelfSamples",a[a.ModuleName=5]="ModuleName",a[a.CategoryName=6]="CategoryName",a[a.CallCount=7]="CallCount"}.apply(t,[a,t]),void 0===o||(e.exports=o)},8558:(e,t,a)=>{var o,r;o=[a,t,a(3432),a(3028),a(7886),a(4881),a(8117),a(2560)],r=function(e,t,a,o,r,i,n,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.localizeNumber=t.areToolContextsEqual=t.areTimespansEqual=t.areBigNumbersEqual=t.numberComparator=t.getSortFunction=void 0;let s={};a.Culture.addEventListener("culturechanged",(()=>{s={}})),t.getSortFunction=function(e,t){switch(e){case r.SortColumn.Id:return i.SortFunctions.numericSort("id",t);case r.SortColumn.FunctionName:return i.SortFunctions.stringSort("name",t);case r.SortColumn.SelfSamples:return i.SortFunctions.numericSort("selfSamples",t);case r.SortColumn.TotalSamples:return i.SortFunctions.numericSort("totalSamples",t);case r.SortColumn.ModuleName:return i.SortFunctions.stringSort("moduleName",t);case r.SortColumn.CategoryName:return i.SortFunctions.stringSort("categoryName",t);case r.SortColumn.CallCount:return i.SortFunctions.numericSort("callCount",t);default:throw n.Assert.fail(`Unknown sort column: ${r.SortColumn[e]}`),new Error(`Unknown sort column: ${r.SortColumn[e]}`)}},t.numberComparator=function(e,t){return e-t},t.areBigNumbersEqual=function(e,t){return!e&&!t||e&&t&&e.h===t.h&&e.l===t.l},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)},t.areToolContextsEqual=function(e,t){return!e&&!t||e&&t&&e.rowId===t.rowId&&e.rowType===t.rowType},t.localizeNumber=function(e,t){const o=JSON.stringify(t||{});let r=s[o];if(!r){const e=new Intl.NumberFormat(a.Culture.formatRegion,t);r=t=>e.format(t),s[o]=r}return r(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const a=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(a)}let a=45;const r=e.children;for(let e=0;e<r.length;e++)a+=r.item(e).offsetWidth;const i=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},n=window.matchMedia(d.Utilities.formatString("(max-width: {0}px)",a.toString()));i(n),n.addListener(i),o.utils.domData.set(e,"mediaQuery",n),o.utils.domData.set(e,"mediaQueryListener",i)}}.apply(t,o),void 0===r||(e.exports=r)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=a},3028:e=>{"use strict";e.exports=o},3432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},n={},function e(t){var a=n[t];if(void 0!==a)return a.exports;var o=n[t]={exports:{}};return i[t].call(o.exports,o,o.exports,e),o.exports}(4816);var i,n}));
// SIG // Begin signature block
// SIG // MIIoKwYJKoZIhvcNAQcCoIIoHDCCKBgCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // 301tA/pRrLjoB3EOmgAbIdHonmDX63qBa3x9EJbYCa2g
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAAA061PHrBhG/rKwAA
// SIG // AAADTjANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOVoX
// SIG // DTI0MDMxNDE4NDMyOVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 3QiojSOiARVrryVJn+lnTiamZiMGLORuwCQ+VG3C+rbA
// SIG // vhATw269+qRRqNW7FKed50chWJ53KDIPBStHfIy5cNJY
// SIG // HsQw6+4InH9szgRVqn7/50i8MyRTT+VtNwxf9daGddq0
// SIG // hahpZvjuOnEY0wxQaTEQmWRnXWZUQY4r28tHiNVYEw9U
// SIG // 7wHXwWEHvNn4ZlkJGEf5VpgCvr1v9fmzu4x2sV0zQsSy
// SIG // AVtOxfDwY1HMBcccn23tphweIdS+FNDn2vh1/2kREO0q
// SIG // mGc+fbFzNskjn72MiI56kjvNDRgWs+Q78yBvPCdPgTYT
// SIG // rto5eg33Ko2ELNR/zzEkCCuhO5Vw10qV8wIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFJzHO2Z/7pCgbAYlpMHTX7De
// SIG // aXcAMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDA1MTYwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQA9tb/a
// SIG // R6C3QUjZRQI5pJseF8TmQD7FccV2w8kL9fpBg3vV6YAZ
// SIG // 09ZV58eyQ6RTCgcAMiMHSJ5r4SvaRgWt9U8ni96e0drN
// SIG // C/EgATz0SRwBJODR6QV8R45uEyo3swG0qqm4LMtdGOyg
// SIG // KcvvVKymtpBprLgErJPeT1Zub3puzpk7ONr5tASVFPiT
// SIG // 0C4PGP7HY907Uny2GGQGicEwCIIu3Yc5+YWrS6Ow4c/u
// SIG // E/jKxXfui1GtlN86/e0MMw7YcfkT/f0WZ7q+Ip80kLBu
// SIG // QwlSDKQNZdjVhANygHGtLSNpeoUDWLGii9ZHn3Xxwqz8
// SIG // RK8vKJyY8hhr/WCqC7+gDjuzoSRJm0Jc/8ZLGBtjfyUj
// SIG // ifkKmKRkxLmBWFVmop+x3uo4G+NSW6Thig3RP2/ldqv4
// SIG // F1IBXtoHcE6Qg7L4fEjEaKtfwTV3K+4kwFN/FYK/N4lb
// SIG // T2JhYWTlTNFC6f5Ck1aIqyKT9igsU+DnpDnLbfIK2J4S
// SIG // dekDI5jL+aOd4YzRVzsYoJEFmM1DvusOdINBQHhWvObo
// SIG // AggepVxJNtRRQdRXSB6Y0kH/iz/1tjlfx34Qt7kz4Cm0
// SIG // bV6PN02WBLnaKMmfwFbtPLIm2dzJBjiTkSxETcCpthu6
// SIG // KnTr+EI/GdCaxoDM4+OjRSgMZC0qROaB0GD9R7T8dZT3
// SIG // w+4jUmybD+i4lB1x9TCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoNMIIaCQIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAD
// SIG // TrU8esGEb+srAAAAAANOMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCmj3EpY0ZqK5iN+1lrQQa2s6yQdA+Cb4Gi
// SIG // zBIWHAUkGDBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAEx4wRsI
// SIG // jEJUR1OXxQVU0jIOb5X3TkNpmEpxk+TpmGiER6OXdvh+
// SIG // 0Dy9lUEosW3rfGC9buaO4ursxNjM7W7wHLEaE9ITjAQe
// SIG // x/RKnPj2LHV53zX7lpk2EEUvxIn0wZroSjrgZ3ew8KJD
// SIG // rOqniXaJ9BCm/N+QJAXnGMQ+viXe39X3ACBapY63kDCn
// SIG // DmI71g8oFevv9KAYrcY2EilPYnmzHLsBJEZ6BEEI6XKy
// SIG // PoLpq4/jjNO+esYIrqmOgNkW1oo5enJYIII7/EPqmeL6
// SIG // MxoMZLAdNQ9xi8PLRdkxWA52XplJigdAleJES9E1qUSh
// SIG // dOJZdzWxKpNMAn0sVP2O876nP2yhgheXMIIXkwYKKwYB
// SIG // BAGCNwMDATGCF4Mwghd/BgkqhkiG9w0BBwKgghdwMIIX
// SIG // bAIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgrDR04BvzdJR/sGdSQ4h4
// SIG // xndmnA5Q2zBTJ+UtVmxCsZICBmUoZBI8VhgTMjAyMzEw
// SIG // MjAxNzA0MzUuMjA4WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOkE5MzUtMDNFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR7TCCByAwggUIoAMCAQICEzMAAAHRsltAKGwu0kUA
// SIG // AQAAAdEwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMwNTI1MTkxMjE4WhcN
// SIG // MjQwMjAxMTkxMjE4WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OkE5MzUtMDNFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAmUzaNDnhs9lxXdoC
// SIG // 4OZ05QZvFzqbsCSIl7DFOta8KtWSg6WuON0a0hv6R/Bs
// SIG // +lzZxUChpwqjQrZr6ClCwKcK0/7O/3tV9JTRSpo+1O1+
// SIG // KdNEtLkG1ui8Ep/81h2htnOeGV7BmPgWH4Vg4GxaQk8U
// SIG // c050Qhutm5Fj6emR22T4OB7dQkQgDIYThk0fMCOBu8MF
// SIG // mcHTHOlL1FJatKpfQMQH85GEaYtrUbwxzHZmd78l6aoR
// SIG // cL0RvHIAh/00wo1uaumjW3aii9wRQz81LbgjbD1y9/xN
// SIG // HUdmwzKmtGjR/oiH4RguP73MLrXjjAj1CA1UqgwjXyGj
// SIG // wxMGHItX3fYLtc1cPhxIQ2TOxGt58SFK87fkX6eU6DDI
// SIG // +EAJielGnZvkz2w26PJBSCu9EoZlvMJ/HyZPUXkEBKU7
// SIG // SDeN3kb/UJl8t1HnfNKLDgRPlpHTL0ghYfqoArCnc0MU
// SIG // CRutnE3qFNnqjYR96KaV5sn1VMG7Hn0MzD7W4pwmXdBV
// SIG // JZpTP3R/uDp4qkMmh767WMt8KiGn2N83hSE5VQKD/avb
// SIG // xeFuyh0f7hdJr06QC+TWkwzdaZUEtDHYzJIM2SuYLcKj
// SIG // nv9605agc8cGu2GKd7qz+clpE8yEhp4TViGTsTskCDsW
// SIG // X24iGwB25tzPIY+9ykFnAkeSWr4JMFJp3BRxEmkH+A66
// SIG // rPv9S9UCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBQLjvFM
// SIG // xew3B9JprBeF0McR0L0tozAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // m7va0wB1duJmNKqBuXhJyJs+WpBl074gcCqdmOdbNusP
// SIG // KA61qK/ptNEeP9wXA5mJVCvDa8f2rmBWInWXXXFI8ONk
// SIG // MUkrZr/6lpwkIv9jpx99ilR0PpDDmTwAUExtV5HJ2D1D
// SIG // jhBKK+n/9ybNbo+MIx8xOFeGrpmFwQLK+C+SkfLynrOb
// SIG // RcYTJFjQ/zu1v0Wh2MCTIzJMVaLAaJO1dtbCQJcUnBF8
// SIG // XyWvv6pKlK+wmYMN0eIwh0ZD6kITFom1zzGGq/4hdGbi
// SIG // wfTvPQzCTYYyvQUn+oqoGaDLsyFbfhAaE86b//aeMEOs
// SIG // aAQrNvZpI/xCFhXXPuWt9JLgkDkhDo9O/liNvQOJOkCE
// SIG // QecPnjJmdCXnNLEsnkAeSo8ROdYmDIbZTK1CnK9Opwag
// SIG // rEij2LEgCEwM4LLCQ/mf3E0uwrt+Xya1oTPTWF9uLgMW
// SIG // CwFtIqTbVqbSHlempLmRHhFegTbTN1U5PpgJVef3gv9G
// SIG // Ne2lUoyuf4Mg6CzZq4FcL+UwGgZqv8IEURR5lvVCd87/
// SIG // C5pOpiKAMk6agW7lIzC8q7Wo7krAP5tg5yjDtEIs9b/h
// SIG // UlW6jN/Cfz05YQk1GxTsdJC0+2P+/mcq4pVQs8gGHxSI
// SIG // pwyI1pTPObQ3lPGXyQoxSsKtw7EcVeCWNfMcMPE05qHd
// SIG // 5ZK/TahkOeC5sj1XPuYmza4wggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDUDCCAjgCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjpBOTM1LTAzRTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUARyWNhb/hoS0L
// SIG // UQ0dryMwWkr/+yyggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOjc
// SIG // xUcwIhgPMjAyMzEwMjAwOTIyMTVaGA8yMDIzMTAyMTA5
// SIG // MjIxNVowdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA6NzF
// SIG // RwIBADAKAgEAAgIRoAIB/zAHAgEAAgISVTAKAgUA6N4W
// SIG // xwIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZ
// SIG // CgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqG
// SIG // SIb3DQEBCwUAA4IBAQCMRP/HmBIYtwyHPkkamgvadKth
// SIG // Qs6JT1+xjm0PnTAbeP4CV4COcHq4EQpZSFDYKpl1+SVI
// SIG // 7Wq9D3ebCVbsm8MRPviO2ocQpGlt7m0U70JpXe0zSBiX
// SIG // 8m9h6OEM43Ysprs+8EvW3a2RjPzrKnhwzVBtWbwOYXna
// SIG // VhbleqvrD+Y5RbII3GEQrWeHgjDrYEQJDragBwt+sQZl
// SIG // i5IstXXLv+7Ck6j0hoRmx1sZ++HyqiDDAF2bozfDI4AP
// SIG // gEdsawtGn3GOl0nmEoTt150g3Qcq4abp/0b1gQtUXH/S
// SIG // Fmte6bE7FG1jUT5BxrLbR0YXTWdi0plMIE36pCpQ8zrk
// SIG // lAJc6tSUMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTACEzMAAAHRsltAKGwu0kUAAQAA
// SIG // AdEwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJ
// SIG // AzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQg
// SIG // +CJ97db9JKK7Mwbo2152ZLhC61E2oJVGCPDJldHSRBAw
// SIG // gfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCDMvGF5
// SIG // AgC7+e3ObEYaz07m9auE8CeqFQN+pPCIiPwHDDCBmDCB
// SIG // gKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
// SIG // HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMz
// SIG // AAAB0bJbQChsLtJFAAEAAAHRMCIEIDRkOe9a0I3hgok6
// SIG // UxZg4HzyxyPaM22BILltWwLLuyMnMA0GCSqGSIb3DQEB
// SIG // CwUABIICADypa+3uAp6JvQHhGsuSMZHpLsRvcgI5yfYU
// SIG // HSYBCsz85l9sGFIAR4nlaBrgklpp442QXHJVuCa9WjID
// SIG // nUtOIc1SGapn6UTe9noiTGilH6JZHt3BpV2UgwdbgaWN
// SIG // i+pJKOgSNteESKFcLsU+PXwUdpZIv/zfL94Px1u+DAgd
// SIG // JRBFv4/VcqolOH8OUBquiuetT6sNezEbKbGotVh4NZvV
// SIG // Qa14Hr3TYpZw4XopObA8M81hPJteyNlFBMVTdabZNnxE
// SIG // 2rMmpZC4zQbNUm9XZVotMCY9z0v5dD8L8x9wjWaVIcu4
// SIG // HBqUt41n+IYxhfKyrovZxKoAHULs8PUSKrX+RuGae3K2
// SIG // wt1HNiDXR5NaAH8umGuLlT4bff4ZpihhYnGTNXSUo5mW
// SIG // tQDnPMRLjrx4TjG0iUNDJWIXgMy1vTj1AdW5D+ZFGKst
// SIG // hDMXdJdBsQBJuR5DlqLXYbnYo1xTQ+D5YWKZchHEGSBF
// SIG // hljs4avIsa0gVDKvD20+6pNulx1DtyQAg11yBxKW3FHC
// SIG // baDXG9qaF+l7mQyeCu4MoDDfngsmW4ZsvE8R1OrpKxYd
// SIG // SU1DjtSbpK3WPxcavaihQ4C2PC783N9xrb3MyAkE46+o
// SIG // GEZqxj5TzB1QeMqiSB2NwlSlkBocp+I4iBpTLvYPAX+1
// SIG // wrFdFQ6IEFN9u+xKqUTXP+rpX/Ej5itK
// SIG // End signature block
