define("anyStacksViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,s,i,o)=>{return a={469:e=>{const t=document.createElement("script");t.id="AnyStacksRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogbGFiZWwiPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkVG90YWwiIGRhdGEtY29sdW1uaWQ9InRvdGFsIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRTZWxmIiBkYXRhLWNvbHVtbmlkPSJzZWxmIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1jb2x1bW5pZD0ibW9kdWxlTmFtZSIgZGF0YS1iaW5kPSJ0ZXh0OiBtb2R1bGVOYW1lIj48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},287:e=>{const t=document.createElement("script");t.id="OpenSymbolSettingsButtonView",t.innerHTML=atob("PGRpdiBpZD0ib3BlblN5bWJvbFNldHRpbmdzQnV0dG9uIiBjbGFzcz0iY29udGFpbmVyIj4NCiAgICA8YnV0dG9uIGNsYXNzPSJoeXBlcmxpbmstYnV0dG9uIHRvb2xiYXItYnV0dG9uIiByb2xlPSJsaW5rIiBkYXRhLWJpbmQ9Ig0KICAgICAgICBsb2NhbGl6ZWRUZXh0OiAnQnV0dG9uX09wZW5TeW1ib2xTZXR0aW5ncycsDQogICAgICAgIGVuYWJsZTogZW5hYmxlZCwNCiAgICAgICAgY2xpY2s6IG9uQ2xpY2ssDQogICAgICAgIG9uRW50ZXI6IG9uQ2xpY2ssDQogICAgICAgIGNzczogeyAndG9vbGJhci1idXR0b24tZGlzYWJsZWQnOiAhZW5hYmxlZCgpIH0iPg0KICAgIDwvYnV0dG9uPg0KPC9kaXY+"),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},205:(e,t,s)=>{var i,o;i=[s,t,s(432)],void 0===(o=function(e,s,i){"use strict";Object.defineProperty(s,"__esModule",{value:!0}),t.getSourceFileViewerService=void 0;class o{constructor(){this._proxy=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.VisualStudio.Presentation.JavaScriptModels.SourceFileViewerServiceMarshaler",{},!0)}openSourcePosition(e){return e?this._proxy._call("openSourcePosition",e):Promise.resolve(!1)}}let a=null;t.getSourceFileViewerService=function(){return null===a&&(a=new o),a}}.apply(t,i))||(e.exports=o)},122:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(952),s(560),s(881),s(881),s(881),s(881),s(881),s(117),s(117),s(117),s(117),s(345),s(414),s(766),s(558),s(881),s(478),s(680),s(833),s(103)],o=function(e,t,s,i,o,a,n,r,l,d,c,u,h,g,m,S,b,p,y,v,w){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getAnyStacksViewModel=t.AnyStacksViewModel=void 0;class _{constructor(){this._viewEventManager=u.getViewEventManager(),this._currentStackArgs=null,this._logger=m.getLogger("AnyStacksViewModel"),this._automation=g.getAutomationManager(this._logger),this._currentOverlay=s.pureComputed((()=>this.computeOverlay())),this.initializeAsync()}async initializeAsync(){const e=await h.loadDataWarehouse();this._dataWarehouse=e;const t=await e.getContextService().getGlobalContext(),a=await t.getTimeDomain();this._dao=new S.AnyStacksDAO(this._dataWarehouse,a,C);const n=i.Resources.getString,c=new d.TreeGridHeaderViewModel([{id:"name",text:n("AnyStacksHeaderName"),tooltip:n("AnyStacksHeaderNameToolTip"),hideable:!1,sortable:r.SortDirection.Asc},{id:"total",text:n("AnyStacksHeaderTotal"),tooltip:n("AnyStacksHeaderTotalToolTip"),hideable:!0,sortable:r.SortDirection.Desc},{id:"self",text:n("AnyStacksHeaderSelf"),tooltip:n("AnyStacksHeaderSelfToolTip"),hideable:!0,sortable:r.SortDirection.Desc},{id:"moduleName",text:n("AnyStacksHeaderModuleName"),tooltip:n("AnyStacksHeaderModuleNameToolTip"),hideable:!0,sortable:r.SortDirection.Desc}],new b.AnyStacksColumnSettingsProvider,this._dao.defaultSortColumnId);this._anyStacks=new l.TreeGridViewModel(this._dao,c,"AnyStacksAriaLabel"),this._openSymbolSettingsButtonViewModel=new w.OpenSymbolSettingsButtonViewModel,this._showJmc=new v.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(await e.getJmcService().getJmcEnabledState()),this._showJmc.isChecked.subscribe((()=>{this._dataWarehouse.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new v.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked.subscribe((e=>{C.setNativeCodeEnabled(e)})),this._showNative.isChecked(await C.isNativeCodeEnabled()),C.onUpdateNativeCode.addEventListener((e=>{this._showNative.isChecked(e.isEnabled),this._dao.getNewResult(this.anyStacks,this._currentStackArgs)})),C.onShowAnyStacks.addEventListener(this.showAnyStacks.bind(this)),this._viewEventManager.selectionChanged.addEventListener((e=>{e.isIntermittent||this._dao.timeFilter(e.position)})),this._dao.timeFilter.subscribe((()=>{this._dao.getNewResult(this.anyStacks,this._currentStackArgs)})),this._viewEventManager.jmcEnabledStateChanged.addEventListener((e=>{this._showJmc.isChecked()!==e.currEnabledState&&this._showJmc.isChecked(e.currEnabledState),this._dao.getNewResult(this.anyStacks,this._currentStackArgs)})),s.applyBindings(this),this._currentStackArgs=await C.getLastAnyStacksArgs(),this._dao.getNewResult(this.anyStacks,this._currentStackArgs),this._viewEventManager.detailsViewReady.raiseEvent({Id:o.AnyStacksViewId()})}get anyStacks(){return this._anyStacks}get currentOverlay(){return this._currentOverlay}get openSymbolSettingsButtonViewModel(){return this._openSymbolSettingsButtonViewModel}get showJmc(){return this._showJmc}get showNative(){return this._showNative}showAnyStacks(e,t){this._currentStackArgs=e,this._dao.getNewResult(this.anyStacks,this._currentStackArgs)}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==a.KeyCodes.C)return!0;const s=c.TreeGridUtils.formatTreeGridSelectedToText(this._anyStacks);return navigator.clipboard.writeText(s),!1}contextMenu(e,t){if("number"!=typeof e.id)return null;const s=()=>{"unsearched"===e.sourceFilePosition.sourceFile.path.toLowerCase()?this._dao.getSourceInfo(e.aggregationId).then((t=>{e.sourceFilePosition=t,t?this._dao.showSourceFile(t):this._automation.getAlertPromise(g.AutomationConstants.DataWarehouseRequestKey,i.Resources.getString("NoSource"))})):this._dao.showSourceFile(e.sourceFilePosition)},o=[{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>s(),disabled:()=>!e.sourceFilePosition,type:i.ContextMenu.MenuItemType.command},{type:i.ContextMenu.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_LoadModuleSymbols"),disabled:()=>this.allSelectedRowsHaveSymbols(e),callback:async()=>{await C.loadModuleSymbols(this.getSelectedModulesWithoutSymbols(e))&&this.anyStacks.onResultChanged(0)},type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_LoadAllSymbols"),callback:()=>{this._dao.loadAllSymbols=!0,this.anyStacks.onResultChanged(0)},type:i.ContextMenu.MenuItemType.command},{type:i.ContextMenu.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToText(this._anyStacks);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._anyStacks);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command}];return i.ContextMenu.create(o)}computeOverlay(){return this._dao.dataLoadStatus()===r.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._dao.dataLoadStatus()===r.DataLoadEvent.DataLoadCompleted&&0===this._dao.roots().length?{name:"MessageView",data:i.Resources.getString("NoStackDataMessage")}:null}allSelectedRowsHaveSymbols(e){const t=this._anyStacks.selectedRows(),s=this._anyStacks.treeAsArray();for(let e=0;e<t.length;++e){const i=s[t[e]];if(i&&!i.isModuleSymbolsLoaded)return!1}return!0}getSelectedModulesWithoutSymbols(e){const t={},s=this._anyStacks.selectedRows(),i=this._anyStacks.treeAsArray();for(let e=0;e<s.length;++e){const o=i[s[e]];o&&(o.isModuleSymbolsLoaded||(t[o.moduleName]=!0))}return Object.keys(t)}AnyStacksOnAfterDomInsert(){y.onAfterDomInsert()}}let I;t.AnyStacksViewModel=_;const C=new p.EventsViewerMarshaler;C.getDoubleClickTimeMs().then((e=>{n.Init(e),I=new _})),t.getAnyStacksViewModel=function(){return I}}.apply(t,i),void 0===o||(e.exports=o)},414:(e,t,s)=>{var i,o;i=[s,t,s(766)],o=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.AnyStacksColumnSettingsProvider=void 0,t.AnyStacksColumnSettingsProvider=class{constructor(){this._view="AnyStacks",this._marshaler=new s.EventsViewerMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings(this._view)}onColumnChanged(e){this._onColumnChangedPromise=this._marshaler.onColumnChanged(this._view,e)}}}.apply(t,i),void 0===o||(e.exports=o)},345:(e,t,s)=>{var i,o;i=[s,t,s(28),s(952),s(881),s(881),s(496),s(205),s(117)],o=function(e,t,s,i,o,a,n,r,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.AnyStacksDAO=void 0;class d{constructor(e,t,i){this._roots=s.observableArray([]),this._currentStackArgs=null,this._loadAllSymbols=!1,this._logger=l.getLogger("AnyStacksDAO"),this._dataLoadStatus=s.observable(o.DataLoadEvent.DataLoadStart),this._dataWarehouse=e,this._timeFilter=s.observable(t),this._marshaler=i}set loadAllSymbols(e){this._loadAllSymbols=e}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"total"}get dataLoadStatus(){return this._dataLoadStatus}get roots(){return this._roots}async getRoots(e,t,s){s.onCancellationRequested.addEventListener((()=>{this._dataLoadStatus(o.DataLoadEvent.DataLoadCanceled)}),{once:!0}),this.dataLoadStatus(o.DataLoadEvent.DataLoadStart);const a=await this._marshaler.isNativeCodeEnabled(),r={timeDomain:this.timeFilter(),customDomain:{view:"AnyStacks",rowId:this._currentStackArgs.rowId,matches:this._currentStackArgs.matches,showNative:a,loadAllSymbols:this._loadAllSymbols}},l=await this._dataWarehouse.getFilteredData(r,i.EventsViewerAnalyzerId(),s);if(s.isCancellationRequested)return this.dataLoadStatus(o.DataLoadEvent.DataLoadFailed),[];this._currentResult&&this._currentResult.dispose(),this._currentResult=l;const d=this._currentResult?await this._currentResult.getResult({task:"getRoots"},s):[],c=await this._dataWarehouse.getJmcService().getJmcEnabledState(),u=d.map((e=>new n.AnyStacksRowViewModel(null,e,0,c)));return await this.sort(u,t,s),this._roots(u),this.dataLoadStatus(o.DataLoadEvent.DataLoadCompleted),1===u.length&&await this.expand(u[0],t,s),u}expand(e,t,s){return e.expand(this._currentResult,t,s)}search(e,t,s,i,o,a,n){throw new Error("Method not implemented.")}sort(e,t,s){const i=d.SortFunc[t.columnId](t.direction),o=e=>{e.children&&(e.children.sort(i),e.children().forEach(o))};return e.sort(i),e.forEach(o),Promise.resolve(e)}showSourceFile(e){return r.getSourceFileViewerService().openSourcePosition(e)}getNewResult(e,t){null!==t&&(this._currentStackArgs=t,e.onResultChanged(0))}getSourceInfo(e){return this._currentResult.getResult({task:"getSourceInfo",rowId:e})}}t.AnyStacksDAO=d,d.SortFunc={name:e=>a.SortFunctions.stringSort("name",e),total:e=>a.SortFunctions.numericSort("total",e),self:e=>a.SortFunctions.numericSort("self",e),moduleName:e=>a.SortFunctions.stringSort("moduleName",e)}}.apply(t,i),void 0===o||(e.exports=o)},496:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(881),s(881),s(469)],o=function(e,t,s,i,o,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.AnyStacksRowViewModel=void 0;class n{constructor(e,t,i,o){this._selected=s.observable(!1),this._expanded=s.observable(!1),this._haveLoaded=!1,this._isHotPath=s.observable(!1),this._isHotItem=s.observable(!1),this._isHotRoot=s.observable(!1),this._parent=e,this._dto=t,this._depth=i,this._children=s.observableArray([]),this._jmcEnabled=o,this._label=s.pureComputed((()=>this.computeLabel()))}get templateName(){return"AnyStacksRowView"}get id(){return this._dto.id}get aggregationId(){return this._dto.aid}get rowType(){return this._dto.rt}get isModuleSymbolsLoaded(){return this._dto.sl}get name(){return this._dto.rt===o.RowType.Process?this._dto.n?i.Resources.getString("ProcessNameFormat",this._dto.n,this._dto.pid):i.Resources.getString("ProcessIdFormat",this._dto.pid):this._dto.n}get label(){return this._label}computeLabel(){if(this._dto.rt===o.RowType.Process)return"";if(this._dto.a===o.AggregateType.BrokenStack)return i.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case o.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");case o.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");default:return this.isExpandableEventsRow?i.Resources.getString("EventsRowLabel"):this.expandable?"":i.Resources.getString("EventRowLabel")}if(this._dto.n)switch(this._dto.j){case o.JmcState.SystemCode:return i.Resources.getString("SystemCallLabel");case o.JmcState.LibraryCode:return i.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case o.AggregateType.SystemCode:return i.Resources.getString("SystemCodeLabel");case o.AggregateType.JmcRejected:return i.Resources.getString("ExternalCodeLabel");case o.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");case o.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");default:return this.isExpandableEventsRow?i.Resources.getString("EventsRowLabel"):this.expandable?"":i.Resources.getString("EventRowLabel")}}get total(){return this._dto.t}get localizedTotal(){return this.total?this.total.toLocaleString(i.Culture.formatRegion):""}get self(){return this._dto.s}get localizedSelf(){return this.self.toLocaleString(i.Culture.formatRegion)}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get moduleName(){var e;return null!==(e=this._dto.mn)&&void 0!==e?e:i.Resources.getString("UnknownModuleLabel")}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return void 0===this._dto.c||this._dto.c.length>0}get children(){return this._children}invoke(){}expand(e,t,s){let i=Promise.resolve();return this.expandable?(this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",id:this._dto.id,path:this.getIdPath()},s).then((i=>{null==s||s.throwIfCancellationRequested();let o=i.map((e=>new n(this,e,this.depth+1,this._jmcEnabled)));const a=n.SortFunc[t.columnId](t.direction);return o=o.sort(a),this.children(o),1===o.length?o[0].expand(e,t,s):Promise.resolve()}))),this._expanded(!this._expanded()),i):i}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}get isExpandableEventsRow(){return 5===this._dto.rt&&this.expandable}}t.AnyStacksRowViewModel=n,n.SortFunc={name:e=>a.SortFunctions.stringSort("name",e),total:e=>a.SortFunctions.numericSort("total",e),self:e=>a.SortFunctions.numericSort("self",e),moduleName:e=>a.SortFunctions.stringSort("moduleName",e)}}.apply(t,i),void 0===o||(e.exports=o)},952:(e,t,s)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FilterLimit=t.errorNameCanceled=t.EventCountLimit=t.AnyStacksViewId=t.EventsViewerAnalyzerId=t.EventsListDetailsViewId=void 0,t.EventsListDetailsViewId=function(){return"AC3DC4D0-1FCC-4849-9F63-C8FFB47EC1DC"},t.EventsViewerAnalyzerId=function(){return"D9A8E704-BD31-402F-8990-A33EFB271CF0"},t.AnyStacksViewId=function(){return"FBF21B2D-E165-4C4E-8B10-36F0BC084F20"},t.EventCountLimit=function(){return 2e4},t.errorNameCanceled=function(){return"Canceled"},t.FilterLimit=function(){return 32766}}.apply(t,[s,t]),void 0===i||(e.exports=i)},766:(e,t,s)=>{var i,o;i=[s,t,s(432),s(117)],o=function(e,t,s,i){"use strict";let o;Object.defineProperty(t,"__esModule",{value:!0}),t.EventsViewerMarshaler=void 0,t.EventsViewerMarshaler=class{constructor(){o||(o=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.EventsViewer.EventsViewerMarshaler",{},!0)),this._onShowAnyStacks=new i.ObservableEvent(o,"onShowAnyStacks"),this._updateNativeCodeEvent=new i.ObservableEvent(o,"updateNativeCodeEvent")}openSymbolSettings(){o._post("openSymbolSettings")}loadModuleSymbols(e){return o._call("loadModuleSymbols",e)}get onShowAnyStacks(){return this._onShowAnyStacks}showAnyStacks(e){return o._call("showAnyStacks",e)}isNativeCodeEnabled(){return o._call("isNativeCodeEnabled")}setNativeCodeEnabled(e){return o._call("setNativeCode",{isEnabled:e})}get onUpdateNativeCode(){return this._updateNativeCodeEvent}getDoubleClickTimeMs(){return o._call("getDoubleClickTimeMs")}onColumnChanged(e,t){return o._call("onColumnChanged",e,t)}getColumnSettings(e){return o._call("getColumnSettings",e)}getLastAnyStacksArgs(){return o._call("getLastAnyStacksArgs")}}}.apply(t,i),void 0===o||(e.exports=o)},478:(e,t,s)=>{var i,o;i=[s,t,s(28),s(766),s(287)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.OpenSymbolSettingsButtonViewModel=void 0,t.OpenSymbolSettingsButtonViewModel=class{constructor(){this._marshaler=new i.EventsViewerMarshaler,this._enabled=s.observable(!0)}get enabled(){return this._enabled}onClick(e,t){return!this._enabled()||(this._marshaler.openSymbolSettings(),!1)}}}.apply(t,i),void 0===o||(e.exports=o)},558:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(560)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.LocalizeNumber=void 0;const a={};t.LocalizeNumber=function(e,t){const s=JSON.stringify(t||{});let o=a[s];if(!o){const e=new Intl.NumberFormat(i.Culture.formatRegion,t);o=t=>e.format(t),a[s]=o}return o(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=s.utils.domData.get(e,"mediaQuery");if(t){const i=s.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}let i=45;const a=e.children;for(let e=0;e<a.length;e++)i+=a.item(e).offsetWidth;const n=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},r=window.matchMedia(o.Utilities.formatString("(max-width: {0}px)",i.toString()));n(r),r.addListener(n),s.utils.domData.set(e,"mediaQuery",r),s.utils.domData.set(e,"mediaQueryListener",n)}}.apply(t,i),void 0===o||(e.exports=o)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=s},28:e=>{"use strict";e.exports=i},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},n={},function e(t){var s=n[t];if(void 0!==s)return s.exports;var i=n[t]={exports:{}};return a[t](i,i.exports,e),i.exports}(122);var a,n}));
// SIG // Begin signature block
// SIG // MIIoNwYJKoZIhvcNAQcCoIIoKDCCKCQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // EqAlP7t33foOB11855NWnKx9oySEQE1F3+JPqLIhmCeg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoKMIIaBgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCB62dVpqU1Z5j1R
// SIG // UUNNE6uYmDhh1o77lHVwAGgUODA1AzBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAM4r1336O7nqF231l/Cf5v0O/sOrC/5w
// SIG // b60BeVPeIZKJL7ykeWI9DSdaxmTkeoTWvGUD9EHlQVci
// SIG // RxjCQ6+RWU4+frbMCIwXYAq650hWVtOlSqC7OMvRO6p5
// SIG // KB7R+ccKv4WZOMWa2EJHcp4FW6opt5B3bJf1xsCHSBu8
// SIG // 6JMuj9QUrgOSHH8CQft6HTqOw1wQdyW86PGJ47xOb4q5
// SIG // yJZS9trphV0ab30cyMPmoehHG7fTCbf1F9elEQaUB5I8
// SIG // PeUnoidJ3G42ZQoMiFf9SuWzTJZI0VwkFuUyF2xTvqvH
// SIG // TB6dFoMs4EJ1YZRcv/41V3oUKoDVJi0EfotsyF/WTw5Q
// SIG // TVKhgheUMIIXkAYKKwYBBAGCNwMDATGCF4Awghd8Bgkq
// SIG // hkiG9w0BBwKgghdtMIIXaQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // f0LVd0DLZNcHmQnCMQohGe/+XTkMN6k8LDhFpv4/KkYC
// SIG // BmUos+BdDRgTMjAyMzEwMjAxNzA0MzcuMTIxWjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjMzMDMt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR6jCCByAwggUIoAMCAQIC
// SIG // EzMAAAHMhqXcN+vZYS0AAQAAAcwwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNTI1MTkxMjAxWhcNMjQwMjAxMTkxMjAxWjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOjMzMDMtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEAzLEiBfHvTZhHPvNzVWRoFlmYv8AWLfM4cQH0hjO8
// SIG // cOyuwmwP9QOBoaLz75CGPO97Z8s3cmXvumB18fkXetfJ
// SIG // UA5ppuV+HromBudy3e1iCvg3focotB/ew+hzOGcxqqL5
// SIG // sAdH2d5YfqYSS6D0/vcq0yxc5JCsNlXG+8FzAc4g9DFV
// SIG // WG5sEZUWsqU57Zd/SBDQhIo1vY+jBJU8lz9s63NDrYUD
// SIG // eUazE2OYmY2tzMhwhZmDBop5h37bGht2HYvBmvAUI3ba
// SIG // E5uXVYZ6rNqijRDqmUqJ9vEeF339LZSS+VB8iN28sB//
// SIG // s0HibvKp7EgovFRTzrGRG+nGc4Vx2gIkhrXSgG0EWgCI
// SIG // RMWyFKXicqQu5fsKigtwTvQAxrqQfWYFBW0r+RAhYzA8
// SIG // 235vDOc89gOMWDT0F6mb9MBli/o072+5BWIgzz3vs0cg
// SIG // W85q0qTmwe16o6s1BTSpcKfjMdeZNRexTLORDNrhuvCE
// SIG // LHQBgZGW0g5rhpoz22e3bYpvlx7odzUuiZl2D0u64pKQ
// SIG // m1LDGTJ+XlsYlhSJOn9NLJEeES1podDejqvimCNXwOfS
// SIG // 8xogGzq3MYL0JEaNzg+KNSVvc9UzTMBG5Mz61zKPK6xr
// SIG // LhqMmFnLJvcYXdBlyERxwuuJ82yN3tBuY6hLFkHOLmkH
// SIG // kkcq+9CkYo81clo42H7BLb1TJScCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBSCphxkXTyHS0V7bEeV0UsjN/tpDDAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAeRlDKPV74lJd4O9rvKEE6KyC
// SIG // g6AHYFmeC0PfnQBEApmnrbE4ZMWzZtebHruxpsKWXYTE
// SIG // DfEzXXRpIubOSHvmgNlRKPb2c99ZZbrBwVwFa0Labn0K
// SIG // rSAPtp57rH2mL4ora+qeZFU+tPSyEzmIHSkVhKX8f+Mk
// SIG // +UfcjHisaMZJPLchohj2SuNEk+WdeDj3SX1W5GHgr5S0
// SIG // HJbF9flgWTcf12b2syZl472I07htEG2accOGTt2aH30G
// SIG // MWWEc59M+NVOzAxZV6NooX2rHWx7rmupKR8SfQCKFHr4
// SIG // d5s71MWKdLtM98GAz6S7qPjNlWIfFzglAdLu+cRt0ufv
// SIG // fEyphW6mWIKYK+j/mCnmqNmKQdYs7POdGEs7sGl+5EcQ
// SIG // FEZZjf4+R7+MGm5zn2W9+pg6iaeCHhpsD7cCPLRD7LkQ
// SIG // Jsq3no8oZGVe3X4CeDfN0AYaR1WZQeBZpSUfMhd2gdeU
// SIG // FurcOAmh/jzCA7nehnjiTuHEBPpU3OqyCZjeHH4tk0xu
// SIG // 3uPU74Ql3wUtqczsm/WHpkptJK5PIyYes4Hhqs7ZO83s
// SIG // HxPt7IUEXO+LFy2OfKb1aM534Hxr8tZZW6uDnsveiqLs
// SIG // IroQ7cbipU51u6cO8WjT4SDLDsVvHaUqfdeRbSnzqikf
// SIG // 3XyTrGxw0iWP4oic+JligBqMnXizOsy5qIUQj1pP0OYw
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDTTCC
// SIG // AjUCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjozMzAzLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUATk7md7mH4ooUuM0U6MYrA7fZiaSggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjdFVQwIhgPMjAyMzEwMjAxNTAz
// SIG // NDhaGA8yMDIzMTAyMTE1MDM0OFowdDA6BgorBgEEAYRZ
// SIG // CgQBMSwwKjAKAgUA6N0VVAIBADAHAgEAAgI7IzAHAgEA
// SIG // AgISRTAKAgUA6N5m1AIBADA2BgorBgEEAYRZCgQCMSgw
// SIG // JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIB
// SIG // AAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQAXlUQvj5Cc
// SIG // kFNZHRx8oMSJw42Ek35KNBK89aXMfnDQXoNHsA6zkWh0
// SIG // OwMWgOQ3ldUNImKKL70/8D1Z39LljNLfbKb+VgDDZr0/
// SIG // KBkYrMfMFPbg5a/vObiy20cEqSiGcEElApkXcipsBOCq
// SIG // /cswrzpwWkzpE3gu2+xcGrrK+slkAgYmQZn8U+oFpTC2
// SIG // LFIi1LNAwRdwHo4TmICphZQvkUcL2BTn/ErFMppOPlc/
// SIG // aVpRMRL1gMfuwsIRLIDmMHqjXomc78ZOi9ZoH2/Rkes1
// SIG // QJLmM+tVGWyu0Cfj3g4gzlkE0z1inLcoIA8GZkClOlcx
// SIG // s/5VZncBanFdZmTfpN29P8xyMYIEDTCCBAkCAQEwgZMw
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHM
// SIG // hqXcN+vZYS0AAQAAAcwwDQYJYIZIAWUDBAIBBQCgggFK
// SIG // MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkq
// SIG // hkiG9w0BCQQxIgQgy5oD2yxvuWAzQwGLkFXnmkMe32aE
// SIG // K52xp8OoPFYO9uYwgfoGCyqGSIb3DQEJEAIvMYHqMIHn
// SIG // MIHkMIG9BCDW7mUBwv7DAhPnIClUpMCqQyAn53nxWWIA
// SIG // 2xeB63BY5jCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwAhMzAAABzIal3Dfr2WEtAAEAAAHMMCIE
// SIG // IHx/8LsFSTJz8ulx1RsGFEM/G72MaGZWkWZKpx9rckPv
// SIG // MA0GCSqGSIb3DQEBCwUABIICAHpyhg88aM6rz0E8FirA
// SIG // MRAYdh4Vj2Nx4fHF8swCkHBPp+H5EHgKAC5uD47lS4av
// SIG // GGAQDMFyEQw0HfyMz/gR41GcXN57LGEeX9ZUje37ziRC
// SIG // OGvzlcObErAT2Mq8XSkAsVJv98vxzA8R+I2n9QvJO/Jl
// SIG // jKBIYxcthOiuxY2KbZWJnaEgpkQmJXnkFyjB9+RpJZrD
// SIG // iMQRbwNI7rnvf5fP4ONNlqjs76LMoCM4pjK7KIi29msV
// SIG // lGSfrxxL2IA1pR/gnFAY+ZVntcE6oThIGMgszEADpL8q
// SIG // MJz5xRXJsdNLeocxJ1N8WXLRYoo2mrsV7CmkDndAz4ct
// SIG // ReWWaTvo6ADG3+aavHCWeV7lEDDYTi34yvYDibtdmxv9
// SIG // vClWhuM544jZ13+iEBjwNKx8rzXUPQnjCqnKwatAn72p
// SIG // 8O2BZ4Uu4QOhHtVYa2gFBmVitWo0Rpr+4f5pYgCY84df
// SIG // O+cXH/qJwct67wrGdwqYRdd4vpvJgSi4lyRcMNpcr3Bj
// SIG // zMRFK32wO+ihWHVskng4+MirDhKiaKqeKWVTFpE4aW/e
// SIG // Lvi57U7Ung/mSuRZ3V1B1oMzGxjfA7WMXd2Vt2d/y7JG
// SIG // OTR9vcoutVek6LZZvU++DK65a09Pg7SK2pqtWMjRLIJA
// SIG // 01Lcomc1wptD6Xxdb0JMcWOnhAFirYofLcxtdd6R3gRz
// SIG // WQGb
// SIG // End signature block
