define("eventsViewerUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,s,i,o)=>{return n={149:e=>{const t=document.createElement("script");t.id="PropertyTableRowView",t.innerHTML=atob("PHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IG5hbWUsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdG9vbHRpcDogdG9vbHRpcCI+PC90ZD4NCjx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiB2YWx1ZSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB0b29sdGlwOiB0b29sdGlwIj48L3RkPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},441:e=>{const t=document.createElement("script");t.id="CollapsibleTableView",t.innerHTML=atob("PGRpdiBjbGFzcz0iY29sbGFwc2libGVUYWJsZUNvbnRhaW5lciIgZGF0YS1iaW5kPSJ2aXNpYmxlOiByb3dzKCkubGVuZ3RoID4gMCwNCiAgICAgICAgICAgICAgIGNvbGxhcHNpYmxlVGFibGVGb2N1c2VkUm93OiB7IHJvd3M6IHJvd3MsIHNlbGVjdGVkOiBzZWxlY3RlZFJvd3MsIGZvY3VzZWQ6IGZvY3VzZWRSb3dJbmRleCB9Ij4NCiAgICA8ZGl2IGNsYXNzPSJzZWN0aW9uVGl0bGUiIHRhYmluZGV4PSIwIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgYXJpYUV4cGFuZGVkOiB7IGV4cGFuZGFibGU6IHRydWUsIGV4cGFuZGVkOiBleHBhbmRlZCB9LA0KICAgICAgICAgY2xpY2s6IHRvZ2dsZUV4cGFuZGVkLA0KICAgICAgICAgZXZlbnQ6IHsga2V5ZG93bjogdGl0bGVLZXlEb3duIH0iPg0KICAgICAgICA8ZGl2IGRhdGEtYmluZD0iZXhwYW5kZXI6IGV4cGFuZGVkIj48L2Rpdj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBsYWJlbCI+PC9zcGFuPg0KICAgIDwvZGl2Pg0KICAgIDx0YWJsZSBkYXRhLWJpbmQ9InZpc2libGU6IGV4cGFuZGVkKCkiPg0KICAgICAgICA8dGJvZHkgdGFiaW5kZXg9IjAiIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICBjbGljazogb25DbGljaywNCiAgICAgICAgICAgICAgIGV2ZW50OiB7IGtleWRvd246IG9uS2V5RG93biB9LA0KICAgICAgICAgICAgICAgZHluYW1pY0NvbnRleHRNZW51OiBjb250ZXh0TWVudSI+DQogICAgICAgICAgICA8IS0tIGtvIGZvcmVhY2g6IHJvd3MgLS0+DQogICAgICAgICAgICA8dHIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICAgY29sbGFwc2libGVUYWJsZVJvd0ZvY3VzOiAkcGFyZW50LmZvY3VzZWRSb3coKSA9PT0gJGRhdGEsDQogICAgICAgICAgICAgICAgY3NzOiB7IHNlbGVjdGVkOiBzZWxlY3RlZCgpIH0sDQogICAgICAgICAgICAgICAgdGVtcGxhdGU6IHsgbmFtZTogdGVtcGxhdGVOYW1lIH0iPg0KICAgICAgICAgICAgPC90cj4NCiAgICAgICAgICAgIDwhLS0gL2tvIC0tPg0KICAgICAgICA8L3Rib2R5Pg0KICAgIDwvdGFibGU+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},661:e=>{const t=document.createElement("script");t.id="StackTableRowView",t.innerHTML=atob("PHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGFkZHJlc3MsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdG9vbHRpcDogdG9vbHRpcCI+PC90ZD4="),t.type="text/html",document.head.appendChild(t),e.exports={}},632:e=>{const t=document.createElement("script");t.id="EventsRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJkYXRhR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgZGF0YUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9Ij4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJldmVudE5hbWUiIGRhdGEtYmluZD0idGV4dDogZXZlbnROYW1lIiBkYXRhLWNvbHVtbmlkPSJldmVudE5hbWUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZm9ybWF0dGVkTWVzc2FnZSIgZGF0YS1iaW5kPSJ0ZXh0OiBmb3JtYXR0ZWRNZXNzYWdlIiBkYXRhLWNvbHVtbmlkPSJmb3JtYXR0ZWRNZXNzYWdlIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImFkanVzdGVkVGltZXN0YW1wTVNlYyIgZGF0YS1iaW5kPSJ0ZXh0OiBhZGp1c3RlZFRpbWVzdGFtcE1TZWMiIGRhdGEtY29sdW1uaWQ9ImFkanVzdGVkVGltZXN0YW1wTVNlYyI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJwcm92aWRlckd1aWQiIGRhdGEtYmluZD0idGV4dDogcHJvdmlkZXJHdWlkIiBkYXRhLWNvbHVtbmlkPSJwcm92aWRlckd1aWQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZXZlbnRJZCIgZGF0YS1iaW5kPSJ0ZXh0OiBldmVudElkIiBkYXRhLWNvbHVtbmlkPSJldmVudElkIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InVuaXhUaW1lSW5NaWxsaXNlY29uZHMiIGRhdGEtYmluZD0idGV4dDogdW5peFRpbWVJbk1pbGxpc2Vjb25kcyIgZGF0YS1jb2x1bW5pZD0idW5peFRpbWVJbk1pbGxpc2Vjb25kcyI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJwcm9jZXNzSWQiIGRhdGEtYmluZD0idGV4dDogcHJvY2Vzc0lkIiBkYXRhLWNvbHVtbmlkPSJwcm9jZXNzSWQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0icHJvY2Vzc05hbWUiIGRhdGEtYmluZD0idGV4dDogcHJvY2Vzc05hbWUiIGRhdGEtY29sdW1uaWQ9InByb2Nlc3NOYW1lIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InRocmVhZElkIiBkYXRhLWJpbmQ9InRleHQ6IHRocmVhZElkIiBkYXRhLWNvbHVtbmlkPSJ0aHJlYWRJZCI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},853:(e,t,s)=>{var i,o;i=[s,t,s(28),s(560)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s.bindingHandlers.collapsibleTableFocusedRow={init(e,t,o,n,r){let a=-1;e.addEventListener("keydown",(e=>{if(i.KeyCodes.Shift===e.keyCode){const e=t();return void(a=s.unwrap(e.focused))}if(i.KeyCodes.ArrowUp!==e.keyCode&&i.KeyCodes.ArrowDown!==e.keyCode)return;const o=t(),n=s.unwrap(o.rows);if(0===n.length)return;const r=s.unwrap(o.focused);let l=0;if(i.KeyCodes.ArrowUp===e.keyCode&&-1!==r?l=Math.max(r-1,0):i.KeyCodes.ArrowDown===e.keyCode&&-1!==r&&(l=Math.min(r+1,n.length-1)),e.shiftKey){const e=Math.max(Math.min(l,a),0),t=Math.max(l,a),s=[];for(let i=e;i<=t;++i)s.push(i);a>l&&s.reverse(),o.selected(s)}else o.selected([l]);e.preventDefault()}))},update(e,t,i,o,n){const r=t(),a=s.unwrap(r.focused);if(-1===a)return;const l=e.parentElement,d=l.scrollTop,c=l.clientHeight,u=s.unwrap(r.rows),h=e.clientHeight/u.length,g=l.children;let m=0;for(let t=0;t<g.length&&g[t]!==e;t++)m+=g[t].clientHeight;const p=a*h+m;p<d?l.scrollTop=Math.max(p,0):p+h>d+c&&(l.scrollTop=p+h-c)}}}.apply(t,i),void 0===o||(e.exports=o)},736:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s.bindingHandlers.collapsibleTableRowFocus={previousElement:null,init(e,t,i,o,n){const r=()=>{if(s.bindingHandlers.collapsibleTableRowFocus.previousElement&&s.bindingHandlers.collapsibleTableRowFocus.previousElement!==e){const e=document.createEvent("Event");e.initEvent("blur",!1,!1),s.bindingHandlers.collapsibleTableRowFocus.previousElement.dispatchEvent(e)}const i=t();s.isWriteableObservable(i)&&!i()&&i(!0),s.bindingHandlers.collapsibleTableRowFocus.previousElement=e},a=()=>{const e=t();s.isWriteableObservable(e)&&e()&&e(!1)};e.addEventListener("focus",r),e.addEventListener("blur",a),s.utils.domNodeDisposal.addDisposeCallback(e,(()=>{e.removeEventListener("focus",r),e.removeEventListener("blur",a)}))},update(e,t,o,n,r){if(s.unwrap(t())){let t=e.parentElement;for(;t&&!t.classList.contains("collapsibleTableContainer");)t=t.parentElement;if(t){const s=t.scrollLeft;e.focus(),t.scrollLeft=s}else s.tasks.schedule((()=>{let t=e.parentElement;for(;t&&!t.classList.contains("collapsibleTableContainer");)t=t.parentElement;if(t){const s=t.scrollLeft;e.focus(),t.scrollLeft=s}else i.Assert.fail("Unable to find collapsibleTableContainer. Is this element a CollapsibleTable row?"),e.focus()}))}else e.blur()}}}.apply(t,i),void 0===o||(e.exports=o)},588:function(e,t,s){var i,o,n=this&&this.__createBinding||(Object.create?function(e,t,s,i){void 0===i&&(i=s),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[s]}})}:function(e,t,s,i){void 0===i&&(i=s),e[i]=t[s]}),r=this&&this.__exportStar||function(e,t){for(var s in e)"default"===s||Object.prototype.hasOwnProperty.call(t,s)||n(t,e,s)};i=[s,t,s(28),s(432),s(560),s(881),s(853),s(736),s(64),s(441)],o=function(e,t,s,i,o,n,a,l,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CollapsibleTableViewModel=void 0;var c=i.ContextMenu;r(a,t),r(l,t),r(d,t),t.CollapsibleTableViewModel=class{constructor(e,t){this._selectedRows=s.observableArray([]),this._focusedRowIndex=s.pureComputed((()=>this.computedFocusedRowIndex())),this._focusedRow=s.pureComputed((()=>this.computeFocusedRow())),this._expanded=s.observable(!0),this._rows=e,this._label=t,this._selectedRows.subscribe(this.onSelectionChanged.bind(this),null,"arrayChange")}get selectedRows(){return this._selectedRows}get label(){return this._label}get expanded(){return this._expanded}get rows(){return this._rows}get focusedRowIndex(){return this._focusedRowIndex}get focusedRow(){return this._focusedRow}onClick(e,t){if(t.which!==o.MouseCodes.Left)return;const i=s.contextFor(t.target);if(!i||i.$data===this)return;const n=i.$data,r=this._rows().indexOf(n);if(t.ctrlKey){const e=this._selectedRows().indexOf(r);-1===e?this._selectedRows.push(r):this._selectedRows.splice(e,1)}else if(t.shiftKey){const e=Math.max(Math.min(this.focusedRowIndex(),r),0),t=Math.max(this.focusedRowIndex(),r),s=this._selectedRows(),i=[];for(let o=e;o<=t;++o)-1===s.indexOf(o)&&i.push(o);this.focusedRowIndex()>r&&i.reverse(),i.forEach((e=>this._selectedRows.push(e)))}else this._selectedRows([r])}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==o.KeyCodes.C)return!0;const s=this.formatSelectedRowsToText();return navigator.clipboard.writeText(s),!1}contextMenu(e,t){const s=e;if("string"!=typeof s.templateName)return null;const o=this._rows().indexOf(s);-1===this._selectedRows().indexOf(o)&&this._selectedRows([o]);const n=[{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=this.formatSelectedRowsToText();navigator.clipboard.writeText(e)},type:c.MenuItemType.command}];return c.create(n)}toggleExpanded(e,t){const s=this._expanded();this._expanded(!s)}titleKeyDown(e,t){if(t.keyCode===o.KeyCodes.ArrowRight)this._expanded(!0);else if(t.keyCode===o.KeyCodes.ArrowLeft)this._expanded(!1);else{if(t.keyCode!==o.KeyCodes.Space)return!0;this.toggleExpanded(e,null)}return!1}computedFocusedRowIndex(){const e=this._selectedRows();return e.length>0?e[e.length-1]:-1}computeFocusedRow(){const e=this.computedFocusedRowIndex();return-1!==e?this._rows()[e]:null}onSelectionChanged(e){e.forEach((e=>{void 0===e.moved&&this._rows()[e.value]&&("added"===e.status?this._rows()[e.value].selected(!0):"deleted"===e.status&&this._rows()[e.value].selected(!1))}))}formatSelectedRowsToText(){const e=this.selectedRows().sort(((e,t)=>n.SortFunctions.numberComparator(e,t)));let t="";for(let s=0;s<e.length;++s)t+=`${this.rows()[e[s]].tooltip}\r\n`;return t.trim()}}}.apply(t,i),void 0===o||(e.exports=o)},64:(e,t,s)=>{var i,o;i=[s,t,s(28)],o=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s.bindingHandlers.expander={init:(e,t,s,i,o)=>(e.className="collapsibleTable-expander",{controlsDescendantBindings:!0}),update(e,t,i,o,n){s.unwrap(t())?e.classList.add("expanded"):e.classList.remove("expanded")}},s.virtualElements.allowedBindings.expander=!1}.apply(t,i),void 0===o||(e.exports=o)},355:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117),s(149)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.PropertyTableRowViewModel=void 0,t.PropertyTableRowViewModel=class{constructor(e){this._logger=i.getLogger("PropertyTableRowViewModel"),this._selected=s.observable(!1),this._computeString=s.pureComputed((()=>`${this.name()}\t${this.value()}`)),2===e.length?(this._name=s.observable(e[0]),this._value=s.observable(e[1])):this._logger.error("Expected string array with length 2 for PropertyTableRowViewModel")}get templateName(){return"PropertyTableRowView"}get name(){return this._name}get value(){return this._value}get selected(){return this._selected}get tooltip(){return this._computeString()}}}.apply(t,i),void 0===o||(e.exports=o)},360:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117),s(661)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.StackTableRowViewModel=void 0,t.StackTableRowViewModel=class{constructor(e){this._logger=i.getLogger("StackTableRowViewModel"),this._selected=s.observable(!1),this._computeString=s.pureComputed((()=>this.address())),1===e.length?this._address=s.observable(e[0]):this._logger.error("Expected string array with length 1 for StackTableRowViewModel")}get templateName(){return"StackTableRowView"}get address(){return this._address}get selected(){return this._selected}get tooltip(){return this._computeString()}}}.apply(t,i),void 0===o||(e.exports=o)},952:(e,t,s)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FilterLimit=t.errorNameCanceled=t.EventCountLimit=t.AnyStacksViewId=t.EventsViewerAnalyzerId=t.EventsListDetailsViewId=void 0,t.EventsListDetailsViewId=function(){return"AC3DC4D0-1FCC-4849-9F63-C8FFB47EC1DC"},t.EventsViewerAnalyzerId=function(){return"D9A8E704-BD31-402F-8990-A33EFB271CF0"},t.AnyStacksViewId=function(){return"FBF21B2D-E165-4C4E-8B10-36F0BC084F20"},t.EventCountLimit=function(){return 2e4},t.errorNameCanceled=function(){return"Canceled"},t.FilterLimit=function(){return 32766}}.apply(t,[s,t]),void 0===i||(e.exports=i)},334:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(952),s(560),s(560),s(881),s(881),s(881),s(881),s(881),s(881),s(881),s(881),s(117),s(117),s(117),s(152),s(337),s(766),s(758),s(588),s(355),s(360),s(886),s(680),s(833),s(103)],o=function(e,t,s,i,o,n,r,a,l,d,c,u,h,g,m,p,v,b,I,_,C,w,S,R,A,f){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getEventsListViewModel=t.EventsListViewModel=void 0;var D=i.ContextMenu;class y{constructor(){let e;this._commonProperties=s.pureComputed((()=>this._eventsListDAO.details()?this._eventsListDAO.details().cmp:[])),this._payloadProperties=s.pureComputed((()=>this._eventsListDAO.details()?this._eventsListDAO.details().plp:[])),this._stack=s.pureComputed((()=>this._eventsListDAO.details()?this._eventsListDAO.details().cs:[])),this._showDetails=s.pureComputed((()=>this._eventsListDAO.details()&&(this._eventsListDAO.details().plp.length>0||this._eventsListDAO.details().cmp.length>0||this._eventsListDAO.details().cs.length>0))),this._telemetry=new w.EventsViewerTelemetryMarshaler,this._viewEventManager=v.getViewEventManager(),this._currentOverlay=s.pureComputed((()=>this.computeOverlay())),this._isOverlayActive=s.pureComputed((()=>null!==this._currentOverlay())),this._showInfoBar=!0,this._loadDataWarehousePromise=b.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>Promise.all([Promise.resolve(t),e.getJmcService().getJmcEnabledState(),E.isNativeCodeEnabled()]))).then((t=>{const n=t[0],a=t[1],m=t[2];this._eventsListDAO=new I.EventsListDAO(e,n,E);const p=new g.DataGridHeaderViewModel([{id:"eventName",text:i.Resources.getString("EventsListHeaderEventName"),hideable:!1,filterable:c.FilterType.Expandable},{id:"formattedMessage",text:i.Resources.getString("EventsListHeaderDescription"),hideable:!0},{id:"adjustedTimestampMSec",text:i.Resources.getString("EventsListHeaderAdjustedTimestampMSec"),hideable:!1,sortable:c.SortDirection.Asc},{id:"providerGuid",text:i.Resources.getString("EventsListHeaderProviderGuid"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"eventId",text:i.Resources.getString("EventsListHeaderEventId"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"unixTimeInMilliseconds",text:i.Resources.getString("UnixTimeInMilliseconds"),hideable:!0,sortable:c.SortDirection.Asc},{id:"processId",text:i.Resources.getString("EventsListHeaderProcessId"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"processName",text:i.Resources.getString("EventsListHeaderProcessName"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"threadId",text:i.Resources.getString("EventsListHeaderThreadId"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat}],new _.EventsListColumnSettingsProvider,this._eventsListDAO.defaultSortColumnId);this._showJmc=new u.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(a),this._showJmc.isChecked.subscribe((()=>{this._getJmcServicePromise=e.getJmcService().setJmcEnabledState(this._showJmc.isChecked()).then((()=>{const e=this._eventsList.selectedRows();e.length>=1&&this._eventsListDAO.rows()[e[0]].invoke()}))})),this._showNative=new u.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked.subscribe((e=>{E.setNativeCodeEnabled(e).then((()=>{const e=this._eventsList.selectedRows();e.length>=1&&this._eventsListDAO.rows()[e[0]].invoke()}))})),this._showNative.isChecked(m),E.onUpdateNativeCode.addEventListener((e=>{this._showNative.isChecked(e.isEnabled)})),this._eventsListFilter=new d.DataGridFilterViewModel(this._eventsListDAO.filterOptions,p),this._eventsList=new l.DataGridViewModel(this._eventsListDAO,p,"EventsListAriaLabel",this._eventsListFilter),this._clearFilters=new h.ToolbarButtonViewModel(void 0,"ResetFiltersText","ResetFiltersText",(()=>this.eventsListFilter.resetFilters())),this._payloadTable=new S.CollapsibleTableViewModel(s.pureComputed((()=>this._payloadProperties().map((e=>new R.PropertyTableRowViewModel(e))))),"EventsListSideBarPayloadHeader"),this._commonTable=new S.CollapsibleTableViewModel(s.pureComputed((()=>this._commonProperties().map((e=>new R.PropertyTableRowViewModel(e))))),"EventsListSideBarCommonHeader"),this._commonTable.expanded(!1),this._stackTable=new S.CollapsibleTableViewModel(s.pureComputed((()=>this._stack().map((e=>new A.StackTableRowViewModel(e))))),"EventsListSideBarStackHeader"),this._eventsList.onResultChanged(0),this._eventsListDAO.rows.subscribe((()=>{this._eventsList.onResultChanged(0)})),this._eventsListDAO.count.subscribe((e=>{if(this._showInfoBar){const t=document.getElementById("eventsViewerInfoBar");t&&t.parentElement.removeChild(t),e<o.EventCountLimit()?this._infoBar=new r.InformationBarControl(i.Resources.getString("InformationTotalEvents",e.toLocaleString(i.Culture.formatRegion))):this._infoBar=new r.InformationBarControl(i.Resources.getString("InformationClippedEvents",o.EventCountLimit().toLocaleString(i.Culture.formatRegion),e.toLocaleString(i.Culture.formatRegion))),this._infoBar.container.id="eventsViewerInfoBar",this._infoBar.onClose=()=>{const e=document.getElementById("eventsViewerInfoBar");e&&e.parentElement.removeChild(e)};const s=document.createElement("div");s.classList.add("information-link"),this._infoBar.container.appendChild(s);const n=document.createElement("a");n.text=i.Resources.getString("InformationClippedEventsDoNotShow"),n.setAttribute("role","link"),n.setAttribute("aria-label",i.Resources.getString("InformationClippedEventsDoNotShow")),n.classList.add("information-link-text"),n.onclick=()=>{this._showInfoBar=!1,this._infoBar.onClose()},s.appendChild(n),document.getElementById("mainToolbar").insertAdjacentElement("afterend",this._infoBar.container)}this._telemetry.displayedEventCount(e)})),this._eventsList.selectedRows.subscribe((e=>{1===e.length&&(this._eventsList.rows()[e[0]].invoke(),this._telemetry.additionalPropertiesRequested())})),this._isOverlayActive.subscribe((e=>{e&&this._infoBar&&this._infoBar.onClose()})),this._viewEventManager.selectionChanged.addEventListener((e=>{e.isIntermittent||this._eventsListDAO.timeFilter(e.position)})),this._viewEventManager.jmcEnabledStateChanged.addEventListener((e=>{this._showJmc.isChecked()!==e.currEnabledState&&this._showJmc.isChecked(e.currEnabledState)})),s.applyBindings(this),this._viewEventManager.detailsViewReady.raiseEvent({Id:o.EventsListDetailsViewId()})}))}get clearFilters(){return this._clearFilters}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get payloadTable(){return this._payloadTable}get commonTable(){return this._commonTable}get stackTable(){return this._stackTable}get loadingProperties(){return this._eventsListDAO.loadingProperties}get showDetails(){return this._showDetails}get eventsList(){return this._eventsList}get eventsListFilter(){return this._eventsListFilter}get currentOverlay(){return this._currentOverlay}get dao(){return this._eventsListDAO}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==n.KeyCodes.C)return!0;const s=m.DataGridUtils.formatDataGridSelectedToText(this._eventsList);return navigator.clipboard.writeText(s),!1}contextMenu(e,t){const s=e;if("number"!=typeof s.id)return null;const o=e=>{this._showSourceFilePromise=this._eventsListDAO.showSourceFile(e).then()},n=this._eventsList.selectedRows().length>1;return this._eventsListDAO.loadAdditionalDetailsData(s.id).then((e=>{const t=[{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=m.DataGridUtils.formatDataGridSelectedToText(this._eventsList);navigator.clipboard.writeText(e)},type:D.MenuItemType.command},{type:D.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_TimeFilter_SetStart"),callback:()=>{this._getTimestampPromise=this._eventsListDAO.getTimestampInNanoseconds(s.id).then((e=>{const t=this._eventsListDAO.timeFilter().end;this._viewEventManager.selectionChanged.raiseEvent({position:new p.JsonTimespan(new p.BigNumber(e.h,e.l),t),isIntermittent:!1})}))},type:D.MenuItemType.command},{label:i.Resources.getString("ContextMenu_TimeFilter_SetEnd"),callback:()=>{this._getTimestampPromise=this._eventsListDAO.getTimestampInNanoseconds(s.id).then((e=>{const t=this._eventsListDAO.timeFilter().begin;this._viewEventManager.selectionChanged.raiseEvent({position:new p.JsonTimespan(t,new p.BigNumber(e.h,e.l)),isIntermittent:!1})}))},type:D.MenuItemType.command},{label:i.Resources.getString("ContextMenu_TimeFilter_SetInterval"),callback:()=>{const e=this.eventsList.selectedRows().map((e=>this.eventsList.rows()[e].id));this._getTimestampPromise=this._eventsListDAO.getMinMaxTimestampsInNanoseconds(e).then((e=>{this._viewEventManager.selectionChanged.raiseEvent({position:new p.JsonTimespan(new p.BigNumber(e.min.h,e.min.l),new p.BigNumber(e.max.h,e.max.l)),isIntermittent:!1})}))},type:D.MenuItemType.command,disabled:()=>this.eventsList.selectedRows().length<2},{type:D.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>o(e.sfp),type:D.MenuItemType.command,disabled:()=>n||!e.sfp},{type:D.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_ShowStacks_All"),callback:()=>this.showStacks(s.id,f.MatchFlags.None),type:D.MenuItemType.command},{label:i.Resources.getString("ContextMenu_ShowStacks_Provider"),callback:()=>this.showStacks(s.id,f.MatchFlags.Provider),type:D.MenuItemType.command},{label:i.Resources.getString("ContextMenu_ShowStacks_Task"),callback:()=>this.showStacks(s.id,f.MatchFlags.Provider|f.MatchFlags.Task),type:D.MenuItemType.command},{label:i.Resources.getString("ContextMenu_ShowStacks_Event"),callback:()=>this.showStacks(s.id,f.MatchFlags.Provider|f.MatchFlags.Task|f.MatchFlags.OpCode),type:D.MenuItemType.command}];return D.create(t)}))}computeOverlay(){return this._eventsListDAO.rowDataLoadStatus()===c.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._eventsListDAO.rowDataLoadStatus()===c.DataLoadEvent.DataLoadCompleted&&0===this._eventsList.rows().length?{name:"MessageView",data:i.Resources.getString("NoDataMessage")}:this._eventsListDAO.rowDataLoadStatus()===c.DataLoadEvent.DataLoadCanceled&&this._eventsListDAO.totalFilterCount()>o.FilterLimit()?{name:"MessageView",data:i.Resources.getString("FilterLimitMessage",this._eventsListDAO.totalFilterCount().toLocaleString(i.Culture.formatRegion))}:null}showStacks(e,t){E.showAnyStacks({rowId:e,matches:t}),this._viewEventManager.selectDetailsView(o.AnyStacksViewId())}}let L;t.EventsListViewModel=y;const E=new C.EventsViewerMarshaler;E.getDoubleClickTimeMs().then((e=>{a.Init(e),L=new y})),t.getEventsListViewModel=function(){return L}}.apply(t,i),void 0===o||(e.exports=o)},337:(e,t,s)=>{var i,o;i=[s,t,s(766)],o=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsListColumnSettingsProvider=void 0,t.EventsListColumnSettingsProvider=class{constructor(){this._view="Collections",this._marshaler=new s.EventsViewerMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings(this._view)}onColumnChanged(e){this._onColumnChangedPromise=this._marshaler.onColumnChanged(this._view,e)}}}.apply(t,i),void 0===o||(e.exports=o)},152:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(952),s(117),s(117),s(881),s(881),s(471),s(268),s(117)],o=function(e,t,s,i,o,n,r,a,l,d,c,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsListDAO=void 0;class h{constructor(e,t,i){this._rowDataLoadStatus=s.observable(a.DataLoadEvent.DataLoadStart),this._filterDomain=s.observableArray([]),this._count=s.observable(),this._rows=s.observableArray([]),this._sortInfo={columnId:this.defaultSortColumnId,direction:a.SortDirection.Desc},this._totalFilterCount=s.observable(),this._loadingProperties=s.observable(!1),this._details=s.observable(),this._commonPropertiesLabels=["TaskId","TaskName","OpCode","OpCodeName","Level","LevelName","Version","Keywords","Channel","ProcessorNumber","PointerSize","ActivityId","RelatedActivityId","IsClassicProvider","EventDataLength"],this._dataWarehouse=e,this._logger=n.getLogger("EventsListDAO"),this._marshaler=i,this._rows.subscribe((()=>{this._details(null)})),this._filterOptions=new d.EventsListFilterDAO(e),this._timeFilter=s.observable(t),this._timeFilter.subscribe((e=>{this._logger.debug("Time domain updated, loading new data");const t={timeDomain:e,customDomain:{view:"EventsList"}};this._getFilteredDataPromise=this._dataWarehouse.getFilteredData(t,o.EventsViewerAnalyzerId()).then((e=>(this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this.loadDataFromResult(0,o.EventCountLimit(),this._filterDomain(),this._currentResult)))).then((()=>this._filterOptions.loadFilterOptions(e)))})),this._timeFilter.notifySubscribers(t)}get filterOptions(){return this._filterOptions.filterOptions}get jmcService(){return void 0===this._jmcService&&(this._jmcService=this._dataWarehouse.getJmcService()),this._jmcService}get timeFilter(){return this._timeFilter}get totalFilterCount(){return this._totalFilterCount}get count(){return this._count}get rows(){return this._rows}get defaultSortColumnId(){return"adjustedTimestampMSec"}get rowDataLoadStatus(){return this._rowDataLoadStatus}get loadingProperties(){return this._loadingProperties}get details(){return this._details}get marshaler(){return this._marshaler}invokeRow(e){this._additionalDetailsPromise=e.additionalDetails.then((e=>{this._details(e)}))}getCount(e){return Promise.resolve(this._count())}getRows(e,t){return this.sort(this._rows(),t)}search(e,t,s,i,o,n,r){throw new Error("Method not implemented.")}sort(e,t,s){this._sortInfo=t;const i=h.SortFunc[t.columnId](t.direction);return e.sort(i),Promise.resolve(e)}filter(e,t){return this._filterDomain(e),this.loadDataFromResult(0,o.EventCountLimit(),this._filterDomain(),this._currentResult,t).then((()=>{const e=this._rows();return Promise.resolve(e)}))}getTimestampResult(e){let t=Promise.resolve(this._currentTimestampsResult);if(!this._currentTimestampsResult){const s={customDomain:{view:"Timestamps"}};t=this._dataWarehouse.getFilteredData(s,o.EventsViewerAnalyzerId(),e).then((t=>(null==e||e.throwIfCancellationRequested(),this._currentTimestampsResult=t,t)))}return t}getTimestampInNanoseconds(e){return this._logger.debug(`Getting timestamp in nanoseconds for ${e}`),this.getTimestampResult().then((t=>t.getResult({internalIds:[e]})))}getMinMaxTimestampsInNanoseconds(e){return this._logger.debug(`Getting min and max timestamps in nanoseconds for ${e.toString()}`),this.getTimestampResult().then((t=>t.getResult({internalIds:e})))}loadAdditionalDetailsData(e){this._logger.debug(`Getting additional properties for ${e}`),this._loadingProperties(!0);let t=Promise.resolve(this._currentPropertiesResult);if(!this._currentPropertiesResult){const e={customDomain:{view:"AdditionalProperties"}};t=this._dataWarehouse.getFilteredData(e,o.EventsViewerAnalyzerId()).then((e=>(this._currentPropertiesResult=e,e)))}const s=this.marshaler.isNativeCodeEnabled();return Promise.all([t,s]).then((t=>t[0].getResult({internalId:e,showNative:t[1]}))).then((e=>{let t=[],s=[],o=[],n=null;if(e.plp){const s=JSON.parse(e.plp);t=Object.getOwnPropertyNames(s).map((e=>[e,Object.getOwnPropertyDescriptor(s,e).value]))}return e.cmp&&(s=JSON.parse(e.cmp).map(((e,t)=>[this._commonPropertiesLabels[t],e]))),e.cs&&(o=e.cs.map((e=>("[External Code]"===e?e=i.Resources.getString("ExternalCodeLabel"):"[System Call]"===e&&(e=i.Resources.getString("SystemCallLabel")),[e])))),e.sfp&&(n=e.sfp),this._loadingProperties(!1),{plp:t,cmp:s,cs:o,sfp:n}}))}showSourceFile(e){return r.getSourceFileViewerService().openSourcePosition(e)}loadDataFromResult(e,t,s,i,n){if(this._logger.debug("get event data from result"),this._currentRequestCancellationTokenSource&&this._currentRequestCancellationTokenSource.cancel(),void 0===i)return this._logger.debug("undefined result for eventsListDAO"),Promise.resolve(void 0);this._currentRequestCancellationTokenSource=new u.CancellationTokenSource,this._currentRequestCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._rowDataLoadStatus(a.DataLoadEvent.DataLoadCanceled)}),{once:!0}),this._rowDataLoadStatus(a.DataLoadEvent.DataLoadStart);let r=0;return s.forEach((e=>{r+=e.includeItems.length})),this._totalFilterCount(r+2),this._totalFilterCount()>o.FilterLimit()?(this._logger.debug(`Filter count ${this._totalFilterCount()} exceeds SQLite limit of ${o.FilterLimit()}. Cannot make request.`),this._rowDataLoadStatus(a.DataLoadEvent.DataLoadCanceled),Promise.resolve(void 0)):(this._currentRequestPromise=i.getResult({startIndex:e,numberOfEvents:t,orderByColumn:"time",domain:s},n).then((e=>{this._logger.debug(`Result contains ${e.ec} events out of ${e.tec} total events starting at index ${e.si}`),this._count(e.tec),this._rows(e.ev.map((t=>new c.EventsRowViewModel(t,e.pvgs[t.pvg],e.pvns[t.pvn],e.eids[t.eid],e.ens[t.en],e.ts[t.t],e.pids[t.pid],e.pns[t.pn],e.tids[t.tid],this)))),this.sort(this._rows(),this._sortInfo)})).then((()=>{this.rowDataLoadStatus(a.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==o.errorNameCanceled()&&this._rowDataLoadStatus(a.DataLoadEvent.DataLoadFailed)})),this._currentRequestPromise)}}t.EventsListDAO=h,h.SortFunc={eventName:e=>l.SortFunctions.stringSort("eventName",e),adjustedTimestampMSec:e=>l.SortFunctions.numericSort("adjustedTimestampMSec",e),providerGuid:e=>l.SortFunctions.stringSort("providerGuid",e),eventId:e=>l.SortFunctions.numericSort("eventId",e),unixTimeInMilliseconds:e=>l.SortFunctions.numericSort("unixTimeInMilliseconds",e),processId:e=>l.SortFunctions.numericSort("processId",e),processName:e=>l.SortFunctions.natSort("processName",e),threadId:e=>l.SortFunctions.numericSort("threadId",e)}}.apply(t,i),void 0===o||(e.exports=o)},471:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117),s(952)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsListFilterDAO=void 0,t.EventsListFilterDAO=class{constructor(e){this._filterOptions=s.observableArray([]),this._dataWarehouse=e}get filterOptions(){return this._filterOptions}loadFilterOptions(e){const t={timeDomain:new i.JsonTimespan(i.BigNumber.zero,i.BigNumber.zero),customDomain:{view:"ColumnFilters"}};return this._dataWarehouse.getFilteredData(t,o.EventsViewerAnalyzerId()).then((e=>(this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this._currentResult.getResult({})))).then((e=>(this._filterOptions(e),this._filterOptions())))}}}.apply(t,i),void 0===o||(e.exports=o)},268:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(117),s(632)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsRowViewModel=void 0,t.EventsRowViewModel=class{constructor(e,t,i,n,r,a,l,d,c,u){this._selected=s.observable(!1),this._logger=o.getLogger("EventsRowViewModel"),this._dto=e,this._dao=u,this._providerGuid=t,this._eventId=n,this._eventName=`${i}/${r}`,this._unixTimeInMilliseconds=a,this._processId=l,this._processName=d,this._threadId=c}get adjustedTimestampMSec(){return this._dto.atms}get formattedMessage(){return this._dto.fm?this._dto.fm:i.Resources.getString("UnknownDataLabel")}get providerGuid(){return this._providerGuid?this._providerGuid:i.Resources.getString("UnknownDataLabel")}get eventName(){return this._eventName?this._eventName:i.Resources.getString("UnknownDataLabel")}get eventId(){return this._eventId}get unixTimeInMilliseconds(){if(void 0===this._unixTimeInMilliseconds_DateString){const e=new Date(this._unixTimeInMilliseconds);this._unixTimeInMilliseconds_DateString=e.toLocaleString(i.Culture.formatRegion,{timeZone:"UTC",hour12:!1,year:"numeric",day:"numeric",month:"numeric",hour:"numeric",minute:"numeric",second:"numeric",fractionalSecondDigits:3})}return this._unixTimeInMilliseconds_DateString}get processId(){return this._processId}get processName(){return this._processName}get threadId(){return this._threadId}get additionalDetails(){const e=this._dao.marshaler.isNativeCodeEnabled(),t=this._dao.jmcService.getJmcEnabledState();return Promise.all([t,e]).then((e=>{const t=e[0],s=e[1];return void 0!==this._additionalDetailsPromise&&this._jmcState===t&&this._showNative===s||(this._jmcState=t,this._showNative=s,this._additionalDetailsPromise=this._dao.loadAdditionalDetailsData(this.id)),this._additionalDetailsPromise}))}get templateName(){return"EventsRowView"}get id(){return this._dto.idx}get selected(){return this._selected}invoke(){this._logger.debug(`EventsRowViewModel: Invoke on row: ${this.id}`),this._dao.invokeRow(this)}}}.apply(t,i),void 0===o||(e.exports=o)},371:function(e,t,s){var i,o,n=this&&this.__createBinding||(Object.create?function(e,t,s,i){void 0===i&&(i=s),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[s]}})}:function(e,t,s,i){void 0===i&&(i=s),e[i]=t[s]}),r=this&&this.__exportStar||function(e,t){for(var s in e)"default"===s||Object.prototype.hasOwnProperty.call(t,s)||n(t,e,s)};i=[s,t,s(334),s(558)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),r(s,t),window.EventsViewerUI_onAfterDomInsert=i.onAfterDomInsert}.apply(t,i),void 0===o||(e.exports=o)},886:(e,t,s)=>{var i;i=function(e,t){"use strict";var s;Object.defineProperty(t,"__esModule",{value:!0}),t.MatchFlags=void 0,(s=t.MatchFlags||(t.MatchFlags={}))[s.None=0]="None",s[s.Provider=1]="Provider",s[s.Task=2]="Task",s[s.OpCode=4]="OpCode"}.apply(t,[s,t]),void 0===i||(e.exports=i)},766:(e,t,s)=>{var i,o;i=[s,t,s(432),s(117)],o=function(e,t,s,i){"use strict";let o;Object.defineProperty(t,"__esModule",{value:!0}),t.EventsViewerMarshaler=void 0,t.EventsViewerMarshaler=class{constructor(){o||(o=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.EventsViewer.EventsViewerMarshaler",{},!0)),this._onShowAnyStacks=new i.ObservableEvent(o,"onShowAnyStacks"),this._updateNativeCodeEvent=new i.ObservableEvent(o,"updateNativeCodeEvent")}openSymbolSettings(){o._post("openSymbolSettings")}loadModuleSymbols(e){return o._call("loadModuleSymbols",e)}get onShowAnyStacks(){return this._onShowAnyStacks}showAnyStacks(e){return o._call("showAnyStacks",e)}isNativeCodeEnabled(){return o._call("isNativeCodeEnabled")}setNativeCodeEnabled(e){return o._call("setNativeCode",{isEnabled:e})}get onUpdateNativeCode(){return this._updateNativeCodeEvent}getDoubleClickTimeMs(){return o._call("getDoubleClickTimeMs")}onColumnChanged(e,t){return o._call("onColumnChanged",e,t)}getColumnSettings(e){return o._call("getColumnSettings",e)}getLastAnyStacksArgs(){return o._call("getLastAnyStacksArgs")}}}.apply(t,i),void 0===o||(e.exports=o)},758:(e,t,s)=>{var i,o;i=[s,t,s(432)],o=function(e,t,s){"use strict";let i;Object.defineProperty(t,"__esModule",{value:!0}),t.EventsViewerTelemetryMarshaler=void 0,t.EventsViewerTelemetryMarshaler=class{constructor(){i||(i=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.EventsViewer.EventsViewerTelemetryMarshaler",{},!0))}additionalPropertiesRequested(){i._post("additionalPropertiesRequested")}displayedEventCount(e){i._post("displayedEventCount",e)}}}.apply(t,i),void 0===o||(e.exports=o)},558:(e,t,s)=>{var i,o;i=[s,t,s(28),s(432),s(560)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.LocalizeNumber=void 0;const n={};t.LocalizeNumber=function(e,t){const s=JSON.stringify(t||{});let o=n[s];if(!o){const e=new Intl.NumberFormat(i.Culture.formatRegion,t);o=t=>e.format(t),n[s]=o}return o(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=s.utils.domData.get(e,"mediaQuery");if(t){const i=s.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}let i=45;const n=e.children;for(let e=0;e<n.length;e++)i+=n.item(e).offsetWidth;const r=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},a=window.matchMedia(o.Utilities.formatString("(max-width: {0}px)",i.toString()));r(a),a.addListener(r),s.utils.domData.set(e,"mediaQuery",a),s.utils.domData.set(e,"mediaQueryListener",r)}}.apply(t,i),void 0===o||(e.exports=o)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=s},28:e=>{"use strict";e.exports=i},432:e=>{"use strict";e.exports=require("plugin-vs-v2")}},r={},function e(t){var s=r[t];if(void 0!==s)return s.exports;var i=r[t]={exports:{}};return n[t].call(i.exports,i,i.exports,e),i.exports}(371);var n,r}));
// SIG // Begin signature block
// SIG // MIIoNwYJKoZIhvcNAQcCoIIoKDCCKCQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // bHtJU9zPVRHgePKOtNaPAlEEO3FgAJpomxNSIbtt9WCg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoKMIIaBgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCBJo8xRNkBL+kkD
// SIG // vRa1PhLpRKiGTOh2wvcshK0ZmqbaujBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBABGSmI3T0oGdLc8deuhVDq/uqQ96ZUz1
// SIG // ukuEXqgaxOmh3iFKkQoKp3uvG7ZrmPJbT8t2zNE1QNNz
// SIG // B1zYEok9PhqiLjZXGjqMf1b31X0/8pLFgSvo24OnHgzf
// SIG // 46ncCyH5LdUWwudD4zfdZ10F/ioyBFNfuufdfH2OgCRM
// SIG // biVpHflx4yQF1vU8h3PU25cR1CHXBJZtEYa1q9Pv+2E/
// SIG // otydCHPY/PgSKrkKQH2R4ML4QXPqa4TyBLR6XvOFh9ms
// SIG // 1FhPEAtpYPBCpBbgKuDUzC9nJuKcXJks30P471bZBTVy
// SIG // pe/ETVaI8yAGeNSktch5oI2PsskL8K/NrYrKX7Hx1SSJ
// SIG // CSWhgheUMIIXkAYKKwYBBAGCNwMDATGCF4Awghd8Bgkq
// SIG // hkiG9w0BBwKgghdtMIIXaQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBUgYLKoZIhvcNAQkQAQSgggFBBIIBPTCCATkC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // xPAM/NqWHFpX9BTMmflPz6AWvODq0bY1/KXnlEewqm8C
// SIG // BmUorOGU4RgTMjAyMzEwMjAxNzA0MzcuMTE5WjAEgAIB
// SIG // 9KCB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMG
// SIG // A1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9u
// SIG // czEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkUwMDIt
// SIG // MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNloIIR6jCCByAwggUIoAMCAQIC
// SIG // EzMAAAHZnFwFkrCDaz4AAQAAAdkwDQYJKoZIhvcNAQEL
// SIG // BQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcN
// SIG // MjMwNjAxMTgzMjU4WhcNMjQwMjAxMTgzMjU4WjCByzEL
// SIG // MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
// SIG // EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9z
// SIG // b2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOkUwMDItMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEA1ekgzda4GNt9Oci3QnVDbxwhBOGdLnA+giry+ZQO
// SIG // xzPNUjJFt+kVO+1GgS/T0nL4qn1cxNq9qUW0TLQwTMBM
// SIG // dYmos1dhGbDRhrs3kd1zWDm0LyVS2gogZLQGXau+QTRS
// SIG // Ipfkn3aV4Cs1UGYgwSQzedFggAza62+PGeGe/yr8s2g+
// SIG // Bm/mmXgoqAdhoNZud3fuqVEwXN1jucR2Yv66yP13Z4Yh
// SIG // Ov27KY6VOWrnwpSA8dEA6tUEcNOGnayoXA1shi90mgaf
// SIG // 4YzfuCSVOys77ClmVXU7lz6I52k8FnB3RBn88Ymhd9M3
// SIG // fEmOGEVHDBjzkDkR9SD8JMMJakJHNBwZCQkM4ml2PyKY
// SIG // DEcP1z+FL/iQSfEWRimTdc0T1k/XebxxlEpl95u+0SqA
// SIG // n5IEiYnyIkIuhXNDmCkuoGTgO53eLfpYgK6/Z4qngv1H
// SIG // DTrla3FQuAm5MHydnh5GlodfLFLd1A/EB2C0MJ/eT/h5
// SIG // vD2SYoK9UkS3LJvKTj3nuzwW53SP1XiibJkHY3pNmhTv
// SIG // VRp1LcwwwaMJYV7IbMGTDJCyf+I1M0JlAX5viQB9edeh
// SIG // PhtNsEuzYMzMJqR1gpgGhXXew8iSKhmum3Ga0e0AC3ZM
// SIG // CIVUA4M2QLjcasL4eCGuGSOVaMo+G+81gIZrq6cKTKYo
// SIG // 8/onnlsH+mXZsrEY0f8melF5hmsCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBQcOsEpU2eoBV5dOcP7NxmtX+dcJzAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAKjbVWCzutUzLiGpwu3JbdIvl
// SIG // 0UWx8J8DaNOUN7OKaRbXeJwpgf0yTwyerrxK8sbNL8OW
// SIG // Po0MFIip4ZdlRhsCKtKVgyLmluKaTFdaWEHyenbQRpEY
// SIG // kz9XilbwEWGTEWiE3vWYcCSZ2D/N6TMRwsWhLGQuIpWN
// SIG // /+eXaneGV0ws/3KRuWp5g2q7Z1poMrMoDbLU8G1iSUY/
// SIG // OYGEZI8Yv58SgIhBcZehn5HJ11cvA0RUI9XdwIqrHj6H
// SIG // iM8btYrgCUcA633uDZyh6qE4FrL+3gliZ1o1lkbe0URq
// SIG // 6b8y0KPwcVG/IuPVMEYPRuW8aXeUrtW9tuBr+htR0VPq
// SIG // iRwdc6HuNQ9q/4nNgT6LrFfZ3mCuaiOTxy7IQJ+mE0JZ
// SIG // W1faQmzlL2TtHbXcKeRx9n8OqHyTcCnDxJWqpBHMb64Y
// SIG // UVqsDYGhFU8iFeIzHPIz28djYfcwM7Z2/TX5wxThPv4B
// SIG // fHGak2v0+uUxjT97jIj94K/JyF0NiEcDFVKC5hrtqn5o
// SIG // Q6HsLN3XL5OrNWgOplx8PjADRCAyio8N4thuibWZBHpr
// SIG // tTl7bJIP7Rp38sGjIKuQmrlPW+np07QPlBPhip5okFum
// SIG // FBz4QSNC9kBu+k0Qa3uT6TVR4snP9NW41BDKXmgfiJwB
// SIG // +Jw8WF8dfMGyRPnvyGzL9NeOxBS+/dnRCxdF8KqnFNEw
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDTTCC
// SIG // AjUCAQEwgfmhgdGkgc4wgcsxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9w
// SIG // ZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // TjpFMDAyLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUA4hxFugmt5+QYGVf7UP3wkdPU3/eggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAOjdDkcwIhgPMjAyMzEwMjAxNDMz
// SIG // NDNaGA8yMDIzMTAyMTE0MzM0M1owdDA6BgorBgEEAYRZ
// SIG // CgQBMSwwKjAKAgUA6N0ORwIBADAHAgEAAgIXWjAHAgEA
// SIG // AgITnzAKAgUA6N5fxwIBADA2BgorBgEEAYRZCgQCMSgw
// SIG // JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIB
// SIG // AAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQAlyKoFZDQe
// SIG // bzs6XVy5bvmGQAD02K8psIX5/clUV6vjOnuSgJqGbNK2
// SIG // T9KqkhwZGAqYmOOxHMvVmo9Dx5tno2pYr2BwHc6kgSiR
// SIG // 0WFW/GQBLhSfelmlHJvuNFgfmw+pslG7NepOseQtoMTb
// SIG // OqlIjbsHi3cQnMj1TIOEOw6q7FBmGfwwYZ+HaYtkfX8N
// SIG // pewZX4/HAadzuTPQOfWo1uJeY3RWO+X8l1GZ5GXoc4wv
// SIG // yR8E75dGD9py1ohry1wQOJdF/buqqGo18Ki68dK7x5Ui
// SIG // fETATw+9vxkpebdrngE6hCuRmDKVFkKHF1NEVuvU2aXx
// SIG // UbSPzInzPRjSUWdNmyjUBTkuMYIEDTCCBAkCAQEwgZMw
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHZ
// SIG // nFwFkrCDaz4AAQAAAdkwDQYJYIZIAWUDBAIBBQCgggFK
// SIG // MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkq
// SIG // hkiG9w0BCQQxIgQgebMlo/EonDIkG0zzfX01Lv+d+sro
// SIG // DTYOcdVf3/iP/bQwgfoGCyqGSIb3DQEJEAIvMYHqMIHn
// SIG // MIHkMIG9BCCfoBWyLTpv1DAwJxE82yXtLtA1ndjIKYG9
// SIG // EnG0IAd58zCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwAhMzAAAB2ZxcBZKwg2s+AAEAAAHZMCIE
// SIG // IPUOVde2gAWjKyuqhiqZlCJPYyMfrswf0/G6vlVRSyHR
// SIG // MA0GCSqGSIb3DQEBCwUABIICAFaxA6jIi4uOXglkNTv0
// SIG // Cc+3RBoRjq0lU/JLRi8ARA7JF73vQSTapu1ejZOH+7Ux
// SIG // GbHM5u4qD1ryxR8Se21lsB1VB9W2LUPQYcv5PSZRMW/+
// SIG // ANfox5ZLmv0S9CUWaFOP+2xHWJOB4WAj6fm6Op/eG9c/
// SIG // IhmmxDmgRudSY/SCcgldCvxqpwwLv2YxLGPyyvAWS17C
// SIG // crOZd86SF+jmdxTvBfThSTq/dTBanQPAZzoCsFdnVSYn
// SIG // jwIDtxy/jQ+4ThxiGqOum2xfnqr367m3hhxn30SoEimr
// SIG // Jz4FLLGcd7vXYXBU68EEfyOsZvq9befumxNG5YyLm92x
// SIG // Trx88cGjXvDKt0YvtibKtTkbLzuxw1aDLBHW74bjh3zD
// SIG // BLuLpQYodtx/Z1ReCfU8k3H0i7wMJ5a0ZgZvY38SUmaF
// SIG // 4xfAJd6S3UwRrs2C68S5d7588RuI7BS/Iw88Hi1Gujx1
// SIG // 5tKps6mJ0wDV0dNoELSahTdVQeTPvVxTdSeD6D+2IP7v
// SIG // L5GX8nzMoo2Xxec+Kz7QKm0kFbdxVidyMF7iWV5mjp2s
// SIG // DoM8WOd22o7jm5hFlAVBoSdvFVcGGlGBzX6vrI1lCz7Q
// SIG // uynPKM19cnts9Fx1bau5+DuJojCWHFDXtHg0HkUL50Le
// SIG // dTGeeO7a8l0/NfadImGmhTc4x4nVGxLVvCYVipqmhd5U
// SIG // WYAo
// SIG // End signature block
