"use strict";(()=>{var B,_,le,Ze,A,ce,ie,fe,V={},de=[],Xe=/acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord|itera/i;function C(e,n){for(var t in n)e[t]=n[t];return e}function pe(e){var n=e.parentNode;n&&n.removeChild(e)}function i(e,n,t){var r,s,o,l={};for(o in n)o=="key"?r=n[o]:o=="ref"?s=n[o]:l[o]=n[o];if(arguments.length>2&&(l.children=arguments.length>3?B.call(arguments,2):t),typeof e=="function"&&e.defaultProps!=null)for(o in e.defaultProps)l[o]===void 0&&(l[o]=e.defaultProps[o]);return M(e,l,r,s,null)}function M(e,n,t,r,s){var o={type:e,props:n,key:t,ref:r,__k:null,__:null,__b:0,__e:null,__d:void 0,__c:null,__h:null,constructor:void 0,__v:s??++le};return s==null&&_.vnode!=null&&_.vnode(o),o}function x(e){return e.children}function P(e,n){this.props=e,this.context=n}function R(e,n){if(n==null)return e.__?R(e.__,e.__.__k.indexOf(e)+1):null;for(var t;n<e.__k.length;n++)if((t=e.__k[n])!=null&&t.__e!=null)return t.__e;return typeof e.type=="function"?R(e):null}function _e(e){var n,t;if((e=e.__)!=null&&e.__c!=null){for(e.__e=e.__c.base=null,n=0;n<e.__k.length;n++)if((t=e.__k[n])!=null&&t.__e!=null){e.__e=e.__c.base=t.__e;break}return _e(e)}}function G(e){(!e.__d&&(e.__d=!0)&&A.push(e)&&!O.__r++||ie!==_.debounceRendering)&&((ie=_.debounceRendering)||ce)(O)}function O(){for(var e;O.__r=A.length;)e=A.sort(function(n,t){return n.__v.__b-t.__v.__b}),A=[],e.some(function(n){var t,r,s,o,l,u;n.__d&&(l=(o=(t=n).__v).__e,(u=t.__P)&&(r=[],(s=C({},o)).__v=o.__v+1,Y(u,o,s,t.__n,u.ownerSVGElement!==void 0,o.__h!=null?[l]:null,r,l??R(o),o.__h),ye(r,o),o.__e!=l&&_e(o)))})}function me(e,n,t,r,s,o,l,u,c,d){var a,g,p,f,m,y,v,h=r&&r.__k||de,w=h.length;for(t.__k=[],a=0;a<n.length;a++)if((f=t.__k[a]=(f=n[a])==null||typeof f=="boolean"?null:typeof f=="string"||typeof f=="number"||typeof f=="bigint"?M(null,f,null,null,f):Array.isArray(f)?M(x,{children:f},null,null,null):f.__b>0?M(f.type,f.props,f.key,null,f.__v):f)!=null){if(f.__=t,f.__b=t.__b+1,(p=h[a])===null||p&&f.key==p.key&&f.type===p.type)h[a]=void 0;else for(g=0;g<w;g++){if((p=h[g])&&f.key==p.key&&f.type===p.type){h[g]=void 0;break}p=null}Y(e,f,p=p||V,s,o,l,u,c,d),m=f.__e,(g=f.ref)&&p.ref!=g&&(v||(v=[]),p.ref&&v.push(p.ref,null,f),v.push(g,f.__c||m,f)),m!=null?(y==null&&(y=m),typeof f.type=="function"&&f.__k===p.__k?f.__d=c=ge(f,c,e):c=ve(e,f,p,h,m,c),typeof t.type=="function"&&(t.__d=c)):c&&p.__e==c&&c.parentNode!=e&&(c=R(p))}for(t.__e=y,a=w;a--;)h[a]!=null&&(typeof t.type=="function"&&h[a].__e!=null&&h[a].__e==t.__d&&(t.__d=R(r,a+1)),we(h[a],h[a]));if(v)for(a=0;a<v.length;a++)he(v[a],v[++a],v[++a])}function ge(e,n,t){for(var r,s=e.__k,o=0;s&&o<s.length;o++)(r=s[o])&&(r.__=e,n=typeof r.type=="function"?ge(r,n,t):ve(t,r,r,s,r.__e,n));return n}function ve(e,n,t,r,s,o){var l,u,c;if(n.__d!==void 0)l=n.__d,n.__d=void 0;else if(t==null||s!=o||s.parentNode==null)e:if(o==null||o.parentNode!==e)e.appendChild(s),l=null;else{for(u=o,c=0;(u=u.nextSibling)&&c<r.length;c+=2)if(u==s)break e;e.insertBefore(s,o),l=o}return l!==void 0?l:s.nextSibling}function Qe(e,n,t,r,s){var o;for(o in t)o==="children"||o==="key"||o in n||W(e,o,null,t[o],r);for(o in n)s&&typeof n[o]!="function"||o==="children"||o==="key"||o==="value"||o==="checked"||t[o]===n[o]||W(e,o,n[o],t[o],r)}function se(e,n,t){n[0]==="-"?e.setProperty(n,t):e[n]=t==null?"":typeof t!="number"||Xe.test(n)?t:t+"px"}function W(e,n,t,r,s){var o;e:if(n==="style")if(typeof t=="string")e.style.cssText=t;else{if(typeof r=="string"&&(e.style.cssText=r=""),r)for(n in r)t&&n in t||se(e.style,n,"");if(t)for(n in t)r&&t[n]===r[n]||se(e.style,n,t[n])}else if(n[0]==="o"&&n[1]==="n")o=n!==(n=n.replace(/Capture$/,"")),n=n.toLowerCase()in e?n.toLowerCase().slice(2):n.slice(2),e.l||(e.l={}),e.l[n+o]=t,t?r||e.addEventListener(n,o?ue:ae,o):e.removeEventListener(n,o?ue:ae,o);else if(n!=="dangerouslySetInnerHTML"){if(s)n=n.replace(/xlink[H:h]/,"h").replace(/sName$/,"s");else if(n!=="href"&&n!=="list"&&n!=="form"&&n!=="tabIndex"&&n!=="download"&&n in e)try{e[n]=t??"";break e}catch{}typeof t=="function"||(t!=null&&(t!==!1||n[0]==="a"&&n[1]==="r")?e.setAttribute(n,t):e.removeAttribute(n))}}function ae(e){this.l[e.type+!1](_.event?_.event(e):e)}function ue(e){this.l[e.type+!0](_.event?_.event(e):e)}function Y(e,n,t,r,s,o,l,u,c){var d,a,g,p,f,m,y,v,h,w,L,k=n.type;if(n.constructor!==void 0)return null;t.__h!=null&&(c=t.__h,u=n.__e=t.__e,n.__h=null,o=[u]),(d=_.__b)&&d(n);try{e:if(typeof k=="function"){if(v=n.props,h=(d=k.contextType)&&r[d.__c],w=d?h?h.props.value:d.__:r,t.__c?y=(a=n.__c=t.__c).__=a.__E:("prototype"in k&&k.prototype.render?n.__c=a=new k(v,w):(n.__c=a=new P(v,w),a.constructor=k,a.render=nn),h&&h.sub(a),a.props=v,a.state||(a.state={}),a.context=w,a.__n=r,g=a.__d=!0,a.__h=[]),a.__s==null&&(a.__s=a.state),k.getDerivedStateFromProps!=null&&(a.__s==a.state&&(a.__s=C({},a.__s)),C(a.__s,k.getDerivedStateFromProps(v,a.__s))),p=a.props,f=a.state,g)k.getDerivedStateFromProps==null&&a.componentWillMount!=null&&a.componentWillMount(),a.componentDidMount!=null&&a.__h.push(a.componentDidMount);else{if(k.getDerivedStateFromProps==null&&v!==p&&a.componentWillReceiveProps!=null&&a.componentWillReceiveProps(v,w),!a.__e&&a.shouldComponentUpdate!=null&&a.shouldComponentUpdate(v,a.__s,w)===!1||n.__v===t.__v){a.props=v,a.state=a.__s,n.__v!==t.__v&&(a.__d=!1),a.__v=n,n.__e=t.__e,n.__k=t.__k,n.__k.forEach(function(I){I&&(I.__=n)}),a.__h.length&&l.push(a);break e}a.componentWillUpdate!=null&&a.componentWillUpdate(v,a.__s,w),a.componentDidUpdate!=null&&a.__h.push(function(){a.componentDidUpdate(p,f,m)})}a.context=w,a.props=v,a.state=a.__s,(d=_.__r)&&d(n),a.__d=!1,a.__v=n,a.__P=e,d=a.render(a.props,a.state,a.context),a.state=a.__s,a.getChildContext!=null&&(r=C(C({},r),a.getChildContext())),g||a.getSnapshotBeforeUpdate==null||(m=a.getSnapshotBeforeUpdate(p,f)),L=d!=null&&d.type===x&&d.key==null?d.props.children:d,me(e,Array.isArray(L)?L:[L],n,t,r,s,o,l,u,c),a.base=n.__e,n.__h=null,a.__h.length&&l.push(a),y&&(a.__E=a.__=null),a.__e=!1}else o==null&&n.__v===t.__v?(n.__k=t.__k,n.__e=t.__e):n.__e=en(t.__e,n,t,r,s,o,l,c);(d=_.diffed)&&d(n)}catch(I){n.__v=null,(c||o!=null)&&(n.__e=u,n.__h=!!c,o[o.indexOf(u)]=null),_.__e(I,n,t)}}function ye(e,n){_.__c&&_.__c(n,e),e.some(function(t){try{e=t.__h,t.__h=[],e.some(function(r){r.call(t)})}catch(r){_.__e(r,t.__v)}})}function en(e,n,t,r,s,o,l,u){var c,d,a,g=t.props,p=n.props,f=n.type,m=0;if(f==="svg"&&(s=!0),o!=null){for(;m<o.length;m++)if((c=o[m])&&"setAttribute"in c==!!f&&(f?c.localName===f:c.nodeType===3)){e=c,o[m]=null;break}}if(e==null){if(f===null)return document.createTextNode(p);e=s?document.createElementNS("http://www.w3.org/2000/svg",f):document.createElement(f,p.is&&p),o=null,u=!1}if(f===null)g===p||u&&e.data===p||(e.data=p);else{if(o=o&&B.call(e.childNodes),d=(g=t.props||V).dangerouslySetInnerHTML,a=p.dangerouslySetInnerHTML,!u){if(o!=null)for(g={},m=0;m<e.attributes.length;m++)g[e.attributes[m].name]=e.attributes[m].value;(a||d)&&(a&&(d&&a.__html==d.__html||a.__html===e.innerHTML)||(e.innerHTML=a&&a.__html||""))}if(Qe(e,p,g,s,u),a)n.__k=[];else if(m=n.props.children,me(e,Array.isArray(m)?m:[m],n,t,r,s&&f!=="foreignObject",o,l,o?o[0]:t.__k&&R(t,0),u),o!=null)for(m=o.length;m--;)o[m]!=null&&pe(o[m]);u||("value"in p&&(m=p.value)!==void 0&&(m!==e.value||f==="progress"&&!m||f==="option"&&m!==g.value)&&W(e,"value",m,g.value,!1),"checked"in p&&(m=p.checked)!==void 0&&m!==e.checked&&W(e,"checked",m,g.checked,!1))}return e}function he(e,n,t){try{typeof e=="function"?e(n):e.current=n}catch(r){_.__e(r,t)}}function we(e,n,t){var r,s;if(_.unmount&&_.unmount(e),(r=e.ref)&&(r.current&&r.current!==e.__e||he(r,null,n)),(r=e.__c)!=null){if(r.componentWillUnmount)try{r.componentWillUnmount()}catch(o){_.__e(o,n)}r.base=r.__P=null}if(r=e.__k)for(s=0;s<r.length;s++)r[s]&&we(r[s],n,typeof e.type!="function");t||e.__e==null||pe(e.__e),e.__e=e.__d=void 0}function nn(e,n,t){return this.constructor(e,t)}function Z(e,n,t){var r,s,o;_.__&&_.__(e,n),s=(r=typeof t=="function")?null:t&&t.__k||n.__k,o=[],Y(n,e=(!r&&t||n).__k=i(x,null,[e]),s||V,V,n.ownerSVGElement!==void 0,!r&&t?[t]:s?null:n.firstChild?B.call(n.childNodes):null,o,!r&&t?t:s?s.__e:n.firstChild,r),ye(o,e)}function xe(e,n){var t={__c:n="__cC"+fe++,__:e,Consumer:function(r,s){return r.children(s)},Provider:function(r){var s,o;return this.getChildContext||(s=[],(o={})[n]=this,this.getChildContext=function(){return o},this.shouldComponentUpdate=function(l){this.props.value!==l.value&&s.some(G)},this.sub=function(l){s.push(l);var u=l.componentWillUnmount;l.componentWillUnmount=function(){s.splice(s.indexOf(l),1),u&&u.call(l)}}),r.children}};return t.Provider.__=t.Consumer.contextType=t}B=de.slice,_={__e:function(e,n){for(var t,r,s;n=n.__;)if((t=n.__c)&&!t.__)try{if((r=t.constructor)&&r.getDerivedStateFromError!=null&&(t.setState(r.getDerivedStateFromError(e)),s=t.__d),t.componentDidCatch!=null&&(t.componentDidCatch(e),s=t.__d),s)return t.__E=t}catch(o){e=o}throw e}},le=0,Ze=function(e){return e!=null&&e.constructor===void 0},P.prototype.setState=function(e,n){var t;t=this.__s!=null&&this.__s!==this.state?this.__s:this.__s=C({},this.state),typeof e=="function"&&(e=e(C({},t),this.props)),e&&C(t,e),e!=null&&this.__v&&(n&&this.__h.push(n),G(this))},P.prototype.forceUpdate=function(e){this.__v&&(this.__e=!0,e&&this.__h.push(e),G(this))},P.prototype.render=x,A=[],ce=typeof Promise=="function"?Promise.prototype.then.bind(Promise.resolve()):setTimeout,O.__r=0,fe=0;function S(){}S.prototype={diff:function(n,t){var r=arguments.length>2&&arguments[2]!==void 0?arguments[2]:{},s=r.callback;typeof r=="function"&&(s=r,r={}),this.options=r;var o=this;function l(y){return s?(setTimeout(function(){s(void 0,y)},0),!0):y}n=this.castInput(n),t=this.castInput(t),n=this.removeEmpty(this.tokenize(n)),t=this.removeEmpty(this.tokenize(t));var u=t.length,c=n.length,d=1,a=u+c,g=[{newPos:-1,components:[]}],p=this.extractCommon(g[0],t,n,0);if(g[0].newPos+1>=u&&p+1>=c)return l([{value:this.join(t),count:t.length}]);function f(){for(var y=-1*d;y<=d;y+=2){var v=void 0,h=g[y-1],w=g[y+1],L=(w?w.newPos:0)-y;h&&(g[y-1]=void 0);var k=h&&h.newPos+1<u,I=w&&0<=L&&L<c;if(!k&&!I){g[y]=void 0;continue}if(!k||I&&h.newPos<w.newPos?(v=rn(w),o.pushComponent(v.components,void 0,!0)):(v=h,v.newPos++,o.pushComponent(v.components,!0,void 0)),L=o.extractCommon(v,t,n,y),v.newPos+1>=u&&L+1>=c)return l(tn(o,v.components,t,n,o.useLongestToken));g[y]=v}d++}if(s)(function y(){setTimeout(function(){if(d>a)return s();f()||y()},0)})();else for(;d<=a;){var m=f();if(m)return m}},pushComponent:function(n,t,r){var s=n[n.length-1];s&&s.added===t&&s.removed===r?n[n.length-1]={count:s.count+1,added:t,removed:r}:n.push({count:1,added:t,removed:r})},extractCommon:function(n,t,r,s){for(var o=t.length,l=r.length,u=n.newPos,c=u-s,d=0;u+1<o&&c+1<l&&this.equals(t[u+1],r[c+1]);)u++,c++,d++;return d&&n.components.push({count:d}),n.newPos=u,c},equals:function(n,t){return this.options.comparator?this.options.comparator(n,t):n===t||this.options.ignoreCase&&n.toLowerCase()===t.toLowerCase()},removeEmpty:function(n){for(var t=[],r=0;r<n.length;r++)n[r]&&t.push(n[r]);return t},castInput:function(n){return n},tokenize:function(n){return n.split("")},join:function(n){return n.join("")}};function tn(e,n,t,r,s){for(var o=0,l=n.length,u=0,c=0;o<l;o++){var d=n[o];if(d.removed){if(d.value=e.join(r.slice(c,c+d.count)),c+=d.count,o&&n[o-1].added){var g=n[o-1];n[o-1]=n[o],n[o]=g}}else{if(!d.added&&s){var a=t.slice(u,u+d.count);a=a.map(function(f,m){var y=r[c+m];return y.length>f.length?y:f}),d.value=e.join(a)}else d.value=e.join(t.slice(u,u+d.count));u+=d.count,d.added||(c+=d.count)}}var p=n[l-1];return l>1&&typeof p.value=="string"&&(p.added||p.removed)&&e.equals("",p.value)&&(n[l-2].value+=p.value,n.pop()),n}function rn(e){return{newPos:e.newPos,components:e.components.slice(0)}}var on=new S;function Te(e,n,t){return on.diff(e,n,t)}var ke=/^[A-Za-z\xC0-\u02C6\u02C8-\u02D7\u02DE-\u02FF\u1E00-\u1EFF]+$/,be=/\S/,Le=new S;Le.equals=function(e,n){return this.options.ignoreCase&&(e=e.toLowerCase(),n=n.toLowerCase()),e===n||this.options.ignoreWhitespace&&!be.test(e)&&!be.test(n)};Le.tokenize=function(e){for(var n=e.split(/([^\S\r\n]+|[()[\]{}'"\r\n]|\b)/),t=0;t<n.length-1;t++)!n[t+1]&&n[t+2]&&ke.test(n[t])&&ke.test(n[t+2])&&(n[t]+=n[t+2],n.splice(t+1,2),t--);return n};var Se=new S;Se.tokenize=function(e){var n=[],t=e.split(/(\n|\r\n)/);t[t.length-1]||t.pop();for(var r=0;r<t.length;r++){var s=t[r];r%2&&!this.options.newlineIsToken?n[n.length-1]+=s:(this.options.ignoreWhitespace&&(s=s.trim()),n.push(s))}return n};var sn=new S;sn.tokenize=function(e){return e.split(/(\S.+?[.!?])(?=\s+|$)/)};var an=new S;an.tokenize=function(e){return e.split(/([{}:;,]|\s+)/)};function U(e){return typeof Symbol=="function"&&typeof Symbol.iterator=="symbol"?U=function(n){return typeof n}:U=function(n){return n&&typeof Symbol=="function"&&n.constructor===Symbol&&n!==Symbol.prototype?"symbol":typeof n},U(e)}var un=Object.prototype.toString,E=new S;E.useLongestToken=!0;E.tokenize=Se.tokenize;E.castInput=function(e){var n=this.options,t=n.undefinedReplacement,r=n.stringifyReplacer,s=r===void 0?function(o,l){return typeof l>"u"?t:l}:r;return typeof e=="string"?e:JSON.stringify(X(e,null,null,s),s,"  ")};E.equals=function(e,n){return S.prototype.equals.call(E,e.replace(/,([\r\n])/g,"$1"),n.replace(/,([\r\n])/g,"$1"))};function X(e,n,t,r,s){n=n||[],t=t||[],r&&(e=r(s,e));var o;for(o=0;o<n.length;o+=1)if(n[o]===e)return t[o];var l;if(un.call(e)==="[object Array]"){for(n.push(e),l=new Array(e.length),t.push(l),o=0;o<e.length;o+=1)l[o]=X(e[o],n,t,r,s);return n.pop(),t.pop(),l}if(e&&e.toJSON&&(e=e.toJSON()),U(e)==="object"&&e!==null){n.push(e),l={},t.push(l);var u=[],c;for(c in e)e.hasOwnProperty(c)&&u.push(c);for(u.sort(),o=0;o<u.length;o+=1)c=u[o],l[c]=X(e[c],n,t,r,c);n.pop(),t.pop()}else l=e;return l}var Q=new S;Q.tokenize=function(e){return e.slice()};Q.join=Q.removeEmpty=function(e){return e};var $,b,Ce,z=0,Ae=[],Fe=_.__b,Ie=_.__r,Ne=_.diffed,De=_.__c,Re=_.unmount;function ne(e,n){_.__h&&_.__h(b,e,z||n),z=0;var t=b.__H||(b.__H={__:[],__h:[]});return e>=t.__.length&&t.__.push({}),t.__[e]}function J(e){return z=1,ln(Me,e)}function ln(e,n,t){var r=ne($++,2);return r.t=e,r.__c||(r.__=[t?t(n):Me(void 0,n),function(s){var o=r.t(r.__[0],s);r.__[0]!==o&&(r.__=[o,r.__[1]],r.__c.setState({}))}],r.__c=b),r.__}function H(e,n){var t=ne($++,7);return fn(t.__H,n)&&(t.__=e(),t.__H=n,t.__h=e),t.__}function N(e,n){return z=8,H(function(){return e},n)}function Ee(e){var n=b.context[e.__c],t=ne($++,9);return t.c=e,n?(t.__==null&&(t.__=!0,n.sub(b)),n.props.value):e.__}function cn(){for(var e;e=Ae.shift();)if(e.__P)try{e.__H.__h.forEach(q),e.__H.__h.forEach(ee),e.__H.__h=[]}catch(n){e.__H.__h=[],_.__e(n,e.__v)}}_.__b=function(e){b=null,Fe&&Fe(e)},_.__r=function(e){Ie&&Ie(e),$=0;var n=(b=e.__c).__H;n&&(n.__h.forEach(q),n.__h.forEach(ee),n.__h=[])},_.diffed=function(e){Ne&&Ne(e);var n=e.__c;n&&n.__H&&n.__H.__h.length&&(Ae.push(n)!==1&&Ce===_.requestAnimationFrame||((Ce=_.requestAnimationFrame)||function(t){var r,s=function(){clearTimeout(o),He&&cancelAnimationFrame(r),setTimeout(t)},o=setTimeout(s,100);He&&(r=requestAnimationFrame(s))})(cn)),b=null},_.__c=function(e,n){n.some(function(t){try{t.__h.forEach(q),t.__h=t.__h.filter(function(r){return!r.__||ee(r)})}catch(r){n.some(function(s){s.__h&&(s.__h=[])}),n=[],_.__e(r,t.__v)}}),De&&De(e,n)},_.unmount=function(e){Re&&Re(e);var n,t=e.__c;t&&t.__H&&(t.__H.__.forEach(function(r){try{q(r)}catch(s){n=s}}),n&&_.__e(n,t.__v))};var He=typeof requestAnimationFrame=="function";function q(e){var n=b,t=e.__c;typeof t=="function"&&(e.__c=void 0,t()),b=n}function ee(e){var n=b;e.__c=e.__(),b=n}function fn(e,n){return!e||e.length!==n.length||n.some(function(t,r){return t!==e[r]})}function Me(e,n){return typeof n=="function"?n(e):n}var Pe=e=>!!e;var Pn=Symbol("unset");function Ve(e){let n=[];for(let t of e)n=n.concat(t);return n}var Vn=2**31-1;var Oe=e=>function({value:t,onChange:r}){return i("div",{className:"decision-buttons"},e.map(s=>i("button",{key:s,onClick:()=>r(s),className:t===s?"active":""},s)))};var qe="<node_internals>",ze="node:",$e=e=>e.config.type==="pwa-node"||e.config.type==="pwa-extensionHost"||e.config.type==="node-terminal",j=e=>e.config.type==="pwa-chrome"||e.config.type==="pwa-msedge",te=e=>e.absolutePath.startsWith(qe)||e.url.startsWith(ze)?2:e.absolutePath.includes("node_modules")?1:0,K=(e,n)=>e.url.startsWith(ze)?e.url:e.absolutePath.startsWith(qe)?e.absolutePath:dn(e.absolutePath)&&n.config.__workspaceFolder?_n(n.config.__workspaceFolder,e.absolutePath):e.absolutePath||e.url,D=e=>{let n=(e.prettyName||e.url).split(/\\|\//g);return n[n.length-1]},dn=e=>Je(e)||pn(e),Je=e=>e.startsWith("/"),pn=e=>/^[a-z]:/i.test(e),We=(e,n)=>{let t=e.split("/"),r=n.split("/");for(;t.length&&r[0]===t[0];)t.shift(),r.shift();return(t.length?new Array(t.length).fill(".."):["."]).concat(r).join("/")},_n=(e,n)=>Je(e)?We(e,n):We(Be(Ue(e)),Be(Ue(n))),Be=e=>e.replace(/\\\//g,"/").replace(/\\/g,"/"),Ue=e=>e.slice(0,1).toUpperCase()+e.slice(1);var re=xe(void 0),T=()=>Ee(re);var oe=acquireVsCodeApi(),mn=(e,n)=>{let t=oe.getState()?.componentState||{};return t.hasOwnProperty(e)?t[e]:n},gn=(e,n)=>{let t=oe.getState();oe.setState({...t,componentState:{...t?.componentState,[e]:n}})},F=(e,n)=>{let[t,r]=J(()=>mn(e,n)),s=N(o=>{gn(e,o),r(o)},[e,r]);return[t,s]};var je=()=>{let e=T();return i(x,null,e.breakpoints.map((n,t)=>i(wn,{bp:n,key:t})))},vn=(e,n)=>e.cdp.some(t=>{if("location"in t.args)return!0;if(t.args.url){let r=t.args.url;return n.sources.some(s=>s.url===r)}if(t.args.urlRegex){let r=new RegExp(t.args.urlRegex);return n.sources.some(s=>r.test(s.url))}return!1}),yn=(e,n)=>{let t=0,r=[i("li",{key:t++},i("p",null,"\u2705 This breakpoint was initially set in:"),i("p",null,i("code",null,e.source.path)," line ",e.params.line," column ",e.params.column||1))];if(!vn(e,n))return r.push(i(xn,{bp:e,key:t++})),r;r.push(i("li",{key:t++},i("p",null,"\u2705 In the runtime, the breakpoint was set in:"),i("p",null,i("ul",null,e.cdp.map((l,u)=>i(Tn,{cdp:l,index:u,key:u}))))));let s=e.cdp.filter(l=>l.state===1),o=Ve(s.map(l=>l.state===1?l.uiLocations:[]));return o.length?(r.push(i("li",{key:t++},i("p",null,"\u2705 The runtime acknowledged and adjusted the breakpoint, and it mapped back to the following locations:"),i("ul",null,o.map((l,u)=>i(bn,{loc:l,key:u})))),i("li",{key:t++},i("p",null,"If this is not right, your compiled code might be out of date with your sources. If you don't think this is the case and something else is wrong, please"," ",i("a",{href:"https://github.com/microsoft/vscode-js-debug/issues/new/choose"},"open an issue"),"!"))),r):(r.push(i("li",{key:t++},i(hn,null))),r)},hn=()=>{let e=T();return i("p",null,"\u2753 We sent the breakpoint, but it didn't bind to any locations. If this is unexpected:",i("ul",null,i("li",null,"Make sure that your program is loading or running this script. You can add a"," ",i("code",null,"debugger;")," statement to check this: your program will pause when it hits it."),i("li",null,"If your breakpoint is set in certain places, such as on the last empty line of a file, the runtime might not be able to find anywhere to place it."),$e(e)&&i("li",null,"Unless you"," ",i("a",{href:"https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_breakpoint-validation"},"run with --nolazy"),", Node.js might not resolve breakpoints for code it hasn't parsed yet."),i("li",null,"If necessary, make sure your compiled files are up-to-date with your source files.")))},wn=({bp:e})=>{if(!e.source.path)return null;let n=T();return i("div",{className:"content source-container"},i("h2",null,K({absolutePath:e.source.path,url:e.source.path},n),":",e.params.line,":",e.params.column||1),i("ul",{className:"bp-tracing"},yn(e,n)))},xn=({bp:e})=>{let n=T(),t=D({url:e.source.path}),r=n.sources.filter(s=>D(s).toLowerCase()===t.toLowerCase());return r.length?i("li",null,i("p",null,"\u2753 We couldn't find a corresponding source location, but found some other files with the same name:"),i("ul",null,r.map(s=>i("li",{key:s},i(kn,{original:e.source.path,updated:s.absolutePath||s.url})))),j(n)?i("p",null,"You may need to adjust the ",i("code",null,"webRoot")," in your ",i("code",null,"launch.json")," if you're building from a subfolder, or tweak your ",i("code",null,"sourceMapPathOverrides"),"."):i("p",null,"If this is the same file, you may need to adjust your build tool"," ",j(n)&&i(x,null,"or ",i("code",null,"webRoot")," in the launch.json")," ","to correct the paths.")):i("li",null,i("p",null,i(Cn,{basename:t})))},kn=({original:e,updated:n})=>i("span",{className:"text-diff"},Te(e,n,{ignoreCase:!0}).map((t,r)=>i("span",{className:t.added?"add":t.removed?"rm":"",key:r},t.value))),bn=({loc:e})=>{let t=T().sources.find(r=>r.sourceReference===e.sourceReference);return i(x,null,i("code",null,t?.absolutePath??t?.url??"unknown")," line ",e.lineNumber," column"," ",e.columnNumber)},Tn=({cdp:e,index:n})=>{let t=T(),[r,s]=F(`showCdpBp${n}`,!1),{url:o,line:l,col:u,regex:c}="location"in e.args?{url:t.sources.find(d=>!d.compiledSourceRefToUrl&&d.scriptIds.includes(e.args.location.scriptId))?.url,regex:void 0,line:e.args.location.lineNumber+1,col:(e.args.location.columnNumber||0)+1}:{url:e.args.urlRegex?Ln(e.args.urlRegex):e.args.url,regex:e.args.urlRegex,line:e.args.lineNumber+1,col:(e.args.columnNumber||0)+1};return i("li",null,i("p",null,i("code",null,o)," line ",l," column ",u," ",c&&i("a",{onClick:()=>s(!r)},"via this regex")),r&&i("p",null,i("code",null,c)))},Ln=e=>e.replace(/\[([[a-z])[A-Z]\]/g,(n,t)=>t).replace(/\\\\/,"\\").replace(/\\\//g,"/").replace(/\|.+$/g,"").replace(/\\\./g,".");var Sn=Oe(["Loaded in directly","Be parsed from a sourcemap"]),Cn=({basename:e})=>{let n=T(),[t,r]=J(e.endsWith(".js")?void 0:"Be parsed from a sourcemap");return i(x,null,i("p",null,"\u2753 We couldn't find a corresponding source location, and didn't find any source with the name ",i("code",null,e),"."),i("p",null,"How did you expect this file to be loaded? (If you have a compilation step, you should pick 'sourcemap')",i(Sn,{onChange:r,value:t}),t==="Loaded in directly"&&(j(n)?i("p",null,"It looks like your webpage didn't load this script; breakpoints won't be bound until the file they're set in is loaded. Make sure your script is imported from the right location using a ",i("code",null,"<script>")," tag."):i("p",null,"It looks like your program didn't load this script; breakpoints won't be bound until the file they're set in is loaded. Make sure your script is imported with a"," ",i("code",null,"require()")," or ",i("code",null,"import")," statement, such as"," ",i("code",null,"require('./",e,"')"),".")),t==="Be parsed from a sourcemap"&&i("p",null,"Here's some hints that might help you:",i("ul",null,/\.tsx?$/.test(e)?i("li",null,"Make sure you have ",i("code",null,'"sourceMap": true')," in your tsconfig to generate sourcemaps."):i("li",null,"Make sure your build tool is set up to create sourcemaps."),!n.config.outFiles.includes("!**/node_modules/**")&&i("li",null,"It looks like you narrowed the ",i("code",null,"outFiles")," in your launch.json. Try removing this: it now defaults to the whole workspace, and overspecifying it can unnecessarily narrow places where we'll resolve sourcemaps.")))))};var Ke=({onPick:e})=>i("div",{className:"intro"},i("div",null,i("header",null,"Debug Doctor"),i("div",{className:"intro-content"},i("p",null,"What are you trying to find out?"),i("ul",null,i("li",null,i("a",{role:"button",onClick:()=>e(1)},"Why my breakpoints don't bind")),i("li",null,i("a",{role:"button",onClick:()=>e(2)},"What scripts and sourcemaps are loaded")),i("li",null,i("a",{href:"https://github.com/microsoft/vscode-js-debug/issues/new/choose"},"Something else..."))))));var Ge=()=>{let e=T(),n=H(()=>{let u=new Map;for(let c of e.sources)u.set(c.uniqueId,c);return u},[e.sources]),t=H(()=>e.sources.map(u=>[[u.url,u.absolutePath,u.prettyName].join(" ").toLowerCase(),u]).sort((u,c)=>te(u[1])-te(c[1])),[e.sources]),[r,s]=F("filter",""),o=H(()=>r?t.filter(([u])=>u.includes(r.toLowerCase())).map(([,u])=>u):t.map(u=>u[1]),[t,r]),l=N(u=>s(u.target.value),[]);return i(x,null,i("input",{placeholder:"Filter sources...",className:"source-filter",value:r,onChange:l,onKeyUp:l}),i("small",{style:{marginBottom:"1rem"}},"Showing ",o.length," of ",e.sources.length," sources..."),o.map(u=>i(Fn,{source:u,allSources:n,key:u.sourceReference})))},Fn=({source:e,allSources:n})=>{let[t,r]=F(`sourceBreadCrumbs${e.uniqueId}`,[e.uniqueId]),s=H(()=>t.map(d=>n.get(d)).filter(Pe),[n,t]),[o,l]=F(`sourceExpanded${e.uniqueId}`,!1),u=T(),c=N(()=>l(!o),[o]);return i("div",{className:`source-container ${o?" expanded":""}`},i("h2",{onClick:c},K(e,u)),o&&i(x,null,s.length>1&&i(In,{sources:s,update:r}),i(Nn,{source:s[s.length-1],open:d=>{let a=u.sources.find(g=>g.sourceReference===d);a&&r(t.concat(a.uniqueId))}})))},In=({sources:e,update:n})=>i("ol",{className:"source-breadcrumbs"},e.map((t,r)=>{let s=`${D(t)} (#${t.sourceReference})`;return r===e.length-1?i("li",null,s):i("li",{key:r},i("a",{key:r,onClick:()=>n(e.slice(0,r+1).map(o=>o.uniqueId))},s)," ","\xBB"," ")})),Nn=({source:e,open:n})=>i("dl",{className:"source-data-grid"},i("dt",null,"url"),i("dd",null,i("code",null,e.url)),i("dt",null,"sourceReference"),i("dd",null,i("code",null,e.sourceReference)),i("dt",null,"absolutePath"),i("dd",null,i("code",null,e.absolutePath)),i("dt",null,"absolutePath verified?"),i("dd",null,e.compiledSourceRefToUrl?"\u2705 From sourcemap, assumed correct":e.actualAbsolutePath?"\u2705 Verified on disk":"\u274C Disk verification failed (does not exist or different content)"),i("dt",null,"sourcemap children:"),i("dd",null,e.sourceMap?i("ul",null,Object.entries(e.sourceMap.sources).map(([t,r])=>i("li",{key:t},i(Dn,{url:t,sourceRef:r,pick:n})))):"None (does not have a sourcemap)"),i("dt",null,"referenced from sourcemap:"),i("dd",null,e.compiledSourceRefToUrl?i("ul",null,e.compiledSourceRefToUrl.map(([t,r])=>i("li",{key:r},i(Rn,{url:r,sourceRef:t,pick:n})))):"None (not from a sourcemap)")),Dn=({url:e,sourceRef:n,pick:t})=>{let s=T().sources.find(l=>l.sourceReference===n),o=N(()=>t(n),[n]);return i(x,null,e," \u2192 ",i("a",{onClick:o},s?`${D(s)} (#${n})`:"unknown"))},Rn=({url:e,sourceRef:n,pick:t})=>{let s=T().sources.find(l=>l.sourceReference===n),o=N(()=>t(n),[n]);return i(x,null,i("a",{onClick:o},s?`${D(s)} (#${n})`:"unknown")," as ",e," ","\u2192 this")};var Ye=({dump:e})=>{let[n,t]=F("experience",0);return i(re.Provider,{value:e},n===0?i(Ke,{onPick:t}):i(x,null,i("a",{role:"button",onClick:()=>t(0),className:"back"},"\u2190 Back"),n===1?i(je,null):i(Ge,null)))};typeof DUMP<"u"?Z(i(Ye,{dump:DUMP}),document.body):fetch(document.location.search.slice(1)).then(e=>e.json()).then(e=>Z(i(Ye,{dump:e}),document.body));})();

// SIG // Begin signature block
// SIG // MIInzAYJKoZIhvcNAQcCoIInvTCCJ7kCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // xEX+1sScyAuBcpe6mY4462WCn4ZAoqLammFe5AKM1TWg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAAA01OkaYaKLB4jwAA
// SIG // AAADTTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIzMDMxNjE4NDMyOFoX
// SIG // DTI0MDMxNDE4NDMyOFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // 1Cj3ChlWunG6BkFNNzjW1CspeFqR+kNl6PXD90YV0zmu
// SIG // gukx5bXdkX545VEBvjMKMvd4hphihDBf48jtl3YsDD+N
// SIG // u4/dAvzzGP3eb2N9bMfrnbW4n+xgie4ydby83Y9vM1eK
// SIG // 9BRhushL/rVDXpUyLBZpkm9BVIibVOK+bHwk4b4PHSPx
// SIG // fR4esTGaFbYvpG1ZWvoZRvG3+LNNFU8OLgGYYxkxQmBU
// SIG // crSid/5rXoNqp8LxwzoFe0EnVeXVnXdPsc3LhtKoHd6A
// SIG // ggIx/GZo5qMJB1HuHVJm3GX17IFpTn3OgxuyUvg3iWpN
// SIG // Q72m2pmKh4NQFHmdPrJKZMKysF0xcAUZbQIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFCHdiJoNkqdOVOlyNOI5Ytiq
// SIG // IS/vMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDA1MTcwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQAjBE/Frsy6w8Hsbk1GXvb9sa1vFhlD
// SIG // 0UFZsidW/wcymAWeWlOEL4eS82XvYzhMQ2FJSm/2O95a
// SIG // iCH1HBDv+lt2/u7dT/ZvTNcT62b+XH50goLqKDw6uK0H
// SIG // v4gnTQ8B0+l2FusnrcUyTDqOLVA20ktGIma+zGm9sJI4
// SIG // DRWtI0RYXkvXWk0taCf8+WzZRop8atr/Gs0j/xnB/7fH
// SIG // k6x0H3Gsd1mzxC6BhyG68q0lGjgqYbJwjVKlDeRWxDJW
// SIG // reTLmPeKxjCZ6tSBHekvJ4CugvBPUlqRhDtzQ2tDZQFY
// SIG // qK6RnyNDWCG3cp8jgfOOmlgIzX4E4SHHc3VhbwJf+pLV
// SIG // lyxE5/Lv5WEMlhprpd8s/sNOqbiDw/aeCj4lgZAnrCgx
// SIG // 71y609wWy2fHSqkjlfA7cyxQH3PagLDYhvBKGrYZbiQb
// SIG // G8hW6Xm2nSpRKxYnQF/ChLrJPIbR6okpDccnWpi/7Sn8
// SIG // d1f7wwKEBOfcrL+K96RPs3cnzGoq75BTTcO3D59ZBxnM
// SIG // MPXRUmNkMAMYTM5qDNBvjPmLwZwbucI38TazEYpUW8TO
// SIG // go/YShYdGE8G2ujO857Rx6V93fp2m4xZv05zEUTjoCFy
// SIG // c2G8yimjtoNZFnshtkLbyEdeO85a20A+F9dAG60YPQqc
// SIG // Fu8WMcsHs4/ojQHPkJhc0feHcyZBD1EgiT7ExTCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghmfMIIZmwIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAADTU6RphoosHiPAAAAAANNMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCDZT/ZNKmGE0nFY
// SIG // PQ3/JNxqANu3PW68THBd52eos2GeuDBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAA/BOQUTnPM9icAw8pGZgO3uoPoBJXxa
// SIG // ERyCZQS+F7HY+0Mak/XLMs8ksc/slczlF3bORyULcnJD
// SIG // RORvDR+hEUaVwUjb5tgjOHl7RSaRS+3+srtxgYF5H40Y
// SIG // BQ4KmaWNngR/12zQrjujsyOrggfbMdk+6jhwUHdXif1X
// SIG // 1CU2aZtTDFIjM+dhfdpVaXoOVOucxISKyOXT6/4cxNSQ
// SIG // NCV2vS9uwOPgpmfQC1JTVwWl+bL9TO224Xc/XkpTKDBh
// SIG // s8X7dvTWL/2ryBsTaMIBw0K5m+gcDEv0Bqyw5EiHaduY
// SIG // sFKPRp0cIiXUI2YYorVqKA/9XQOmW24jp6F53yG4mZUf
// SIG // A+GhghcpMIIXJQYKKwYBBAGCNwMDATGCFxUwghcRBgkq
// SIG // hkiG9w0BBwKgghcCMIIW/gIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBWQYLKoZIhvcNAQkQAQSgggFIBIIBRDCCAUAC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // OseIlks1aVq0ZeQ47sYl0UzIjTPtgaQ65HoeGq8a9FkC
// SIG // BmULJhIiXBgTMjAyMzA5MjYwOTA3NTMuMTU5WjAEgAIB
// SIG // 9KCB2KSB1TCB0jELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsG
// SIG // A1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9u
// SIG // cyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVT
// SIG // TjoxNzlFLTRCQjAtODI0NjElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCEXgwggcnMIIF
// SIG // D6ADAgECAhMzAAABta0a39eFcG0TAAEAAAG1MA0GCSqG
// SIG // SIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
// SIG // EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
// SIG // HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAk
// SIG // BgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAy
// SIG // MDEwMB4XDTIyMDkyMDIwMjIxMVoXDTIzMTIxNDIwMjIx
// SIG // MVowgdIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsT
// SIG // JE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGlt
// SIG // aXRlZDEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046MTc5
// SIG // RS00QkIwLTgyNDYxJTAjBgNVBAMTHE1pY3Jvc29mdCBU
// SIG // aW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
// SIG // AQUAA4ICDwAwggIKAoICAQCXCwq4ZV6Cwo2JhcXBT4JI
// SIG // ee3Zrs99bDbI/CJb5hGUQmwfeJsUiI9+T/JuUynwkZqe
// SIG // 277sOL/7d7nBY3+dslQgxSMRYmdzwkyOg+YcJawy0k65
// SIG // H/VG7hprVGvFC0h6WrT3xMGXiTs2wQTzuXuooWbLyLAY
// SIG // 1COTCvRsy7gEnDLsFReJcd6A5JT33at9DjE1mjHOe/jZ
// SIG // MtCxz02ZwGrlayWSpUBNxzw9J+AEsSl0bUOnbCo3Dgms
// SIG // kXAk0DVt/NNJxgAFzmyZFkGCw/gmIr/wJWuWhyF4TJCi
// SIG // eObesW22uiMCt5JSeLEAu72kOuwEjgNQ8YbfighuJ4jW
// SIG // ioWX/GTsD7u4zyTijyJ8xVY1NpzNs+V0Ni2fqEGt7uvb
// SIG // lEQPi55wLE/wPHLfhg9QSVaWU8/csBenlwzBGPH4RbOM
// SIG // S0gsQpe4Bx/GtcJPDJiGblc3MIJliHj+AXZTbL9th96Q
// SIG // qlqgVjCShl5PpnGhBtfkp+2CP61mQVXbVS9kiQnpvfhr
// SIG // /jh22uwrp2JOZWc1Mz0no/oSGWTax9xTBscgYvyZip0o
// SIG // 6LJ3hHE4KZK9wU2RkSCuTnjyYcJsNtPI73FLM3USRbFu
// SIG // nyf8sdWdn1+nmEgsae2QzNoPlpdEJDIdIiGw+1HtD+sq
// SIG // gfKMWqC0Y71+2fFi/HM2tsp4wLPCZyrAytfodzF7RJ4p
// SIG // nwIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFGxQhtmChlVd
// SIG // VdVZBfQ6TVU7ZsdTMB8GA1UdIwQYMBaAFJ+nFV0AXmJd
// SIG // g/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCGTmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3Js
// SIG // L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAy
// SIG // MDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4wXAYIKwYB
// SIG // BQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFt
// SIG // cCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwGA1UdEwEB/wQC
// SIG // MAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0P
// SIG // AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQCQUY6n
// SIG // KMpXazawD7BOoPAN2GnSYWs+2JTis3c6idNapvzkzpYf
// SIG // X1z8/nXvG6MsKKH8eWU/nEpaZecAhFXX81AOQkEtJ0tN
// SIG // v81C1xPUVYZDsIxOeuf20tnGogW0pXKW9A3KHfUL+qQL
// SIG // xCY2nLNqQ7Qbfy44aA6Qn0SricD7tDBV+hsOWCBa4SnN
// SIG // 0WdF3JcvfaA6pK+suMUqm/goRWpoFOJrEJZkOUiEbdiB
// SIG // TNrtycblnZID994yr8iJXToDNRp1nDpeBxOupeYSYTS0
// SIG // yZ2XjgwwULfAZT0BV4UJYp0P1Y6dgDbMeD5cXYtBW2jR
// SIG // Vi0Ut3pzoNAVyYHfwa88IpVhKfyvXQShe5E36BDuEtyK
// SIG // bXZ6w6dbgXhscKYdZNVZ4AaA+JIi0cdF8YosRRmai1U5
// SIG // 0U9HzCK4ANP98dJcGSR2kvXa2+AQYQt5POfMW6VnXpv8
// SIG // 2/p21uBJFmt56wkE0qlON1iO78aqeUCSl+UvonTDGT3n
// SIG // v9RVieaONFjrWNf3RAZCYHOb2+z/7ZuPTZfH9tdfLy+r
// SIG // nuOY1dDa585ombecBwPao5pLJcQ6P2aqEy3i128yMeGI
// SIG // 0+V1+PRDsqrUeB1EGspaTMJA2Li2zwdEkGKk1pWlZ9Ts
// SIG // FxGfwF5jN0ugjPBEsO1q3PpoGGjegP9tcetlqDGmszky
// SIG // wwH+tV9vlefVhLv+4TCCB3EwggVZoAMCAQICEzMAAAAV
// SIG // xedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgx
// SIG // CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
// SIG // MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jv
// SIG // c29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
// SIG // MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIy
// SIG // NVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIi
// SIG // MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM
// SIG // 57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/
// SIG // bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1
// SIG // jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhx
// SIG // XFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41
// SIG // JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP
// SIG // 1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3j
// SIG // tIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF
// SIG // 50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg
// SIG // 3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F
// SIG // 37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
// SIG // lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlM
// SIG // jgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLX
// SIG // pyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJ
// SIG // YfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzF
// SIG // ER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+e
// SIG // FnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYB
// SIG // BAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS
// SIG // /mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0A
// SIG // XmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYB
// SIG // BAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBv
// SIG // c2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZ
// SIG // BgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8E
// SIG // BAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAW
// SIG // gBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBN
// SIG // MEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
// SIG // cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAx
// SIG // MC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsG
// SIG // AQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
// SIG // cGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIz
// SIG // LmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4Swf
// SIG // ZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518Jx
// SIG // Nj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6
// SIG // th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9I
// SIG // dQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq
// SIG // 95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBew
// SIG // VIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7
// SIG // bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa
// SIG // 2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzH
// SIG // VG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZ
// SIG // c9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakUR
// SIG // R6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
// SIG // QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKi
// SIG // excdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+AN
// SIG // uOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/
// SIG // OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQd
// SIG // VTNYs6FwZvKhggLUMIICPQIBATCCAQChgdikgdUwgdIx
// SIG // CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
// SIG // MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jv
// SIG // c29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEm
// SIG // MCQGA1UECxMdVGhhbGVzIFRTUyBFU046MTc5RS00QkIw
// SIG // LTgyNDYxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAI0wn2vX
// SIG // VFmPQ9a7e6T5pAcXcixVoIGDMIGApH4wfDELMAkGA1UE
// SIG // BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
// SIG // BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
// SIG // b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
// SIG // bWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEFBQAC
// SIG // BQDovOSWMCIYDzIwMjMwOTI2MTMwMzE4WhgPMjAyMzA5
// SIG // MjcxMzAzMThaMHQwOgYKKwYBBAGEWQoEATEsMCowCgIF
// SIG // AOi85JYCAQAwBwIBAAICJJswBwIBAAICEjMwCgIFAOi+
// SIG // NhYCAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGE
// SIG // WQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkq
// SIG // hkiG9w0BAQUFAAOBgQAMBFR5PFXjAEVgaJPnwusyEmba
// SIG // vXBP3zOhhrMOtE7qUZvE/XcDvyK4SJw3CaVBQpGmnQmA
// SIG // X6n6I+k+RpxBeZKPgbmbNfNAV5DAFdYv+NPoaJtwGKyz
// SIG // F6XWpkk00M/7VtRhQNJJTvbPzNdSzb83DzjHOJKPTDj9
// SIG // FsPbzIjttBB+XjGCBA0wggQJAgEBMIGTMHwxCzAJBgNV
// SIG // BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
// SIG // VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
// SIG // Q29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBU
// SIG // aW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABta0a39eFcG0T
// SIG // AAEAAAG1MA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkqhkiG
// SIG // 9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZIhvcNAQkE
// SIG // MSIEIHEh2wsPOgW0nK2raXLanbsv8kHC2uBpgPccob1Z
// SIG // TDE7MIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCBvQQg
// SIG // J8oNNS1oZxaJ9hzc5WcimntiSfRLwlyVXOuUCAXxyIMw
// SIG // gZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
// SIG // VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
// SIG // MAITMwAAAbWtGt/XhXBtEwABAAABtTAiBCDme/kFxTUe
// SIG // Y2MuLKy4LTzcu0YXZrLHmJoQ05lbAU5YkzANBgkqhkiG
// SIG // 9w0BAQsFAASCAgAb0U1wfqO6HaNl2oAZjLF2mzvHhpVr
// SIG // yPmWeMzMOzIlBkuq+cQ+Gj8jd44uT893/BAzaf2TzKLq
// SIG // AyDmRmec6WoAAXMWo1v6Y3XhZ9ICXiLn4FfZzW8o9MCp
// SIG // CDFZgYfDpQ73yty/Qx1lu5HNW/6i1hsV4G9ydfJZumZS
// SIG // n/4Q6eVJNFtLHl8th4brn/4fF/+84k9j13zG9/TOEWBH
// SIG // mixg6KFrkE6w46rxJoGnCKSdCCyCxTM5ZdtUx108eZIA
// SIG // gLWFyogJV47EFYbxCSqCwkzpimyTanYZyK+7ARVvGX/b
// SIG // E/a72k6iP91XPTdKBZ21bbM0/ie9I3fkJZM8W1kUazQ/
// SIG // AW6lUJ6IbVGkt0KePmUJxyF0GPuVOQ3KpaomEs0KDKBE
// SIG // 36tUUSfA1JW2ukwh4xTuSgzNijeFspoddLCLXf4g2WuY
// SIG // wmA2UgDnT57ale0/EWHCXWmy/j9NNzV1HJvb+0g2N6h6
// SIG // QZF3gWtB6dpum5h6mH7jvXQK8UN6FHXZHQsvgA4JlHeJ
// SIG // La6NC7/od1qIxYxef8x//d0lK0SmUd3aOiqz11HWiVqg
// SIG // 6xiF9qD30GhAbh6QqsusClNCuX+I7eurU3Rpn3Xg9O+F
// SIG // HXs5YThRTBiexX3GS08h/BRZLnsxoFyBi0FGi3iKwv+1
// SIG // 0wsiti0BQtfOPkfHnHH2iO1bF8PejGqbrRo30w==
// SIG // End signature block
